// Centraid — CSS generator.
// `toCss()` walks the typed tokens (themes, densities, palette, radii) and
// emits the entire `:root` + `[data-theme='dark']` + density-override
// blocks as a single CSS string. Desktop injects this into a <style> tag
// at preload time — the only token-related CSS it ships.

import { BRAND, themes, type Theme, type ThemeName } from './themes';
import { densities, type DensityScale } from './density';
import { library } from './library';
import { palette } from './palette';
import { radii } from './radii';
import { fontStacks, marketingType, type, typeShorthand } from './typography';

function block(selector: string, props: Record<string, string>): string {
  const lines: string[] = [`${selector} {`];
  for (const [k, v] of Object.entries(props)) {
    lines.push(`  ${k}: ${v};`);
  }
  lines.push('}');
  return lines.join('\n');
}

function themeProps(t: Theme): Record<string, string> {
  const out: Record<string, string> = {
    '--accent': t.accent,
    '--accent-deep': t.accentDeep,
    '--accent-light': t.accentLight,
    '--accent-midnight': t.accentMidnight,
    '--accent-violet': t.accentViolet,
    '--danger': t.danger,
    '--success': t.success,
  };
  // --bg-l must precede --bg/--bg-elev/--bg-sunken/--bg-app on dark, since
  // those reference it via var(). Light theme omits it entirely.
  if (t.bgL !== undefined) out['--bg-l'] = t.bgL;
  Object.assign(out, {
    '--bezel': t.bezel,
    '--bezel-inner': t.bezelInner,
    '--bg': t.bg,
    '--bg-app': t.bgApp,
    '--bg-elev': t.bgElev,
    '--bg-sunken': t.bgSunken,
    '--bg-wall': t.bgWall,
    '--device-wall': t.deviceWall,
    '--ink': t.ink,
    '--ink-2': t.ink2,
    '--ink-3': t.ink3,
    '--ink-4': t.ink4,
    '--ink-inv': t.inkInv,
    '--line': t.line,
    '--line-strong': t.lineStrong,
    '--shadow-lg': t.shadowLg,
    '--shadow-md': t.shadowMd,
    '--shadow-sm': t.shadowSm,
    '--sidebar-bg': t.sidebarBg,
    '--sidebar-blur': t.sidebarBlur,
    '--sidebar-divider': t.sidebarDivider,
  });
  return out;
}

function densityProps(d: DensityScale): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(d)) {
    out[`--d-${k}`] = `${v}px`;
  }
  return out;
}

/**
 * Returns the full token CSS string. Stable order: static (palette, radii,
 * default density) → light theme → dark theme → density overrides.
 */
export function toCss(): string {
  const staticProps: Record<string, string> = {};
  // App-icon palette gets two names: the legacy `--c-<hue>` (still used
  // throughout the renderer and mobile theme code) and the redesign-spec
  // `--icon-<hue>` (used by ds-update/02-chrome-components.css and any
  // markup imported verbatim from the design system). Same hex value
  // either way — `--icon-*` is an alias for cross-codebase portability.
  for (const [k, v] of Object.entries(palette)) {
    staticProps[`--c-${k}`] = v;
    staticProps[`--icon-${k}`] = v;
  }
  for (const [k, v] of Object.entries(radii)) staticProps[`--r-${k}`] = `${v}px`;
  // Brand teal — theme-independent, matches the logo / app-icon SVGs.
  staticProps['--brand'] = BRAND;
  // Typography — web font stacks + the semantic type scale as CSS `font`
  // shorthands (`font: var(--t-title)`). camelCase keys emit kebab-case
  // (`bodyStrong` → `--t-body-strong`, `display1` → `--t-display-1`).
  for (const [k, v] of Object.entries(fontStacks)) staticProps[`--font-${k}`] = v;
  for (const [k, v] of Object.entries({ ...type, ...marketingType })) {
    const kebab = k.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
    staticProps[`--t-${kebab}`] = typeShorthand(v);
  }
  // Shared library-tile tokens (Home + Discover render the same tile).
  for (const [k, v] of Object.entries(library)) staticProps[`--lib-${k}`] = v;
  Object.assign(staticProps, densityProps(densities.regular));

  const blocks = [
    '/* Generated by @centraid/design-tokens — do not edit by hand. */',
    block(':root', { ...staticProps, ...themeProps(themes.light) }),
  ];

  // One block per registered theme — picker selections write the matching
  // `data-theme` attribute on <html> and the right block wins.
  for (const name of Object.keys(themes) as ThemeName[]) {
    blocks.push(block(`[data-theme='${name}']`, themeProps(themes[name])));
  }

  for (const name of Object.keys(densities) as Array<keyof typeof densities>) {
    blocks.push(block(`[data-density='${name}']`, densityProps(densities[name])));
  }

  // Tweaks · Cool blue cast — turning it off neutralises the dark ramp's
  // hue + saturation (hue 0, sat 0%) while keeping the same --bg-l anchor,
  // so the lightness slider still drives all four surfaces. Light themes
  // have no blue cast to begin with and are unaffected. Redefining
  // --bg-wall here neutralises the main panes AND the device-wall
  // composite — which references var(--bg-wall) — in one place.
  blocks.push(
    block(`[data-theme='dark'][data-cool-cast='off']`, {
      '--bg': 'hsl(0 0% var(--bg-l))',
      '--bg-app': 'hsl(0 0% calc(var(--bg-l) - 5%))',
      '--bg-elev': 'hsl(0 0% calc(var(--bg-l) + 4.5%))',
      '--bg-sunken': 'hsl(0 0% calc(var(--bg-l) - 4%))',
      '--bg-wall':
        'linear-gradient(180deg, hsl(0 0% calc(var(--bg-l) + 2%)) 0%, hsl(0 0% calc(var(--bg-l) - 2%)) 100%)',
      '--sidebar-bg': 'hsl(0 0% calc(var(--bg-l) + 2%) / 0.65)',
    }),
  );

  return blocks.join('\n\n') + '\n';
}
