// Literal ramps — do not derive dark from `hsl(0 0% calc(...))`; `#171716`
// is warm paper, not greyscale. Paper, not elevation: light raised is
// darker than the page, dark raised is lighter.

import { palette, paletteDark } from "../palette";
import {
  ACCENT_HOVER,
  ACCENT_HOVER_DARK,
  ACCENT_INK_HOVER,
  ACCENT_INK_HOVER_DARK,
  ACCENT_LIGHT,
  ACCENT_LIGHT_DARK,
  ATTENTION,
  ATTENTION_DARK,
  BRAND,
  BRAND_DARK,
  DANGER,
  DANGER_DARK,
  INK_RAMP,
  LINK,
  LINK_DARK,
  NET,
  NET_DARK,
  NET_HOVER,
  NET_HOVER_DARK,
  NET_WASH,
  NET_WASH_DARK,
  PAGE,
  RING,
  RING_DARK,
  SEAM,
  SEAM_DARK,
  SUCCESS,
  SUCCESS_LIGHT,
  WALL,
  WARNING,
  WARNING_LIGHT,
} from "./shared";
import type { Theme } from "./shared";

export const lightTheme: Theme = {
  kind: "light",
  accent: BRAND,
  accentDeep: BRAND,
  accentHover: ACCENT_HOVER,
  accentInkHover: ACCENT_INK_HOVER,
  accentLight: ACCENT_LIGHT,
  accentText: BRAND,
  attention: ATTENTION,
  bg: PAGE.light,
  bgApp: WALL.light,
  bgElev: "#F5F4F2",
  // Deeper than this and `--text-faint` on the groove fails AA.
  bgSunken: "#F9F8F6",
  bgWall: WALL.light,
  deviceWall:
    "repeating-linear-gradient(0deg, transparent 0 23px, rgba(20,20,20,.035) 23px 24px), " +
    "repeating-linear-gradient(90deg, transparent 0 23px, rgba(20,20,20,.035) 23px 24px), " +
    "linear-gradient(180deg, #EAE9E6 0%, #E1E0DC 100%)",
  skel: "#E4E3E0",
  text: INK_RAMP.light.text,
  textSoft: INK_RAMP.light.soft,
  textFaint: INK_RAMP.light.faint,
  textGhost: INK_RAMP.light.ghost,
  textDisabled: INK_RAMP.light.disabled,
  textInv: PAGE.light,
  line: "#EFEEEB",
  lineStrong: "#E5E4E1",
  link: LINK,
  net: NET,
  netHover: NET_HOVER,
  netWash: NET_WASH,
  ring: RING,
  seam: SEAM,
  // Warm 0.3 — do not "fix" to cool ink or 0.48 (reads as a grey plate).
  scrim: "rgba(26,24,21,0.3)",
  palette,
  shadowLg: "0 24px 48px -16px rgba(20,20,20,.16)",
  shadowMd: "0 8px 24px -8px rgba(20,20,20,.10)",
  shadowSm: "0 1px 2px rgba(20,20,20,.06)",
  sidebarBg: "#F5F4F2",
  sidebarBlur: "none",
  sidebarDivider: "1px solid #E5E4E1",
  success: SUCCESS_LIGHT,
  danger: DANGER,
  warning: WARNING_LIGHT,
};

export const darkTheme: Theme = {
  kind: "dark",
  accent: BRAND_DARK,
  accentDeep: BRAND_DARK,
  accentHover: ACCENT_HOVER_DARK,
  accentInkHover: ACCENT_INK_HOVER_DARK,
  accentLight: ACCENT_LIGHT_DARK,
  accentText: BRAND_DARK,
  attention: ATTENTION_DARK,
  bg: PAGE.dark,
  bgApp: WALL.dark,
  // Lighter than the page — validate `--text-faint` against this, not `--bg`.
  bgElev: "#171716",
  bgSunken: "#121211",
  bgWall: WALL.dark,
  deviceWall:
    "repeating-linear-gradient(0deg, transparent 0 23px, rgba(255,255,255,.022) 23px 24px), " +
    "repeating-linear-gradient(90deg, transparent 0 23px, rgba(255,255,255,.022) 23px 24px), " +
    "var(--bg-wall)",
  skel: "#1E1E1D",
  text: INK_RAMP.dark.text,
  textSoft: INK_RAMP.dark.soft,
  textFaint: INK_RAMP.dark.faint,
  textGhost: INK_RAMP.dark.ghost,
  textDisabled: INK_RAMP.dark.disabled,
  textInv: PAGE.dark,
  line: "#1B1B1A",
  lineStrong: "#232322",
  link: LINK_DARK,
  net: NET_DARK,
  netHover: NET_HOVER_DARK,
  netWash: NET_WASH_DARK,
  ring: RING_DARK,
  seam: SEAM_DARK,
  // 0.62 — do not raise toward 0.72 (near-black page would vanish).
  scrim: "rgba(0,0,0,0.62)",
  palette: paletteDark,
  shadowLg: "0 30px 70px -24px rgba(0,0,0,.7)",
  shadowMd: "0 12px 30px -14px rgba(0,0,0,.6)",
  shadowSm: "0 1px 0 rgba(0,0,0,.4)",
  sidebarBg: "#121211",
  sidebarBlur: "none",
  sidebarDivider: "1px solid #232322",
  success: SUCCESS,
  danger: DANGER_DARK,
  warning: WARNING,
};
