// GENERATED by contracts/tools/export-native-catalog.ts. Do not edit.
//
// The app catalogue, the resolved identity marks and the shared icon
// silhouettes, lowered from packages/design (#1020, wave A). A hand-edited
// copy of this table is a lowering with no drift gate, which is what
// `git diff --exit-code design copy mobile` in the mobile-jvm gate step
// exists to prevent.

package dev.centraid.design

/** One first-party app's launcher identity. */
public data class NativeApp(
    public val id: String,
    public val name: String,
    public val desc: String,
    public val iconKey: String,
    public val colorKey: String,
)

/**
 * An app's icon chip, already composited.
 *
 * `chipBackground` is [hue] over the page at the scheme's tint share and
 * `markColor` is the hue's solved text rung — both computed by
 * `packages/design`'s `iconChipFinish`, because a blend computed twice is
 * two blends. The chip is the ONLY place an app's hue appears on Home: the
 * springboard itself takes no identity hue.
 */
public data class NativeAppMark(
    public val hue: Long,
    public val chipBackground: Long,
    public val markColor: Long,
)

/** One `<path>` of a silhouette: SVG path data in a 24x24 viewBox. */
public data class NativeIconPath(
    public val d: String,
    /** Filled with the mark colour rather than stroked. */
    public val filled: Boolean,
    /** The knockout rule the silhouette contract specifies. */
    public val evenOdd: Boolean,
)

public object CentraidCatalog {
    /**
     * The eight first-party apps, in CATALOGUE order.
     *
     * This is the all-apps listing's order and says nothing about the grid
     * — `SpringboardPolicy.SPRINGBOARD_ORDER` owns that.
     */
    public val apps: List<NativeApp> = listOf(
        NativeApp(id = "notes", name = "Notes", desc = "Write and revisit durable notes.", iconKey = "Book", colorKey = "slate"),
        NativeApp(id = "people", name = "People", desc = "Keep people and relationships close.", iconKey = "AddressBook", colorKey = "violet"),
        NativeApp(id = "photos", name = "Photos", desc = "Browse and protect your photos.", iconKey = "Camera", colorKey = "amber"),
        NativeApp(id = "locker", name = "Locker", desc = "Keep private secrets behind a lock.", iconKey = "Lock", colorKey = "rose"),
        NativeApp(id = "tally", name = "Tally", desc = "See balances and simple trends.", iconKey = "Receipt", colorKey = "indigo"),
        NativeApp(id = "tasks", name = "Tasks", desc = "Capture the next thing to do.", iconKey = "Check", colorKey = "ochre"),
        NativeApp(id = "docs", name = "Docs", desc = "Read and organize your documents.", iconKey = "Folder", colorKey = "teal"),
        NativeApp(id = "agenda", name = "Agenda", desc = "Keep dates, events, and plans together.", iconKey = "Calendar", colorKey = "forest"),
    )

    /** By id, for the header that names one app. */
    public val byId: Map<String, NativeApp> = apps.associateBy { it.id }

    public val lightMarks: Map<String, NativeAppMark> = mapOf(
        "notes" to NativeAppMark(hue = 0xFF3E6596L, chipBackground = 0xFFE4E9EFL, markColor = 0xFF3A5E8BL),
        "people" to NativeAppMark(hue = 0xFF7A5283L, chipBackground = 0xFFECE7ECL, markColor = 0xFF744E7DL),
        "photos" to NativeAppMark(hue = 0xFF904E46L, chipBackground = 0xFFEFE6E4L, markColor = 0xFF894A43L),
        "locker" to NativeAppMark(hue = 0xFF8C4C61L, chipBackground = 0xFFEEE6E8L, markColor = 0xFF894A5FL),
        "tally" to NativeAppMark(hue = 0xFF635A93L, chipBackground = 0xFFE9E8EEL, markColor = 0xFF5F568DL),
        "tasks" to NativeAppMark(hue = 0xFF845922L, chipBackground = 0xFFEDE8E0L, markColor = 0xFF7C5420L),
        "docs" to NativeAppMark(hue = 0xFF00707EL, chipBackground = 0xFFDCEBECL, markColor = 0xFF006774L),
        "agenda" to NativeAppMark(hue = 0xFF397247L, chipBackground = 0xFFE4EBE4L, markColor = 0xFF346841L),
    )

    public val darkMarks: Map<String, NativeAppMark> = mapOf(
        "notes" to NativeAppMark(hue = 0xFF7EA7DCL, chipBackground = 0xFF242D37L, markColor = 0xFF7EA7DCL),
        "people" to NativeAppMark(hue = 0xFFBE92C8L, chipBackground = 0xFF312833L, markColor = 0xFFBE92C8L),
        "photos" to NativeAppMark(hue = 0xFFD78F85L, chipBackground = 0xFF362826L, markColor = 0xFFD78F85L),
        "locker" to NativeAppMark(hue = 0xFFD48DA2L, chipBackground = 0xFF36272CL, markColor = 0xFFD48DA2L),
        "tally" to NativeAppMark(hue = 0xFFA39BDAL, chipBackground = 0xFF2C2A37L, markColor = 0xFFA39BDAL),
        "tasks" to NativeAppMark(hue = 0xFFC99B65L, chipBackground = 0xFF332A1FL, markColor = 0xFFC99B65L),
        "docs" to NativeAppMark(hue = 0xFF58B4C4L, chipBackground = 0xFF1D2F32L, markColor = 0xFF58B4C4L),
        "agenda" to NativeAppMark(hue = 0xFF7BB587L, chipBackground = 0xFF242F26L, markColor = 0xFF7BB587L),
    )

    /**
     * Lucide-style silhouettes as raw SVG path data, viewBox 24x24.
     *
     * ONE ordered list per icon, drawn in order. Compose reads these with
     * `PathParser`, which speaks SVG path data directly; the iOS side has
     * its own parser beside its renderer. Neither shell ships a second
     * icon set, because two silhouettes for one concept is two products.
     */
    public val icons: Map<String, List<NativeIconPath>> = mapOf(
        "Activity" to listOf(
            NativeIconPath(d = "M3 12h4l3 8 4-16 3 8h4", filled = false, evenOdd = false),
        ),
        "AddressBook" to listOf(
            NativeIconPath(d = "M5 4h14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2z", filled = false, evenOdd = false),
            NativeIconPath(d = "M8 10h.01M8 14h.01M11 10h6M11 14h6", filled = false, evenOdd = false),
        ),
        "AlertCircle" to listOf(
            NativeIconPath(d = "M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0z", filled = false, evenOdd = false),
            NativeIconPath(d = "M12 8v4M12 16h.01", filled = false, evenOdd = false),
        ),
        "AlertTriangle" to listOf(
            NativeIconPath(d = "M21.73 18l-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3z", filled = false, evenOdd = false),
            NativeIconPath(d = "M12 9v4M12 17h.01", filled = false, evenOdd = false),
        ),
        "Archive" to listOf(
            NativeIconPath(d = "M4 5h16v4H4z", filled = false, evenOdd = false),
            NativeIconPath(d = "M6 9v10h12V9M9 13h6", filled = false, evenOdd = false),
        ),
        "ArrowLeft" to listOf(
            NativeIconPath(d = "M19 12H5M12 19l-7-7 7-7", filled = false, evenOdd = false),
        ),
        "ArrowRight" to listOf(
            NativeIconPath(d = "M5 12h14M12 5l7 7-7 7", filled = false, evenOdd = false),
        ),
        "BarChart2" to listOf(
            NativeIconPath(d = "M4 20V10M10 20V4M16 20v-7M22 20H2", filled = false, evenOdd = false),
        ),
        "Battery" to listOf(
            NativeIconPath(d = "M2 7h18v10H2z", filled = false, evenOdd = false),
            NativeIconPath(d = "M4 9h10v6H4z", filled = true, evenOdd = false),
            NativeIconPath(d = "M22 11v2", filled = false, evenOdd = false),
        ),
        "BatteryCharging" to listOf(
            NativeIconPath(d = "M2 7h18v10H2z", filled = false, evenOdd = false),
            NativeIconPath(d = "M22 11v2M11 10l-2 3h3l-1 3 4-5h-3l1-1z", filled = false, evenOdd = false),
        ),
        "Beaker" to listOf(
            NativeIconPath(d = "M14 2v6a2 2 0 0 0 .245.96l5.51 10.08A2 2 0 0 1 18 22H6a2 2 0 0 1-1.755-2.96l5.51-10.08A2 2 0 0 0 10 8V2z", filled = false, evenOdd = false),
            NativeIconPath(d = "M8.5 2h7M7 16h10", filled = false, evenOdd = false),
        ),
        "Bell" to listOf(
            NativeIconPath(d = "M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9z", filled = false, evenOdd = false),
            NativeIconPath(d = "M10.3 21a1.94 1.94 0 0 0 3.4 0", filled = false, evenOdd = false),
        ),
        "Bolt" to listOf(
            NativeIconPath(d = "M13 2L4 13h7l-2 9 11-13h-8z", filled = false, evenOdd = false),
        ),
        "BoltOff" to listOf(
            NativeIconPath(d = "m3 3 18 18", filled = false, evenOdd = false),
            NativeIconPath(d = "m13 2-9 11h7l-2 9 4-4", filled = false, evenOdd = false),
        ),
        "Book" to listOf(
            NativeIconPath(d = "M4 5a2 2 0 0 1 2-2h13v18H6a2 2 0 0 1-2-2z", filled = false, evenOdd = false),
            NativeIconPath(d = "M4 17a2 2 0 0 1 2-2h13", filled = false, evenOdd = false),
        ),
        "Bookmark" to listOf(
            NativeIconPath(d = "M6 4h12v17l-6-3-6 3z", filled = false, evenOdd = false),
        ),
        "Braces" to listOf(
            NativeIconPath(d = "M8 3H7a2 2 0 0 0-2 2v5a2 2 0 0 1-2 2 2 2 0 0 1 2 2v5a2 2 0 0 0 2 2h1", filled = false, evenOdd = false),
            NativeIconPath(d = "M16 3h1a2 2 0 0 1 2 2v5a2 2 0 0 0 2 2 2 2 0 0 0-2 2v5a2 2 0 0 1-2 2h-1", filled = false, evenOdd = false),
        ),
        "Calendar" to listOf(
            NativeIconPath(d = "M5 5h14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2z", filled = false, evenOdd = false),
            NativeIconPath(d = "M3 10h18M8 3v4M16 3v4", filled = false, evenOdd = false),
        ),
        "CalendarBlank" to listOf(
            NativeIconPath(d = "M5 4h14a2 2 0 0 1 2 2v13a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V6a2 2 0 0 1 2-2z", filled = false, evenOdd = false),
            NativeIconPath(d = "M3 9h18", filled = false, evenOdd = false),
        ),
        "CalendarPlus" to listOf(
            NativeIconPath(d = "M5 4h14a2 2 0 0 1 2 2v13a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V6a2 2 0 0 1 2-2z", filled = false, evenOdd = false),
            NativeIconPath(d = "M3 9h18M12 12v6M9 15h6", filled = false, evenOdd = false),
        ),
        "Camera" to listOf(
            NativeIconPath(d = "M3 8a2 2 0 0 1 2-2h2l2-2h6l2 2h2a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z", filled = false, evenOdd = false),
            NativeIconPath(d = "M12 17a4 4 0 1 0 0-8 4 4 0 0 0 0 8z", filled = false, evenOdd = false),
        ),
        "Cellular" to listOf(
            NativeIconPath(d = "M2 18v3h2v-3zM7 14v7h2v-7zM12 10v11h2V10zM17 6v15h2V6z", filled = true, evenOdd = false),
        ),
        "Check" to listOf(
            NativeIconPath(d = "M5 12l5 5L20 7", filled = false, evenOdd = false),
        ),
        "CheckCircle" to listOf(
            NativeIconPath(d = "M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0z", filled = false, evenOdd = false),
            NativeIconPath(d = "M8.5 12.5l2.5 2.5 4.5-5", filled = false, evenOdd = false),
        ),
        "ChevronDown" to listOf(
            NativeIconPath(d = "M6 9l6 6 6-6", filled = false, evenOdd = false),
        ),
        "ChevronLeft" to listOf(
            NativeIconPath(d = "M15 6l-6 6 6 6", filled = false, evenOdd = false),
        ),
        "ChevronRight" to listOf(
            NativeIconPath(d = "M9 6l6 6-6 6", filled = false, evenOdd = false),
        ),
        "ChevronsDown" to listOf(
            NativeIconPath(d = "m7 7 5 5 5-5M7 13l5 5 5-5", filled = false, evenOdd = false),
        ),
        "CirclePlus" to listOf(
            NativeIconPath(d = "M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0z", filled = false, evenOdd = false),
            NativeIconPath(d = "M12 8v8M8 12h8", filled = false, evenOdd = false),
        ),
        "Clock" to listOf(
            NativeIconPath(d = "M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0z", filled = false, evenOdd = false),
            NativeIconPath(d = "M12 7v5l3 2", filled = false, evenOdd = false),
        ),
        "Cloud" to listOf(
            NativeIconPath(d = "M7 18h10a4 4 0 0 0 .7-7.94A6 6 0 0 0 6.2 8.4 4.5 4.5 0 0 0 7 18z", filled = false, evenOdd = false),
        ),
        "CloudOff" to listOf(
            NativeIconPath(d = "m3 3 18 18", filled = false, evenOdd = false),
            NativeIconPath(d = "M7 18h10a4 4 0 0 0 .7-7.94A6 6 0 0 0 6.2 8.4 4.5 4.5 0 0 0 7 18z", filled = false, evenOdd = false),
        ),
        "Code" to listOf(
            NativeIconPath(d = "M8 6l-6 6 6 6M16 6l6 6-6 6", filled = false, evenOdd = false),
        ),
        "Coin" to listOf(
            NativeIconPath(d = "M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0z", filled = false, evenOdd = false),
            NativeIconPath(d = "M14.5 8.5c0-1.4-1.1-2-2.5-2s-2.5.7-2.5 2 1.1 1.9 2.5 1.9 2.5.6 2.5 2-1.1 2.1-2.5 2.1-2.5-.7-2.5-2.1M12 5v1.5M12 17v1.5", filled = false, evenOdd = false),
        ),
        "Command" to listOf(
            NativeIconPath(d = "M9 7.5A2.5 2.5 0 1 0 6.5 10H10v4H6.5A2.5 2.5 0 1 0 9 16.5V13h6v3.5A2.5 2.5 0 1 0 17.5 14H14v-4h3.5A2.5 2.5 0 1 0 15 7.5V11H9z", filled = false, evenOdd = false),
        ),
        "Compass" to listOf(
            NativeIconPath(d = "M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0z", filled = false, evenOdd = false),
            NativeIconPath(d = "M16 8l-2.4 5.6L8 16l2.4-5.6z", filled = true, evenOdd = false),
        ),
        "Copy" to listOf(
            NativeIconPath(d = "M9 9h10a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1H9a1 1 0 0 1-1-1V10a1 1 0 0 1 1-1z", filled = false, evenOdd = false),
            NativeIconPath(d = "M5 15H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v1", filled = false, evenOdd = false),
        ),
        "Cpu" to listOf(
            NativeIconPath(d = "M6 4h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2z", filled = false, evenOdd = false),
            NativeIconPath(d = "M9 9h6v6H9z", filled = false, evenOdd = false),
            NativeIconPath(d = "M9 2v2M15 2v2M9 20v2M15 20v2M2 9h2M2 15h2M20 9h2M20 15h2", filled = false, evenOdd = false),
        ),
        "Database" to listOf(
            NativeIconPath(d = "M12 3c4.4 0 8 1.3 8 3s-3.6 3-8 3-8-1.3-8-3 3.6-3 8-3z", filled = false, evenOdd = false),
            NativeIconPath(d = "M4 6v6c0 1.7 3.6 3 8 3s8-1.3 8-3V6", filled = false, evenOdd = false),
            NativeIconPath(d = "M4 12v6c0 1.7 3.6 3 8 3s8-1.3 8-3v-6", filled = false, evenOdd = false),
        ),
        "Devices" to listOf(
            NativeIconPath(d = "M9 17H4a1 1 0 0 1-1-1V6a1 1 0 0 1 1-1h13a1 1 0 0 1 1 1v3", filled = false, evenOdd = false),
            NativeIconPath(d = "M14 11h6a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1h-6a1 1 0 0 1-1-1v-8a1 1 0 0 1 1-1z", filled = false, evenOdd = false),
            NativeIconPath(d = "M7 21h4", filled = false, evenOdd = false),
        ),
        "Download" to listOf(
            NativeIconPath(d = "M12 3v12m0 0 4-4m-4 4-4-4M5 21h14", filled = false, evenOdd = false),
        ),
        "EnvelopeSimple" to listOf(
            NativeIconPath(d = "M3 6a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z", filled = false, evenOdd = false),
            NativeIconPath(d = "M3 7l9 6 9-6", filled = false, evenOdd = false),
        ),
        "Eye" to listOf(
            NativeIconPath(d = "M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12z", filled = false, evenOdd = false),
            NativeIconPath(d = "M12 9a3 3 0 1 0 0 6 3 3 0 0 0 0-6z", filled = false, evenOdd = false),
        ),
        "EyeOff" to listOf(
            NativeIconPath(d = "M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7-10-7-10-7z", filled = false, evenOdd = false),
            NativeIconPath(d = "m4 4 16 16", filled = false, evenOdd = false),
        ),
        "FileEdit" to listOf(
            NativeIconPath(d = "M14 3H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-7M14 3v6h6", filled = false, evenOdd = false),
            NativeIconPath(d = "M18 13l3 3-5 5h-3v-3z", filled = false, evenOdd = false),
        ),
        "FileText" to listOf(
            NativeIconPath(d = "M6 3h7l5 5v13a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1z", filled = false, evenOdd = false),
            NativeIconPath(d = "M13 3v5h5", filled = false, evenOdd = false),
        ),
        "Filter" to listOf(
            NativeIconPath(d = "M22 3H2l8 9.46V19l4 2v-8.54z", filled = false, evenOdd = false),
        ),
        "Folder" to listOf(
            NativeIconPath(d = "M3 7a2 2 0 0 1 2-2h4l2 2h8a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z", filled = false, evenOdd = false),
        ),
        "FolderPlus" to listOf(
            NativeIconPath(d = "M3 7a2 2 0 0 1 2-2h4l2 2h8a2 2 0 0 1 2 2v9H3z", filled = false, evenOdd = false),
            NativeIconPath(d = "M12 11v5M9.5 13.5h5", filled = false, evenOdd = false),
        ),
        "Gauge" to listOf(
            NativeIconPath(d = "M12 14l4-4", filled = false, evenOdd = false),
            NativeIconPath(d = "M3.34 19a10 10 0 1 1 17.32 0", filled = false, evenOdd = false),
        ),
        "Gift" to listOf(
            NativeIconPath(d = "M3 9h18v12H3zM3 13h18M12 9v12", filled = false, evenOdd = false),
            NativeIconPath(d = "M12 9c-2 0-4-1-4-3a2 2 0 0 1 4 0c0 2 0 3 0 3zM12 9c2 0 4-1 4-3a2 2 0 0 0-4 0c0 2 0 3 0 3z", filled = false, evenOdd = false),
        ),
        "GitBranch" to listOf(
            NativeIconPath(d = "M6 3v12a3 3 0 0 0 3 3h6a3 3 0 0 0 3-3V9", filled = false, evenOdd = false),
            NativeIconPath(d = "M6 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4zM18 11a2 2 0 1 0 0-4 2 2 0 0 0 0 4z", filled = false, evenOdd = false),
        ),
        "Globe" to listOf(
            NativeIconPath(d = "M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0z", filled = false, evenOdd = false),
            NativeIconPath(d = "M3 12h18M12 3c2.5 2.5 3.8 5.7 3.8 9s-1.3 6.5-3.8 9c-2.5-2.5-3.8-5.7-3.8-9S9.5 5.5 12 3z", filled = false, evenOdd = false),
        ),
        "Grid" to listOf(
            NativeIconPath(d = "M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z", filled = false, evenOdd = false),
        ),
        "Gym" to listOf(
            NativeIconPath(d = "M6 9v6M3 11v2M18 9v6M21 11v2M6 12h12", filled = false, evenOdd = false),
        ),
        "Habit" to listOf(
            NativeIconPath(d = "M12 21s-7-4.5-7-10a4 4 0 0 1 7-2.5A4 4 0 0 1 19 11c0 5.5-7 10-7 10z", filled = false, evenOdd = false),
        ),
        "Heart" to listOf(
            NativeIconPath(d = "M12 20s-7-4.4-7-9.4A3.8 3.8 0 0 1 12 8a3.8 3.8 0 0 1 7 2.6c0 5-7 9.4-7 9.4z", filled = false, evenOdd = false),
        ),
        "History" to listOf(
            NativeIconPath(d = "M3 12a9 9 0 1 0 3-6.7L3 8", filled = false, evenOdd = false),
            NativeIconPath(d = "M3 3v5h5M12 7v5l3 2", filled = false, evenOdd = false),
        ),
        "Home" to listOf(
            NativeIconPath(d = "M3 11l9-8 9 8v9a2 2 0 0 1-2 2h-4v-7h-6v7H5a2 2 0 0 1-2-2z", filled = false, evenOdd = false),
        ),
        "Image" to listOf(
            NativeIconPath(d = "M3 5h18v14H3z", filled = false, evenOdd = false),
            NativeIconPath(d = "M5 17l4-4 3 3 2-2 5 3", filled = false, evenOdd = false),
            NativeIconPath(d = "M8 9h.01", filled = false, evenOdd = false),
        ),
        "Inbox" to listOf(
            NativeIconPath(d = "M22 12h-6l-2 3h-4l-2-3H2", filled = false, evenOdd = false),
            NativeIconPath(d = "M5.45 5.11 2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z", filled = false, evenOdd = false),
        ),
        "Info" to listOf(
            NativeIconPath(d = "M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0z", filled = false, evenOdd = false),
            NativeIconPath(d = "M12 11v5", filled = false, evenOdd = false),
            NativeIconPath(d = "M12 8h.01", filled = false, evenOdd = false),
        ),
        "Journal" to listOf(
            NativeIconPath(d = "M5 4a2 2 0 0 1 2-2h11v20H7a2 2 0 0 1-2-2z", filled = false, evenOdd = false),
            NativeIconPath(d = "M9 8h6M9 12h6M9 16h4", filled = false, evenOdd = false),
        ),
        "Key" to listOf(
            NativeIconPath(d = "M12 15a4 4 0 1 1-8 0 4 4 0 0 1 8 0z", filled = false, evenOdd = false),
            NativeIconPath(d = "M11 12l9-9", filled = false, evenOdd = false),
            NativeIconPath(d = "M17 6l3 3M14 9l3 3", filled = false, evenOdd = false),
        ),
        "Layers" to listOf(
            NativeIconPath(d = "m12 3 9 5-9 5-9-5 9-5zM3 12l9 5 9-5M3 16l9 5 9-5", filled = false, evenOdd = false),
        ),
        "List" to listOf(
            NativeIconPath(d = "M4 6h16M4 12h16M4 18h16", filled = false, evenOdd = false),
        ),
        "Loader" to listOf(
            NativeIconPath(d = "M21 12a9 9 0 1 1-6.219-8.56", filled = false, evenOdd = false),
        ),
        "Lock" to listOf(
            NativeIconPath(d = "M5 10h14v10H5z", filled = false, evenOdd = false),
            NativeIconPath(d = "M8 10V7a4 4 0 0 1 8 0v3M12 14v2", filled = false, evenOdd = false),
        ),
        "MapPin" to listOf(
            NativeIconPath(d = "M12 21s7-7.58 7-12a7 7 0 0 0-14 0c0 4.42 7 12 7 12z", filled = false, evenOdd = false),
            NativeIconPath(d = "M12 11.5a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z", filled = false, evenOdd = false),
        ),
        "Maximize" to listOf(
            NativeIconPath(d = "M8 3H3v5M16 3h5v5M8 21H3v-5M21 16v5h-5", filled = false, evenOdd = false),
        ),
        "Menu" to listOf(
            NativeIconPath(d = "M4 7h16M4 12h16M4 17h16", filled = false, evenOdd = false),
        ),
        "MessageCircle" to listOf(
            NativeIconPath(d = "M20 11.5a7.5 7.5 0 0 1-8 7.5 8.5 8.5 0 0 1-4-.9L4 20l1.1-3.5A7.5 7.5 0 1 1 20 11.5z", filled = false, evenOdd = false),
        ),
        "Monitor" to listOf(
            NativeIconPath(d = "M3 4h18v12H3z", filled = false, evenOdd = false),
            NativeIconPath(d = "M9 20h6M12 16v4", filled = false, evenOdd = false),
        ),
        "Mood" to listOf(
            NativeIconPath(d = "M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0z", filled = false, evenOdd = false),
            NativeIconPath(d = "M9 10v0M15 10v0", filled = false, evenOdd = false),
            NativeIconPath(d = "M8.5 14.5a4 4 0 0 0 7 0", filled = false, evenOdd = false),
        ),
        "Moon" to listOf(
            NativeIconPath(d = "M20 14.5A8 8 0 1 1 9.5 4a6.5 6.5 0 0 0 10.5 10.5z", filled = false, evenOdd = false),
        ),
        "MoreHoriz" to listOf(
            NativeIconPath(d = "M6 12h.01M12 12h.01M18 12h.01", filled = false, evenOdd = false),
        ),
        "MoreVert" to listOf(
            NativeIconPath(d = "M12 6h.01M12 12h.01M12 18h.01", filled = false, evenOdd = false),
        ),
        "Music" to listOf(
            NativeIconPath(d = "M9 18V5l11-2v13", filled = false, evenOdd = false),
            NativeIconPath(d = "M6 21a3 3 0 1 0 0-6 3 3 0 0 0 0 6z", filled = false, evenOdd = false),
            NativeIconPath(d = "M17 19a3 3 0 1 0 0-6 3 3 0 0 0 0 6z", filled = false, evenOdd = false),
        ),
        "NewChat" to listOf(
            NativeIconPath(d = "M21 15a2 2 0 0 1-2 2H8l-4 4V5a2 2 0 0 1 2-2h13a2 2 0 0 1 2 2z", filled = false, evenOdd = false),
            NativeIconPath(d = "M9 10h6M12 7v6", filled = false, evenOdd = false),
        ),
        "OpenExternal" to listOf(
            NativeIconPath(d = "M14 4h6v6", filled = false, evenOdd = false),
            NativeIconPath(d = "M20 4 11 13", filled = false, evenOdd = false),
            NativeIconPath(d = "M18 14v5a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h5", filled = false, evenOdd = false),
        ),
        "PaperPlaneTilt" to listOf(
            NativeIconPath(d = "M22 2L11 13M22 2l-7 20-4-9-9-4z", filled = false, evenOdd = false),
        ),
        "Paperclip" to listOf(
            NativeIconPath(d = "M21.44 11.05l-9.19 9.19a6 6 0 0 1-8.49-8.49l9.19-9.19a4 4 0 0 1 5.66 5.66l-9.2 9.19a2 2 0 0 1-2.83-2.83l8.49-8.48", filled = false, evenOdd = false),
        ),
        "Pause" to listOf(
            NativeIconPath(d = "M6 5h4v14H6zM14 5h4v14h-4z", filled = true, evenOdd = false),
        ),
        "Pencil" to listOf(
            NativeIconPath(d = "M14 4l6 6L9 21H3v-6z", filled = false, evenOdd = false),
            NativeIconPath(d = "M14 4l3-3 6 6-3 3", filled = false, evenOdd = false),
        ),
        "Phone" to listOf(
            NativeIconPath(d = "M7 2h10a1 1 0 0 1 1 1v18a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V3a1 1 0 0 1 1-1z", filled = false, evenOdd = false),
            NativeIconPath(d = "M11 18.5h2", filled = false, evenOdd = false),
        ),
        "Pin" to listOf(
            NativeIconPath(d = "M9 4h6l-1 6 3 3v2H7v-2l3-3-1-6zM12 15v5", filled = false, evenOdd = false),
        ),
        "Plant" to listOf(
            NativeIconPath(d = "M12 22V11", filled = false, evenOdd = false),
            NativeIconPath(d = "M12 11c-3 0-6-2-6-6 4 0 6 3 6 6z", filled = false, evenOdd = false),
            NativeIconPath(d = "M12 14c3 0 6-2 6-6-4 0-6 3-6 6z", filled = false, evenOdd = false),
            NativeIconPath(d = "M8 22h8", filled = false, evenOdd = false),
        ),
        "Play" to listOf(
            NativeIconPath(d = "M7 5l12 7-12 7z", filled = true, evenOdd = false),
        ),
        "Plug" to listOf(
            NativeIconPath(d = "M9 7V4M15 7V4M7 7h10v6a4 4 0 1 1-10 0z", filled = false, evenOdd = false),
            NativeIconPath(d = "M12 17v3", filled = false, evenOdd = false),
        ),
        "Plus" to listOf(
            NativeIconPath(d = "M12 5v14M5 12h14", filled = false, evenOdd = false),
        ),
        "Pomodoro" to listOf(
            NativeIconPath(d = "M20 13a8 8 0 1 1-16 0 8 8 0 0 1 16 0z", filled = false, evenOdd = false),
            NativeIconPath(d = "M12 13l3-2M9 4h6M12 4V2", filled = false, evenOdd = false),
        ),
        "Power" to listOf(
            NativeIconPath(d = "M12 2v10", filled = false, evenOdd = false),
            NativeIconPath(d = "M18.36 6.64a9 9 0 1 1-12.73 0", filled = false, evenOdd = false),
        ),
        "Print" to listOf(
            NativeIconPath(d = "M7 8V4a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v4", filled = false, evenOdd = false),
            NativeIconPath(d = "M7 18H5a2 2 0 0 1-2-2v-4a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v4a2 2 0 0 1-2 2h-2", filled = false, evenOdd = false),
            NativeIconPath(d = "M7 14h10v6a1 1 0 0 1-1 1H8a1 1 0 0 1-1-1z", filled = false, evenOdd = false),
        ),
        "Receipt" to listOf(
            NativeIconPath(d = "M5 3h14v18l-3-2-4 2-4-2-3 2z", filled = false, evenOdd = false),
            NativeIconPath(d = "M8 8h8M8 12h8M8 16h5", filled = false, evenOdd = false),
        ),
        "Refresh" to listOf(
            NativeIconPath(d = "M21 12a9 9 0 1 1-3-6.7M21 3v5h-5", filled = false, evenOdd = false),
        ),
        "Repeat" to listOf(
            NativeIconPath(d = "M17 2l4 4-4 4", filled = false, evenOdd = false),
            NativeIconPath(d = "M3 11V9a4 4 0 0 1 4-4h14", filled = false, evenOdd = false),
            NativeIconPath(d = "M7 22l-4-4 4-4", filled = false, evenOdd = false),
            NativeIconPath(d = "M21 13v2a4 4 0 0 1-4 4H3", filled = false, evenOdd = false),
        ),
        "Reset" to listOf(
            NativeIconPath(d = "M3 12a9 9 0 1 0 3-6.7L3 8", filled = false, evenOdd = false),
            NativeIconPath(d = "M3 3v5h5", filled = false, evenOdd = false),
        ),
        "Save" to listOf(
            NativeIconPath(d = "M5 4h11l4 4v12a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1z", filled = false, evenOdd = false),
            NativeIconPath(d = "M8 4v5h7V4M8 14h8v7H8z", filled = false, evenOdd = false),
        ),
        "Search" to listOf(
            NativeIconPath(d = "M11 18a7 7 0 1 0 0-14 7 7 0 0 0 0 14z", filled = false, evenOdd = false),
            NativeIconPath(d = "M20 20l-3.5-3.5", filled = false, evenOdd = false),
        ),
        "Send" to listOf(
            NativeIconPath(d = "M22 2L11 13", filled = false, evenOdd = false),
            NativeIconPath(d = "M22 2l-7 20-4-9-9-4z", filled = false, evenOdd = false),
        ),
        "Settings" to listOf(
            NativeIconPath(d = "M19.4 15a1.7 1.7 0 0 0 .3 1.8l.1.1a2 2 0 1 1-2.8 2.8l-.1-.1a1.7 1.7 0 0 0-1.8-.3 1.7 1.7 0 0 0-1 1.5V21a2 2 0 0 1-4 0v-.1a1.7 1.7 0 0 0-1-1.5 1.7 1.7 0 0 0-1.8.3l-.1.1a2 2 0 1 1-2.8-2.8l.1-.1a1.7 1.7 0 0 0 .3-1.8 1.7 1.7 0 0 0-1.5-1H3a2 2 0 0 1 0-4h.1a1.7 1.7 0 0 0 1.5-1 1.7 1.7 0 0 0-.3-1.8l-.1-.1a2 2 0 1 1 2.8-2.8l.1.1a1.7 1.7 0 0 0 1.8.3h0a1.7 1.7 0 0 0 1-1.5V3a2 2 0 0 1 4 0v.1a1.7 1.7 0 0 0 1 1.5h0a1.7 1.7 0 0 0 1.8-.3l.1-.1a2 2 0 1 1 2.8 2.8l-.1.1a1.7 1.7 0 0 0-.3 1.8v0a1.7 1.7 0 0 0 1.5 1H21a2 2 0 0 1 0 4h-.1a1.7 1.7 0 0 0-1.5 1z", filled = false, evenOdd = false),
            NativeIconPath(d = "M12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6z", filled = false, evenOdd = false),
        ),
        "Share" to listOf(
            NativeIconPath(d = "M4 12v7a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-7", filled = false, evenOdd = false),
            NativeIconPath(d = "M16 6l-4-4-4 4M12 2v14", filled = false, evenOdd = false),
        ),
        "Shield" to listOf(
            NativeIconPath(d = "M12 3 20 6v5c0 5-3.4 8.7-8 10-4.6-1.3-8-5-8-10V6z", filled = false, evenOdd = false),
        ),
        "Skip" to listOf(
            NativeIconPath(d = "M6 4l10 8-10 8zM18 5v14", filled = false, evenOdd = false),
        ),
        "Sliders" to listOf(
            NativeIconPath(d = "M21 4H14M10 4H3M21 12H12M8 12H3M21 20H16M12 20H3M14 2v4M8 10v4M16 18v4", filled = false, evenOdd = false),
        ),
        "Smartphone" to listOf(
            NativeIconPath(d = "M7 2h10a2 2 0 0 1 2 2v16a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2z", filled = false, evenOdd = false),
            NativeIconPath(d = "M11 18h2", filled = false, evenOdd = false),
        ),
        "Sparkle" to listOf(
            NativeIconPath(d = "M12 3l1.8 4.7L18 9l-4.2 1.3L12 15l-1.8-4.7L6 9l4.2-1.3z", filled = false, evenOdd = false),
            NativeIconPath(d = "M19 15l.6 1.6L21 17l-1.4.4L19 19l-.6-1.6L17 17l1.4-.4z", filled = false, evenOdd = false),
        ),
        "Star" to listOf(
            NativeIconPath(d = "M12 3l2.7 5.5 6 .9-4.35 4.25 1.05 6L12 17.8 6.6 20.65l1.05-6L3.3 9.4l6-.9z", filled = false, evenOdd = false),
        ),
        "Stop" to listOf(
            NativeIconPath(d = "M8 6h8a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2z", filled = true, evenOdd = false),
        ),
        "Sun" to listOf(
            NativeIconPath(d = "M12 3v2M12 19v2M3 12h2M19 12h2M5.6 5.6 7 7M17 17l1.4 1.4M18.4 5.6 17 7M7 17l-1.4 1.4", filled = false, evenOdd = false),
            NativeIconPath(d = "M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0z", filled = false, evenOdd = false),
        ),
        "SwitchVert" to listOf(
            NativeIconPath(d = "M8 4v16M8 20l-3-3M8 4l3 3M16 20V4M16 4l3 3M16 20l-3-3", filled = false, evenOdd = false),
        ),
        "Table" to listOf(
            NativeIconPath(d = "M4 4h16v16H4z", filled = false, evenOdd = false),
            NativeIconPath(d = "M4 10h16M4 15h16M10 4v16", filled = false, evenOdd = false),
        ),
        "Tablet" to listOf(
            NativeIconPath(d = "M5 3h14a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1z", filled = false, evenOdd = false),
            NativeIconPath(d = "M11 18h2", filled = false, evenOdd = false),
        ),
        "Tag" to listOf(
            NativeIconPath(d = "M4 11 11 4h8v8l-7 7z", filled = false, evenOdd = false),
            NativeIconPath(d = "M15.5 8.5h.01", filled = false, evenOdd = false),
        ),
        "Todo" to listOf(
            NativeIconPath(d = "M4 7a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2z", filled = false, evenOdd = false),
            NativeIconPath(d = "M8 10h8M8 14h5", filled = false, evenOdd = false),
            NativeIconPath(d = "M7 10l1 1 2-2", filled = false, evenOdd = false),
        ),
        "Trash" to listOf(
            NativeIconPath(d = "M3 6h18M8 6V4a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1v2M5 6l1 14a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2l1-14M10 11v6M14 11v6", filled = false, evenOdd = false),
        ),
        "Upload" to listOf(
            NativeIconPath(d = "M12 15V3m0 0 4 4m-4-4-4 4M5 21h14", filled = false, evenOdd = false),
        ),
        "User" to listOf(
            NativeIconPath(d = "M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8z", filled = false, evenOdd = false),
            NativeIconPath(d = "M4.5 20.5a7.5 7.5 0 0 1 15 0", filled = false, evenOdd = false),
        ),
        "UserPlus" to listOf(
            NativeIconPath(d = "M9 11.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z", filled = false, evenOdd = false),
            NativeIconPath(d = "M2.5 20.5a6.5 6.5 0 0 1 13 0M19 8v6M16 11h6", filled = false, evenOdd = false),
        ),
        "Users" to listOf(
            NativeIconPath(d = "M9 11.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z", filled = false, evenOdd = false),
            NativeIconPath(d = "M2.5 20.5a6.5 6.5 0 0 1 13 0", filled = false, evenOdd = false),
            NativeIconPath(d = "M16.5 4.8a3.5 3.5 0 0 1 0 6.9M22 20.5a6.5 6.5 0 0 0-4.2-6.1", filled = false, evenOdd = false),
        ),
        "Video" to listOf(
            NativeIconPath(d = "M3 6h14v12H3z", filled = false, evenOdd = false),
            NativeIconPath(d = "m17 10 4-3v10l-4-3", filled = false, evenOdd = false),
        ),
        "Water" to listOf(
            NativeIconPath(d = "M12 3l-5 7a6 6 0 0 0 10 0z", filled = false, evenOdd = false),
            NativeIconPath(d = "M9.5 13a2.5 2.5 0 0 0 2.5 2.5", filled = false, evenOdd = false),
        ),
        "Webhook" to listOf(
            NativeIconPath(d = "M18 16.98h-5.99c-1.1 0-1.95.94-2.48 1.9A4 4 0 0 1 2 17c.01-.7.2-1.4.57-2", filled = false, evenOdd = false),
            NativeIconPath(d = "M6 17l3.13-5.78c.53-.97.1-2.18-.5-3.1a4 4 0 1 1 6.89-4.06", filled = false, evenOdd = false),
            NativeIconPath(d = "M12 6l3.13 5.73C15.66 12.7 16.9 13 18 13a4 4 0 1 1-3.92 4.74", filled = false, evenOdd = false),
        ),
        "Wifi" to listOf(
            NativeIconPath(d = "M5 12.5a10 10 0 0 1 14 0M2 8.5a15 15 0 0 1 20 0M8.5 16.5a5 5 0 0 1 7 0", filled = false, evenOdd = false),
            NativeIconPath(d = "M12 20a1 1 0 1 0 0-2 1 1 0 0 0 0 2z", filled = true, evenOdd = false),
        ),
        "X" to listOf(
            NativeIconPath(d = "M6 6l12 12M18 6L6 18", filled = false, evenOdd = false),
        ),
        "XCircle" to listOf(
            NativeIconPath(d = "M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0z", filled = false, evenOdd = false),
            NativeIconPath(d = "m9 9 6 6M15 9l-6 6", filled = false, evenOdd = false),
        ),
        "add" to listOf(
            NativeIconPath(d = "M12 5v14M5 12h14", filled = false, evenOdd = false),
        ),
        "album" to listOf(
            NativeIconPath(d = "M4 7h13v13a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1z", filled = false, evenOdd = false),
            NativeIconPath(d = "M7 4h13v13a1 1 0 0 1-1 1H8a1 1 0 0 1-1-1V4z", filled = false, evenOdd = false),
        ),
        "download" to listOf(
            NativeIconPath(d = "M12 3v12m0 0 4-4m-4 4-4-4M5 21h14", filled = false, evenOdd = false),
        ),
        "dupe" to listOf(
            NativeIconPath(d = "M9 9h10a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1H9a1 1 0 0 1-1-1V10a1 1 0 0 1 1-1z", filled = false, evenOdd = false),
            NativeIconPath(d = "M5 15H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v1", filled = false, evenOdd = false),
        ),
        "heart" to listOf(
            NativeIconPath(d = "M12 20s-7-4.4-7-9.4A3.8 3.8 0 0 1 12 8a3.8 3.8 0 0 1 7 2.6c0 5-7 9.4-7 9.4z", filled = false, evenOdd = false),
        ),
        "info" to listOf(
            NativeIconPath(d = "M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0z", filled = false, evenOdd = false),
            NativeIconPath(d = "M12 16v-4M12 8h.01", filled = false, evenOdd = false),
        ),
        "more" to listOf(
            NativeIconPath(d = "M6 12h.01M12 12h.01M18 12h.01", filled = false, evenOdd = false),
        ),
        "person" to listOf(
            NativeIconPath(d = "M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8z", filled = false, evenOdd = false),
            NativeIconPath(d = "M4.5 20.5a7.5 7.5 0 0 1 15 0", filled = false, evenOdd = false),
        ),
        "place" to listOf(
            NativeIconPath(d = "M12 21s7-7.58 7-12a7 7 0 0 0-14 0c0 4.42 7 12 7 12z", filled = false, evenOdd = false),
            NativeIconPath(d = "M12 11.5a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z", filled = false, evenOdd = false),
        ),
        "removeFrom" to listOf(
            NativeIconPath(d = "M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0z", filled = false, evenOdd = false),
            NativeIconPath(d = "M8 12h8", filled = false, evenOdd = false),
        ),
        "restore" to listOf(
            NativeIconPath(d = "M4 7h16M6 7l1 12a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2l1-12M8 7V5a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1v2", filled = false, evenOdd = false),
            NativeIconPath(d = "M12 15V9M9 12l3-3 3 3", filled = false, evenOdd = false),
        ),
        "share" to listOf(
            NativeIconPath(d = "M4 12v7a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-7", filled = false, evenOdd = false),
            NativeIconPath(d = "M16 6l-4-4-4 4M12 2v14", filled = false, evenOdd = false),
        ),
        "trash" to listOf(
            NativeIconPath(d = "M3 6h18M8 6V4a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1v2M5 6l1 14a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2l1-14M10 11v6M14 11v6", filled = false, evenOdd = false),
        ),
    )
}

/** Geometry both shells need that the token table does not carry. */
public object CentraidGeometry {
    public const val APP_MARK_SMALL_STROKE: Double = 1.75
    public const val APP_MARK_STROKE: Double = 1.6
    public const val APP_MARK_VIEW_BOX: Int = 24
    public const val DURATION_ONE: Int = 140
    public const val DURATION_TWO: Int = 280
    public const val HAIRLINE: Int = 1
    public const val ICON_CHIP_RADIUS_RATIO: Double = 0.26
    public const val ICON_CHIP_TINT_DARK: Double = 0.2
    public const val ICON_CHIP_TINT_LIGHT: Double = 0.13
    public const val PAGE_MARGIN: Int = 18
    public const val TARGET_MIN_COARSE: Int = 44
    public const val TARGET_MIN_FINE: Int = 34
}
