// GENERATED by contracts/tools/export-native-theme.ts. Do not edit.
//
// The native lowering of packages/design (#1020, D-1020-E6). A hand-edited
// copy of this table is a fourth lowering with no drift gate, which is what
// `git diff --exit-code design copy mobile` in the mobile-jvm gate step
// exists to prevent.

package dev.centraid.design

/**
 * Copy, emitted from v0's per-app `*-copy.ts` leaves (#1020, D-1020-E6).
 *
 * STRINGS ONLY. A leaf's function exports are listed in `copy/<app>.json`'s
 * `functions` array and are NOT emitted: a function is a decision about how to
 * compose a sentence, and a generated Kotlin port of one would be a second
 * implementation that drifts. Wave 4 moves those into the kit.
 */
public object CentraidCopy {
    public object Notes {
        public const val ANCHOR_DEGRADED: String = "the passage was edited · this anchor now points at the note"
        public const val BACKLINKS_NOTE: String = "The reverse query is not built yet · these two are the link rows read forwards"
        public const val CAPTURE_CUSTODY: String = "On this phone only until the gateway answers"
        public const val CAPTURE_SCANNER: String = "Docs owns the scanner."
        public const val CAPTURE_WHAT: String = "This is a photograph, attached to a note."
        public const val CONFLICT_INTACT: String = "Nothing was overwritten."
        public const val CONFLICT_KEPT: String = "Both are kept."
        public const val CONFLICT_TITLE: String = "Two devices changed this passage"
        public const val DELETE_NOTE_BODY: String = "It stays restorable for 30 days, with its links, tags and files."
        public const val DELETE_NOTE_TITLE: String = "Move this note to trash?"
        public const val DELETE_NOTE_VERB: String = "Trash"
        public const val DELETE_NOTEBOOK_KEPT: String = "Nothing is deleted with it."
        public const val DELETE_NOTEBOOK_VERB: String = "Delete"
        public const val DENIED_ASK: String = "Ask the owner of this vault for access."
        public const val DENIED_INTACT: String = "Your notes, versions and receipts are untouched."
        public const val DENIED_TITLE: String = "Notes cannot read this vault"
        public const val EMPTY_DAY_ONE: String = "Write the first one."
        public const val HISTORY_NEEDS_NOTE: String = "Open a note to see its versions."
        public const val JOURNAL_ROW: String = "Journal · written by People · kept apart from the rest"
        public const val ORIGIN_SEAT_ONLY: String = "This act belongs to the phone."
        public const val PENDING_CHIP: String = "Saved on this device · queued for the vault"
        public const val POWERBOX_FOOT: String = "Locker is not searched · a secret is never a link target"
        public const val RAIL_NOTEBOOKS: String = "Notebooks · where a note lives"
        public const val RAIL_TAGS: String = "Tags · how a note is seen"
        public const val RENAME_REFUSAL: String = "A notebook cannot share a name with its sibling"
        public const val SEARCH_EMPTY: String = "Type to search titles and bodies."
        public const val SEARCH_SCOPE: String = "the live library"
        public const val SEND_TO_TASKS: String = "Send to Tasks"
        public const val STALE_VERB: String = "Refresh"
        public const val TRASH_STATUS: String = "Restorable for 30 days, then erased"
        public const val UNFILED_NOTE: String = "a note that was never filed still opens"
        public const val UNFILED_ROW: String = "Unfiled"
        public const val VERSION_TEXT_ELSEWHERE: String = "This version's text is not on this device."
        public const val VOICE_AUDIO_READABLE: String = "The audio is safe and readable as audio."
        public const val VOICE_NO_TRANSCRIPT_YET: String = "No transcript yet."
        public const val WINDOW_END_VERB: String = "Show older"
    }

    public object Photos {
        public const val PHOTOS_ARCHIVE: String = "Archive"
        public const val PHOTOS_ARCHIVE_EMPTY: String = "Archive is empty."
        public const val PHOTOS_EMPTY_DUPLICATES: String = "No near-identical clusters in your library."
        public const val PHOTOS_EMPTY_FAVORITES: String = "No favorites yet — tap the heart on any photograph."
        public const val PHOTOS_ERROR_EDIT_NOT_SAVED: String = "Photograph not saved."
        public const val PHOTOS_ERROR_EXPORT_FAILED: String = "Photograph not exported."
        public const val PHOTOS_ERROR_FREE_UP_PAUSED: String = "Free up vault paused."
        public const val PHOTOS_ERROR_IN_CLOUD: String = "Original is still in iCloud."
        public const val PHOTOS_ERROR_WRITE_NOT_SAVED: String = "Photo change not saved."
        public const val PHOTOS_SAVE_AS_NEW: String = "Save as a new photograph"
        public const val PHOTOS_SAVE_AS_NEW_EXPLANATION: String = "Saving writes a new photograph dated today; the original is not touched."
        public const val PHOTOS_SAVED_AS_NEW: String = "Saved as a new photograph"
        public const val PHOTOS_SEARCH_PLACEHOLDER: String = "Search photographs, people, places, albums"
        public const val PHOTOS_UNARCHIVE: String = "Unarchive"
        public const val PHOTOS_VIDEO_STATUS: String = "Video · playing from the display copy on this device"
        public const val PLACE_NO_LOCATION: String = "No location yet"
        public const val PLACE_UNNAMED: String = "A place with no name yet"
    }

    public object Shared {
        public const val LEAVING_SHARED_VAULT: String = "Leaving ends your access to this vault; copies already shared into your own vault stay."
        public const val SAVED_TO_MY_VAULT: String = "Saved to my vault"
        public const val SHARE_ENRICHMENT_IS_THEIRS: String = "Their vault makes its own thumbnails, text and search for the copy, under their settings."
        public const val SHARE_FAILED: String = "Could not share with the selected people."
        public const val SHARE_IS_A_COPY: String = "Ending a share removes their copy and stops updates; anything they exported first stays theirs."
        public const val VAULT_DENIED_TITLE: String = "No vault access yet."
    }

    public object Tally {
    }

}
