import { defineConfig } from "oxfmt";
import ultracite from "ultracite/oxfmt";

// Ultracite supplies the reviewed formatting baseline. Oxfmt is the sole style
// owner and this file is the repository's only formatter configuration.
//
// In addition to the preset's standard generated-output exclusions, these
// entries exist because oxfmt must not rewrite them:
//   - `.governance/**` and the kit-managed CI workflow are owned by
//     governance-kit and re-stamped on every `kit update`; reformatting them
//     diverges from upstream and re-breaks CI (this happened once already on
//     the 0.2 -> 0.3 update).
//   - the rest are generator output whose byte-exactness is asserted elsewhere,
//     so reformatting them just re-breaks `format:check` on regeneration.
const base = ultracite;

export default defineConfig({
  ...base,
  sortImports: {
    groups: [
      "builtin",
      "external",
      ["internal", "subpath"],
      ["parent", "sibling", "index"],
      "style",
      "unknown",
    ],
    ignoreCase: true,
    internalPattern: ["@centraid/", "~/", "@/", "#"],
    newlinesBetween: true,
    order: "asc",
    // Import evaluation order can be observable. Formatting never reorders
    // side-effect imports.
    sortSideEffects: false,
  },
  sortPackageJson: {
    sortScripts: true,
  },
  ignorePatterns: [
    // Ultracite's baseline contains dependencies/VCS state, build output,
    // generated code, coverage, mobile build trees, lockfiles, and generated
    // framework declarations. Those files have external or generator owners.
    ...base.ignorePatterns,
    // Xcode owns asset catalog metadata.
    "**/*.xcassets/**/Contents.json",
    // governance-kit owns this vendored tree and workflow byte-for-byte.
    ".governance/**",
    ".github/workflows/governance.yml",
    // Governance freezes historical receipts/ledgers byte-for-byte and freezes
    // historical sections in the constitution and quality ledger.
    "receipts/**",
    "COSTS.md",
    "STEERING.md",
    "CONSTITUTION.md",
    "QUALITY.md",
    // Design-agent handoff bundle is vendored byte-for-byte (#707); the
    // prototype runtime is generated by the design tool, not owned here.
    "docs/design/handoff-binding-layer/**",
    // Generator-owned outputs with regeneration checks elsewhere in the repo.
    "apps/web/public/sw.js",
    "scripts/docs-site/src/content/**",
    "packages/blueprints/manifest.json",
    "packages/design/kit/tokens.css",
    "packages/design/kit/wall.css",
  ],
});
