//! `cargo xtask photos-sample` — regenerate the Photos sample fixtures from the
//! sample files themselves (#1025 S4).
//!
//! ## WHY THIS EXISTS
//!
//! `contracts/apps/photos/sample/manifest.json` and the `core_content_item`
//! rows of `contracts/apps/photos/rows.json` name the same nineteen frames by
//! their digest. That digest was SHA-256 and is now BLAKE3
//! (D-1025-S4-1), and `contracts/apps/photos/rows.json` additionally carried
//! `blob:sha256-` URIs, which `crates/blobs` stopped being able to parse at all
//! when #1025 S3 made `blob:blake3-` the only form. Both files were generated by
//! v0 tooling the v0 retirement deleted, so there was nothing to regenerate them
//! WITH — and hand-editing nineteen digests is not something a reviewer can
//! check.
//!
//! ## THE RULE IT ENFORCES, which is what makes it a generator and not a script
//!
//! *A sample-backed content row is named by the hash of the file it is.* The
//! manifest is read off the PNGs on disk — dimensions from the IHDR chunk, size
//! and digest from the bytes — and every `core_content_item` row is matched to a
//! frame **by its declared `byte_size`** (the nineteen are distinct, and this
//! asserts it), then rewritten to carry that frame's hash in both the column and
//! the URI. Run it twice and the second run changes nothing.
//!
//! The one frame that is not a file is the twenty-four-byte video v0's seed
//! carried inline as base64. Its bytes are [`INLINE_VIDEO_BASE64`], recovered
//! from that seed before it was deleted and now kept here, because a frame whose
//! bytes nothing in the repository holds is a digest nobody can ever check.
//!
//! ## It writes the files; `format:check` restyles them
//!
//! Output is `serde_json` pretty-printing, which is not oxfmt's JSON style. The
//! repository's existing convention for generated JSON under `contracts/` is
//! generate-then-format, and `bun run format` is what settles the bytes.

use std::collections::BTreeMap;
use std::path::Path;

use anyhow::{Context, Result, bail};

/// v0's `seed.js` `VIDEO.data`: 24 bytes of MP4 header, base64.
pub const INLINE_VIDEO_BASE64: &str = "AAAAHGZ0eXBtcDQyAAAAAG1wNDJpc29t";

/// The inline frame's own facts, which are not readable off any file.
const INLINE_VIDEO: (&str, u32, u32) = ("tahoe-pan.mp4", 360, 240);

/// Why the inline frame is listed at all — carried into the manifest verbatim so
/// the generated file explains itself to its next reader.
const INLINE_VIDEO_WHY: &str = "A tiny deterministic video payload, inline base64 in v0's seed rather than a file beside it. The journey corpus needs media-kind diversity, not playback fidelity: the viewer's capability rows and the video badge read the vault's honest kind/duration metadata. Its bytes are `INLINE_VIDEO_BASE64` in crates/xtask/src/photos_sample.rs; nothing is copied into contracts/ for it.";

struct Frame {
    file: String,
    width: u32,
    height: u32,
    byte_size: u64,
    hash: String,
    inline: bool,
}

/// Regenerate both fixtures. Returns the paths it wrote.
pub fn run(root: &Path) -> Result<Vec<String>> {
    let sample = root.join("contracts/apps/photos/sample");
    let mut frames = read_png_frames(&sample)?;
    frames.push(inline_frame()?);
    frames.sort_by(|left, right| left.file.cmp(&right.file));

    let mut written = Vec::new();
    write_json(&sample.join("manifest.json"), &manifest(&frames)?)?;
    written.push("contracts/apps/photos/sample/manifest.json".to_owned());

    let rows_path = root.join("contracts/apps/photos/rows.json");
    let rows = rekey_rows(&rows_path, &frames)?;
    write_json(&rows_path, &rows)?;
    written.push("contracts/apps/photos/rows.json".to_owned());
    Ok(written)
}

fn read_png_frames(sample: &Path) -> Result<Vec<Frame>> {
    let mut frames = Vec::new();
    for entry in std::fs::read_dir(sample)
        .with_context(|| format!("reading {}", sample.display()))?
        .collect::<std::result::Result<Vec<_>, _>>()?
    {
        let path = entry.path();
        if path.extension().is_none_or(|ext| ext != "png") {
            continue;
        }
        let bytes = std::fs::read(&path)?;
        let (width, height) = png_dimensions(&bytes)
            .with_context(|| format!("{} is not a PNG this reads", path.display()))?;
        frames.push(Frame {
            file: path
                .file_name()
                .and_then(|name| name.to_str())
                .context("a sample file name is UTF-8")?
                .to_owned(),
            width,
            height,
            byte_size: bytes.len() as u64,
            hash: hash_of(&bytes),
            inline: false,
        });
    }
    if frames.is_empty() {
        bail!("{} holds no PNG frames", sample.display());
    }
    Ok(frames)
}

fn inline_frame() -> Result<Frame> {
    use base64::Engine as _;
    let bytes = base64::engine::general_purpose::STANDARD
        .decode(INLINE_VIDEO_BASE64)
        .context("the inline video payload is base64")?;
    let (file, width, height) = INLINE_VIDEO;
    Ok(Frame {
        file: file.to_owned(),
        width,
        height,
        byte_size: bytes.len() as u64,
        hash: hash_of(&bytes),
        inline: true,
    })
}

/// The one digest, the vault's own: `blake3`, lowercase hex (#1025 S4).
fn hash_of(bytes: &[u8]) -> String {
    blake3::hash(bytes)
        .as_bytes()
        .iter()
        .fold(String::with_capacity(64), |mut text, byte| {
            use std::fmt::Write as _;
            let _ = write!(text, "{byte:02x}");
            text
        })
}

/// Width and height out of a PNG's IHDR, which is always the first chunk.
fn png_dimensions(bytes: &[u8]) -> Option<(u32, u32)> {
    const SIGNATURE: &[u8] = b"\x89PNG\r\n\x1a\n";
    if bytes.len() < 33 || !bytes.starts_with(SIGNATURE) || &bytes[12..16] != b"IHDR" {
        return None;
    }
    let width = u32::from_be_bytes(bytes[16..20].try_into().ok()?);
    let height = u32::from_be_bytes(bytes[20..24].try_into().ok()?);
    Some((width, height))
}

fn manifest(frames: &[Frame]) -> Result<serde_json::Value> {
    let files: Vec<serde_json::Value> = frames
        .iter()
        .map(|frame| {
            let mut entry = serde_json::json!({
                "file": frame.file,
                "width": frame.width,
                "height": frame.height,
                "long_edge": frame.width.max(frame.height),
                "byte_size": frame.byte_size,
                "content_hash": frame.hash,
            });
            if frame.inline {
                entry["inline"] = serde_json::Value::Bool(true);
                entry["why"] = serde_json::Value::String(INLINE_VIDEO_WHY.to_owned());
            }
            entry
        })
        .collect();
    let inline = frames.iter().filter(|frame| frame.inline).count();
    Ok(serde_json::json!({
        "schema": "centraid-photos-sample/1",
        "source": "contracts/apps/photos/sample",
        "generator": "cargo xtask photos-sample",
        "thumbEdge": 360,
        "rule": "long_edge <= thumbEdge",
        "why": "The Photos grid paints the ORIGINAL instead of probing a ?variant=thumb derivative when an asset's long edge is at or under THUMB_EDGE. Every sample frame is <= 360 px on its long edge ON PURPOSE, so a seeded vault renders without a preview backstop having generated anything. That coupling between a seed's PIXEL DIMENSIONS and a renderer's constant had no test on either side.",
        "files": files,
        "inlineFrames": inline,
        "pngFrames": frames.len() - inline,
    }))
}

/// Rewrite every `core_content_item` row to carry the hash of the frame it IS.
fn rekey_rows(path: &Path, frames: &[Frame]) -> Result<serde_json::Value> {
    let text =
        std::fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
    let mut document: serde_json::Value = serde_json::from_str(&text)?;

    let mut by_size: BTreeMap<u64, &Frame> = BTreeMap::new();
    for frame in frames {
        if by_size.insert(frame.byte_size, frame).is_some() {
            // The match is by size, so two frames of one size would silently
            // re-key a row to the wrong file's hash.
            bail!(
                "two sample frames are {} bytes, so a row cannot be matched by size",
                frame.byte_size
            );
        }
    }

    let tables = document
        .as_array_mut()
        .context("rows.json is an array of tables")?;
    let mut rekeyed = 0usize;
    for table in tables {
        if table.get("table").and_then(serde_json::Value::as_str) != Some("core_content_item") {
            continue;
        }
        let columns: Vec<String> = serde_json::from_value(table["columns"].clone())?;
        let uri_at = column_index(&columns, "content_uri")?;
        let hash_at = column_index(&columns, "content_hash")?;
        let size_at = column_index(&columns, "byte_size")?;
        for row in table["rows"]
            .as_array_mut()
            .context("a table's rows are an array")?
        {
            let row = row.as_array_mut().context("a row is an array")?;
            let size = row[size_at].as_u64().context("byte_size is a number")?;
            let frame = by_size.get(&size).with_context(|| {
                format!("no sample frame is {size} bytes, so this row names no file")
            })?;
            row[hash_at] = serde_json::Value::String(frame.hash.clone());
            row[uri_at] = serde_json::Value::String(format!("blob:blake3-{}", frame.hash));
            rekeyed += 1;
        }
    }
    if rekeyed == 0 {
        bail!("{} has no core_content_item rows to key", path.display());
    }
    Ok(document)
}

fn column_index(columns: &[String], name: &str) -> Result<usize> {
    columns
        .iter()
        .position(|column| column == name)
        .with_context(|| format!("core_content_item has no `{name}` column"))
}

fn write_json(path: &Path, value: &serde_json::Value) -> Result<()> {
    let mut text = serde_json::to_string_pretty(value)?;
    text.push('\n');
    std::fs::write(path, text).with_context(|| format!("writing {}", path.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_png_header_gives_its_dimensions_and_anything_else_gives_none() {
        let mut png = Vec::from(*b"\x89PNG\r\n\x1a\n");
        png.extend_from_slice(&13_u32.to_be_bytes());
        png.extend_from_slice(b"IHDR");
        png.extend_from_slice(&270_u32.to_be_bytes());
        png.extend_from_slice(&360_u32.to_be_bytes());
        png.extend_from_slice(&[8, 6, 0, 0, 0, 0, 0, 0, 0]);
        assert_eq!(png_dimensions(&png), Some((270, 360)));
        assert_eq!(
            png_dimensions(b"not a png at all, not even long enough"),
            None
        );
    }

    /// THE INLINE FRAME'S BYTES ARE KEPT, so its digest is checkable.
    #[test]
    fn the_inline_video_is_twenty_four_bytes_and_hashes_to_a_stable_name() {
        let frame = inline_frame().expect("the payload decodes");
        assert_eq!(frame.byte_size, 24);
        assert_eq!(frame.hash.len(), 64);
        assert_eq!(frame.hash, inline_frame().unwrap().hash);
    }
}
