#!/usr/bin/env node
/**
 * Single-source monorepo version → workspace package.jsons (issue #501 / #468
 * J6).
 *
 * Canonical string: root package.json `version`. The mobile native numbers are
 * NOT stamped here: `apps/mobile/ios` and `android` are generated by
 * `expo prebuild` and never committed, and `apps/mobile/app.config.ts` derives
 * `version`, `ios.buildNumber` and `android.versionCode` from the workspace
 * package.json + `version-core.cjs` at every prebuild. Stamping the workspace
 * package IS the native stamp.
 *
 *   node scripts/release/sync-versions.ts [--version X.Y.Z] [--dry-run]
 *
 * When --version is omitted, re-stamps workspaces to match root.
 */

import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import { pathToFileURL } from "node:url";

const root = path.resolve(import.meta.dirname, "../..");
const require = createRequire(import.meta.url);
const { nativeBuildNumber } = require(
  path.join(root, "apps/mobile/src/version-core.cjs")
) as { nativeBuildNumber: (version: string) => number };

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function collectPackageJsons(rootDir: string) {
  const out = [path.join(rootDir, "package.json")];
  for (const dir of ["packages", "apps"]) {
    const base = path.join(rootDir, dir);
    if (!existsSync(base)) continue;
    for (const name of readdirSync(base)) {
      const p = path.join(base, name, "package.json");
      if (existsSync(p)) out.push(p);
    }
  }
  return out;
}

export function runSyncVersions({
  rootDir = root,
  version,
  dryRun = false,
}: {
  rootDir?: string;
  version?: string;
  dryRun?: boolean;
} = {}) {
  const rootPkgPath = path.join(rootDir, "package.json");
  const rootPkg: unknown = JSON.parse(readFileSync(rootPkgPath, "utf8"));
  if (!isRecord(rootPkg) || typeof rootPkg.version !== "string") {
    throw new Error(`unparseable package.json at ${rootPkgPath}`);
  }
  const prev = rootPkg.version;
  const ver = version || prev;
  if (!/^\d+\.\d+\.\d+$/u.test(ver)) {
    throw new Error(`unparseable version ${ver}`);
  }
  const build = nativeBuildNumber(ver);

  function write(filePath: string, content: string) {
    if (dryRun) return;
    writeFileSync(filePath, content);
  }

  const workspaces: string[] = [];
  for (const p of collectPackageJsons(rootDir)) {
    const parsed: unknown = JSON.parse(readFileSync(p, "utf8"));
    if (!isRecord(parsed)) continue;
    if (parsed.version === prev || p === rootPkgPath) {
      parsed.version = ver;
      write(p, JSON.stringify(parsed, null, 2) + "\n");
      workspaces.push(path.relative(rootDir, p));
    }
  }

  return { prev, version: ver, build, dryRun, workspaces };
}

function isMain() {
  const entry = process.argv[1];
  if (!entry) return false;
  try {
    return import.meta.url === pathToFileURL(path.resolve(entry)).href;
  } catch {
    return false;
  }
}

if (isMain()) {
  const args = process.argv.slice(2);
  let version = null;
  let dryRun = false;
  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--version") version = args[++i];
    else if (args[i] === "--dry-run") dryRun = true;
  }
  try {
    const report = runSyncVersions({ version: version || undefined, dryRun });
    console.log(JSON.stringify(report, null, 2));
  } catch (error) {
    console.error(error instanceof Error ? error.message : error);
    process.exit(2);
  }
}
