// What each springboard tile SAYS, derived from replica rows (#708 A).
//
// The Binding Layer's Home is made of content, not of icons: every tile carries
// an INVARIANT header — app icon, app name at the UI role, a count in the
// tabular numeric register — over a body whose STRUCTURE is different per app.
// The header is what makes the grid one grid; the body is what makes a tile
// recognisable at a glance without reading a word of it.
//
// This module is pure (no React, no react-native, no replica imports beyond the
// row type) for the same reason ./catalog and ./band are: the selection rules
// are the part that can be wrong, so they are the part that is unit-tested.
// ./useSpringboardTiles owns the reads; this owns what to do with the rows.
//
// Two honesty rules run through everything here:
//
//  1. A tile never invents content. Where mobile has no read path for an app
//     (Locker: its items are sealed columns behind an online, session-gated
//     `locker.items` RPC — see apps/locker/LockerHome.tsx), the tile renders its
//     designed body with no data and its count reads withheld, never zero.
//  2. "Empty" and "not loaded yet" are different answers. First-run means the
//     vault has no content; a query still in flight means we do not know yet.
//     `springboardState` refuses to call first-run on either an unsettled or an
//     unknown tile, because the day-one treatment is a claim about the vault.

import type { ReplicaRow } from "@centraid/client/replica/native";

/** Every tile's data-availability answer, before any styling decision. */
export type TileStatus =
  /** A read this tile needs has not settled. Body renders static skeletons. */
  | "loading"
  /** No replica/grant/read path — we cannot say whether content exists. */
  | "unknown"
  /** Settled, and the app genuinely holds nothing. */
  | "empty"
  /** Settled, with something to show. */
  | "content";

export interface TilePhoto {
  id: string;
  /**
   * Absolute gateway thumb URL, or a pinned on-device thumbnail path.
   *
   * `undefined` when the asset EXISTS but its bytes are not addressable from
   * this device yet — no gateway to fetch from, and nothing pinned locally.
   * That is a cell, not an absence: it paints the skeleton ground at the exact
   * geometry the photograph will occupy and keeps it until the bytes arrive.
   * Dropping the row instead is what made a vault of ten photographs render as
   * one blank rectangle under a header reading "10".
   */
  uri?: string;
  /**
   * The undownscaled bytes, when `uri` points at a DERIVATIVE of them.
   *
   * The thumb variant is generated by the gateway's preview backstop, which
   * runs after the record lands — so between those two moments `uri` 404s while
   * the original is whole in CAS, and the mosaic sat on its skeleton ground for
   * ever with no way to know the difference. Absent for a pinned on-device
   * thumbnail, which is not a variant of anything reachable.
   */
  originalUri?: string;
}

export interface TileFace {
  /** The person's `party_id` — a STABLE identity. The renderer derives the
   *  circle's hue from this when there is no stored colour, so it has to be the
   *  id and never the display name: a rename must not repaint a person. */
  id: string;
  initials: string;
  /**
   * The person's own avatar colour when they have chosen one; else undefined.
   *
   * A stored colour always wins — it is the member's (or the People app's) own
   * choice and nothing here overrides it. Blank and whitespace-only values are
   * NOT a choice, though: the seeded vault leaves `avatar_color` empty, and
   * treating `""` as a colour is what painted the tile's faces with no fill at
   * all. Those fall through to the derivation.
   */
  color?: string;
}

export interface TileTaskRow {
  id: string;
  title: string;
  done: boolean;
}

/** One ruled row in the Docs body: the file's name and its size in mono. */
export interface TileDocRow {
  id: string;
  name: string;
  /** Already formatted ("4.1 MB"); empty when the byte size is not recorded. */
  size: string;
}

/** The structurally distinct bodies. One member per first-party app. */
export type TileBody =
  | { kind: "photos"; photos: TilePhoto[] }
  | { kind: "docs"; rows: TileDocRow[] }
  | { kind: "agenda"; title: string; at: string; after: string }
  | { kind: "people"; faces: TileFace[]; more: number }
  | { kind: "tasks"; rows: TileTaskRow[] }
  // `after` is optional: the brief's third line (:5079, "Everyday · £1,120")
  // needs a second read mobile's ./useSpringboardTiles does not build yet
  // (this month's figure is already read; a same-period rolling comparison
  // is a follow-up, out of scope for the tile-body layer this module and
  // ./TileBody own). The body renders the line the moment a caller supplies
  // it and stays honestly silent otherwise, rather than fabricating one.
  | { kind: "tally"; figure: string; caption: string; after?: string }
  | { kind: "locker"; locked: boolean }
  | { kind: "notes"; title: string; excerpt: string };

export interface TileData {
  appId: string;
  status: TileStatus;
  /** `undefined` renders the withheld glyph, never a fabricated 0. */
  count?: number;
  /** True when `count` hit the read's ceiling, so it renders as `N+`. */
  countCapped?: boolean;
  /** What the count counted — "open", "this month", "next 7 days". */
  countLabel: string;
  body: TileBody;
}

const text = (row: ReplicaRow, key: string): string =>
  row[key] == null ? "" : String(row[key]);

/** Newest first by an ISO column; ties fall back to the row's own id column. */
function byDescending(
  column: string,
  idColumn: string
): (left: ReplicaRow, right: ReplicaRow) => number {
  return (left, right) =>
    text(right, column).localeCompare(text(left, column)) ||
    text(left, idColumn).localeCompare(text(right, idColumn));
}

// ──────────────────────────────────────────────────────────────── photos ───

/**
 * The newest assets, as a mosaic that bleeds to the tile edge.
 *
 * Rows arrive already ordered by the read, but a replica read merges N vault
 * scopes, so the order is re-established here rather than trusted.
 *
 * An asset whose bytes are not addressable yet still yields a CELL, with no
 * `uri`. "The tile exists" and "the bytes are decoded" are two different
 * moments and the window between them is a designed state: the cell holds the
 * exact geometry the photograph will occupy and paints the skeleton ground
 * meanwhile. Returning fewer cells than there are photographs would make the
 * tile reflow when they land, and returning none at all — which is what a
 * gateway-side seed produced — draws an empty box under a header saying 10.
 */
export function selectPhotoMosaic(
  rows: readonly ReplicaRow[],
  gatewayBase: string | undefined,
  pinned: (scopeId: string, contentId: string) => string | undefined,
  count = MOSAIC_SLOTS
): TilePhoto[] {
  return [...rows]
    .sort(byDescending("captured_at", "asset_id"))
    .flatMap((row) => {
      const contentId = text(row, "content_id");
      const assetId = text(row, "asset_id");
      // No content id is the one case with no cell to draw: there is no
      // photograph behind it to be waiting for.
      if (!contentId || !assetId) return [];
      const scopeId = text(row, "__centraidScopeId");
      const local = pinned(scopeId, contentId);
      if (local) return [{ id: assetId, uri: local }];
      if (!gatewayBase) return [{ id: assetId }];
      // Same address the Photos timeline builds (apps/photos/timeline-engine),
      // so a tile thumbnail is a cache hit on the grid the tile opens into.
      const blob = `${gatewayBase}/centraid/_gateway/blobs/${encodeURIComponent(
        scopeId
      )}/${encodeURIComponent(contentId)}`;
      const variant = text(row, "kind") === "video" ? "poster" : "thumb";
      return [
        { id: assetId, uri: `${blob}?variant=${variant}`, originalUri: blob },
      ];
    })
    .slice(0, count);
}

/** True when the mosaic has cells but not one of them can paint bytes yet — the
 *  moment the tile has to SAY where the originals are rather than look broken. */
export function mosaicAwaitingBytes(photos: readonly TilePhoto[]): boolean {
  return photos.length > 0 && photos.every((photo) => !photo.uri);
}

/**
 * How many cells the mosaic draws. Always this many, in every state.
 *
 * Four is ONE row across the tile's full bled width (the brief's
 * `repeat(4,1fr)`, :5044) — mobile never draws the desktop's second row. A
 * FIXED count is the no-reflow contract: the grid looks the same the instant it
 * mounts, while the read is in flight, while the bytes are being fetched, and
 * once they land — only the contents of each cell change.
 */
export const MOSAIC_SLOTS = 4;

/**
 * The cell's height in points, and the reason it is stated rather than derived.
 *
 * A percentage-width cell sized by `aspectRatio` can resolve to zero height,
 * and a zero-height cell inside a container with a minimum height of its own is
 * invisible — the container's ground is all that shows, which reads as one
 * large deliberate blank rectangle instead of as a layout failure. That is
 * exactly how a seeded vault's Photos tile appeared to be a design decision.
 * Lives here, beside the slot count, so the geometry the tile depends on is
 * asserted in the same place the selection rules are.
 *
 * The row bleeds to the full card width rather than sitting inside three
 * columns of padded content, so a single row of four reads roughly square at
 * ordinary phone widths. It carries the whole tile's vertical budget alone
 * rather than splitting it across two rows.
 */
export const MOSAIC_CELL_HEIGHT = 88;

/**
 * Tile content padding — `R.gap.m` in the brief (:5031). Shared between the
 * card's own padding (./LauncherGrid) and the photo mosaic's negative margins
 * (./TileBody): the mosaic reaching the tile's own edge is only true while its
 * bleed exactly cancels whatever padding the card uses, so a mismatch here is
 * a photo mosaic that stops a few points short of the edge for no visible
 * reason.
 */
export const TILE_PAD = 12;

/**
 * The mosaic's slots: exactly `MOSAIC_SLOTS` of them, each holding a photograph
 * or nothing. A slot with nothing in it is still a cell and still paints.
 */
export function mosaicCells(
  photos: readonly TilePhoto[]
): (TilePhoto | undefined)[] {
  return Array.from({ length: MOSAIC_SLOTS }, (_, index) => photos[index]);
}

// ──────────────────────────────────────────────────────────── prose bodies ───

/**
 * Decode a `core.content_item` body. Notes and short documents store their text
 * as a `data:` URI — the wire shape `core.content_item` bodies always take;
 * anything else (a PDF, an image) has no prose to excerpt and returns "".
 */
export function decodeProse(contentUri: unknown): string {
  if (typeof contentUri !== "string" || !contentUri.startsWith("data:"))
    return "";
  const comma = contentUri.indexOf(",");
  if (comma < 0) return "";
  const meta = contentUri.slice(0, comma);
  const payload = contentUri.slice(comma + 1);
  // Base64 bodies need `atob`, which is not worth reaching for on a tile: the
  // percent-encoded form is what the note/doc editors write, and a tile that
  // cannot read a body simply shows its title.
  if (meta.includes(";base64")) return "";
  try {
    return decodeURIComponent(payload);
  } catch {
    return "";
  }
}

/**
 * The first line of actual PROSE.
 *
 * Headings are skipped outright rather than stripped: the tile already shows
 * the note's or document's title on the line above, and a markdown `# Heading`
 * is almost always that same title again. Quote and list markers are stripped
 * from what survives — they are syntax, not words.
 */
export function firstProseLine(body: string, maxChars = 220): string {
  for (const raw of body.split("\n")) {
    if (raw.trimStart().startsWith("#")) continue;
    const line = raw.replace(/^[>\-*\s]+/u, "").trim();
    if (line) return line.slice(0, maxChars);
  }
  return "";
}

/** Newest note, in the reading register: its title plus its opening line. */
export function selectNoteExcerpt(
  notes: readonly ReplicaRow[],
  contents: readonly ReplicaRow[]
): { title: string; excerpt: string } | undefined {
  const newest = [...notes].sort(byDescending("updated_at", "note_id"))[0];
  if (!newest) return undefined;
  const body = contents.find(
    (row) => row.content_id === newest.body_content_id
  );
  return {
    title: text(newest, "title") || "Untitled",
    excerpt: firstProseLine(decodeProse(body?.content_uri)),
  };
}

// ────────────────────────────────────────────────────────────────── docs ───

const BYTE_UNITS = ["bytes", "KB", "MB", "GB", "TB"] as const;

/**
 * A file size in the numeric register — "4.1 MB", the brief's own example.
 *
 * One decimal above the byte rung and none below it: "1,024 bytes" is a size a
 * reader can hold, "1.0 KB" is not more precise than "1 KB" but is longer, and
 * a size is scanned rather than compared, so a second decimal is noise. A
 * missing or nonsensical byte count returns "" — the row then shows a name with
 * no size, which is the honest answer, never a fabricated 0 bytes.
 */
export function formatBytes(bytes: unknown): string {
  const value = Number(bytes);
  if (!Number.isFinite(value) || value < 0) return "";
  let size = value;
  let unit = 0;
  while (size >= 1024 && unit < BYTE_UNITS.length - 1) {
    size /= 1024;
    unit += 1;
  }
  const rounded = unit === 0 ? Math.round(size) : Math.round(size * 10) / 10;
  return `${rounded.toLocaleString()} ${BYTE_UNITS[unit]}`;
}

/**
 * The Docs body: RULED ROWS, name and size — not a prose excerpt.
 *
 * Docs and Notes both hold text, and drawing both as a title over an opening
 * line made two tiles that were impossible to tell apart at a glance, which is
 * the one thing a springboard body exists to prevent. The brief separates them
 * on exactly this axis: Notes is prose in the reading register, Docs is a FILE
 * LIST — because what a member wants from a document tile is which files are
 * there and how big they are, not the first sentence of one of them.
 */
export function selectDocRows(
  documents: readonly ReplicaRow[],
  contents: readonly ReplicaRow[],
  limit = 3
): TileDocRow[] {
  const sizes = new Map<string, unknown>();
  for (const row of contents) sizes.set(text(row, "content_id"), row.byte_size);
  return [...documents]
    .sort(byDescending("updated_at", "document_id"))
    .slice(0, limit)
    .map((row) => ({
      id: text(row, "document_id"),
      name: text(row, "title") || "Untitled",
      size: formatBytes(sizes.get(text(row, "current_content_id"))),
    }));
}

// ──────────────────────────────────────────────────────────────── agenda ───

export interface AgendaOccurrence {
  instanceKey: string;
  summary: string;
  start: string;
}

/**
 * The next event, plus the after-line the brief pins to the tile bottom.
 *
 * The after-line is the whole point of the Agenda body: "then …" answers the
 * question a next-event alone leaves open, and when there is nothing after it
 * has to SAY so rather than going blank — a blank reads as a missing render.
 */
export function selectNextEvent(
  occurrences: readonly AgendaOccurrence[],
  now: Date,
  formatTime: (iso: string) => string
): { title: string; at: string; after: string } | undefined {
  const nowIso = now.toISOString();
  const upcoming = occurrences
    .filter((occurrence) => occurrence.start >= nowIso)
    .sort((left, right) => left.start.localeCompare(right.start));
  const next = upcoming[0];
  if (!next) return undefined;
  const after = upcoming[1];
  return {
    title: next.summary || "Untitled event",
    at: formatTime(next.start),
    after: after
      ? `then ${after.summary || "Untitled event"}`
      : "nothing after it",
  };
}

/** How many occurrences land inside the next `days` — the tile's count. */
export function countUpcoming(
  occurrences: readonly AgendaOccurrence[],
  now: Date,
  days: number
): number {
  const from = now.toISOString();
  const to = new Date(now.getTime() + days * 86_400_000).toISOString();
  return occurrences.filter(
    (occurrence) => occurrence.start >= from && occurrence.start <= to
  ).length;
}

// ──────────────────────────────────────────────────────────────── people ───

/** Overlapping face circles: a sample of the directory, name-ordered. */
export function selectFaces(
  profiles: readonly ReplicaRow[],
  namesByParty: ReadonlyMap<string, string>,
  count = 5
): TileFace[] {
  return profiles
    .filter((row) => row.deleted_at == null)
    .map((row) => {
      const partyId = text(row, "party_id");
      return {
        id: partyId,
        name: namesByParty.get(partyId) ?? "",
        color: text(row, "avatar_color").trim(),
      };
    })
    .sort((left, right) => left.name.localeCompare(right.name))
    .slice(0, count)
    .map((person) => ({
      id: person.id,
      initials: initialsOf(person.name),
      ...(person.color ? { color: person.color } : {}),
    }));
}

/**
 * ONE initial. The handoff's faces carry a single letter (the fixture faces
 * are single letters, and the 30px disc at 12px/500 initials is sized for
 * one) — never two, which is what a `first + last` pairing drew. An unnamed
 * person still gets a circle, not a hole.
 */
export function initialsOf(name: string): string {
  const parts = name.trim().split(/\s+/u).filter(Boolean);
  if (parts.length === 0) return "?";
  return (parts[0]![0] ?? "").toUpperCase();
}

// ───────────────────────────────────────────────────────────────── tasks ───

const OPEN_STATUSES = new Set(["needs-action", "in-process"]);

/** Open tasks only — the number the tile counts, and the rows it draws. */
export function openTasks(rows: readonly ReplicaRow[]): ReplicaRow[] {
  return rows.filter((row) => OPEN_STATUSES.has(text(row, "status")));
}

/**
 * A few checkbox rows with EXACTLY ONE struck through.
 *
 * The struck row is the most recently completed task, and it is what makes the
 * body legible as a task list rather than as any other list of short strings.
 * It is appended last so the tile always reads open-work-then-a-win, and it is
 * only there when a completion actually exists.
 */
export function selectTaskRows(
  rows: readonly ReplicaRow[],
  limit = 4
): TileTaskRow[] {
  const open = openTasks(rows)
    .sort(
      (left, right) =>
        Number(left.sort_order ?? 0) - Number(right.sort_order ?? 0) ||
        text(left, "task_id").localeCompare(text(right, "task_id"))
    )
    .map((row) => ({
      id: text(row, "task_id"),
      title: text(row, "title"),
      done: false,
    }));
  const done = rows
    .filter((row) => text(row, "status") === "completed" && row.completed_at)
    .sort(byDescending("completed_at", "task_id"))[0];
  if (!done) return open.slice(0, limit);
  return [
    ...open.slice(0, Math.max(limit - 1, 0)),
    { id: text(done, "task_id"), title: text(done, "title"), done: true },
  ];
}

// ───────────────────────────────────────────────────────────────── tally ───

/** Minor units summed over the rows the read already scoped to this month. */
export function sumMinor(rows: readonly ReplicaRow[]): number {
  return rows.reduce((total, row) => total + Number(row.amount_minor ?? 0), 0);
}

/** First day of the current local month, as the ISO date `spent_on` stores. */
export function monthStartDate(now: Date): string {
  return [
    now.getFullYear(),
    String(now.getMonth() + 1).padStart(2, "0"),
    "01",
  ].join("-");
}
