#!/usr/bin/env bash
# Rebuild the browser Iroh WASM binding (issue #468 K15).
# Portable: works on macOS (Homebrew LLVM) and Linux CI (system clang).
# Under `set -e`, never call bare `brew` when it may be missing — that used to
# exit 127 on Ubuntu and fail verify / client-e2e before any cargo step ran.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REPO_ROOT="$(cd "$ROOT/../.." && pwd)"
CRATE="$ROOT/iroh-wasm"
OUT="$ROOT/src/generated"

find_wasm_clang() {
  # Prefer Homebrew LLVM on macOS (Xcode clang lacks the wasm backend).
  if command -v brew >/dev/null 2>&1; then
    local brew_llvm
    brew_llvm="$(brew --prefix llvm 2>/dev/null || true)"
    if [[ -n "${brew_llvm}" && -x "${brew_llvm}/bin/clang" ]]; then
      echo "${brew_llvm}/bin/clang"
      return 0
    fi
  fi
  # Linux CI / generic: system clang usually ships with wasm32 support.
  local candidate
  for candidate in clang-20 clang-19 clang-18 clang-17 clang; do
    if command -v "${candidate}" >/dev/null 2>&1; then
      command -v "${candidate}"
      return 0
    fi
  done
  return 1
}

LLVM_CLANG="${CC_wasm32_unknown_unknown:-}"
if [[ -z "${LLVM_CLANG}" ]]; then
  LLVM_CLANG="$(find_wasm_clang || true)"
fi
if [[ -z "${LLVM_CLANG}" || ! -x "${LLVM_CLANG}" ]]; then
  echo "Iroh WASM requires a clang with the WebAssembly backend." >&2
  echo "  macOS: brew install llvm" >&2
  echo "  Ubuntu: sudo apt-get install -y clang lld" >&2
  echo "  Or set CC_wasm32_unknown_unknown to a wasm-capable clang." >&2
  exit 1
fi

if ! command -v wasm-bindgen >/dev/null 2>&1; then
  echo "Install wasm-bindgen-cli 0.2.108 before rebuilding the browser transport." >&2
  echo "  cargo install wasm-bindgen-cli --version 0.2.108 --locked" >&2
  exit 1
fi

if ! command -v rustup >/dev/null 2>&1; then
  echo "rustup is required to add the wasm32-unknown-unknown target." >&2
  exit 1
fi

rustup target add wasm32-unknown-unknown
CC_wasm32_unknown_unknown="$LLVM_CLANG" \
  cargo build --manifest-path "$CRATE/Cargo.toml" --target wasm32-unknown-unknown --release
mkdir -p "$OUT"
wasm-bindgen \
  "$CRATE/target/wasm32-unknown-unknown/release/centraid_web_iroh.wasm" \
  --out-dir "$OUT" \
  --target web \
  --weak-refs

# Shrink the bindgen output. Optional: skip with a warning if wasm-opt is
# absent so the build still produces a working (larger) artifact.
if command -v wasm-opt >/dev/null 2>&1; then
  # --all-features: the bindgen output uses post-MVP features (bulk memory,
  # reference types); without this wasm-opt rejects the module outright.
  wasm-opt -Oz --all-features "$OUT/centraid_web_iroh_bg.wasm" -o "$OUT/centraid_web_iroh_bg.wasm"
else
  echo "wasm-opt not found; skipping -Oz size pass (optional: install binaryen)." >&2
fi

# wasm-bindgen emits blanket ESLint directives and an unowned follow-up marker. Preserve the
# generated intent while keeping each exception tied to the issue that owns the
# checked-in binding.
perl -pi -e 's{\/\* eslint-disable \*\/}{/* eslint-disable -- generated by wasm-bindgen; tracked by issue #462 */}g' \
  "$OUT/centraid_web_iroh.d.ts" \
  "$OUT/centraid_web_iroh_bg.wasm.d.ts"
perl -pi -e 's{\bTODO\b}{Follow-up (issue #462):}g' "$OUT/centraid_web_iroh.js"

# Generated JS and declarations are committed and participate in the root
# format gate. Keep formatting inside the generator so rebuild-and-diff CI
# and `bun run format:check` have one byte-exact answer.
OXFMT="$REPO_ROOT/node_modules/.bin/oxfmt"
if [[ ! -x "$OXFMT" ]]; then
  echo "oxfmt is required to finalize generated bindings; run bun install first." >&2
  exit 1
fi
"$OXFMT" \
  "$OUT/centraid_web_iroh.js" \
  "$OUT/centraid_web_iroh.d.ts" \
  "$OUT/centraid_web_iroh_bg.wasm.d.ts"
