#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REPO_ROOT="$(cd "$ROOT/../.." && pwd)"
CRATE="$ROOT/iroh-wasm"
OUT="$ROOT/src/generated"
LLVM_CLANG="${CC_wasm32_unknown_unknown:-}"

if [[ -z "$LLVM_CLANG" ]] && [[ -x /opt/homebrew/opt/llvm/bin/clang ]]; then
  LLVM_CLANG=/opt/homebrew/opt/llvm/bin/clang
fi
if [[ -z "$LLVM_CLANG" ]] && [[ -x /usr/local/opt/llvm/bin/clang ]]; then
  LLVM_CLANG=/usr/local/opt/llvm/bin/clang
fi
if [[ -z "$LLVM_CLANG" ]] && command -v clang >/dev/null 2>&1; then
  LLVM_CLANG="$(command -v clang)"
fi

if [[ -z "$LLVM_CLANG" || ! -x "$LLVM_CLANG" ]]; then
  echo "Iroh WASM requires LLVM clang with the WebAssembly backend." >&2
  echo "Set CC_wasm32_unknown_unknown or install LLVM with your platform package manager." >&2
  exit 1
fi
if ! command -v wasm-bindgen >/dev/null 2>&1; then
  echo "Install wasm-bindgen-cli 0.2.108 before rebuilding the browser transport." >&2
  exit 1
fi

rustup target add wasm32-unknown-unknown
CC_wasm32_unknown_unknown="$LLVM_CLANG" \
  cargo build --manifest-path "$CRATE/Cargo.toml" --target wasm32-unknown-unknown --release
mkdir -p "$OUT"
wasm-bindgen \
  "$CRATE/target/wasm32-unknown-unknown/release/centraid_web_iroh.wasm" \
  --out-dir "$OUT" \
  --target web \
  --weak-refs

# Shrink the bindgen output. Optional: skip with a warning if wasm-opt is
# absent so the build still produces a working (larger) artifact.
if command -v wasm-opt >/dev/null 2>&1; then
  # --all-features: the bindgen output uses post-MVP features (bulk memory,
  # reference types); without this wasm-opt rejects the module outright.
  wasm-opt -Oz --all-features "$OUT/centraid_web_iroh_bg.wasm" -o "$OUT/centraid_web_iroh_bg.wasm"
else
  echo "wasm-opt not found; skipping -Oz size pass (brew install binaryen to enable)." >&2
fi

# wasm-bindgen emits blanket ESLint directives and an unowned follow-up marker. Preserve the
# generated intent while keeping each exception tied to the issue that owns the
# checked-in binding.
perl -pi -e 's{\/\* eslint-disable \*\/}{/* eslint-disable -- generated by wasm-bindgen; tracked by issue #462 */}g' \
  "$OUT/centraid_web_iroh.d.ts" \
  "$OUT/centraid_web_iroh_bg.wasm.d.ts"
perl -pi -e 's{\bTODO\b}{Follow-up (issue #462):}g' "$OUT/centraid_web_iroh.js"

# Generated JS and declarations are committed and participate in the root
# format gate. Keep formatting inside the generator so rebuild-and-diff CI
# and `bun run format:check` have one byte-exact answer.
OXFMT="$REPO_ROOT/node_modules/.bin/oxfmt"
if [[ ! -x "$OXFMT" ]]; then
  echo "oxfmt is required to finalize generated bindings; run bun install first." >&2
  exit 1
fi
"$OXFMT" \
  "$OUT/centraid_web_iroh.js" \
  "$OUT/centraid_web_iroh.d.ts" \
  "$OUT/centraid_web_iroh_bg.wasm.d.ts"
