import { StyleSheet } from "react-native";

import { radii, spacing, t } from "../../kit/theme";
import {
  FILMSTRIP,
  VIEWER_ACTION_TARGET,
  VIEWER_CHROME_CHIP,
  VIEWER_CHROME_INSET,
} from "./viewer-model";

export const styles = StyleSheet.create({
  actionRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: VIEWER_CHROME_INSET,
    paddingVertical: VIEWER_CHROME_INSET,
  },
  viewerReadOnlyReason: {
    ...t("mono"),
    paddingBottom: spacing[2],
    paddingHorizontal: spacing[3],
  },
  facts: { ...t("mono"), flex: 1, marginTop: spacing[1] },
  factLabel: { ...t("small"), flexGrow: 0, flexShrink: 0, width: 96 },
  factsRow: { flexDirection: "row", gap: spacing[3], paddingVertical: 3 },
  fill: { flex: 1 },
  filmstrip: {
    height: FILMSTRIP.height,
  },
  filmstripContent: {
    alignItems: "center",
    paddingHorizontal: spacing[3],
  },
  filmstripCurrent: {
    borderWidth: FILMSTRIP.currentOutlineWidth,
    height: FILMSTRIP.current,
    width: FILMSTRIP.current,
  },
  filmstripFrame: { marginEnd: FILMSTRIP.gap },
  filmstripNeighbour: {
    height: FILMSTRIP.neighbour,
    width: FILMSTRIP.neighbour,
  },
  grabberSlot: { paddingBottom: spacing[1] },
  infoLabel: { ...t("small"), flex: 1 },
  infoMeaning: { ...t("small"), marginTop: 2 },
  infoRow: { paddingVertical: spacing[2] },
  infoValue: { ...t("small") },
  refusal: {
    borderRadius: radii.md,
    borderWidth: 1,
    gap: 2,
    marginTop: spacing[2],
    padding: spacing[2],
  },
  refusalText: { ...t("small") },
  refusalTitle: { ...t("control") },
  hairline: {
    borderTopWidth: 1,
    marginTop: spacing[3],
    paddingTop: spacing[2],
  },
  liveText: { ...t("eyebrow") },
  mediaCenter: { alignItems: "center", justifyContent: "center" },
  modalBackdrop: { flex: 1 },
  pager: {
    alignItems: "center",
    borderRadius: radii.pill,
    borderWidth: 1,
    height: 44,
    justifyContent: "center",
    position: "absolute",
    top: "50%",
    width: 44,
  },
  pagerNext: { insetInlineEnd: spacing[3] },
  pagerPrev: { insetInlineStart: spacing[3] },
  chip: {
    alignItems: "center",
    borderRadius: radii.pill,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing[1],
    paddingHorizontal: spacing[2],
    paddingVertical: 6,
  },
  chipRow: { flexDirection: "row", flexWrap: "wrap", gap: spacing[1] },
  chipText: { ...t("control") },
  captionInput: { ...t("small"), borderBottomWidth: 1, paddingVertical: 6 },
  sheet: {
    borderTopLeftRadius: radii.lg,
    borderTopRightRadius: radii.lg,
    bottom: 0,
    paddingHorizontal: spacing[4],
    position: "absolute",
    width: "100%",
  },
  sheetBody: { paddingBottom: spacing[5] },
  sheetTitle: { ...t("title"), marginBottom: spacing[1] },
  statusLine: {
    alignItems: "center",
    borderTopWidth: 1,
    flexDirection: "row",
    gap: spacing[2],
    minHeight: 30,
    paddingHorizontal: spacing[3],
    paddingVertical: 6,
  },
  statusAction: { ...t("control") },
  statusText: { ...t("mono"), flex: 1 },
  track: { borderRadius: radii.pill, flex: 1, height: 3 },
  trackFill: { borderRadius: radii.pill, height: 3 },
  scrubStrip: { flexDirection: "row", gap: 2, paddingHorizontal: spacing[3] },
  scrubStripFrame: { borderRadius: radii.sm, height: 34, width: 34 },
  transport: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing[2],
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[2],
  },
  transportClock: { ...t("mono") },
  chromeTop: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: spacing[2],
    insetInlineEnd: 0,
    insetInlineStart: 0,
    justifyContent: "space-between",
    paddingBottom: VIEWER_CHROME_INSET,
    paddingHorizontal: VIEWER_CHROME_INSET,
    position: "absolute",
    top: 0,
    zIndex: 2,
  },
  chromePlate: {
    alignItems: "center",
    borderRadius: radii.pill,
    borderWidth: 1,
    flexDirection: "row",
    flexShrink: 1,
    minHeight: VIEWER_CHROME_CHIP,
    minWidth: 0,
    overflow: "hidden",
  },
  chromeSpacer: { height: VIEWER_CHROME_CHIP, width: VIEWER_CHROME_CHIP },
  chromeStamp: {
    alignItems: "center",
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[1],
  },
  chromeStampDate: { ...t("smallStrong") },
  chromeStampTime: { ...t("mono") },
  chromeTarget: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: VIEWER_CHROME_CHIP,
    minWidth: VIEWER_CHROME_CHIP,
  },
  chromeTargetWide: { minWidth: VIEWER_ACTION_TARGET },
  chromeTextTarget: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: VIEWER_CHROME_CHIP,
    paddingHorizontal: spacing[3],
  },
  kindLabel: {
    ...t("eyebrow"),
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[2],
    textAlign: "center",
  },
  zoomPill: {
    alignItems: "center",
    alignSelf: "center",
    borderRadius: radii.pill,
    borderWidth: 1,
    bottom: spacing[3],
    flexDirection: "row",
    gap: 2,
    paddingHorizontal: spacing[1],
    position: "absolute",
  },
  zoomStep: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: 44,
    minWidth: 44,
    paddingHorizontal: spacing[1],
  },
  zoomStepLabel: { ...t("control") },
  zoomReadout: { ...t("mono"), paddingEnd: spacing[2] },
});
