// THE RETRY LADDER for a vault photograph's bytes, in one place.
//
// Every surface that draws a replica asset asks for a DERIVATIVE first —
// `?variant=thumb` for a grid tile, the same for a face crop — because a
// downscaled copy is the right thing to pull over a tunnel. But the derivative
// is generated by the gateway's preview backstop, which runs AFTER the record
// lands. Between those two moments the variant URL 404s while the original
// sits in CAS, whole and decodable.
//
// The web grid has always handled this (`packages/blueprints/apps/photos/
// media.ts`, `originalFallback`): on error, fall back to the original once,
// and only call it a failure if THAT fails too. Mobile had no such ladder, so
// a 404 on a derivative rendered as `could not decode` over bytes that were
// right there — a whole library of failed tiles, and a face-review card with
// no evidence on it, on a vault where nothing was actually wrong.
//
// One hook rather than one copy per surface: the tile and the face card hit
// this within a single pass of each other, and a ladder implemented twice is a
// ladder that drifts.

import { useCallback, useState } from "react";

export interface ImageFallback {
  /** The URI to render right now — the derivative, then the original. */
  source: string;
  /** Both rungs failed. The photograph is genuinely unreadable. */
  failed: boolean;
  /** True once the bytes decode, at whichever rung. */
  decoded: boolean;
  /**
   * A recycling key that CHANGES when the rung does. Reusing one key across
   * rungs hands expo-image its cached failure for the URL it just gave up on.
   */
  recyclingKey: string;
  onLoad: () => void;
  onError: () => void;
}

export function useImageFallback(
  /** What the surface wants: usually a `?variant=…` URL. */
  preferred: string,
  /** The undownscaled bytes. Absent for a device-resident asset. */
  original: string | undefined,
  /** Identity for recycling — the asset id. */
  key: string
): ImageFallback {
  const [fellBack, setFellBack] = useState(false);
  const [failed, setFailed] = useState(false);
  const [decoded, setDecoded] = useState(false);

  const canFallBack = !fellBack && !!original && original !== preferred;
  const onError = useCallback(() => {
    if (canFallBack) setFellBack(true);
    else setFailed(true);
  }, [canFallBack]);

  return {
    source: fellBack && original ? original : preferred,
    failed,
    decoded,
    recyclingKey: fellBack ? `${key}:original` : key,
    onLoad: useCallback(() => setDecoded(true), []),
    onError,
  };
}
