// The mobile tree is its own Gradle build (#1020, D-1020-E1, D-1020-E0).
//
// A build under `mobile/` rather than a root-level one: the repository root is
// a Rust workspace plus a bun workspace, and a Gradle build rooted there would
// claim `settings.gradle.kts` at the top of a tree where neither of the other
// two toolchains expects one. `cargo xtask`'s `mobile-jvm` step runs
// `./gradlew` with this directory as its working directory.
//
// D-1020-E0: Gradle, not the Kotlin Toolchain and not Amper — AGP, XCFramework
// and SPM integration are mature there. D-1020-E0-1: the wrapper is the current
// stable Gradle (9.7.1) and not the container's preinstalled 8.14.3, and
// `org.gradle.warning.mode=fail` makes a deprecated Gradle feature a red.

pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        // The Android plugin lives in Google's repository. Declared
        // unconditionally: a repository nobody resolves from costs nothing, and
        // a conditional repository list is how `-Pcentraid.android=true` would
        // fail with "plugin not found" instead of its own message.
        google()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        google()
    }
}

rootProject.name = "centraid-mobile"

// ALWAYS BUILT, ALWAYS TESTED HERE. `:core` is the C ABI binding and `:shared`
// is the screen state machines, the navigation model and the sync scheduler —
// both have a JVM target, and the JVM target is what this machine can prove.
include(":core")
include(":shared")

// THE ANDROID APP IS GATED, LOUDLY.
//
// `-Pcentraid.android=true` needs a real Android SDK. Without the flag the
// module is not included at all, so `./gradlew tasks` does not advertise a task
// that cannot run — the one thing worse than a missing target is a target that
// fails in the middle with an SDK error a reader has to decode.
val androidRequested = providers.gradleProperty("centraid.android").orNull == "true"
if (androidRequested) {
    val androidHome = providers.environmentVariable("ANDROID_HOME").orNull
        ?: providers.environmentVariable("ANDROID_SDK_ROOT").orNull
    require(!androidHome.isNullOrBlank()) {
        "-Pcentraid.android=true was passed but neither ANDROID_HOME nor " +
            "ANDROID_SDK_ROOT is set. The Android target of mobile/ needs a real " +
            "SDK; see mobile/README.md -> \"Building the Android app\"."
    }
    include(":androidApp")
} else {
    gradle.projectsLoaded {
        rootProject.logger.lifecycle(
            "mobile: the Android target is OFF. Pass -Pcentraid.android=true " +
                "with ANDROID_HOME set to build :androidApp (mobile/README.md).",
        )
    }
}

// iOS is not a Gradle module at all: `mobile/iosApp` is an Xcode project
// generated by XcodeGen, consuming the shared framework through SPM. The Kotlin
// side of it is `:shared`'s and `:core`'s ios* targets, declared in their build
// files and disabled by the Kotlin plugin on a non-macOS host.
