// Centraid — CSS generator.
// `toCss()` walks the typed tokens (themes, densities, palette, radii) and
// emits the entire `:root` + `[data-theme='dark']` + density-override
// blocks as a single CSS string. Desktop injects this into a <style> tag
// at preload time — the only token-related CSS it ships.

import { themes, type Theme } from './themes';
import { densities, type DensityScale } from './density';
import { palette } from './palette';
import { radii } from './radii';

function block(selector: string, props: Record<string, string>): string {
  const lines: string[] = [`${selector} {`];
  for (const [k, v] of Object.entries(props)) {
    lines.push(`  ${k}: ${v};`);
  }
  lines.push('}');
  return lines.join('\n');
}

function themeProps(t: Theme): Record<string, string> {
  const out: Record<string, string> = {
    '--accent': t.accent,
    '--accent-deep': t.accentDeep,
    '--accent-light': t.accentLight,
    '--accent-midnight': t.accentMidnight,
    '--accent-violet': t.accentViolet,
    '--danger': t.danger,
    '--success': t.success,
  };
  // --bg-l must precede --bg/--bg-elev/--bg-sunken/--bg-app on dark, since
  // those reference it via var(). Light theme omits it entirely.
  if (t.bgL !== undefined) out['--bg-l'] = t.bgL;
  Object.assign(out, {
    '--bezel': t.bezel,
    '--bezel-inner': t.bezelInner,
    '--bg': t.bg,
    '--bg-app': t.bgApp,
    '--bg-elev': t.bgElev,
    '--bg-sunken': t.bgSunken,
    '--bg-wall': t.bgWall,
    '--device-wall': t.deviceWall,
    '--ink': t.ink,
    '--ink-2': t.ink2,
    '--ink-3': t.ink3,
    '--ink-4': t.ink4,
    '--ink-inv': t.inkInv,
    '--line': t.line,
    '--line-strong': t.lineStrong,
    '--shadow-lg': t.shadowLg,
    '--shadow-md': t.shadowMd,
    '--shadow-sm': t.shadowSm,
    '--sidebar-bg': t.sidebarBg,
    '--sidebar-blur': t.sidebarBlur,
    '--sidebar-divider': t.sidebarDivider,
  });
  return out;
}

function densityProps(d: DensityScale): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(d)) {
    out[`--d-${k}`] = `${v}px`;
  }
  return out;
}

/**
 * Returns the full token CSS string. Stable order: static (palette, radii,
 * default density) → light theme → dark theme → density overrides.
 */
export function toCss(): string {
  const staticProps: Record<string, string> = {};
  // App-icon palette gets two names: the legacy `--c-<hue>` (still used
  // throughout the renderer and mobile theme code) and the redesign-spec
  // `--icon-<hue>` (used by ds-update/02-chrome-components.css and any
  // markup imported verbatim from the design system). Same hex value
  // either way — `--icon-*` is an alias for cross-codebase portability.
  for (const [k, v] of Object.entries(palette)) {
    staticProps[`--c-${k}`] = v;
    staticProps[`--icon-${k}`] = v;
  }
  for (const [k, v] of Object.entries(radii)) staticProps[`--r-${k}`] = `${v}px`;
  Object.assign(staticProps, densityProps(densities.regular));

  const blocks = [
    '/* Generated by @centraid/design-tokens — do not edit by hand. */',
    block(':root', { ...staticProps, ...themeProps(themes.light) }),
    block(`[data-theme='light']`, themeProps(themes.light)),
    block(`[data-theme='dark']`, themeProps(themes.dark)),
  ];

  for (const name of Object.keys(densities) as Array<keyof typeof densities>) {
    blocks.push(block(`[data-density='${name}']`, densityProps(densities[name])));
  }

  return blocks.join('\n\n') + '\n';
}
