// Centraid — CSS generator.
// `toCss()` walks the typed tokens (themes, densities, palette, radii) and
// emits the entire `:root` + `[data-theme='dark']` + density-override
// blocks as a single CSS string. Desktop injects this into a <style> tag
// at preload time — the only token-related CSS it ships.

import { themes, type Theme } from './themes';
import { densities, type DensityScale } from './density';
import { palette } from './palette';
import { radii } from './radii';

function block(selector: string, props: Record<string, string>): string {
  const lines: string[] = [`${selector} {`];
  for (const [k, v] of Object.entries(props)) {
    lines.push(`  ${k}: ${v};`);
  }
  lines.push('}');
  return lines.join('\n');
}

function themeProps(t: Theme): Record<string, string> {
  return {
    '--accent': t.accent,
    '--bezel': t.bezel,
    '--bezel-inner': t.bezelInner,
    '--bg': t.bg,
    '--bg-app': t.bgApp,
    '--bg-elev': t.bgElev,
    '--bg-sunken': t.bgSunken,
    '--device-wall': t.deviceWall,
    '--ink': t.ink,
    '--ink-2': t.ink2,
    '--ink-3': t.ink3,
    '--ink-4': t.ink4,
    '--ink-inv': t.inkInv,
    '--line': t.line,
    '--line-strong': t.lineStrong,
    '--shadow-lg': t.shadowLg,
    '--shadow-md': t.shadowMd,
    '--shadow-sm': t.shadowSm,
  };
}

function densityProps(d: DensityScale): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(d)) {
    out[`--d-${k}`] = `${v}px`;
  }
  return out;
}

/**
 * Returns the full token CSS string. Stable order: static (palette, radii,
 * default density) → light theme → dark theme → density overrides.
 */
export function toCss(): string {
  const staticProps: Record<string, string> = {};
  for (const [k, v] of Object.entries(palette)) staticProps[`--c-${k}`] = v;
  for (const [k, v] of Object.entries(radii)) staticProps[`--r-${k}`] = `${v}px`;
  Object.assign(staticProps, densityProps(densities.regular));

  const blocks = [
    '/* Generated by @centraid/design-tokens — do not edit by hand. */',
    block(':root', { ...staticProps, ...themeProps(themes.light) }),
    block(`[data-theme='light']`, themeProps(themes.light)),
    block(`[data-theme='dark']`, themeProps(themes.dark)),
  ];

  for (const name of Object.keys(densities) as Array<keyof typeof densities>) {
    blocks.push(block(`[data-density='${name}']`, densityProps(densities[name])));
  }

  return blocks.join('\n\n') + '\n';
}
