/*
 * Codex provider routing — two strategies for pointing a spawned codex
 * process at a custom OpenAI-compatible endpoint.
 *
 * Codex resolves its config + thread state under `$CODEX_HOME` (default
 * `~/.codex`). To route model calls through a non-default provider we
 * have two options:
 *
 *   1. `materializeCodexHome` — write a generated `config.toml` into a
 *      centraid-owned directory and redirect `CODEX_HOME` there. Isolates
 *      thread state, but DROPS everything else in the user's real home,
 *      including their `[mcp_servers.*]`.
 *
 *   2. `codexProviderOverrideArgs` — pass `-c key=value` overrides that
 *      layer on top of the user's real `~/.codex/config.toml`. Honored by
 *      `codex exec` (and `app-server`) since codex-cli 0.128.0, our pinned
 *      minimum. Preserves the user's MCP servers — this is what lets
 *      deterministic `ctx.tool` dispatch ride on top of the user's codex.
 *
 * The API key is never written to the toml or the overrides. It flows
 * through the child env under `provider.envKey`; see the spawn env wiring
 * in `codex-app-server.ts` / `run-automation-cli-spawn.ts`.
 */

import { promises as fs } from 'node:fs';
import path from 'node:path';
import type { OpenAICompatProvider } from './types.js';

/**
 * Materialize a scoped `CODEX_HOME` for a custom OpenAI-compatible provider.
 *
 * Writes `<baseDir>/codex-homes/<sanitized-id>/config.toml`. Codex uses
 * this as the root for its config + thread state when `CODEX_HOME` is set
 * in the child env. The user's `~/.codex` is left untouched.
 *
 * Re-runs on every spawn (cheap, atomic via `writeFile`), so a settings
 * change to the provider is picked up on the next turn without an
 * explicit invalidate step.
 */
export async function materializeCodexHome(
  provider: OpenAICompatProvider,
  baseDir: string,
): Promise<string> {
  const home = path.join(baseDir, 'codex-homes', sanitizeProviderId(provider.id));
  await fs.mkdir(home, { recursive: true });
  await fs.writeFile(path.join(home, 'config.toml'), buildProviderToml(provider), 'utf8');
  return home;
}

/**
 * Render a codex `config.toml` that declares `provider` as the active
 * model provider. Never includes the API key — that flows via env var.
 *
 * Exported for unit tests.
 */
export function buildProviderToml(p: OpenAICompatProvider): string {
  const idKey = tomlBareOrQuotedKey(p.id);
  const lines = [
    `# Generated by @centraid/agent-runtime — do not edit by hand.`,
    `# CODEX_HOME is set to this directory only for the spawned codex process;`,
    `# the user's ~/.codex is not read or modified.`,
    ``,
    `model_provider = ${tomlString(p.id)}`,
    ``,
    `[model_providers.${idKey}]`,
    `name = ${tomlString(p.name)}`,
    `base_url = ${tomlString(p.baseUrl)}`,
    // codex 0.128+ rejects `wire_api = "chat"` at config load; the
    // Responses API is the only supported wire format, so it is the
    // default here. Callers can still pass `wireApi` explicitly.
    `wire_api = ${tomlString(p.wireApi ?? 'responses')}`,
  ];
  if (p.envKey) lines.push(`env_key = ${tomlString(p.envKey)}`);
  lines.push('');
  return lines.join('\n');
}

/**
 * Build `-c key=value` config-override args that route a spawned codex
 * process's model calls through `provider`, layered on top of the user's
 * real `~/.codex/config.toml`.
 *
 * Unlike `materializeCodexHome` (which redirects `CODEX_HOME` to a bare
 * generated home and thereby DROPS the user's `[mcp_servers.*]`), these
 * overrides preserve everything in the real home — the user's MCP servers
 * stay reachable during deterministic `ctx.tool` dispatch. That is the
 * whole point of the "ride on top of the user's codex" model.
 *
 * Each value is rendered as a TOML basic string (via `tomlString`) so
 * codex's override parser treats it unambiguously as a string — bare URLs
 * and ids would otherwise hit its TOML-value fast path and misparse.
 *
 * Honored by `codex exec` since codex-cli 0.128.0 (POC-proven, issue
 * #158). The API key is never emitted here — it flows via the child env
 * under `provider.envKey`, exactly as with the generated toml.
 *
 * Exported for unit tests.
 */
export function codexProviderOverrideArgs(p: OpenAICompatProvider): string[] {
  const ns = `model_providers.${tomlBareOrQuotedKey(p.id)}`;
  const args = [
    '-c',
    `model_provider=${tomlString(p.id)}`,
    '-c',
    `${ns}.name=${tomlString(p.name)}`,
    '-c',
    `${ns}.base_url=${tomlString(p.baseUrl)}`,
    // codex 0.128+ rejects `wire_api = "chat"`; `responses` is the default.
    '-c',
    `${ns}.wire_api=${tomlString(p.wireApi ?? 'responses')}`,
  ];
  if (p.envKey) args.push('-c', `${ns}.env_key=${tomlString(p.envKey)}`);
  return args;
}

function tomlString(s: string): string {
  // TOML basic strings: double-quoted, with \", \\, and the standard
  // escape set. Control characters (< 0x20, plus 0x7f) get \uXXXX.
  let out = '"';
  for (const ch of s) {
    const code = ch.charCodeAt(0);
    if (ch === '"' || ch === '\\') out += '\\' + ch;
    else if (ch === '\n') out += '\\n';
    else if (ch === '\r') out += '\\r';
    else if (ch === '\t') out += '\\t';
    else if (code < 0x20 || code === 0x7f) out += '\\u' + code.toString(16).padStart(4, '0');
    else out += ch;
  }
  return out + '"';
}

function tomlBareOrQuotedKey(s: string): string {
  // TOML bare keys accept A-Za-z0-9_- only; anything else needs to be
  // wrapped as a quoted key to remain valid TOML.
  return /^[A-Za-z0-9_-]+$/.test(s) ? s : tomlString(s);
}

function sanitizeProviderId(s: string): string {
  // Filesystem-safe slug for the CODEX_HOME subdir. Avoids path
  // traversal and OS reserved chars without round-tripping back to the
  // toml (we use the original `id` for the toml key).
  return s.replace(/[^A-Za-z0-9_.-]/g, '_').slice(0, 64) || 'provider';
}
