/*
 * Provider-scoped CODEX_HOME materialization.
 *
 * Codex resolves its config + thread state under `$CODEX_HOME` (default
 * `~/.codex`). When the user has configured a custom OpenAI-compatible
 * provider, we point the spawned codex process at a centraid-owned
 * directory containing a generated `config.toml` declaring the provider —
 * the user's real `~/.codex/{config.toml,auth.json}` is never touched.
 *
 * The API key is never written to the toml. It flows through the child
 * env under `provider.envKey`; see `codex-app-server.ts` for the spawn
 * env wiring.
 */

import { promises as fs } from 'node:fs';
import path from 'node:path';
import type { OpenAICompatProvider } from './types.js';

/**
 * Materialize a scoped `CODEX_HOME` for a custom OpenAI-compatible provider.
 *
 * Writes `<baseDir>/codex-homes/<sanitized-id>/config.toml`. Codex uses
 * this as the root for its config + thread state when `CODEX_HOME` is set
 * in the child env. The user's `~/.codex` is left untouched.
 *
 * Re-runs on every spawn (cheap, atomic via `writeFile`), so a settings
 * change to the provider is picked up on the next turn without an
 * explicit invalidate step.
 */
export async function materializeCodexHome(
  provider: OpenAICompatProvider,
  baseDir: string,
): Promise<string> {
  const home = path.join(baseDir, 'codex-homes', sanitizeProviderId(provider.id));
  await fs.mkdir(home, { recursive: true });
  await fs.writeFile(path.join(home, 'config.toml'), buildProviderToml(provider), 'utf8');
  return home;
}

/**
 * Render a codex `config.toml` that declares `provider` as the active
 * model provider. Never includes the API key — that flows via env var.
 *
 * Exported for unit tests.
 */
export function buildProviderToml(p: OpenAICompatProvider): string {
  const idKey = tomlBareOrQuotedKey(p.id);
  const lines = [
    `# Generated by @centraid/agent-runtime — do not edit by hand.`,
    `# CODEX_HOME is set to this directory only for the spawned codex process;`,
    `# the user's ~/.codex is not read or modified.`,
    ``,
    `model_provider = ${tomlString(p.id)}`,
    ``,
    `[model_providers.${idKey}]`,
    `name = ${tomlString(p.name)}`,
    `base_url = ${tomlString(p.baseUrl)}`,
    `wire_api = ${tomlString(p.wireApi ?? 'chat')}`,
  ];
  if (p.envKey) lines.push(`env_key = ${tomlString(p.envKey)}`);
  lines.push('');
  return lines.join('\n');
}

function tomlString(s: string): string {
  // TOML basic strings: double-quoted, with \", \\, and the standard
  // escape set. Control characters (< 0x20, plus 0x7f) get \uXXXX.
  let out = '"';
  for (const ch of s) {
    const code = ch.charCodeAt(0);
    if (ch === '"' || ch === '\\') out += '\\' + ch;
    else if (ch === '\n') out += '\\n';
    else if (ch === '\r') out += '\\r';
    else if (ch === '\t') out += '\\t';
    else if (code < 0x20 || code === 0x7f) out += '\\u' + code.toString(16).padStart(4, '0');
    else out += ch;
  }
  return out + '"';
}

function tomlBareOrQuotedKey(s: string): string {
  // TOML bare keys accept A-Za-z0-9_- only; anything else needs to be
  // wrapped as a quoted key to remain valid TOML.
  return /^[A-Za-z0-9_-]+$/.test(s) ? s : tomlString(s);
}

function sanitizeProviderId(s: string): string {
  // Filesystem-safe slug for the CODEX_HOME subdir. Avoids path
  // traversal and OS reserved chars without round-tripping back to the
  // toml (we use the original `id` for the toml key).
  return s.replace(/[^A-Za-z0-9_.-]/g, '_').slice(0, 64) || 'provider';
}
