#!/usr/bin/env node
// The doctrine digest a worker is briefed with (#1005).
//
// A brief that lists the law by hand is a brief that is wrong the first time
// somebody amends it, and an agent held to a rule that was not in its brief is
// being held to unwritten law. So the digest is GENERATED: this prints the law
// as it stands at HEAD — its digest, every enabled rule with its door, its
// severity and its statute, the doctrine domains and the decisions they answer
// to, and the exceptions in force — and the digest it prints is the one a
// brief is stamped with.
//
// The stamp is what makes it a contract rather than a courtesy. Paste this
// into a brief, and a run of the law under `--brief-digest <hex>` says whether
// the law moved since. The agent is held to HEAD; the stamp tells everyone,
// including the agent, exactly what it was not told.
//
// Usage:
//   node .governance/law/brief.ts            # the digest, for a brief
//   node .governance/law/brief.ts --json     # the same, machine-readable
import { lawDigestAt } from "./arrival.ts";
import { treeSource } from "./lib/git.ts";
import { collectDocket } from "./lib/registries.ts";
import { loadRules, readPacks } from "./eslint.config.ts";

/**
 * The law as it stands, as data.
 *
 * @returns {Promise<object>} The brief.
 */
export async function buildBrief() {
  const rows = await loadRules();
  return {
    digest: lawDigestAt("HEAD"),
    rules: rows.map((row) => ({
      id: row.id,
      door: row.door,
      severity: row.severity,
      description: row.rule?.meta?.docs?.description ?? "",
      statute: row.rule?.meta?.docs?.url ?? "",
    })),
    domains: readPacks().flatMap((pack) => pack.domains),
    // A brief is the law at HEAD, docket included: the register a worker is
    // held to is the one that is committed, not the one in somebody's tree.
    docket: collectDocket(null, treeSource("HEAD")).rows,
  };
}

/**
 * Render a brief as the markdown a worker brief carries.
 *
 * @param {object} brief The brief.
 * @returns {string} Markdown, with a trailing newline.
 */
export function renderBrief(brief: {
  digest: string;
  rules: { id: string; door: string; severity: string; description: string; statute: string }[];
  domains: { id: string; paths?: string[]; decision: string }[];
  docket: { id: string; rule: string; path?: string | null; expires: string; authority: string; reason: string }[];
}) {
  const lines = [
    `## Doctrine digest — law \`${brief.digest.slice(0, 12)}\``,
    "",
    "Generated by `node .governance/law/brief.ts`. Stamp the digest in the brief;",
    "`node .governance/law/run.ts --brief-digest <digest>` reports whether the law",
    "moved under the work. **The agent is held to HEAD, not to this page.**",
    "",
    "### Rules in force",
    "",
  ];
  for (const rule of brief.rules) {
    lines.push(`- \`${rule.id}\` · ${rule.door} · ${rule.severity} — ${rule.description} (${rule.statute})`);
  }
  lines.push("", "### Doctrine domains", "");
  if (brief.domains.length === 0) lines.push("- _(none declared)_");
  for (const domain of brief.domains) {
    lines.push(
      `- \`${domain.id}\` — ${(domain.paths ?? []).map((glob) => `\`${glob}\``).join(", ")} → [docs/decisions.md${domain.decision}](../../docs/decisions.md${domain.decision})`
    );
  }
  lines.push("", "### Exceptions in force", "");
  if (brief.docket.length === 0) lines.push("- _(the docket is empty)_");
  for (const row of brief.docket) {
    lines.push(
      `- \`${row.id}\` · \`${row.rule}\`${row.path ? ` · \`${row.path}\`` : ""} · expires ${row.expires} · ${row.authority} — ${row.reason}`
    );
  }
  return `${lines.join("\n")}\n`;
}

/**
 * The CLI.
 *
 * @param {string[]} argv Arguments after the script name.
 * @returns {Promise<string>} What was printed.
 */
export async function main(argv: string[]) {
  const brief = await buildBrief();
  return argv.includes("--json")
    ? `${JSON.stringify(brief, null, 2)}\n`
    : renderBrief(brief);
}

if (process.argv[1] === import.meta.filename) {
  process.stdout.write(await main(process.argv.slice(2)));
}
