#!/usr/bin/env python3
"""Parse every `canonical` in map.json against the grammar in GRAMMAR.md.

Stdlib only.  Run it from anywhere:

    python3 crates/evalsuite/grammar/check.py

It fails (exit 1) when a canonical does not parse, when a terminal is not in
the ontology-derived lexicon, or when the stored `tree` disagrees with the tree
this parser builds.  That last check is what stops map.json and the grammar
drifting apart: the map's trees are GENERATED by this parser, never typed.

The lexicons below are DERIVED, not authored — see GRAMMAR.md "Deriving the
terminals".  The typed-command list is read LIVE from `crates/vault/src/commands`, so a
renamed command fails this check rather than drifting.
"""

import json
import os
import re
import sys

# ---------------------------------------------------------------------------
# LEXICONS.  GENERATED, not authored — see GRAMMAR.md "How the terminals are
# derived".  `derive/emit.py` walks the ontology (the DDL, the registries, the
# eight app manifests and the typed command registry), validates the names in
# `derive/terminals.json` against it, and writes BOTH this module's lexicon and
# `crates/candidates/src/canon_terminals.rs` from the one source.  The two
# parsers can no longer drift from each other or from the vault.
# ---------------------------------------------------------------------------

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from lexicon import (  # noqa: E402
    COMMANDS, DECLINE_REASONS, FIELDS, KINDS, REFS, VERB_CLASSES,
    WINDOW_PHRASES,
)

ORDINAL_REF = re.compile(r"^the (\d+)(?:st|nd|rd|th) one$")

AGGS = {"count", "sum", "min", "max"}
CMPS = {"=", "!=", "<", ">", "<=", ">="}


def terminals_are_current():
    """A stale generated lexicon is a red run, not a silent divergence."""
    here = os.path.dirname(os.path.abspath(__file__))
    sys.path.insert(0, os.path.join(here, "derive"))
    try:
        import emit
    except Exception as error:                      # pragma: no cover
        return "the terminal generator is not importable: %s" % error
    if emit.main(["--check"]) != 0:
        return "the generated lexicons are stale; run `python3 derive/emit.py`"
    return None

# ---------------------------------------------------------------------------
# TOKENIZER
# ---------------------------------------------------------------------------

TOKEN = re.compile(r"""
    (?P<ws>\s+)
  | (?P<string>"(?:[^"\\]|\\.)*")
  | (?P<daterange>\d{4}-\d{2}-\d{2}\.\.\d{4}-\d{2}-\d{2})
  | (?P<datetime>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(?::\d{2}(?:\.\d+)?)?Z?)
  | (?P<date>\d{4}-\d{2}-\d{2})
  | (?P<month>\d{4}-\d{2})
  | (?P<duration>[+-]\d+[hdm])
  | (?P<ordinal>\d+(?:st|nd|rd|th))
  | (?P<number>-?\d+(?:\.\d+)?)
  | (?P<same>same\?)
  | (?P<ident>[A-Za-z_][A-Za-z0-9_.]*)
  | (?P<op><=|>=|!=|=|<|>)
  | (?P<punct>[(){}:,])
""", re.VERBOSE)


class ParseError(Exception):
    pass


def lex(text):
    tokens, pos = [], 0
    while pos < len(text):
        match = TOKEN.match(text, pos)
        if not match:
            raise ParseError("bad character at %d: %r" % (pos, text[pos:pos + 12]))
        pos = match.end()
        group = match.lastgroup
        if group == "ws":
            continue
        tokens.append((group, match.group()))
    tokens.append(("eof", ""))
    return tokens


# ---------------------------------------------------------------------------
# PARSER
# ---------------------------------------------------------------------------

class Parser:
    def __init__(self, text):
        self.text = text
        self.tokens = lex(text)
        self.at = 0

    # -- token helpers ------------------------------------------------------
    def peek(self, ahead=0):
        return self.tokens[min(self.at + ahead, len(self.tokens) - 1)]

    def word(self, ahead=0):
        kind, raw = self.peek(ahead)
        return raw if kind == "ident" else None

    def take(self):
        token = self.tokens[self.at]
        self.at += 1
        return token

    def expect_word(self, *words):
        raw = self.word()
        if raw not in words:
            raise ParseError("expected %s, found %r" % ("/".join(words), self.peek()[1]))
        self.take()
        return raw

    def expect_punct(self, char):
        kind, raw = self.peek()
        if raw != char:
            raise ParseError("expected %r, found %r" % (char, raw))
        self.take()

    def eat_word(self, *words):
        if self.word() in words:
            self.take()
            return True
        return False

    def eat_punct(self, char):
        if self.peek()[1] == char and self.peek()[0] in ("punct", "op"):
            self.take()
            return True
        return False

    # -- turn ---------------------------------------------------------------
    def parse_turn(self):
        node = self.turn()
        if self.peek()[0] != "eof":
            raise ParseError("trailing input at %r" % self.peek()[1])
        return node

    def turn(self):
        raw = self.word()
        if raw == "nothing":
            self.take()
            return {"node": "nothing"}
        if raw in ("refuse", "clarify"):
            self.take()
            self.expect_punct(":")
            reason = self.word()
            if reason not in DECLINE_REASONS:
                raise ParseError("unknown decline reason %r" % reason)
            self.take()
            return {"node": raw, "reason": reason}
        if raw == "show":
            self.take()
            return {"node": "show", "set": self.set_expr()}
        # `same? A B` -- the IDENTITY question (GRAMMAR.md 1.1).  Executed as
        # an id-set intersection, and `clarify` rather than `no` when the two
        # sets are of unrelated kinds.
        if self.peek()[0] == "same":
            self.take()
            left = self.set_primary_or_group()
            right = self.set_primary_or_group()
            return {"node": "same", "left": left, "right": right}
        if raw is not None and self.peek(1)[1] == "{":
            first = self.cmd()
            if self.word() != "then":
                return first
            # `Cmd then Cmd` -- an ORDERED SEQUENCE of typed writes in one
            # turn.  Forced by s107.3, s113.3 and h61.0: two writes with
            # DIFFERENT arguments, or of different verbs, are what one
            # sentence asks for and a single `Cmd` has room for one.  The
            # order is the sentence's and the executor keeps it.
            steps = [first]
            while self.eat_word("then"):
                steps.append(self.cmd())
            return {"node": "seq", "steps": steps}
        return self.value()

    # -- value --------------------------------------------------------------
    def looks_like_value(self):
        raw = self.word()
        if raw in AGGS or raw == "balance":
            return True
        return raw is not None and self.word(1) == "of"

    def value(self):
        raw = self.word()
        if raw == "count":
            self.take()
            self.expect_word("of")
            return {"node": "agg", "agg": "count", "field": None,
                    "set": self.set_expr()}
        if raw in ("sum", "min", "max"):
            self.take()
            field = self.field()
            self.expect_word("of")
            return {"node": "agg", "agg": raw, "field": field,
                    "set": self.set_expr()}
        if raw == "balance":
            self.take()
            self.expect_word("of")
            who = self.set_expr()
            self.expect_word("in")
            where = self.set_expr()
            return {"node": "balance", "of": who, "in": where}
        if raw is not None and self.word(1) == "of":
            field = self.field()
            self.expect_word("of")
            return {"node": "project", "field": field, "set": self.set_expr()}
        raise ParseError("expected a value, found %r" % self.peek()[1])

    # -- command ------------------------------------------------------------
    def cmd(self):
        verb = self.word()
        if verb is None:
            raise ParseError("expected a verb")
        if verb not in VERB_CLASSES and COMMANDS and verb not in COMMANDS:
            raise ParseError("unknown verb %r (not a typed command "
                             "and not a verb class)" % verb)
        self.take()
        self.expect_punct("{")
        args = {}
        if not self.eat_punct("}"):
            while True:
                key = self.word()
                if key is None:
                    raise ParseError("expected an argument name")
                self.take()
                self.expect_punct(":")
                args[key] = self.argval()
                if self.eat_punct(","):
                    continue
                self.expect_punct("}")
                break
        node = {"node": "cmd", "verb": verb,
                "is_class": verb in VERB_CLASSES, "args": args, "on": None}
        if self.eat_word("on"):
            node["on"] = self.set_expr()
        return node

    def argval(self):
        kind, raw = self.peek()
        if raw == "(":
            self.take()
            inner = self.set_expr()
            self.expect_punct(")")
            return {"node": "setarg", "set": inner}
        if kind == "ident" and self.looks_like_value():
            return self.value()
        if kind in ("string", "number", "date", "datetime", "month",
                    "daterange", "duration"):
            self.take()
            return {"node": "lit", "type": kind, "value": unquote(raw)}
        if kind == "ident" and raw in ("null", "true", "false", "me"):
            self.take()
            return {"node": "lit", "type": "keyword", "value": raw}
        raise ParseError("bad argument value %r" % raw)

    # -- set ----------------------------------------------------------------
    def set_expr(self):
        # `and` / `except` bind LOOSER than the postfix operators (`called`,
        # `that`, `during`, `ordered by`), so `photos called "Ana" and photos
        # called "Marco"` is a union of two named sets and not a named union.
        # A postfix over a union is written with the union parenthesised,
        # which GRAMMAR.md 1 already requires of a nested Set operand.
        node = self.set_postfix()
        while True:
            raw = self.word()
            if raw == "and":
                self.take()
                node = {"node": "union", "left": node, "right": self.set_postfix()}
            elif raw == "except":
                self.take()
                node = {"node": "except", "left": node,
                        "right": self.set_postfix()}
            else:
                return node

    def set_postfix(self):
        node = self.set_primary()
        while True:
            raw = self.word()
            if raw == "called":
                self.take()
                node = {"node": "called", "set": node, "lit": self.string()}
            elif raw == "that":
                self.take()
                self.expect_punct("(")
                pred = self.pred()
                self.expect_punct(")")
                node = {"node": "filter", "set": node, "pred": pred}
            elif raw == "during":
                self.take()
                node = {"node": "during", "set": node, "window": self.window()}
            elif raw == "ordered":
                self.take()
                self.expect_word("by")
                field = self.field()
                direction = self.expect_word("asc", "desc")
                node = {"node": "order", "set": node, "field": field,
                        "dir": direction}
            else:
                return node

    def set_primary(self):
        if self.eat_punct("("):
            node = self.set_expr()
            self.expect_punct(")")
            return node
        if self.word() == "first":
            self.take()
            kind, raw = self.take()
            if kind != "number":
                raise ParseError("expected a count after `first`")
            self.expect_word("of")
            return {"node": "first", "n": int(raw), "set": self.set_expr()}
        ref = self.ref()
        if ref is not None:
            return ref
        kind = self.kind()
        node = {"node": "kind", "kind": kind, "entity": KINDS[kind][0],
                "door": KINDS[kind][1]}
        if self.word() == "of":
            self.take()
            return {"node": "walk", "kind": node, "from": self.set_primary_or_group()}
        return node

    def set_primary_or_group(self):
        if self.eat_punct("("):
            node = self.set_expr()
            self.expect_punct(")")
            return node
        return self.set_primary()

    def ref(self):
        if (self.word() == "the" and self.peek(1)[0] == "ordinal"
                and self.word(2) == "one"):
            number = int(re.match(r"\d+", self.peek(1)[1]).group())
            self.at += 3
            return {"node": "ref", "ref": "ordinal", "n": number}
        # 2 IS IN THIS TUPLE because `that one` is a two-word terminal: it was
        # in REFS and unreachable, so no canonical could say it.
        for length in (5, 4, 3, 2, 1):
            words = []
            for index in range(length):
                raw = self.word(index)
                if raw is None:
                    words = None
                    break
                words.append(raw)
            if words is None:
                continue
            phrase = " ".join(words)
            if phrase in REFS:
                self.at += length
                return {"node": "ref", "ref": phrase}
        return None

    def kind(self):
        for length in (2, 1):
            words = []
            for index in range(length):
                raw = self.word(index)
                if raw is None:
                    words = None
                    break
                words.append(raw)
            if words is None:
                continue
            phrase = " ".join(words)
            if phrase in KINDS:
                self.at += length
                return phrase
        raise ParseError("unknown kind at %r" % self.peek()[1])

    # -- predicate ----------------------------------------------------------
    def pred(self):
        node = self.pred_atom()
        while self.word() in ("and", "or"):
            how = self.take()[1]
            node = {"node": how, "left": node, "right": self.pred_atom()}
        return node

    def pred_atom(self):
        if self.eat_word("not"):
            return {"node": "not", "pred": self.pred_atom()}
        if self.eat_punct("("):
            node = self.pred()
            self.expect_punct(")")
            return node
        # `count of Kind Cmp Num` -- a COUNT OVER THE WALK from the row being
        # filtered.  Forced by s112.1 ("which of these places have I got
        # exactly two photos from?").  The edge is the ontology's (2.3); the
        # count is over the rows that walk reaches from THIS row, so no
        # correlated reference terminal is needed.
        if self.word() == "count" and self.word(1) == "of":
            self.take(); self.take()
            kind = self.kind()
            operator = self.peek()
            if operator[0] != "op":
                raise ParseError("expected a comparison after `count of %s`" % kind)
            self.take()
            number = self.take()
            if number[0] != "number":
                raise ParseError("expected a number after `count of %s %s`"
                                 % (kind, operator[1]))
            return {"node": "countwalk", "kind": kind,
                    "entity": KINDS[kind][0], "door": KINDS[kind][1],
                    "op": operator[1], "n": int(number[1])}
        if self.word() == "member" and self.word(1) == "of":
            self.take(); self.take()
            return {"node": "member", "set": self.set_primary_or_group()}
        field = self.field()
        raw = self.word()
        if raw == "is":
            self.take()
            negated = self.eat_word("not")
            what = self.expect_word("null", "me")
            return {"node": "is", "field": field, "what": what, "not": negated}
        if raw == "during":
            self.take()
            return {"node": "pwindow", "field": field, "window": self.window()}
        if raw == "around":
            self.take()
            kind, number = self.take()
            if kind != "number":
                raise ParseError("expected a number after `around`")
            return {"node": "band", "field": field, "centre": float(number)}
        if raw == "contains":
            self.take()
            return {"node": "contains", "field": field, "lit": self.string()}
        if raw == "in":
            self.take()
            self.expect_punct("(")
            items = [self.string()]
            while self.eat_punct(","):
                items.append(self.string())
            self.expect_punct(")")
            return {"node": "oneof", "field": field, "lits": items}
        kind, operator = self.peek()
        if kind == "op":
            self.take()
            return {"node": "cmp", "field": field, "op": operator,
                    "rhs": self.operand()}
        raise ParseError("expected a predicate operator, found %r" % self.peek()[1])

    def operand(self):
        kind, raw = self.peek()
        if raw == "(":
            self.take()
            inner = self.set_expr()
            self.expect_punct(")")
            return {"node": "setarg", "set": inner}
        if kind in ("string", "number", "date", "datetime", "month", "daterange"):
            self.take()
            return {"node": "lit", "type": kind, "value": unquote(raw)}
        if kind == "ident" and raw in ("true", "false", "null", "me"):
            self.take()
            return {"node": "lit", "type": "keyword", "value": raw}
        if kind == "ident":
            return {"node": "fieldref", "field": self.field()}
        raise ParseError("bad operand %r" % raw)

    # -- leaves -------------------------------------------------------------
    def field(self):
        raw = self.word()
        if raw is None:
            raise ParseError("expected a field, found %r" % self.peek()[1])
        if raw not in FIELDS:
            raise ParseError("unknown field %r" % raw)
        self.take()
        return raw

    def string(self):
        kind, raw = self.peek()
        if kind != "string":
            raise ParseError("expected a quoted literal, found %r" % raw)
        self.take()
        return unquote(raw)

    def window(self):
        kind, raw = self.peek()
        if kind in ("date", "datetime", "month", "daterange"):
            self.take()
            return {"node": "window", "how": kind, "value": raw}
        if self.word() == "from":
            self.take()
            self.expect_punct("(")
            start = self.value()
            self.expect_punct(")")
            self.expect_word("to")
            self.expect_punct("(")
            end = self.value()
            self.expect_punct(")")
            return {"node": "window", "how": "anchored", "from": start, "to": end}
        if self.word() == "next" and self.peek(1)[0] == "number":
            self.take()
            count = int(self.take()[1])
            unit = self.expect_word("months", "days", "weeks")
            return {"node": "window", "how": "rolling", "n": count, "unit": unit}
        for length in (2, 1):
            words = []
            for index in range(length):
                got = self.word(index)
                if got is None:
                    words = None
                    break
                words.append(got)
            if words is None:
                continue
            phrase = " ".join(words)
            if phrase in WINDOW_PHRASES:
                self.at += length
                return {"node": "window", "how": "phrase", "value": phrase}
        raise ParseError("unknown window at %r" % self.peek()[1])


def unquote(raw):
    if raw.startswith('"'):
        return raw[1:-1].replace('\\"', '"').replace("\\\\", "\\")
    return raw


def parse(text):
    return Parser(text).parse_turn()


# ---------------------------------------------------------------------------
# SHAPE MEASUREMENTS (used by COVERAGE.md; exported so they cannot drift)
# ---------------------------------------------------------------------------

def walk(node):
    """Every dict node in the tree, depth-first."""
    if isinstance(node, dict):
        yield node
        for value in node.values():
            yield from walk(value)
    elif isinstance(node, list):
        for item in node:
            yield from walk(item)


def depth(node):
    """Set-expression depth: how many set constructors nest."""
    if not isinstance(node, dict):
        return 0
    inner = [depth(value) for value in node.values()]
    here = 1 if node.get("node") in {
        "kind", "called", "filter", "during", "order", "union", "except",
        "first", "walk", "ref"} else 0
    return here + (max(inner) if inner else 0)


def skeleton(node):
    """The tree with every literal masked — the canonical SKELETON."""
    if isinstance(node, dict):
        out = {}
        for key, value in node.items():
            if key in ("lit", "lits", "value", "centre", "n") and \
                    node.get("node") in ("called", "lit", "contains", "oneof",
                                         "band", "first", "window", "ref",
                                         "countwalk"):
                out[key] = "?"
            else:
                out[key] = skeleton(value)
        return out
    if isinstance(node, list):
        return [skeleton(item) for item in node]
    return node


def counts(node):
    tally = {"walk": 0, "filter": 0, "agg": 0}
    for found in walk(node):
        name = found.get("node") if isinstance(found, dict) else None
        if name == "walk":
            tally["walk"] += 1
        elif name in ("filter", "during", "called"):
            tally["filter"] += 1
        elif name in ("agg", "balance", "project"):
            tally["agg"] += 1
    return tally


# ---------------------------------------------------------------------------
# MAIN
# ---------------------------------------------------------------------------

def main():
    here = os.path.dirname(os.path.abspath(__file__))
    path = os.path.join(here, "map.json")
    with open(path, encoding="utf-8") as handle:
        rows = json.load(handle)["turns"]

    failures, parsed, skipped = [], 0, 0
    for row in rows:
        label = "%s/%s.%s" % (row["corpus"], row["session"], row["turn"])
        if not row["covered"]:
            skipped += 1
            continue
        try:
            tree = parse(row["canonical"])
        except ParseError as error:
            failures.append("%s: %s\n      %s" % (label, error, row["canonical"]))
            continue
        if tree != row["tree"]:
            failures.append("%s: stored tree disagrees with the parse" % label)
            continue
        parsed += 1

    stale = terminals_are_current()
    if stale:
        failures.append(stale)

    print("canonicals parsed : %d" % parsed)
    print("uncovered (skipped): %d" % skipped)
    print("failures           : %d" % len(failures))
    for failure in failures:
        print("  FAIL %s" % failure)
    if COMMANDS:
        print("command registry   : %d typed commands, derived from crates/vault"
              % len(COMMANDS))
    else:
        print("command registry   : not reachable; verb names were not checked")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
