"""GENERATED — do not edit. Written by `crates/evalsuite/grammar/derive/emit.py` from `derive/derived.json` (the ontology, walked) and `derive/terminals.json` (the names). Regenerate with `python3 derive/emit.py`; `python3 check.py` verifies it."""

KINDS = {
    'events': ('core.event', 'agenda'),
    'tasks': ('schedule.task', 'tasks'),
    'notes': ('knowledge.note', 'notes'),
    'journal notes': ('knowledge.note', 'people'),
    'documents': ('core.document', 'docs'),
    'parties': ('core.party', 'people'),
    'members': ('core.party', 'tally'),
    'profiles': ('people.profile', 'people'),
    'important dates': ('people.important_date', 'people'),
    'contact channels': ('social.contact_channel', 'people'),
    'activities': ('core.activity', 'people'),
    'obligations': ('tally.obligation', 'people'),
    'photos': ('core.content_item', 'photos'),
    'albums': ('media.album', 'photos'),
    'notebooks': ('knowledge.notebook', 'notes'),
    'places': ('core.place', 'photos'),
    'expenses': ('tally.expense', 'tally'),
    'groups': ('tally.group', 'tally'),
    'circles': ('social.circle', 'tally'),
    'settlements': ('tally.settlement', 'tally'),
    'accounts': ('core.account', 'tally'),
    'transactions': ('core.transaction', 'tally'),
    'projects': ('schedule.project', 'tasks'),
    'locker items': ('locker.item', 'locker'),
    'things': ('*', '*'),
}

FIELDS = {
    'account_id',
    'activity_id',
    'actor_party_id',
    'address',
    'address_json',
    'album',
    'album_titles',
    'amount_minor',
    'archived_at',
    'area',
    'asset_id',
    'attendee_party_ids',
    'author_party_id',
    'avatar_color',
    'avatar_content_id',
    'birth_date',
    'body_content_id',
    'brand',
    'byte_size',
    'cadence_days',
    'camera_device_id',
    'capture_group_id',
    'captured_at',
    'cardholder',
    'category',
    'category_concept_id',
    'channel_id',
    'circle_id',
    'closed_at',
    'collection_id',
    'color',
    'completed_at',
    'compromised',
    'connection_id',
    'content_hash',
    'content_id',
    'content_uri',
    'counterparty_party_id',
    'cover_content_id',
    'created_at',
    'creator_party_id',
    'currency',
    'current_content_id',
    'current_revision_id',
    'date_id',
    'deleted_at',
    'description',
    'direction',
    'display_name',
    'document_id',
    'dtend',
    'dtstart',
    'due_at',
    'duration_s',
    'effort_min',
    'email',
    'end_tz',
    'ended_at',
    'event_id',
    'exif_json',
    'expense_id',
    'expiry',
    'external_id',
    'external_ref',
    'favorite',
    'folder',
    'format',
    'from_party',
    'fullname',
    'geo_lat',
    'geo_lng',
    'geohash',
    'group_id',
    'height',
    'ical_uid',
    'icon',
    'incurred_on',
    'institution_party_id',
    'is_asset',
    'is_preferred',
    'item_id',
    'key_id',
    'kind',
    'kind_concept_id',
    'label',
    'language',
    'last_contacted_at',
    'location_place_id',
    'member_party_ids',
    'met',
    'month_day',
    'name',
    'network',
    'next_occurrence',
    'nickname',
    'normalized_value',
    'note_id',
    'notebooks',
    'notes',
    'obligation_id',
    'opened_at',
    'organizer_party_id',
    'origin_device_id',
    'original_amount_minor',
    'original_currency',
    'owed_to_me',
    'owed_to_them',
    'owner_party_id',
    'paid_by',
    'paid_on',
    'parent_collection_id',
    'parent_place_id',
    'parent_task_id',
    'party_id',
    'password_set_at',
    'phone',
    'pinned',
    'place',
    'place_id',
    'posted_at',
    'priority',
    'profile_id',
    'project_id',
    'provenance_json',
    'purge_at',
    'rate_date',
    'rate_scale',
    'rate_scaled',
    'rate_source',
    'reason',
    'recurrence_anchor',
    'recurrence_semantics',
    'recurring_template_id',
    'remind_before_min',
    'reminder_on',
    'role',
    'row_version',
    'rrule',
    'rrule_support',
    'section_id',
    'sequence',
    'series_id',
    'settled_at',
    'settlement_currency',
    'settlement_id',
    'simplify_opt_in',
    'sort_name',
    'sort_order',
    'source_app_id',
    'source_asset_id',
    'spent_on',
    'split_method',
    'split_params_json',
    'starred',
    'start_tz',
    'started_at',
    'status',
    'summary',
    'task_id',
    'title',
    'to_party',
    'transfer_group_id',
    'txn_id',
    'type',
    'tz',
    'tz_offset_min',
    'updated_at',
    'url',
    'url_match_policy',
    'username',
    'value',
    'width',
}

VERB_CLASSES = {
    'reschedule': {
        'schedule.task': 'schedule.edit_task',
        'core.event': 'schedule.reschedule_event',
    },
    'delete': {
        'schedule.task': 'schedule.delete_task',
        'core.event': 'schedule.delete_event',
        'knowledge.note': 'knowledge.delete_note',
        'core.document': 'core.trash_document',
        'tally.expense': 'tally.delete_expense',
        'locker.item': 'locker.trash_item',
        'core.content_item': 'media.delete_asset',
        'core.party': 'people.trash_person',
    },
    'restore': {
        'schedule.task': 'schedule.restore_task',
        'core.event': 'schedule.restore_event',
        'knowledge.note': 'knowledge.restore_note',
        'core.document': 'core.restore_document',
        'tally.expense': 'tally.restore_expense',
        'locker.item': 'locker.restore_item',
        'core.content_item': 'media.restore_asset',
        'core.party': 'people.restore_person',
    },
    'complete': {
        'schedule.task': 'people.complete_task',
    },
    'cancel': {
        'core.event': 'schedule.cancel_event',
    },
}

REFS = {
    'it',
    'them',
    'that one',
    'the other one',
    'the earlier one',
    'the last thing I added',
}

WINDOW_PHRASES = {
    'today',
    'tomorrow',
    'yesterday',
    'this week',
    'last week',
    'next week',
    'this weekend',
    'last weekend',
    'this month',
    'last month',
    'next month',
    'before now',
    'recently',
}

DECLINE_REASONS = {
    'out_of_ontology',
    'sealed_egress',
    'fabricated_secret',
    'unbounded_destruction',
}

EGRESS_VERBS = {
    'locker.export',
    'social.send_message',
}

COMMANDS = {
    'core.add_document',
    'core.add_party',
    'core.anchor_link',
    'core.attach',
    'core.create_folder',
    'core.delete_folder',
    'core.detach',
    'core.edit_document',
    'core.empty_document_trash',
    'core.link_entities',
    'core.merge_party',
    'core.move_document',
    'core.rename_document',
    'core.rename_folder',
    'core.replace_document_content',
    'core.restore_document',
    'core.restore_document_version',
    'core.set_extracted_text',
    'core.star_document',
    'core.tag_item',
    'core.trash_document',
    'core.unlink_entities',
    'core.unstar_document',
    'core.untag_item',
    'core.update_party',
    'knowledge.create_note',
    'knowledge.create_notebook',
    'knowledge.delete_note',
    'knowledge.delete_notebook',
    'knowledge.edit_note',
    'knowledge.move_note',
    'knowledge.rename_notebook',
    'knowledge.restore_note',
    'knowledge.restore_note_version',
    'locker.add_item',
    'locker.archive_item',
    'locker.clear_passkey',
    'locker.counts',
    'locker.duplicate_item',
    'locker.edit_item',
    'locker.export',
    'locker.purge_item',
    'locker.remove_field',
    'locker.restore_item',
    'locker.reveal_receipt',
    'locker.rotate_key',
    'locker.set_addresses',
    'locker.set_field',
    'locker.set_memo',
    'locker.set_passkey',
    'locker.star_item',
    'locker.totp_code',
    'locker.trash_item',
    'locker.unarchive_item',
    'locker.unstar_item',
    'locker.watchtower',
    'media.add_asset',
    'media.add_to_album',
    'media.answer_face_proposal',
    'media.create_album',
    'media.delete_album',
    'media.delete_asset',
    'media.derive_missing',
    'media.forget_person',
    'media.name_place',
    'media.promote_caption',
    'media.purge_asset',
    'media.remove_from_album',
    'media.rename_album',
    'media.restore_album',
    'media.restore_asset',
    'media.set_album_cover',
    'media.set_archived',
    'media.set_asset_place',
    'media.set_favorite',
    'media.set_place_gazetteer',
    'media.update_asset',
    'people.add_debt',
    'people.add_gift',
    'people.add_important_date',
    'people.add_journal_entry',
    'people.add_note',
    'people.add_person',
    'people.add_relationship',
    'people.add_task',
    'people.complete_task',
    'people.create_list',
    'people.delete_contact_channel',
    'people.delete_list',
    'people.edit_person',
    'people.log_interaction',
    'people.move_person',
    'people.rename_list',
    'people.reopen_task',
    'people.restore_person',
    'people.save_contact_channel',
    'people.set_cadence',
    'people.settle_debt',
    'people.star_person',
    'people.toggle_gift',
    'people.toggle_reminder',
    'people.trash_person',
    'people.undo_contact_channel',
    'people.undo_person',
    'people.unstar_person',
    'schedule.add_task',
    'schedule.cancel_event',
    'schedule.delete_event',
    'schedule.delete_task',
    'schedule.edit_event',
    'schedule.edit_event_occurrence',
    'schedule.edit_task',
    'schedule.organize_task',
    'schedule.propose_event',
    'schedule.reschedule_event',
    'schedule.respond_rsvp',
    'schedule.restore_event',
    'schedule.restore_task',
    'schedule.save_project',
    'schedule.save_section',
    'schedule.set_task_status',
    'social.draft_message',
    'social.mark_thread_read',
    'social.resolve_identity',
    'social.send_message',
    'tally.add_expense',
    'tally.add_friend',
    'tally.add_group_member',
    'tally.add_receipt_expense',
    'tally.archive_group',
    'tally.bind_txn',
    'tally.create_group',
    'tally.delete_expense',
    'tally.delete_group',
    'tally.edit_expense',
    'tally.edit_recurring_expense_occurrence',
    'tally.leave_group',
    'tally.materialize_recurring_expense',
    'tally.nudge',
    'tally.reallocate_receipt',
    'tally.remove_group_member',
    'tally.rename_group',
    'tally.restore_expense',
    'tally.save_recurring_expense',
    'tally.set_expense_memo',
    'tally.set_group_simplification',
    'tally.settle_up',
    'tally.undo_expense',
}
