export default {
  packageManager: "npm",
  testRunner: "vitest",
  vitest: { configFile: "vitest.notes.mutation.config.ts", related: false },
  testFiles: [
    "apps/notes/logic.test.ts",
    "apps/notes/logic-commands.test.ts",
    "apps/notes/logic-panes.test.ts",
    "apps/notes/format.test.ts",
    "apps/notes/shelves.test.ts",
    "apps/notes/send-to-tasks.test.ts",
    "apps/notes/powerbox.test.ts",
    "apps/notes/commonmark.test.ts",
  ],
  mutate: [
    "apps/notes/logic.ts",
    "apps/notes/format.ts",
    "apps/notes/shelves.ts",
    "apps/notes/send-to-tasks.ts",
    "apps/notes/powerbox.ts",
    "apps/notes/commonmark.ts",
  ],
  reporters: ["clear-text", "json"],
  jsonReporter: {
    fileName: "../../artifacts/mutation/notes-report.json",
  },
  thresholds: { high: 80, low: 50, break: null },
  timeoutMS: 60_000,
  concurrency: 2,
  ignoreStatic: true,
  disableTypeChecks: true,
};
