export default {
  packageManager: "npm",
  testRunner: "vitest",
  vitest: { configFile: "vitest.agenda.mutation.config.ts", related: false },
  testFiles: [
    "apps/agenda/logic.test.ts",
    "apps/agenda/logic-search.test.ts",
    "apps/agenda/edits.test.ts",
    "apps/agenda/views.test.ts",
    "apps/agenda/day-context.test.ts",
    "apps/agenda/view-copy.test.ts",
    "apps/agenda/format-locale.test.ts",
  ],
  mutate: [
    "apps/agenda/logic.ts",
    "apps/agenda/edits.ts",
    "apps/agenda/views.ts",
    "apps/agenda/day-context.ts",
    "apps/agenda/format.ts",
  ],
  reporters: ["clear-text", "json"],
  jsonReporter: {
    fileName: "../../artifacts/mutation/agenda-report.json",
  },
  thresholds: { high: 80, low: 50, break: null },
  timeoutMS: 60_000,
  concurrency: 2,
  ignoreStatic: true,
  disableTypeChecks: true,
};
