import { StyleSheet } from "react-native";

import { radii, spacing, t } from "../../kit/theme";
import type { ThemeColors } from "../../kit/theme";

export const makeStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    assistantBubble: {
      backgroundColor: colors.bgElev,
      borderColor: colors.line,
      borderRadius: radii.lg,
      borderWidth: 1,
      maxWidth: "86%",
      paddingHorizontal: 14,
      paddingVertical: 10,
    },
    assistantText: { ...t("body"), color: colors.text },
    attachButton: {
      alignItems: "center",
      height: 36,
      justifyContent: "center",
      width: 30,
    },
    attachmentChip: {
      alignItems: "center",
      backgroundColor: colors.bgElev,
      borderColor: colors.line,
      borderRadius: radii.md,
      borderWidth: 1,
      flexDirection: "row",
      gap: spacing[1],
      maxWidth: 180,
      paddingHorizontal: spacing[2],
      paddingVertical: spacing[1],
    },
    attachmentRow: {
      flexDirection: "row",
      gap: spacing[2],
      paddingBottom: spacing[2],
    },
    composer: {
      alignItems: "flex-end",
      backgroundColor: colors.bgSunken,
      borderRadius: radii.lg,
      flexDirection: "row",
      gap: spacing[2],
      paddingHorizontal: spacing[3],
      paddingVertical: spacing[2],
    },
    composerWrap: { paddingHorizontal: spacing[4], paddingTop: spacing[2] },
    statusStrip: {
      alignItems: "center",
      flexDirection: "row",
      gap: spacing[2],
      paddingBottom: spacing[2],
    },
    statusChip: {
      backgroundColor: colors.bgElev,
      borderColor: colors.line,
      borderRadius: radii.md,
      borderWidth: 1,
      maxWidth: 120,
      paddingHorizontal: spacing[2],
      paddingVertical: spacing[1],
    },
    statusText: { ...t("control"), color: colors.textSoft },
    activityDot: {
      backgroundColor: colors.textFaint,
      borderRadius: radii.sm,
      height: 7,
      width: 7,
    },
    activityDotBusy: { backgroundColor: colors.accent },
    contextTrack: {
      backgroundColor: colors.bgSunken,
      borderRadius: radii.sm,
      flex: 1,
      height: 4,
      minWidth: 28,
      overflow: "hidden",
    },
    contextFill: {
      backgroundColor: colors.accent,
      borderRadius: radii.sm,
      height: 4,
    },
    emptyBody: {
      ...t("body"),
      color: colors.textSoft,
      marginTop: spacing[2],
      textAlign: "center",
    },
    emptyTitle: { ...t("title"), color: colors.text, textAlign: "center" },
    emptyWrap: {
      alignItems: "center",
      flex: 1,
      justifyContent: "center",
      paddingBottom: spacing[6],
      paddingHorizontal: spacing[6],
    },
    errorText: { ...t("body"), color: colors.danger },
    header: {
      alignItems: "center",
      flexDirection: "row",
      gap: spacing[3],
      paddingHorizontal: spacing[4],
      paddingTop: spacing[2],
    },
    headerText: { flex: 1, minWidth: 0 },
    input: {
      ...t("body"),
      color: colors.text,
      flex: 1,
      maxHeight: 120,
      paddingVertical: spacing[2],
    },
    list: {
      flexGrow: 1,
      gap: spacing[3],
      paddingHorizontal: spacing[4],
      paddingVertical: spacing[4],
    },
    pendingText: { ...t("body"), color: colors.textFaint, fontStyle: "italic" },
    rowLeft: { alignItems: "flex-start" },
    rowRight: { alignItems: "flex-end" },
    safe: { backgroundColor: colors.bg, flex: 1 },
    sendButton: {
      alignItems: "center",
      backgroundColor: colors.accent,
      borderRadius: radii.lg,
      height: 36,
      justifyContent: "center",
      width: 36,
    },
    sendButtonDisabled: {
      backgroundColor: colors.bgSunken,
      borderColor: colors.line,
      borderWidth: 1,
    },
    selectionError: {
      ...t("control"),
      color: colors.danger,
      paddingBottom: spacing[2],
    },
    subtitle: { ...t("small"), color: colors.textSoft, marginTop: 2 },
    title: {
      ...t("display"),
      color: colors.text,
    },
    userBubble: {
      backgroundColor: colors.accent,
      borderRadius: radii.lg,
      maxWidth: "86%",
      paddingHorizontal: 14,
      paddingVertical: 10,
    },
    userText: { ...t("body"), color: colors.textInv },
  });
