import { StyleSheet } from "react-native";

import { borders, spacing, t, radii } from "../kit/theme";

export const styles = StyleSheet.create({
  action: {
    alignItems: "center",
    borderRadius: radii.lg,
    borderWidth: borders.hairline,
    justifyContent: "center",
    minHeight: 48,
    paddingHorizontal: spacing[4],
  },
  actionText: t("control"),
  actions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing[2],
    marginTop: spacing[3],
  },
  body: { ...t("reading"), marginBottom: spacing[4] },
  content: { padding: spacing[4] + 2, paddingBottom: spacing[6] + 18 },
  error: { ...t("control"), marginVertical: spacing[1] + 1 },
  eyebrow: t("eyebrow"),
  fact: {
    borderBottomWidth: borders.hairline,
    borderLeftColor: "transparent",
    borderLeftWidth: 2,
    minHeight: 44,
    paddingVertical: spacing[2],
  },
  factFlagged: { paddingLeft: spacing[3] },
  factLabel: t("mono"),
  factValue: { ...t("mono"), marginTop: spacing[1] },
  filled: { borderColor: "transparent" },
  header: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing[3],
    minHeight: 50,
    paddingHorizontal: spacing[4] - 2,
  },
  headerCopy: { flex: 1 },
  hero: {
    alignItems: "center",
    borderRadius: radii.lg,
    borderWidth: 1,
    padding: spacing[5] + 2,
  },
  heroFlagged: { borderLeftWidth: 2, paddingLeft: spacing[5] },
  heroValue: { ...t("bodyStrong"), marginTop: spacing[3] },
  meta: { ...t("control"), marginTop: spacing[1] + 1 },
  note: { ...t("small"), marginBottom: spacing[2] },
  panel: {
    borderRadius: radii.lg,
    borderWidth: borders.hairline,
    marginTop: spacing[4],
    padding: spacing[4],
  },
  panelTitle: {
    ...t("title"),
    marginBottom: spacing[3],
    marginTop: spacing[2],
  },
  rule: {
    alignItems: "center",
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 52,
  },
  ruleFlagged: { borderLeftWidth: 2, paddingLeft: spacing[3] },
  ruleLabel: { ...t("body") },
  ruleText: { flex: 1, paddingRight: spacing[3], paddingVertical: spacing[2] },
  ruleReason: { ...t("small"), marginTop: 2 },
  safe: { flex: 1 },
  section: {
    ...t("eyebrow"),
    marginBottom: spacing[1] + 2,
    marginTop: spacing[6] - 6,
  },
  settings: {
    alignItems: "center",
    borderRadius: radii.lg,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing[2] + 2,
    marginTop: spacing[6],
    padding: spacing[3] + 3,
  },
  settingsText: t("smallStrong"),
  subtitle: { ...t("small"), marginTop: 2 },
  title: t("bodyStrong"),
  unavailable: { ...t("small"), marginTop: spacing[3] },
});
