//! `contracts/schema/vault-ddl.sql` is the schema a NEW VAULT GETS (#1029).
//!
//! The owner's ruling of 2026-09-21 splits one fixture into two. The corpus's
//! own description stays beside the corpus (`contracts/golden/issue-1020/
//! vault-ddl.sql`, regenerated by `centraid-ontology`'s `export-ddl`) and
//! records a frozen v0 file as it was. This file records something else: the
//! `sqlite_master` of a vault founded at the ladder head — every rung run, in
//! order, exactly as `Vault::create` runs them.
//!
//! The two were the same text while the ladder only added. They stop being the
//! same the moment a rung drops a table, which is the whole reason the ruling
//! separates them: v0's record must not be edited, and v0's table list must not
//! be what v1 founds.
//!
//! A fixture nobody regenerates is a lie with a filename, so this test founds a
//! vault in a scratch directory and re-renders the fixture in memory from its
//! live schema, exactly as `bin/export-ladder-ddl` does, and diffs.

use centraid_ontology::golden::repo_root;
use centraid_vault::migrations::render_ladder_ddl;

/// The first differing line of two texts, as a message a reviewer can act on.
///
/// The same shape as `crates/ontology/tests/fixtures.rs`'s, and deliberately a
/// second copy: the two crates do not share a test-support crate, and a
/// `assert_eq!` over two 20,000-line strings prints something nobody reads.
fn first_difference(expected: &str, actual: &str) -> Option<String> {
    let mut expected_lines = expected.lines().enumerate();
    let mut actual_lines = actual.lines();
    loop {
        match (expected_lines.next(), actual_lines.next()) {
            (None, None) => return None,
            (Some((index, left)), Some(right)) if left != right => {
                return Some(format!(
                    "line {}:\n  fixture: {left}\n  live:    {right}",
                    index + 1
                ));
            }
            (Some((index, left)), None) => {
                return Some(format!(
                    "the fixture has {} extra line(s), first: {left}",
                    { expected.lines().count() - index }
                ));
            }
            (None, Some(right)) => {
                return Some(format!("the live schema has extra line(s), first: {right}"));
            }
            (Some(_), Some(_)) => {}
        }
    }
}

#[test]
fn the_ddl_fixture_still_describes_what_a_new_vault_founds() {
    let live = render_ladder_ddl().expect("the DDL renders");
    let fixture = std::fs::read_to_string(repo_root().join("contracts/schema/vault-ddl.sql"))
        .expect("the DDL fixture is committed");
    assert_eq!(
        first_difference(&fixture, &live),
        None,
        "regenerate with: cargo run -p centraid-vault --bin export-ladder-ddl \
         > contracts/schema/vault-ddl.sql"
    );
}

#[test]
fn the_ddl_fixture_is_not_vacuous() {
    // A fixture that rendered to its header alone would compare equal to a
    // vault with no schema, which is the one way this gate could pass for free.
    let fixture = std::fs::read_to_string(repo_root().join("contracts/schema/vault-ddl.sql"))
        .expect("the DDL fixture is committed");
    let statements = fixture.matches("\nCREATE ").count();
    assert!(
        statements > 500,
        "only {statements} statements in the fixture"
    );
    assert!(fixture.contains("CREATE TABLE core_party"));
    assert!(fixture.contains("CREATE VIRTUAL TABLE fts_knowledge_note"));
}

#[test]
fn the_fixture_is_the_ladder_head_and_not_the_corpuss_description() {
    // THE POINT OF THE SPLIT. The two files are different fixtures answering
    // different questions, and this is what stops one being silently repointed
    // at the other: the ladder head carries every rung's objects, and the
    // corpus, a v0 file, carries none of them.
    let fixture = std::fs::read_to_string(repo_root().join("contracts/schema/vault-ddl.sql"))
        .expect("the ladder-head fixture is committed");
    let corpus =
        std::fs::read_to_string(repo_root().join("contracts/golden/issue-1020/vault-ddl.sql"))
            .expect("the corpus's description is committed");
    for object in [
        "core_entity_revision_no_self_parent",
        "core_link_no_revises_edge",
        "backup_base_range",
        "backup_blob_custody",
    ] {
        assert!(
            fixture.contains(object),
            "`{object}` is a rung's object and is not in the ladder-head fixture"
        );
        assert!(
            !corpus.contains(object),
            "`{object}` is in the corpus's description, which is a v0 file"
        );
    }
}
