//! **v0 is the oracle**: every case in `contracts/time/` is compared against
//! this crate's answer (#1020, wave 4 lane Schedule, D-1020-D3-6).
//!
//! The corpus is generated by `contracts/tools/export-time-corpus.ts` from the
//! live `packages/core/src/time` modules, and
//! `tests/quality/time-corpus.contract.test.ts` is both the emitter and the
//! v0-side oracle. Nothing here is typed by hand and nothing here is
//! regenerated from this crate: a fixture a port could rewrite proves nothing.
//!
//! ## What each file proves
//!
//! | File | The claim it would falsify |
//! |---|---|
//! | `rrule-cases.json` | a part this engine cannot honour is REFUSED with v0's own sentence, and the summariser says v0's words |
//! | `dst-cases.json` | a gap is skipped, a fold occurs once at the earlier instant, and a wall clock survives an offset change — in six zones, one with a 30-minute shift, one with negative DST and one at a :45 offset |
//! | `occurrence-cases.json` | the occurrence key is `original_start_local`, the SERIES-LOCAL WALL CLOCK, and keying on the resolved instant matches nothing (ONT-25) |

use std::collections::BTreeMap;
use std::path::PathBuf;

use centraid_vault::time::occurrence::{SeriesType, StoredExceptionRow};
use centraid_vault::time::recurrence::{
    CollapseInput, ExceptionAction, ExceptionScope, ExpandInput, NextOccurrenceInput,
    RecurrenceAnchor, Semantics,
};
use centraid_vault::time::zone::{FireZone, parse_wall_iso};
use centraid_vault::time::{occurrence, recurrence, rrule, temporal};
use serde_json::Value;

fn fixture(name: &str) -> Value {
    let path: PathBuf = [
        env!("CARGO_MANIFEST_DIR"),
        "..",
        "..",
        "contracts",
        "time",
        name,
    ]
    .iter()
    .collect();
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("{} is missing: {error}", path.display()));
    serde_json::from_str(&text).unwrap_or_else(|error| panic!("{name} is not JSON: {error}"))
}

fn text(value: &Value, key: &str) -> String {
    value[key].as_str().unwrap_or_default().to_owned()
}

/// A zone the corpus names. `(none)` is the floating and all-day half, where
/// there is deliberately no zone at all.
fn zone_of(name: &str) -> Option<FireZone> {
    if name == "(none)" {
        return None;
    }
    Some(FireZone::named(name).unwrap_or_else(|error| panic!("{name}: {error}")))
}

// ---------------------------------------------------------------------------
// rrule-cases.json
// ---------------------------------------------------------------------------

#[test]
fn every_rrule_case_agrees_with_v0() {
    let corpus = fixture("rrule-cases.json");
    let cases = corpus["cases"].as_array().expect("cases");
    assert!(
        cases.len() > 200,
        "the corpus is not empty: {}",
        cases.len()
    );
    let mut accepted = 0_usize;
    let mut refused = 0_usize;
    for case in cases {
        let value = text(case, "rrule");
        let label = format!("rrule {value:?}");
        assert_eq!(
            rrule::canonicalize(&value),
            text(case, "canonical"),
            "{label}: canonical form"
        );
        assert_eq!(
            rrule::rrule_line(&value),
            text(case, "line"),
            "{label}: RRULE: line"
        );
        assert_eq!(
            rrule::describe(&value),
            case["summary"].as_str().map(str::to_owned),
            "{label}: the one summariser"
        );
        match rrule::inspect(&value) {
            Ok(rule) => {
                accepted += 1;
                assert!(
                    case["accepted"].as_bool().unwrap_or_default(),
                    "{label}: v0 refused and this build accepted"
                );
                let expected = &case["rule"];
                assert_eq!(
                    rule.freq.as_str(),
                    expected["freq"].as_str().unwrap_or_default(),
                    "{label}: freq"
                );
                assert_eq!(
                    rule.interval,
                    expected["interval"].as_i64().unwrap_or(1),
                    "{label}: interval"
                );
                assert_eq!(rule.count, expected["count"].as_i64(), "{label}: count");
                assert_eq!(
                    rule.until,
                    expected["until"].as_str().map(str::to_owned),
                    "{label}: until"
                );
                let expected_days: Option<Vec<String>> = expected["byDay"].as_array().map(|days| {
                    days.iter()
                        .map(|day| day.as_str().unwrap_or_default().to_owned())
                        .collect()
                });
                let found_days: Option<Vec<String>> = rule
                    .by_day
                    .as_ref()
                    .map(|days| days.iter().map(|day| (*day).to_owned()).collect());
                assert_eq!(found_days, expected_days, "{label}: byDay");
            }
            Err(refusal) => {
                refused += 1;
                assert!(
                    !case["accepted"].as_bool().unwrap_or_default(),
                    "{label}: v0 accepted and this build refused with {refusal}"
                );
                assert_eq!(refusal.reason(), text(case, "reason"), "{label}: reason");
                assert_eq!(
                    refusal.message(),
                    text(case, "message"),
                    "{label}: THE SENTENCE — a member reads this one"
                );
                match &refusal {
                    rrule::Refusal::UnsupportedPart { part } => {
                        assert_eq!(*part, text(case, "part"), "{label}: part");
                    }
                    rrule::Refusal::UnsupportedFreq { freq } => {
                        assert_eq!(*freq, text(case, "freq"), "{label}: freq");
                    }
                    rrule::Refusal::Malformed => {
                        assert!(case["part"].is_null(), "{label}: malformed names no part");
                    }
                }
            }
        }
    }
    assert!(
        accepted > 80 && refused > 30,
        "{accepted} accepted / {refused} refused"
    );
}

#[test]
fn the_cautionary_case_is_refused_with_its_own_sentence() {
    let corpus = fixture("rrule-cases.json");
    let cautionary = &corpus["cautionary"];
    assert_eq!(text(cautionary, "rrule"), "FREQ=MONTHLY;BYSETPOS=-1");
    let refusal = rrule::inspect("FREQ=MONTHLY;BYSETPOS=-1").expect_err("refused");
    assert_eq!(refusal.message(), text(cautionary, "message"));
    assert_eq!(rrule::parse("FREQ=MONTHLY;BYSETPOS=-1"), None);
}

// ---------------------------------------------------------------------------
// dst-cases.json
// ---------------------------------------------------------------------------

fn semantics_of(name: &str) -> Semantics {
    match name {
        "floating" => Semantics::Floating,
        "all-day" => Semantics::AllDay,
        _ => Semantics::Zoned,
    }
}

fn compare_expansion(case: &Value, label: &str) {
    let zone = zone_of(&text(case, "zone"));
    let rrule_text = text(case, "rrule");
    let start = text(case, "start");
    let from = text(case, "rangeFrom");
    let to = text(case, "rangeTo");
    let mut input = ExpandInput::new(&rrule_text, &start, &from, &to)
        .with_semantics(semantics_of(&text(case, "semantics")))
        .at_most(usize::try_from(case["maxInstances"].as_u64().unwrap_or(366)).unwrap_or(366));
    input.zone = zone.as_ref();
    let found = recurrence::expand(&input);
    let expected = case["occurrences"].as_array().expect("occurrences");
    assert_eq!(
        found.len(),
        expected.len(),
        "{label}: occurrence count (found {:?})",
        found
            .iter()
            .map(|item| item.wall_start.as_str())
            .collect::<Vec<_>>()
    );
    for (index, (occurrence, want)) in found.iter().zip(expected).enumerate() {
        assert_eq!(
            occurrence.start,
            text(want, "start"),
            "{label}[{index}]: start"
        );
        assert_eq!(
            occurrence.wall_start,
            text(want, "wallStart"),
            "{label}[{index}]: THE KEY"
        );
        assert_eq!(
            occurrence.overlap,
            want["overlap"].as_bool().unwrap_or_default(),
            "{label}[{index}]: overlap"
        );
    }
}

#[test]
fn every_zoned_expansion_agrees_with_v0() {
    let corpus = fixture("dst-cases.json");
    let cases = corpus["cases"].as_array().expect("cases");
    assert_eq!(cases.len(), 78);
    let mut occurrences = 0_usize;
    for case in cases {
        let label = format!(
            "{} / {} / {}",
            text(case, "zone"),
            text(case, "rrule"),
            text(case, "start")
        );
        compare_expansion(case, &label);
        occurrences += case["occurrences"].as_array().map_or(0, Vec::len);
    }
    assert!(occurrences > 400, "{occurrences} occurrences compared");
}

#[test]
fn every_floating_and_all_day_expansion_agrees_with_v0() {
    let corpus = fixture("dst-cases.json");
    for case in corpus["floating"].as_array().expect("floating") {
        let label = format!("{} / {}", text(case, "semantics"), text(case, "rrule"));
        compare_expansion(case, &label);
    }
}

#[test]
fn every_wall_clock_resolution_agrees_with_v0() {
    let corpus = fixture("dst-cases.json");
    let mut gaps = 0_usize;
    let mut folds = 0_usize;
    for case in corpus["wallResolutions"]
        .as_array()
        .expect("wallResolutions")
    {
        let name = text(case, "zone");
        let probe = text(case, "wall");
        let label = format!("{name} @ {probe}");
        let zone = FireZone::named(&name).expect("a real zone");
        let wall = parse_wall_iso(&probe).unwrap_or_else(|| panic!("{label}: unparseable probe"));
        let resolved = zone.resolve_wall_time(wall);
        match case["instant"].as_str() {
            None => {
                assert!(resolved.is_none(), "{label}: v0 found no instant (a GAP)");
                gaps += 1;
            }
            Some(instant) => {
                let resolved = resolved.unwrap_or_else(|| panic!("{label}: this build found none"));
                assert_eq!(resolved.instant, instant, "{label}: instant");
                let overlap = case["overlap"].as_bool().unwrap_or_default();
                assert_eq!(resolved.overlap, overlap, "{label}: overlap");
                if overlap {
                    folds += 1;
                }
            }
        }
    }
    assert!(gaps > 0, "the corpus contains a gap");
    assert!(folds > 0, "the corpus contains a fold");
}

// ---------------------------------------------------------------------------
// occurrence-cases.json
// ---------------------------------------------------------------------------

fn stored_rows(corpus: &Value) -> Vec<StoredExceptionRow> {
    corpus["rows"]
        .as_array()
        .expect("rows")
        .iter()
        .map(|row| StoredExceptionRow {
            target_type: row["target_type"].as_str().map(str::to_owned),
            target_id: row["target_id"].as_str().map(str::to_owned),
            original_start_local: row["original_start_local"].as_str().map(str::to_owned),
            recurrence_semantics: row["recurrence_semantics"].as_str().map(str::to_owned),
            scope: row["scope"].as_str().map(str::to_owned),
            action: row["action"].as_str().map(str::to_owned),
            override_json: row["override_json"].as_str().map(str::to_owned),
        })
        .collect()
}

#[test]
fn the_occurrence_column_is_spelled_once_and_v0_agrees() {
    let corpus = fixture("occurrence-cases.json");
    assert_eq!(
        occurrence::OCCURRENCE_LOCAL_START_COLUMN,
        text(&corpus, "column")
    );
}

#[test]
fn every_stored_exception_reads_as_v0_reads_it() {
    let corpus = fixture("occurrence-cases.json");
    let rows = stored_rows(&corpus);
    let found = occurrence::exceptions_of(&rows, SeriesType::Event, "event-1");
    let expected = corpus["exceptions"].as_array().expect("exceptions");
    assert_eq!(
        found.len(),
        expected.len(),
        "a row with no key is not an exception"
    );
    for (exception, want) in found.iter().zip(expected) {
        let label = text(want, "localStart");
        assert_eq!(exception.key.local_start, label, "local start");
        assert_eq!(
            exception.key.series_type.as_str(),
            text(want, "seriesType"),
            "{label}: series type"
        );
        assert_eq!(
            exception.key.semantics.as_str(),
            text(want, "semantics"),
            "{label}: semantics"
        );
        assert_eq!(exception.key.token(), text(want, "token"), "{label}: token");
        let action = match exception.action {
            ExceptionAction::Skip => "skip",
            ExceptionAction::Override => "override",
        };
        assert_eq!(action, text(want, "action"), "{label}: action");
        let scope = match exception.scope {
            ExceptionScope::Occurrence => "occurrence",
            ExceptionScope::Future => "future",
        };
        assert_eq!(scope, text(want, "scope"), "{label}: scope");
        assert_eq!(
            exception.override_value.as_ref(),
            want["override"].as_object().map(|_| &want["override"]),
            "{label}: override"
        );
    }
}

#[test]
fn every_override_lookup_agrees_with_v0() {
    let corpus = fixture("occurrence-cases.json");
    let rows = stored_rows(&corpus);
    let exceptions = occurrence::exceptions_of(&rows, SeriesType::Event, "event-1");
    for case in corpus["overrideAt"].as_array().expect("overrideAt") {
        let at = text(case, "localStart");
        let found = occurrence::override_at(&exceptions, &at);
        let want = &case["override"];
        if want.is_null() {
            assert!(found.is_none(), "{at}: v0 found no override");
        } else {
            assert_eq!(found, Some(want), "{at}: override");
        }
    }
}

#[test]
fn the_exception_fold_agrees_with_v0_before_and_after() {
    let corpus = fixture("occurrence-cases.json");
    let expansion = &corpus["expansion"];
    let zone = FireZone::named(&text(expansion, "zone")).expect("a real zone");
    let rrule_text = text(expansion, "rrule");
    let start = text(expansion, "start");
    let from = text(expansion, "rangeFrom");
    let to = text(expansion, "rangeTo");
    let instances = recurrence::expand(
        &ExpandInput::new(&rrule_text, &start, &from, &to)
            .in_zone(&zone)
            .at_most(400),
    );
    let before = expansion["before"].as_array().expect("before");
    assert_eq!(instances.len(), before.len());
    for (occurrence, want) in instances.iter().zip(before) {
        assert_eq!(occurrence.wall_start, text(want, "wallStart"));
        assert_eq!(occurrence.start, text(want, "start"));
    }
    let rows = stored_rows(&corpus);
    let exceptions = occurrence::exceptions_of(&rows, SeriesType::Event, "event-1");
    let applied = recurrence::apply_exceptions(
        &instances,
        &occurrence::recurrence_exceptions_of(&exceptions),
    );
    let after = expansion["after"].as_array().expect("after");
    assert_eq!(applied.len(), after.len(), "the skip removed exactly one");
    for (occurrence, want) in applied.iter().zip(after) {
        assert_eq!(occurrence.wall_start, text(want, "wallStart"));
        assert_eq!(
            occurrence.start,
            text(want, "start"),
            "the override moved it"
        );
    }
}

/// ONT-25, held as a test rather than a paragraph.
#[test]
fn a_skip_keyed_on_the_resolved_instant_still_matches_nothing() {
    let corpus = fixture("occurrence-cases.json");
    let ont25 = &corpus["ont25"];
    let expansion = &corpus["expansion"];
    let zone = FireZone::named(&text(expansion, "zone")).expect("a real zone");
    let rrule_text = text(expansion, "rrule");
    let start = text(expansion, "start");
    let from = text(expansion, "rangeFrom");
    let to = text(expansion, "rangeTo");
    let instances = recurrence::expand(
        &ExpandInput::new(&rrule_text, &start, &from, &to)
            .in_zone(&zone)
            .at_most(400),
    );
    let wrong = recurrence::apply_exceptions(
        &instances,
        &[recurrence::RecurrenceException {
            original_start: text(ont25, "instantKey"),
            action: ExceptionAction::Skip,
            scope: ExceptionScope::Occurrence,
            start: None,
        }],
    );
    assert_eq!(
        wrong.len(),
        usize::try_from(ont25["keptWithInstantKey"].as_u64().unwrap_or_default())
            .unwrap_or_default(),
        "the instant key matches nothing, exactly as v0 says"
    );
    let right = recurrence::apply_exceptions(
        &instances,
        &[recurrence::RecurrenceException {
            original_start: text(ont25, "wallKey"),
            action: ExceptionAction::Skip,
            scope: ExceptionScope::Occurrence,
            start: None,
        }],
    );
    assert_eq!(right.len(), instances.len() - 1, "the wall key matches one");
}

#[test]
fn every_search_window_agrees_with_v0() {
    let corpus = fixture("occurrence-cases.json");
    for case in corpus["searchWindows"].as_array().expect("searchWindows") {
        let at = text(case, "localStart");
        let found = occurrence::search_window(&at, occurrence::SEARCH_WINDOW_DAYS);
        let want = &case["window"];
        if want.is_null() {
            assert!(found.is_none(), "{at}: v0 found no window");
        } else {
            let (from, to) = found.unwrap_or_else(|| panic!("{at}: this build found none"));
            assert_eq!(from, text(want, "from"), "{at}: from");
            assert_eq!(to, text(want, "to"), "{at}: to");
        }
    }
}

#[test]
fn every_next_occurrence_agrees_with_v0() {
    let corpus = fixture("occurrence-cases.json");
    for case in corpus["nextOccurrence"].as_array().expect("nextOccurrence") {
        let zone = FireZone::named(&text(case, "zone")).expect("a real zone");
        let rrule_text = text(case, "rrule");
        let scheduled = text(case, "scheduledStart");
        let after = text(case, "after");
        let found = recurrence::next_occurrence(&NextOccurrenceInput {
            rrule: &rrule_text,
            scheduled_start: &scheduled,
            after: &after,
            zone: Some(&zone),
            anchor: RecurrenceAnchor::from_stored(case["anchor"].as_str()),
        });
        assert_eq!(
            found.as_deref(),
            case["next"].as_str(),
            "{rrule_text} after {after}"
        );
    }
}

#[test]
fn every_missed_collapse_agrees_with_v0() {
    let corpus = fixture("occurrence-cases.json");
    for case in corpus["collapse"].as_array().expect("collapse") {
        let zone = FireZone::named(&text(case, "zone")).expect("a real zone");
        let rrule_text = text(case, "rrule");
        let scheduled = text(case, "scheduledStart");
        let now = text(case, "now");
        let completed = case["lastCompletedAt"].as_str().map(str::to_owned);
        let found = recurrence::collapse_missed(&CollapseInput {
            rrule: &rrule_text,
            scheduled_start: &scheduled,
            zone: Some(&zone),
            anchor: RecurrenceAnchor::from_stored(case["anchor"].as_str()),
            now: &now,
            last_completed_at: completed.as_deref(),
        });
        let want = &case["collapsed"];
        assert_eq!(
            i64::try_from(found.missed).unwrap_or_default(),
            want["missed"].as_i64().unwrap_or_default(),
            "{rrule_text} @ {now}: missed"
        );
        assert_eq!(
            found.next_due.as_deref(),
            want["nextDue"].as_str(),
            "{rrule_text} @ {now}: next due"
        );
    }
}

#[test]
fn every_temporal_classification_agrees_with_v0() {
    let corpus = fixture("occurrence-cases.json");
    let mut seen: BTreeMap<&str, usize> = BTreeMap::new();
    for case in corpus["temporal"].as_array().expect("temporal") {
        let value = text(case, "value");
        let found = temporal::classify(&value).map(temporal::Kind::as_str);
        assert_eq!(found, case["kind"].as_str(), "{value:?}");
        *seen.entry(found.unwrap_or("null")).or_default() += 1;
    }
    assert_eq!(seen.len(), 5, "all four readings and the refusal appear");
}
