// GENERATED by contracts/tools/export-native-catalog.ts. Do not edit.
//
// The app catalogue, the resolved identity marks and the shared icon
// silhouettes, lowered from packages/design (#1020, wave A). A hand-edited
// copy of this table is a lowering with no drift gate, which is what
// `git diff --exit-code design copy mobile` in the mobile-jvm gate step
// exists to prevent.

import SwiftUI

/// One first-party app's launcher identity.
///
/// `…Meta`, not `CentraidApp`: the shell's `@main` entry point is a SwiftUI
/// `App` named `CentraidApp`, and the two would collide.
public struct CentraidAppMeta {
    public let id: String
    public let name: String
    public let desc: String
    public let iconKey: String
    public let colorKey: String
}

/// An app's icon chip, already composited. See the Kotlin table.
public struct CentraidAppMark {
    public let hue: Color
    public let chipBackground: Color
    public let markColor: Color
}

/// One `<path>` of a silhouette: SVG path data in a 24x24 viewBox.
public struct CentraidIconPath {
    public let d: String
    public let filled: Bool
    public let evenOdd: Bool
}

public enum CentraidCatalog {
    /// The eight first-party apps, in CATALOGUE order — the all-apps
    /// listing's order, which says nothing about the grid.
    public static let apps: [CentraidAppMeta] = [
        CentraidAppMeta(id: "notes", name: "Notes", desc: "Write and revisit durable notes.", iconKey: "Book", colorKey: "slate"),
        CentraidAppMeta(id: "people", name: "People", desc: "Keep people and relationships close.", iconKey: "AddressBook", colorKey: "violet"),
        CentraidAppMeta(id: "photos", name: "Photos", desc: "Browse and protect your photos.", iconKey: "Camera", colorKey: "amber"),
        CentraidAppMeta(id: "locker", name: "Locker", desc: "Keep private secrets behind a lock.", iconKey: "Lock", colorKey: "rose"),
        CentraidAppMeta(id: "tally", name: "Tally", desc: "See balances and simple trends.", iconKey: "Receipt", colorKey: "indigo"),
        CentraidAppMeta(id: "tasks", name: "Tasks", desc: "Capture the next thing to do.", iconKey: "Check", colorKey: "ochre"),
        CentraidAppMeta(id: "docs", name: "Docs", desc: "Read and organize your documents.", iconKey: "Folder", colorKey: "teal"),
        CentraidAppMeta(id: "agenda", name: "Agenda", desc: "Keep dates, events, and plans together.", iconKey: "Calendar", colorKey: "forest"),
    ]

    /// By id, for the header that names one app.
    public static let byID: [String: CentraidAppMeta] = Dictionary(
        uniqueKeysWithValues: apps.map { ($0.id, $0) })

    public static let lightMarks: [String: CentraidAppMark] = [
        "notes": CentraidAppMark(hue: Color(.sRGB, red: 0.243137, green: 0.396078, blue: 0.588235, opacity: 1.000000), chipBackground: Color(.sRGB, red: 0.894118, green: 0.913725, blue: 0.937255, opacity: 1.000000), markColor: Color(.sRGB, red: 0.227451, green: 0.368627, blue: 0.545098, opacity: 1.000000)),
        "people": CentraidAppMark(hue: Color(.sRGB, red: 0.478431, green: 0.321569, blue: 0.513725, opacity: 1.000000), chipBackground: Color(.sRGB, red: 0.925490, green: 0.905882, blue: 0.925490, opacity: 1.000000), markColor: Color(.sRGB, red: 0.454902, green: 0.305882, blue: 0.490196, opacity: 1.000000)),
        "photos": CentraidAppMark(hue: Color(.sRGB, red: 0.564706, green: 0.305882, blue: 0.274510, opacity: 1.000000), chipBackground: Color(.sRGB, red: 0.937255, green: 0.901961, blue: 0.894118, opacity: 1.000000), markColor: Color(.sRGB, red: 0.537255, green: 0.290196, blue: 0.262745, opacity: 1.000000)),
        "locker": CentraidAppMark(hue: Color(.sRGB, red: 0.549020, green: 0.298039, blue: 0.380392, opacity: 1.000000), chipBackground: Color(.sRGB, red: 0.933333, green: 0.901961, blue: 0.909804, opacity: 1.000000), markColor: Color(.sRGB, red: 0.537255, green: 0.290196, blue: 0.372549, opacity: 1.000000)),
        "tally": CentraidAppMark(hue: Color(.sRGB, red: 0.388235, green: 0.352941, blue: 0.576471, opacity: 1.000000), chipBackground: Color(.sRGB, red: 0.913725, green: 0.909804, blue: 0.933333, opacity: 1.000000), markColor: Color(.sRGB, red: 0.372549, green: 0.337255, blue: 0.552941, opacity: 1.000000)),
        "tasks": CentraidAppMark(hue: Color(.sRGB, red: 0.517647, green: 0.349020, blue: 0.133333, opacity: 1.000000), chipBackground: Color(.sRGB, red: 0.929412, green: 0.909804, blue: 0.878431, opacity: 1.000000), markColor: Color(.sRGB, red: 0.486275, green: 0.329412, blue: 0.125490, opacity: 1.000000)),
        "docs": CentraidAppMark(hue: Color(.sRGB, red: 0.000000, green: 0.439216, blue: 0.494118, opacity: 1.000000), chipBackground: Color(.sRGB, red: 0.862745, green: 0.921569, blue: 0.925490, opacity: 1.000000), markColor: Color(.sRGB, red: 0.000000, green: 0.403922, blue: 0.454902, opacity: 1.000000)),
        "agenda": CentraidAppMark(hue: Color(.sRGB, red: 0.223529, green: 0.447059, blue: 0.278431, opacity: 1.000000), chipBackground: Color(.sRGB, red: 0.894118, green: 0.921569, blue: 0.894118, opacity: 1.000000), markColor: Color(.sRGB, red: 0.203922, green: 0.407843, blue: 0.254902, opacity: 1.000000)),
    ]

    public static let darkMarks: [String: CentraidAppMark] = [
        "notes": CentraidAppMark(hue: Color(.sRGB, red: 0.494118, green: 0.654902, blue: 0.862745, opacity: 1.000000), chipBackground: Color(.sRGB, red: 0.141176, green: 0.176471, blue: 0.215686, opacity: 1.000000), markColor: Color(.sRGB, red: 0.494118, green: 0.654902, blue: 0.862745, opacity: 1.000000)),
        "people": CentraidAppMark(hue: Color(.sRGB, red: 0.745098, green: 0.572549, blue: 0.784314, opacity: 1.000000), chipBackground: Color(.sRGB, red: 0.192157, green: 0.156863, blue: 0.200000, opacity: 1.000000), markColor: Color(.sRGB, red: 0.745098, green: 0.572549, blue: 0.784314, opacity: 1.000000)),
        "photos": CentraidAppMark(hue: Color(.sRGB, red: 0.843137, green: 0.560784, blue: 0.521569, opacity: 1.000000), chipBackground: Color(.sRGB, red: 0.211765, green: 0.156863, blue: 0.149020, opacity: 1.000000), markColor: Color(.sRGB, red: 0.843137, green: 0.560784, blue: 0.521569, opacity: 1.000000)),
        "locker": CentraidAppMark(hue: Color(.sRGB, red: 0.831373, green: 0.552941, blue: 0.635294, opacity: 1.000000), chipBackground: Color(.sRGB, red: 0.211765, green: 0.152941, blue: 0.172549, opacity: 1.000000), markColor: Color(.sRGB, red: 0.831373, green: 0.552941, blue: 0.635294, opacity: 1.000000)),
        "tally": CentraidAppMark(hue: Color(.sRGB, red: 0.639216, green: 0.607843, blue: 0.854902, opacity: 1.000000), chipBackground: Color(.sRGB, red: 0.172549, green: 0.164706, blue: 0.215686, opacity: 1.000000), markColor: Color(.sRGB, red: 0.639216, green: 0.607843, blue: 0.854902, opacity: 1.000000)),
        "tasks": CentraidAppMark(hue: Color(.sRGB, red: 0.788235, green: 0.607843, blue: 0.396078, opacity: 1.000000), chipBackground: Color(.sRGB, red: 0.200000, green: 0.164706, blue: 0.121569, opacity: 1.000000), markColor: Color(.sRGB, red: 0.788235, green: 0.607843, blue: 0.396078, opacity: 1.000000)),
        "docs": CentraidAppMark(hue: Color(.sRGB, red: 0.345098, green: 0.705882, blue: 0.768627, opacity: 1.000000), chipBackground: Color(.sRGB, red: 0.113725, green: 0.184314, blue: 0.196078, opacity: 1.000000), markColor: Color(.sRGB, red: 0.345098, green: 0.705882, blue: 0.768627, opacity: 1.000000)),
        "agenda": CentraidAppMark(hue: Color(.sRGB, red: 0.482353, green: 0.709804, blue: 0.529412, opacity: 1.000000), chipBackground: Color(.sRGB, red: 0.141176, green: 0.184314, blue: 0.149020, opacity: 1.000000), markColor: Color(.sRGB, red: 0.482353, green: 0.709804, blue: 0.529412, opacity: 1.000000)),
    ]

    /// Lucide-style silhouettes as raw SVG path data, viewBox 24x24.
    ///
    /// ONE ordered list per icon, drawn in order. See the Kotlin table:
    /// neither shell ships a second icon set.
    public static let icons: [String: [CentraidIconPath]] = [
        "Activity": [
            CentraidIconPath(d: "M3 12h4l3 8 4-16 3 8h4", filled: false, evenOdd: false),
        ],
        "AddressBook": [
            CentraidIconPath(d: "M5 4h14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M8 10h.01M8 14h.01M11 10h6M11 14h6", filled: false, evenOdd: false),
        ],
        "AlertCircle": [
            CentraidIconPath(d: "M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M12 8v4M12 16h.01", filled: false, evenOdd: false),
        ],
        "AlertTriangle": [
            CentraidIconPath(d: "M21.73 18l-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M12 9v4M12 17h.01", filled: false, evenOdd: false),
        ],
        "Archive": [
            CentraidIconPath(d: "M4 5h16v4H4z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M6 9v10h12V9M9 13h6", filled: false, evenOdd: false),
        ],
        "ArrowLeft": [
            CentraidIconPath(d: "M19 12H5M12 19l-7-7 7-7", filled: false, evenOdd: false),
        ],
        "ArrowRight": [
            CentraidIconPath(d: "M5 12h14M12 5l7 7-7 7", filled: false, evenOdd: false),
        ],
        "BarChart2": [
            CentraidIconPath(d: "M4 20V10M10 20V4M16 20v-7M22 20H2", filled: false, evenOdd: false),
        ],
        "Battery": [
            CentraidIconPath(d: "M2 7h18v10H2z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M4 9h10v6H4z", filled: true, evenOdd: false),
            CentraidIconPath(d: "M22 11v2", filled: false, evenOdd: false),
        ],
        "BatteryCharging": [
            CentraidIconPath(d: "M2 7h18v10H2z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M22 11v2M11 10l-2 3h3l-1 3 4-5h-3l1-1z", filled: false, evenOdd: false),
        ],
        "Beaker": [
            CentraidIconPath(d: "M14 2v6a2 2 0 0 0 .245.96l5.51 10.08A2 2 0 0 1 18 22H6a2 2 0 0 1-1.755-2.96l5.51-10.08A2 2 0 0 0 10 8V2z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M8.5 2h7M7 16h10", filled: false, evenOdd: false),
        ],
        "Bell": [
            CentraidIconPath(d: "M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M10.3 21a1.94 1.94 0 0 0 3.4 0", filled: false, evenOdd: false),
        ],
        "Bolt": [
            CentraidIconPath(d: "M13 2L4 13h7l-2 9 11-13h-8z", filled: false, evenOdd: false),
        ],
        "BoltOff": [
            CentraidIconPath(d: "m3 3 18 18", filled: false, evenOdd: false),
            CentraidIconPath(d: "m13 2-9 11h7l-2 9 4-4", filled: false, evenOdd: false),
        ],
        "Book": [
            CentraidIconPath(d: "M4 5a2 2 0 0 1 2-2h13v18H6a2 2 0 0 1-2-2z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M4 17a2 2 0 0 1 2-2h13", filled: false, evenOdd: false),
        ],
        "Bookmark": [
            CentraidIconPath(d: "M6 4h12v17l-6-3-6 3z", filled: false, evenOdd: false),
        ],
        "Braces": [
            CentraidIconPath(d: "M8 3H7a2 2 0 0 0-2 2v5a2 2 0 0 1-2 2 2 2 0 0 1 2 2v5a2 2 0 0 0 2 2h1", filled: false, evenOdd: false),
            CentraidIconPath(d: "M16 3h1a2 2 0 0 1 2 2v5a2 2 0 0 0 2 2 2 2 0 0 0-2 2v5a2 2 0 0 1-2 2h-1", filled: false, evenOdd: false),
        ],
        "Calendar": [
            CentraidIconPath(d: "M5 5h14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M3 10h18M8 3v4M16 3v4", filled: false, evenOdd: false),
        ],
        "CalendarBlank": [
            CentraidIconPath(d: "M5 4h14a2 2 0 0 1 2 2v13a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V6a2 2 0 0 1 2-2z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M3 9h18", filled: false, evenOdd: false),
        ],
        "CalendarPlus": [
            CentraidIconPath(d: "M5 4h14a2 2 0 0 1 2 2v13a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V6a2 2 0 0 1 2-2z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M3 9h18M12 12v6M9 15h6", filled: false, evenOdd: false),
        ],
        "Camera": [
            CentraidIconPath(d: "M3 8a2 2 0 0 1 2-2h2l2-2h6l2 2h2a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M12 17a4 4 0 1 0 0-8 4 4 0 0 0 0 8z", filled: false, evenOdd: false),
        ],
        "Cellular": [
            CentraidIconPath(d: "M2 18v3h2v-3zM7 14v7h2v-7zM12 10v11h2V10zM17 6v15h2V6z", filled: true, evenOdd: false),
        ],
        "Check": [
            CentraidIconPath(d: "M5 12l5 5L20 7", filled: false, evenOdd: false),
        ],
        "CheckCircle": [
            CentraidIconPath(d: "M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M8.5 12.5l2.5 2.5 4.5-5", filled: false, evenOdd: false),
        ],
        "ChevronDown": [
            CentraidIconPath(d: "M6 9l6 6 6-6", filled: false, evenOdd: false),
        ],
        "ChevronLeft": [
            CentraidIconPath(d: "M15 6l-6 6 6 6", filled: false, evenOdd: false),
        ],
        "ChevronRight": [
            CentraidIconPath(d: "M9 6l6 6-6 6", filled: false, evenOdd: false),
        ],
        "ChevronsDown": [
            CentraidIconPath(d: "m7 7 5 5 5-5M7 13l5 5 5-5", filled: false, evenOdd: false),
        ],
        "CirclePlus": [
            CentraidIconPath(d: "M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M12 8v8M8 12h8", filled: false, evenOdd: false),
        ],
        "Clock": [
            CentraidIconPath(d: "M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M12 7v5l3 2", filled: false, evenOdd: false),
        ],
        "Cloud": [
            CentraidIconPath(d: "M7 18h10a4 4 0 0 0 .7-7.94A6 6 0 0 0 6.2 8.4 4.5 4.5 0 0 0 7 18z", filled: false, evenOdd: false),
        ],
        "CloudOff": [
            CentraidIconPath(d: "m3 3 18 18", filled: false, evenOdd: false),
            CentraidIconPath(d: "M7 18h10a4 4 0 0 0 .7-7.94A6 6 0 0 0 6.2 8.4 4.5 4.5 0 0 0 7 18z", filled: false, evenOdd: false),
        ],
        "Code": [
            CentraidIconPath(d: "M8 6l-6 6 6 6M16 6l6 6-6 6", filled: false, evenOdd: false),
        ],
        "Coin": [
            CentraidIconPath(d: "M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M14.5 8.5c0-1.4-1.1-2-2.5-2s-2.5.7-2.5 2 1.1 1.9 2.5 1.9 2.5.6 2.5 2-1.1 2.1-2.5 2.1-2.5-.7-2.5-2.1M12 5v1.5M12 17v1.5", filled: false, evenOdd: false),
        ],
        "Command": [
            CentraidIconPath(d: "M9 7.5A2.5 2.5 0 1 0 6.5 10H10v4H6.5A2.5 2.5 0 1 0 9 16.5V13h6v3.5A2.5 2.5 0 1 0 17.5 14H14v-4h3.5A2.5 2.5 0 1 0 15 7.5V11H9z", filled: false, evenOdd: false),
        ],
        "Compass": [
            CentraidIconPath(d: "M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M16 8l-2.4 5.6L8 16l2.4-5.6z", filled: true, evenOdd: false),
        ],
        "Copy": [
            CentraidIconPath(d: "M9 9h10a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1H9a1 1 0 0 1-1-1V10a1 1 0 0 1 1-1z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M5 15H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v1", filled: false, evenOdd: false),
        ],
        "Cpu": [
            CentraidIconPath(d: "M6 4h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M9 9h6v6H9z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M9 2v2M15 2v2M9 20v2M15 20v2M2 9h2M2 15h2M20 9h2M20 15h2", filled: false, evenOdd: false),
        ],
        "Database": [
            CentraidIconPath(d: "M12 3c4.4 0 8 1.3 8 3s-3.6 3-8 3-8-1.3-8-3 3.6-3 8-3z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M4 6v6c0 1.7 3.6 3 8 3s8-1.3 8-3V6", filled: false, evenOdd: false),
            CentraidIconPath(d: "M4 12v6c0 1.7 3.6 3 8 3s8-1.3 8-3v-6", filled: false, evenOdd: false),
        ],
        "Devices": [
            CentraidIconPath(d: "M9 17H4a1 1 0 0 1-1-1V6a1 1 0 0 1 1-1h13a1 1 0 0 1 1 1v3", filled: false, evenOdd: false),
            CentraidIconPath(d: "M14 11h6a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1h-6a1 1 0 0 1-1-1v-8a1 1 0 0 1 1-1z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M7 21h4", filled: false, evenOdd: false),
        ],
        "Download": [
            CentraidIconPath(d: "M12 3v12m0 0 4-4m-4 4-4-4M5 21h14", filled: false, evenOdd: false),
        ],
        "EnvelopeSimple": [
            CentraidIconPath(d: "M3 6a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M3 7l9 6 9-6", filled: false, evenOdd: false),
        ],
        "Eye": [
            CentraidIconPath(d: "M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M12 9a3 3 0 1 0 0 6 3 3 0 0 0 0-6z", filled: false, evenOdd: false),
        ],
        "EyeOff": [
            CentraidIconPath(d: "M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7-10-7-10-7z", filled: false, evenOdd: false),
            CentraidIconPath(d: "m4 4 16 16", filled: false, evenOdd: false),
        ],
        "FileEdit": [
            CentraidIconPath(d: "M14 3H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-7M14 3v6h6", filled: false, evenOdd: false),
            CentraidIconPath(d: "M18 13l3 3-5 5h-3v-3z", filled: false, evenOdd: false),
        ],
        "FileText": [
            CentraidIconPath(d: "M6 3h7l5 5v13a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M13 3v5h5", filled: false, evenOdd: false),
        ],
        "Filter": [
            CentraidIconPath(d: "M22 3H2l8 9.46V19l4 2v-8.54z", filled: false, evenOdd: false),
        ],
        "Folder": [
            CentraidIconPath(d: "M3 7a2 2 0 0 1 2-2h4l2 2h8a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z", filled: false, evenOdd: false),
        ],
        "FolderPlus": [
            CentraidIconPath(d: "M3 7a2 2 0 0 1 2-2h4l2 2h8a2 2 0 0 1 2 2v9H3z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M12 11v5M9.5 13.5h5", filled: false, evenOdd: false),
        ],
        "Gauge": [
            CentraidIconPath(d: "M12 14l4-4", filled: false, evenOdd: false),
            CentraidIconPath(d: "M3.34 19a10 10 0 1 1 17.32 0", filled: false, evenOdd: false),
        ],
        "Gift": [
            CentraidIconPath(d: "M3 9h18v12H3zM3 13h18M12 9v12", filled: false, evenOdd: false),
            CentraidIconPath(d: "M12 9c-2 0-4-1-4-3a2 2 0 0 1 4 0c0 2 0 3 0 3zM12 9c2 0 4-1 4-3a2 2 0 0 0-4 0c0 2 0 3 0 3z", filled: false, evenOdd: false),
        ],
        "GitBranch": [
            CentraidIconPath(d: "M6 3v12a3 3 0 0 0 3 3h6a3 3 0 0 0 3-3V9", filled: false, evenOdd: false),
            CentraidIconPath(d: "M6 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4zM18 11a2 2 0 1 0 0-4 2 2 0 0 0 0 4z", filled: false, evenOdd: false),
        ],
        "Globe": [
            CentraidIconPath(d: "M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M3 12h18M12 3c2.5 2.5 3.8 5.7 3.8 9s-1.3 6.5-3.8 9c-2.5-2.5-3.8-5.7-3.8-9S9.5 5.5 12 3z", filled: false, evenOdd: false),
        ],
        "Grid": [
            CentraidIconPath(d: "M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z", filled: false, evenOdd: false),
        ],
        "Gym": [
            CentraidIconPath(d: "M6 9v6M3 11v2M18 9v6M21 11v2M6 12h12", filled: false, evenOdd: false),
        ],
        "Habit": [
            CentraidIconPath(d: "M12 21s-7-4.5-7-10a4 4 0 0 1 7-2.5A4 4 0 0 1 19 11c0 5.5-7 10-7 10z", filled: false, evenOdd: false),
        ],
        "Heart": [
            CentraidIconPath(d: "M12 20s-7-4.4-7-9.4A3.8 3.8 0 0 1 12 8a3.8 3.8 0 0 1 7 2.6c0 5-7 9.4-7 9.4z", filled: false, evenOdd: false),
        ],
        "History": [
            CentraidIconPath(d: "M3 12a9 9 0 1 0 3-6.7L3 8", filled: false, evenOdd: false),
            CentraidIconPath(d: "M3 3v5h5M12 7v5l3 2", filled: false, evenOdd: false),
        ],
        "Home": [
            CentraidIconPath(d: "M3 11l9-8 9 8v9a2 2 0 0 1-2 2h-4v-7h-6v7H5a2 2 0 0 1-2-2z", filled: false, evenOdd: false),
        ],
        "Image": [
            CentraidIconPath(d: "M3 5h18v14H3z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M5 17l4-4 3 3 2-2 5 3", filled: false, evenOdd: false),
            CentraidIconPath(d: "M8 9h.01", filled: false, evenOdd: false),
        ],
        "Inbox": [
            CentraidIconPath(d: "M22 12h-6l-2 3h-4l-2-3H2", filled: false, evenOdd: false),
            CentraidIconPath(d: "M5.45 5.11 2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z", filled: false, evenOdd: false),
        ],
        "Info": [
            CentraidIconPath(d: "M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M12 11v5", filled: false, evenOdd: false),
            CentraidIconPath(d: "M12 8h.01", filled: false, evenOdd: false),
        ],
        "Journal": [
            CentraidIconPath(d: "M5 4a2 2 0 0 1 2-2h11v20H7a2 2 0 0 1-2-2z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M9 8h6M9 12h6M9 16h4", filled: false, evenOdd: false),
        ],
        "Key": [
            CentraidIconPath(d: "M12 15a4 4 0 1 1-8 0 4 4 0 0 1 8 0z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M11 12l9-9", filled: false, evenOdd: false),
            CentraidIconPath(d: "M17 6l3 3M14 9l3 3", filled: false, evenOdd: false),
        ],
        "Layers": [
            CentraidIconPath(d: "m12 3 9 5-9 5-9-5 9-5zM3 12l9 5 9-5M3 16l9 5 9-5", filled: false, evenOdd: false),
        ],
        "List": [
            CentraidIconPath(d: "M4 6h16M4 12h16M4 18h16", filled: false, evenOdd: false),
        ],
        "Loader": [
            CentraidIconPath(d: "M21 12a9 9 0 1 1-6.219-8.56", filled: false, evenOdd: false),
        ],
        "Lock": [
            CentraidIconPath(d: "M5 10h14v10H5z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M8 10V7a4 4 0 0 1 8 0v3M12 14v2", filled: false, evenOdd: false),
        ],
        "MapPin": [
            CentraidIconPath(d: "M12 21s7-7.58 7-12a7 7 0 0 0-14 0c0 4.42 7 12 7 12z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M12 11.5a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z", filled: false, evenOdd: false),
        ],
        "Maximize": [
            CentraidIconPath(d: "M8 3H3v5M16 3h5v5M8 21H3v-5M21 16v5h-5", filled: false, evenOdd: false),
        ],
        "Menu": [
            CentraidIconPath(d: "M4 7h16M4 12h16M4 17h16", filled: false, evenOdd: false),
        ],
        "MessageCircle": [
            CentraidIconPath(d: "M20 11.5a7.5 7.5 0 0 1-8 7.5 8.5 8.5 0 0 1-4-.9L4 20l1.1-3.5A7.5 7.5 0 1 1 20 11.5z", filled: false, evenOdd: false),
        ],
        "Monitor": [
            CentraidIconPath(d: "M3 4h18v12H3z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M9 20h6M12 16v4", filled: false, evenOdd: false),
        ],
        "Mood": [
            CentraidIconPath(d: "M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M9 10v0M15 10v0", filled: false, evenOdd: false),
            CentraidIconPath(d: "M8.5 14.5a4 4 0 0 0 7 0", filled: false, evenOdd: false),
        ],
        "Moon": [
            CentraidIconPath(d: "M20 14.5A8 8 0 1 1 9.5 4a6.5 6.5 0 0 0 10.5 10.5z", filled: false, evenOdd: false),
        ],
        "MoreHoriz": [
            CentraidIconPath(d: "M6 12h.01M12 12h.01M18 12h.01", filled: false, evenOdd: false),
        ],
        "MoreVert": [
            CentraidIconPath(d: "M12 6h.01M12 12h.01M12 18h.01", filled: false, evenOdd: false),
        ],
        "Music": [
            CentraidIconPath(d: "M9 18V5l11-2v13", filled: false, evenOdd: false),
            CentraidIconPath(d: "M6 21a3 3 0 1 0 0-6 3 3 0 0 0 0 6z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M17 19a3 3 0 1 0 0-6 3 3 0 0 0 0 6z", filled: false, evenOdd: false),
        ],
        "NewChat": [
            CentraidIconPath(d: "M21 15a2 2 0 0 1-2 2H8l-4 4V5a2 2 0 0 1 2-2h13a2 2 0 0 1 2 2z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M9 10h6M12 7v6", filled: false, evenOdd: false),
        ],
        "OpenExternal": [
            CentraidIconPath(d: "M14 4h6v6", filled: false, evenOdd: false),
            CentraidIconPath(d: "M20 4 11 13", filled: false, evenOdd: false),
            CentraidIconPath(d: "M18 14v5a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h5", filled: false, evenOdd: false),
        ],
        "PaperPlaneTilt": [
            CentraidIconPath(d: "M22 2L11 13M22 2l-7 20-4-9-9-4z", filled: false, evenOdd: false),
        ],
        "Paperclip": [
            CentraidIconPath(d: "M21.44 11.05l-9.19 9.19a6 6 0 0 1-8.49-8.49l9.19-9.19a4 4 0 0 1 5.66 5.66l-9.2 9.19a2 2 0 0 1-2.83-2.83l8.49-8.48", filled: false, evenOdd: false),
        ],
        "Pause": [
            CentraidIconPath(d: "M6 5h4v14H6zM14 5h4v14h-4z", filled: true, evenOdd: false),
        ],
        "Pencil": [
            CentraidIconPath(d: "M14 4l6 6L9 21H3v-6z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M14 4l3-3 6 6-3 3", filled: false, evenOdd: false),
        ],
        "Phone": [
            CentraidIconPath(d: "M7 2h10a1 1 0 0 1 1 1v18a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V3a1 1 0 0 1 1-1z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M11 18.5h2", filled: false, evenOdd: false),
        ],
        "Pin": [
            CentraidIconPath(d: "M9 4h6l-1 6 3 3v2H7v-2l3-3-1-6zM12 15v5", filled: false, evenOdd: false),
        ],
        "Plant": [
            CentraidIconPath(d: "M12 22V11", filled: false, evenOdd: false),
            CentraidIconPath(d: "M12 11c-3 0-6-2-6-6 4 0 6 3 6 6z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M12 14c3 0 6-2 6-6-4 0-6 3-6 6z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M8 22h8", filled: false, evenOdd: false),
        ],
        "Play": [
            CentraidIconPath(d: "M7 5l12 7-12 7z", filled: true, evenOdd: false),
        ],
        "Plug": [
            CentraidIconPath(d: "M9 7V4M15 7V4M7 7h10v6a4 4 0 1 1-10 0z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M12 17v3", filled: false, evenOdd: false),
        ],
        "Plus": [
            CentraidIconPath(d: "M12 5v14M5 12h14", filled: false, evenOdd: false),
        ],
        "Pomodoro": [
            CentraidIconPath(d: "M20 13a8 8 0 1 1-16 0 8 8 0 0 1 16 0z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M12 13l3-2M9 4h6M12 4V2", filled: false, evenOdd: false),
        ],
        "Power": [
            CentraidIconPath(d: "M12 2v10", filled: false, evenOdd: false),
            CentraidIconPath(d: "M18.36 6.64a9 9 0 1 1-12.73 0", filled: false, evenOdd: false),
        ],
        "Print": [
            CentraidIconPath(d: "M7 8V4a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v4", filled: false, evenOdd: false),
            CentraidIconPath(d: "M7 18H5a2 2 0 0 1-2-2v-4a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v4a2 2 0 0 1-2 2h-2", filled: false, evenOdd: false),
            CentraidIconPath(d: "M7 14h10v6a1 1 0 0 1-1 1H8a1 1 0 0 1-1-1z", filled: false, evenOdd: false),
        ],
        "Receipt": [
            CentraidIconPath(d: "M5 3h14v18l-3-2-4 2-4-2-3 2z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M8 8h8M8 12h8M8 16h5", filled: false, evenOdd: false),
        ],
        "Refresh": [
            CentraidIconPath(d: "M21 12a9 9 0 1 1-3-6.7M21 3v5h-5", filled: false, evenOdd: false),
        ],
        "Repeat": [
            CentraidIconPath(d: "M17 2l4 4-4 4", filled: false, evenOdd: false),
            CentraidIconPath(d: "M3 11V9a4 4 0 0 1 4-4h14", filled: false, evenOdd: false),
            CentraidIconPath(d: "M7 22l-4-4 4-4", filled: false, evenOdd: false),
            CentraidIconPath(d: "M21 13v2a4 4 0 0 1-4 4H3", filled: false, evenOdd: false),
        ],
        "Reset": [
            CentraidIconPath(d: "M3 12a9 9 0 1 0 3-6.7L3 8", filled: false, evenOdd: false),
            CentraidIconPath(d: "M3 3v5h5", filled: false, evenOdd: false),
        ],
        "Save": [
            CentraidIconPath(d: "M5 4h11l4 4v12a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M8 4v5h7V4M8 14h8v7H8z", filled: false, evenOdd: false),
        ],
        "Search": [
            CentraidIconPath(d: "M11 18a7 7 0 1 0 0-14 7 7 0 0 0 0 14z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M20 20l-3.5-3.5", filled: false, evenOdd: false),
        ],
        "Send": [
            CentraidIconPath(d: "M22 2L11 13", filled: false, evenOdd: false),
            CentraidIconPath(d: "M22 2l-7 20-4-9-9-4z", filled: false, evenOdd: false),
        ],
        "Settings": [
            CentraidIconPath(d: "M19.4 15a1.7 1.7 0 0 0 .3 1.8l.1.1a2 2 0 1 1-2.8 2.8l-.1-.1a1.7 1.7 0 0 0-1.8-.3 1.7 1.7 0 0 0-1 1.5V21a2 2 0 0 1-4 0v-.1a1.7 1.7 0 0 0-1-1.5 1.7 1.7 0 0 0-1.8.3l-.1.1a2 2 0 1 1-2.8-2.8l.1-.1a1.7 1.7 0 0 0 .3-1.8 1.7 1.7 0 0 0-1.5-1H3a2 2 0 0 1 0-4h.1a1.7 1.7 0 0 0 1.5-1 1.7 1.7 0 0 0-.3-1.8l-.1-.1a2 2 0 1 1 2.8-2.8l.1.1a1.7 1.7 0 0 0 1.8.3h0a1.7 1.7 0 0 0 1-1.5V3a2 2 0 0 1 4 0v.1a1.7 1.7 0 0 0 1 1.5h0a1.7 1.7 0 0 0 1.8-.3l.1-.1a2 2 0 1 1 2.8 2.8l-.1.1a1.7 1.7 0 0 0-.3 1.8v0a1.7 1.7 0 0 0 1.5 1H21a2 2 0 0 1 0 4h-.1a1.7 1.7 0 0 0-1.5 1z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6z", filled: false, evenOdd: false),
        ],
        "Share": [
            CentraidIconPath(d: "M4 12v7a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-7", filled: false, evenOdd: false),
            CentraidIconPath(d: "M16 6l-4-4-4 4M12 2v14", filled: false, evenOdd: false),
        ],
        "Shield": [
            CentraidIconPath(d: "M12 3 20 6v5c0 5-3.4 8.7-8 10-4.6-1.3-8-5-8-10V6z", filled: false, evenOdd: false),
        ],
        "Skip": [
            CentraidIconPath(d: "M6 4l10 8-10 8zM18 5v14", filled: false, evenOdd: false),
        ],
        "Sliders": [
            CentraidIconPath(d: "M21 4H14M10 4H3M21 12H12M8 12H3M21 20H16M12 20H3M14 2v4M8 10v4M16 18v4", filled: false, evenOdd: false),
        ],
        "Smartphone": [
            CentraidIconPath(d: "M7 2h10a2 2 0 0 1 2 2v16a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M11 18h2", filled: false, evenOdd: false),
        ],
        "Sparkle": [
            CentraidIconPath(d: "M12 3l1.8 4.7L18 9l-4.2 1.3L12 15l-1.8-4.7L6 9l4.2-1.3z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M19 15l.6 1.6L21 17l-1.4.4L19 19l-.6-1.6L17 17l1.4-.4z", filled: false, evenOdd: false),
        ],
        "Star": [
            CentraidIconPath(d: "M12 3l2.7 5.5 6 .9-4.35 4.25 1.05 6L12 17.8 6.6 20.65l1.05-6L3.3 9.4l6-.9z", filled: false, evenOdd: false),
        ],
        "Stop": [
            CentraidIconPath(d: "M8 6h8a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2z", filled: true, evenOdd: false),
        ],
        "Sun": [
            CentraidIconPath(d: "M12 3v2M12 19v2M3 12h2M19 12h2M5.6 5.6 7 7M17 17l1.4 1.4M18.4 5.6 17 7M7 17l-1.4 1.4", filled: false, evenOdd: false),
            CentraidIconPath(d: "M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0z", filled: false, evenOdd: false),
        ],
        "SwitchVert": [
            CentraidIconPath(d: "M8 4v16M8 20l-3-3M8 4l3 3M16 20V4M16 4l3 3M16 20l-3-3", filled: false, evenOdd: false),
        ],
        "Table": [
            CentraidIconPath(d: "M4 4h16v16H4z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M4 10h16M4 15h16M10 4v16", filled: false, evenOdd: false),
        ],
        "Tablet": [
            CentraidIconPath(d: "M5 3h14a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M11 18h2", filled: false, evenOdd: false),
        ],
        "Tag": [
            CentraidIconPath(d: "M4 11 11 4h8v8l-7 7z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M15.5 8.5h.01", filled: false, evenOdd: false),
        ],
        "Todo": [
            CentraidIconPath(d: "M4 7a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M8 10h8M8 14h5", filled: false, evenOdd: false),
            CentraidIconPath(d: "M7 10l1 1 2-2", filled: false, evenOdd: false),
        ],
        "Trash": [
            CentraidIconPath(d: "M3 6h18M8 6V4a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1v2M5 6l1 14a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2l1-14M10 11v6M14 11v6", filled: false, evenOdd: false),
        ],
        "Upload": [
            CentraidIconPath(d: "M12 15V3m0 0 4 4m-4-4-4 4M5 21h14", filled: false, evenOdd: false),
        ],
        "User": [
            CentraidIconPath(d: "M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M4.5 20.5a7.5 7.5 0 0 1 15 0", filled: false, evenOdd: false),
        ],
        "UserPlus": [
            CentraidIconPath(d: "M9 11.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M2.5 20.5a6.5 6.5 0 0 1 13 0M19 8v6M16 11h6", filled: false, evenOdd: false),
        ],
        "Users": [
            CentraidIconPath(d: "M9 11.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M2.5 20.5a6.5 6.5 0 0 1 13 0", filled: false, evenOdd: false),
            CentraidIconPath(d: "M16.5 4.8a3.5 3.5 0 0 1 0 6.9M22 20.5a6.5 6.5 0 0 0-4.2-6.1", filled: false, evenOdd: false),
        ],
        "Video": [
            CentraidIconPath(d: "M3 6h14v12H3z", filled: false, evenOdd: false),
            CentraidIconPath(d: "m17 10 4-3v10l-4-3", filled: false, evenOdd: false),
        ],
        "Water": [
            CentraidIconPath(d: "M12 3l-5 7a6 6 0 0 0 10 0z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M9.5 13a2.5 2.5 0 0 0 2.5 2.5", filled: false, evenOdd: false),
        ],
        "Webhook": [
            CentraidIconPath(d: "M18 16.98h-5.99c-1.1 0-1.95.94-2.48 1.9A4 4 0 0 1 2 17c.01-.7.2-1.4.57-2", filled: false, evenOdd: false),
            CentraidIconPath(d: "M6 17l3.13-5.78c.53-.97.1-2.18-.5-3.1a4 4 0 1 1 6.89-4.06", filled: false, evenOdd: false),
            CentraidIconPath(d: "M12 6l3.13 5.73C15.66 12.7 16.9 13 18 13a4 4 0 1 1-3.92 4.74", filled: false, evenOdd: false),
        ],
        "Wifi": [
            CentraidIconPath(d: "M5 12.5a10 10 0 0 1 14 0M2 8.5a15 15 0 0 1 20 0M8.5 16.5a5 5 0 0 1 7 0", filled: false, evenOdd: false),
            CentraidIconPath(d: "M12 20a1 1 0 1 0 0-2 1 1 0 0 0 0 2z", filled: true, evenOdd: false),
        ],
        "X": [
            CentraidIconPath(d: "M6 6l12 12M18 6L6 18", filled: false, evenOdd: false),
        ],
        "XCircle": [
            CentraidIconPath(d: "M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0z", filled: false, evenOdd: false),
            CentraidIconPath(d: "m9 9 6 6M15 9l-6 6", filled: false, evenOdd: false),
        ],
        "add": [
            CentraidIconPath(d: "M12 5v14M5 12h14", filled: false, evenOdd: false),
        ],
        "album": [
            CentraidIconPath(d: "M4 7h13v13a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M7 4h13v13a1 1 0 0 1-1 1H8a1 1 0 0 1-1-1V4z", filled: false, evenOdd: false),
        ],
        "download": [
            CentraidIconPath(d: "M12 3v12m0 0 4-4m-4 4-4-4M5 21h14", filled: false, evenOdd: false),
        ],
        "dupe": [
            CentraidIconPath(d: "M9 9h10a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1H9a1 1 0 0 1-1-1V10a1 1 0 0 1 1-1z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M5 15H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v1", filled: false, evenOdd: false),
        ],
        "heart": [
            CentraidIconPath(d: "M12 20s-7-4.4-7-9.4A3.8 3.8 0 0 1 12 8a3.8 3.8 0 0 1 7 2.6c0 5-7 9.4-7 9.4z", filled: false, evenOdd: false),
        ],
        "info": [
            CentraidIconPath(d: "M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M12 16v-4M12 8h.01", filled: false, evenOdd: false),
        ],
        "more": [
            CentraidIconPath(d: "M6 12h.01M12 12h.01M18 12h.01", filled: false, evenOdd: false),
        ],
        "person": [
            CentraidIconPath(d: "M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M4.5 20.5a7.5 7.5 0 0 1 15 0", filled: false, evenOdd: false),
        ],
        "place": [
            CentraidIconPath(d: "M12 21s7-7.58 7-12a7 7 0 0 0-14 0c0 4.42 7 12 7 12z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M12 11.5a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z", filled: false, evenOdd: false),
        ],
        "removeFrom": [
            CentraidIconPath(d: "M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0z", filled: false, evenOdd: false),
            CentraidIconPath(d: "M8 12h8", filled: false, evenOdd: false),
        ],
        "restore": [
            CentraidIconPath(d: "M4 7h16M6 7l1 12a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2l1-12M8 7V5a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1v2", filled: false, evenOdd: false),
            CentraidIconPath(d: "M12 15V9M9 12l3-3 3 3", filled: false, evenOdd: false),
        ],
        "share": [
            CentraidIconPath(d: "M4 12v7a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-7", filled: false, evenOdd: false),
            CentraidIconPath(d: "M16 6l-4-4-4 4M12 2v14", filled: false, evenOdd: false),
        ],
        "trash": [
            CentraidIconPath(d: "M3 6h18M8 6V4a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1v2M5 6l1 14a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2l1-14M10 11v6M14 11v6", filled: false, evenOdd: false),
        ],
    ]
}

/// Geometry both shells need that the token table does not carry.
public enum CentraidGeometry {
    public static let appMarkSmallStroke: CGFloat = 1.75
    public static let appMarkStroke: CGFloat = 1.6
    public static let appMarkViewBox: CGFloat = 24
    public static let durationOne: CGFloat = 140
    public static let durationTwo: CGFloat = 280
    public static let hairline: CGFloat = 1
    public static let iconChipRadiusRatio: CGFloat = 0.26
    public static let iconChipTintDark: CGFloat = 0.2
    public static let iconChipTintLight: CGFloat = 0.13
    public static let pageMargin: CGFloat = 18
    public static let targetMinCoarse: CGFloat = 44
    public static let targetMinFine: CGFloat = 34
}
