export { MAX_MULTIPLEX_REPLICA_SCOPES as MAX_MOUNTED_NATIVE_SCOPES } from "@centraid/core/protocol";

export const MOBILE_REPLICA_BOOTSTRAP_WINDOW = 5_000;
export const THUMBNAIL_SOURCE_BUDGET_BYTES = 128 * 1024 * 1024;

export const OFFLINE_CONTENT_BUDGET_BYTES = 256 * 1024 * 1024;
