import { StyleSheet } from "react-native";

import { family, radii, spacing, t } from "../../kit/theme";
import type { ThemeColors } from "../../kit/theme";

export const makeLockerStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    biometricCard: {
      backgroundColor: colors.bgElev,
      borderColor: colors.lineStrong,
      borderRadius: radii.md,
      borderWidth: 1,
      marginBottom: spacing[4],
      padding: spacing[4],
    },
    biometricCopy: { ...t("small"), color: colors.ink3, marginTop: 3 },
    biometricTitle: { ...t("bodyStrong"), color: colors.ink },
    center: { flex: 1 },
    copyButton: { paddingVertical: spacing[2] },
    copyText: { ...t("small"), color: colors.accent },
    detailHeader: {
      alignItems: "center",
      borderBottomColor: colors.line,
      borderBottomWidth: StyleSheet.hairlineWidth,
      flexDirection: "row",
      justifyContent: "space-between",
      padding: spacing[5],
    },
    detailList: { padding: spacing[5] },
    detailSafe: { backgroundColor: colors.bg, flex: 1 },
    detailTitle: { ...t("title"), color: colors.ink },
    disabled: { opacity: 0.5 },
    error: { ...t("small"), color: colors.danger, marginTop: spacing[3] },
    field: {
      borderBottomColor: colors.line,
      borderBottomWidth: StyleSheet.hairlineWidth,
      paddingVertical: spacing[4],
    },
    fieldCopy: { gap: 4 },
    fieldLabel: {
      ...t("tiny"),
      color: colors.ink3,
      fontFamily: family.monoMedium,
      textTransform: "uppercase",
    },
    fieldValue: { ...t("body"), color: colors.ink, marginTop: spacing[1] },
    input: {
      ...t("body"),
      backgroundColor: colors.bgElev,
      borderColor: colors.lineStrong,
      borderRadius: radii.md,
      borderWidth: 1,
      color: colors.ink,
      marginTop: spacing[4],
      paddingHorizontal: spacing[4],
      paddingVertical: spacing[3],
      width: "100%",
    },
    list: { padding: spacing[4] },
    listHeading: {
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: spacing[2],
    },
    listTitle: { ...t("title"), color: colors.ink },
    locked: {
      alignItems: "center",
      flex: 1,
      justifyContent: "center",
      paddingHorizontal: spacing[6],
    },
    lockNow: { ...t("bodyStrong"), color: colors.accent },
    mask: {
      alignItems: "center",
      backgroundColor: colors.bg,
      bottom: 0,
      justifyContent: "center",
      left: 0,
      position: "absolute",
      right: 0,
      top: 0,
    },
    modalActions: {
      flexDirection: "row",
      gap: spacing[3],
      justifyContent: "flex-end",
      marginTop: spacing[4],
    },
    modalBack: {
      alignItems: "center",
      backgroundColor: "rgba(0, 0, 0, 0.45)",
      flex: 1,
      justifyContent: "center",
      padding: spacing[5],
    },
    modalCard: {
      backgroundColor: colors.bgElev,
      borderRadius: radii.xl,
      maxWidth: 440,
      padding: spacing[5],
      width: "100%",
    },
    modalTitle: { ...t("title"), color: colors.ink },
    primary: {
      alignItems: "center",
      alignSelf: "stretch",
      backgroundColor: colors.accent,
      borderRadius: radii.md,
      justifyContent: "center",
      marginTop: spacing[4],
      minHeight: 48,
      paddingHorizontal: spacing[4],
    },
    primaryText: { ...t("bodyStrong"), color: colors.inkInv },
    row: {
      alignItems: "center",
      borderBottomColor: colors.line,
      borderBottomWidth: StyleSheet.hairlineWidth,
      flexDirection: "row",
      gap: spacing[3],
      minHeight: 68,
    },
    rowCopy: { flex: 1, minWidth: 0 },
    rowIcon: {
      alignItems: "center",
      backgroundColor: colors.bgElev,
      borderRadius: radii.md,
      height: 38,
      justifyContent: "center",
      width: 38,
    },
    rowSubtitle: { ...t("small"), color: colors.ink3, marginTop: 2 },
    rowTitle: { ...t("bodyStrong"), color: colors.ink },
    safe: { backgroundColor: colors.bg, flex: 1 },
    secondary: {
      alignItems: "center",
      alignSelf: "stretch",
      borderColor: colors.lineStrong,
      borderRadius: radii.md,
      borderWidth: 1,
      justifyContent: "center",
      marginTop: spacing[3],
      minHeight: 48,
      paddingHorizontal: spacing[4],
    },
    secondaryText: { ...t("bodyStrong"), color: colors.ink2 },
    stateCopy: {
      ...t("body"),
      color: colors.ink2,
      marginTop: spacing[2],
      maxWidth: 420,
      textAlign: "center",
    },
    stateTitle: { ...t("title"), color: colors.ink, marginTop: spacing[3] },
  });

export type LockerStyles = ReturnType<typeof makeLockerStyles>;
