export default {
  packageManager: "npm",
  testRunner: "vitest",
  vitest: { configFile: "vitest.mutation.config.ts", related: false },
  testFiles: [
    "src/lib/backoff.test.ts",
    "src/lib/coalesce.test.ts",
    "src/lib/conditional-fetch.test.ts",
    "src/lib/notification-model.test.ts",
    "src/lib/notifications-plan.test.ts",
    "src/lib/phone-link.test.ts",
    "src/lib/upload/transfer-policy.test.ts",
    "src/lib/upload/reconcile-gate.test.ts",
    "src/lib/replica/background-scopes.test.ts",
    "src/lib/replica/mobile-intent-id.test.ts",
  ],
  mutate: [
    "src/lib/backoff.ts",
    "src/lib/coalesce.ts",
    "src/lib/conditional-fetch.ts",
    "src/lib/notifications-plan.ts",
    "src/lib/phone-link-core.ts",
    "src/lib/upload/transfer-policy.ts",
    "src/lib/upload/reconcile-gate.ts",
    "src/lib/replica/background-scopes.ts",
    "src/lib/replica/mobile-intent-id.ts",
  ],
  reporters: ["clear-text", "json"],
  jsonReporter: {
    fileName: "../../artifacts/mutation/mobile-report.json",
  },
  thresholds: { high: 80, low: 50, break: null },
  timeoutMS: 60_000,
  concurrency: 2,
  ignoreStatic: true,
  disableTypeChecks: true,
};
