import { StyleSheet } from "react-native";

import { family, radii } from "../../kit/theme";

export const styles = StyleSheet.create({
  backlink: {
    borderRadius: radii.md,
    borderWidth: StyleSheet.hairlineWidth,
    gap: 2,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  backlinkLabel: {
    fontFamily: family.sansMedium,
    fontSize: 13,
  },
  backlinkMeta: {
    fontFamily: family.monoRegular,
    fontSize: 10,
  },
  backlinks: { gap: 8, marginTop: 18 },
  body: {
    fontFamily: family.sansRegular,
    fontSize: 15,
    lineHeight: 23,
    minHeight: 280,
    paddingTop: 12,
    textAlignVertical: "top",
  },
  button: {
    alignItems: "center",
    borderRadius: radii.lg,
    flexDirection: "row",
    gap: 7,
    justifyContent: "center",
    minHeight: 44,
    paddingHorizontal: 16,
  },
  buttonText: {
    fontFamily: family.sansBold,
    fontSize: 14,
  },
  chip: {
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  chipText: {
    fontFamily: family.sansMedium,
    fontSize: 12,
  },
  controls: {
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  editor: { flex: 1, paddingHorizontal: 20 },
  editorActions: {
    flexDirection: "row",
    gap: 9,
    paddingBottom: 18,
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  empty: {
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 36,
    paddingVertical: 72,
  },
  emptyBody: {
    fontFamily: family.sansRegular,
    fontSize: 14,
    lineHeight: 20,
    textAlign: "center",
  },
  emptyTitle: {
    fontFamily: family.sansBold,
    fontSize: 19,
  },
  fill: { flex: 1 },
  header: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 20,
    paddingVertical: 14,
  },
  headerCopy: { flex: 1 },
  headerTitle: {
    fontFamily: family.sansBold,
    fontSize: 28,
    letterSpacing: -0.7,
  },
  iconButton: {
    alignItems: "center",
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  linkAction: {
    borderRadius: radii.md,
    borderWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  linkMeta: {
    fontFamily: family.sansRegular,
    fontSize: 11,
    marginTop: 2,
  },
  linkTitle: {
    fontFamily: family.sansMedium,
    fontSize: 13,
  },
  linkWrap: { gap: 7, marginTop: 16 },
  list: { paddingBottom: 110, paddingHorizontal: 20 },
  modalHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 20,
    paddingVertical: 14,
  },
  modalTitle: {
    flex: 1,
    fontFamily: family.sansBold,
    fontSize: 20,
  },
  note: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    gap: 6,
    paddingVertical: 17,
  },
  noteMeta: {
    fontFamily: family.monoRegular,
    fontSize: 10,
  },
  notePreview: {
    fontFamily: family.sansRegular,
    fontSize: 13,
    lineHeight: 19,
  },
  noteTitle: {
    fontFamily: family.sansMedium,
    fontSize: 17,
  },
  picker: { flex: 1, paddingHorizontal: 20 },
  pickerCopy: {
    fontFamily: family.sansRegular,
    fontSize: 13,
    lineHeight: 19,
    marginBottom: 12,
  },
  search: {
    alignItems: "center",
    borderRadius: radii.lg,
    borderWidth: StyleSheet.hairlineWidth,
    flex: 1,
    flexDirection: "row",
    gap: 8,
    minHeight: 44,
    paddingHorizontal: 12,
  },
  searchInput: {
    flex: 1,
    fontFamily: family.sansRegular,
    fontSize: 15,
    minHeight: 42,
  },
  sheet: { flex: 1 },
  subtitle: {
    fontFamily: family.sansRegular,
    fontSize: 12,
    marginTop: 2,
  },
  title: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    fontFamily: family.sansBold,
    fontSize: 23,
    paddingBottom: 10,
    paddingTop: 12,
  },
});
