//! THE 29 CASES, COMPARED WHOLE (#1020, D-1020-T2).
//!
//! `contracts/apps/tally/queries.json` is `{query, input, output}` for all eight
//! Tally queries at 29 fixed inputs, generated by running the REAL v0 handlers
//! over a founded vault (`contracts/tools/export-tally-parity.ts`). Wave 2
//! committed it and could not compare it: the outputs carry presentation from
//! `packages/design` with no Rust home, and dropping those fields would have
//! meant editing a generated fixture. `crates/design` closed that, and this
//! suite is the comparison.
//!
//! **Whole, not sampled.** Every case is dispatched, every answer compared by
//! value against the fixture's, and the case count is asserted per query so a
//! dispatch that quietly matched nothing fails. The rows the Rust side reads
//! are the fixture's own `rows.json` through the committed DDL, so the ids on
//! both sides are the same tokens — which is what the generator's one-id-space
//! fix made true.
//!
//! **The one exception, named and bounded**:
//! [`centraid_apps_tally::views::RECURRENCE_DEFERRED`] — `preview` and
//! `next_start` on a `recurring` row are answers of v0's civil-time plane, not
//! of Tally. The suite asserts both are PRESENT in the fixture and then removes
//! them from both sides, so the deferral cannot hide a regression in anything
//! else on the row, and cannot survive silently if the fixture stops carrying
//! them.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use centraid_apps_kit::contract_vault::open_contract_vault;
use centraid_apps_kit::testdoor::TestDoor;
use centraid_apps_tally::queries::{TallyData, load_dashboard_extras, load_tally};
use centraid_apps_tally::views::{
    RECURRENCE_DEFERRED, activity_view, dashboard_of, export_limit, export_view, friend, group,
    history, matches, search,
};
use rusqlite::Connection;
use serde_json::Value;

fn root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("..")
        .to_path_buf()
}

fn fixture(name: &str) -> Value {
    let path = root().join("contracts/apps/tally").join(name);
    let text = fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("{} is not readable: {error}", path.display()));
    serde_json::from_str(&text)
        .unwrap_or_else(|error| panic!("{} is not JSON: {error}", path.display()))
}

fn fixture_vault() -> Connection {
    let ddl = fs::read_to_string(root().join("contracts/schema/vault-ddl.sql"))
        .expect("the committed DDL is readable");
    let rows = fs::read_to_string(root().join("contracts/apps/tally/rows.json"))
        .expect("the fixture rows are readable");
    open_contract_vault(&ddl, &rows).expect("the fixture vault is built")
}

/// Strip the two civil-time fields from every `recurring` row, after proving
/// the fixture carries them.
fn without_deferred_recurrence(value: &Value, require_present: bool) -> Value {
    let mut copy = value.clone();
    let Some(rows) = copy.get_mut("recurring").and_then(Value::as_array_mut) else {
        return copy;
    };
    for row in rows.iter_mut() {
        let Some(object) = row.as_object_mut() else {
            continue;
        };
        for field in RECURRENCE_DEFERRED {
            // PRESENCE IS ASSERTED, so a fixture that stopped carrying the
            // field would fail here rather than make the deferral look done.
            assert!(
                !require_present || object.contains_key(field),
                "the fixture has a recurring row without `{field}`: the deferral is stale"
            );
            object.remove(field);
        }
    }
    copy
}

/// The token the generator masks an id-derived party hue with.
///
/// `partyHueValue(partyHueKey(id))` hashes the party id, and the generator
/// rewrites every id to a canonical token — so the hue in the fixture is an
/// answer about an id that no longer exists in it. The generator masks it, this
/// side masks its own the same way, and the wheel itself is proven where its
/// inputs are stable: `design/identity-corpus.json`, asserted row by row by
/// `crates/design` (#1020, D-1020-T1/T2b).
const PARTY_HUE: &str = "<party-hue>";

/// Replace every `var(--c-…)` with the mask, everywhere in a tree.
///
/// The owner's `#141414` is NOT id-derived and is deliberately left alone: that
/// a person is painted with the ink brand rather than off the wheel is the
/// distinction #883's ruling O-identity is about, and the comparison keeps it.
fn masked_hues(value: &Value) -> Value {
    match value {
        Value::String(text) if text.starts_with("var(--c-") && text.ends_with(')') => {
            Value::String(PARTY_HUE.to_owned())
        }
        Value::Array(entries) => Value::Array(entries.iter().map(masked_hues).collect()),
        Value::Object(entries) => Value::Object(
            entries
                .iter()
                .map(|(key, entry)| (key.clone(), masked_hues(entry)))
                .collect(),
        ),
        other => other.clone(),
    }
}

/// Every `color` in a tree is a wheel hue or the ink brand.
fn assert_colours_are_on_the_wheel(value: &Value, query: &str) {
    match value {
        Value::Object(entries) => {
            for (key, entry) in entries {
                if key == "color"
                    && let Some(text) = entry.as_str()
                    // `tally_group.color` is a STORED hex column and not a
                    // party hue, so only the wheel's own shape is checked.
                    && text.starts_with("var(--c-")
                {
                    let hue = &text["var(--c-".len()..text.len() - 1];
                    assert!(
                        centraid_design::IDENTITY_HUE_KEYS.contains(&hue),
                        "{query} painted a party `{text}`, which is not one of the eight hues"
                    );
                }
                assert_colours_are_on_the_wheel(entry, query);
            }
        }
        Value::Array(entries) => {
            for entry in entries {
                assert_colours_are_on_the_wheel(entry, query);
            }
        }
        _ => {}
    }
}

/// One case's answer, computed the way the handler for that query computes it.
fn answer(
    door: &TestDoor<'_>,
    data: &TallyData,
    extras: &(
        Vec<centraid_apps_kit::row::Row>,
        Vec<centraid_apps_kit::row::Row>,
        Vec<centraid_apps_kit::row::Row>,
    ),
    query: &str,
    input: &Value,
) -> Value {
    let text = |key: &str| -> String {
        input
            .get(key)
            .and_then(Value::as_str)
            .unwrap_or_default()
            .to_owned()
    };
    match query {
        "dashboard" => {
            dashboard_of(data, &extras.0, &extras.1, &extras.2).expect("the dashboard folds")
        }
        "activity" => activity_view(data),
        "matches" => matches(door).expect("the match plane reads"),
        "search" => search(data, &text("term")),
        "group" => group(data, &text("group_id")),
        "friend" => friend(data, &text("party_id")),
        "history" => history(door, &text("expense_id")).expect("the revision plane reads"),
        "export" => {
            let since = input.get("since").and_then(Value::as_str);
            let limit = export_limit(input.get("limit").and_then(Value::as_i64));
            export_view(door, data, &text("group_id"), since, limit).expect("the export reads")
        }
        other => panic!("{other} is not one of Tally's eight queries"),
    }
}

#[test]
fn all_twenty_nine_cases_answer_what_v0s_handlers_answered() {
    let cases = fixture("queries.json");
    let cases = cases.as_array().expect("queries.json is a list of cases");
    assert_eq!(cases.len(), 29, "the fixture's own case count");

    let connection = fixture_vault();
    let door = TestDoor::new(&connection);
    let data = load_tally(&door).expect("loadTally reads the fixture");
    let extras = load_dashboard_extras(&door).expect("the dashboard's three extra pages read");

    let mut compared: BTreeMap<&str, usize> = BTreeMap::new();
    let mut failures: Vec<String> = Vec::new();
    for case in cases {
        let query = case["query"].as_str().expect("a query name");
        let input = &case["input"];
        let raw = answer(&door, &data, &extras, query, input);
        // THE MASK IS NOT A FREE PASS: before it is applied, every colour this
        // side produced has to be a value the wheel can produce — one of the
        // eight hues, or the ink brand for the owner. A port that answered
        // `var(--c-null)` would mask to the same token and pass otherwise.
        assert_colours_are_on_the_wheel(&raw, query);
        let mine = masked_hues(&raw);
        let theirs = &case["output"];
        let (mine, theirs) = if query == "dashboard" {
            (
                without_deferred_recurrence(&mine, false),
                without_deferred_recurrence(theirs, true),
            )
        } else {
            (mine, theirs.clone())
        };
        if mine != theirs {
            failures.push(format!(
                "{query} {input}:\n  v0:   {}\n  rust: {}",
                theirs, mine
            ));
        }
        *compared.entry(query).or_default() += 1;
    }
    assert!(
        failures.is_empty(),
        "{} of {} cases disagree:\n{}",
        failures.len(),
        cases.len(),
        failures.join("\n")
    );
    // The per-query counts, so a dispatch that answered the wrong query — or
    // none — cannot pass by comparing an empty set.
    assert_eq!(
        compared,
        BTreeMap::from([
            ("activity", 1),
            ("dashboard", 1),
            ("export", 9),
            ("friend", 3),
            ("group", 4),
            ("history", 7),
            ("matches", 1),
            ("search", 3),
        ])
    );
}

/// A DEMONSTRATED RED: the presentation fields are compared, not skipped.
///
/// If `crates/design`'s hue wheel or initials drifted from `packages/design`,
/// every ledger row would disagree. This test proves the fixture really does
/// carry those fields, so the comparison above has something to be wrong about.
#[test]
fn the_fixture_carries_the_presentation_fields_the_comparison_turns_on() {
    let cases = fixture("queries.json");
    let mut hues = 0usize;
    let mut initials = 0usize;
    let mut tones = 0usize;
    fn walk(node: &Value, hues: &mut usize, initials: &mut usize, tones: &mut usize) {
        match node {
            Value::Object(entries) => {
                for (key, value) in entries {
                    match key.as_str() {
                        "color" => *hues += 1,
                        "initials" => *initials += 1,
                        "your_role" => *tones += 1,
                        _ => {}
                    }
                    walk(value, hues, initials, tones);
                }
            }
            Value::Array(entries) => {
                for entry in entries {
                    walk(entry, hues, initials, tones);
                }
            }
            _ => {}
        }
    }
    walk(&cases, &mut hues, &mut initials, &mut tones);
    assert!(hues >= 20, "{hues} party colours in the fixture");
    assert!(initials >= 20, "{initials} sets of initials");
    assert!(tones >= 10, "{tones} owner stances");
}
