// Injects the design-system CSS (generated by @centraid/design-tokens →
// `toCss()`) into a single <style> tag in <head>. Runs before any other
// renderer script so by the time styles.css resolves against actual
// elements, every var() lookup has a value.
//
// All token values (light + dark themes, density tiers, palette, radii,
// shadows, device-wall) live in the design-tokens package. This file
// owns the *delivery* mechanism, nothing more — tweaks to design values
// happen in TS, not here.

(function () {
  const tokens = window.CentraidTokens;
  if (!tokens?.cssText) {
    console.error('CentraidTokens.cssText missing — design-tokens preload may be stale.');
    return;
  }
  const style = document.createElement('style');
  style.id = 'centraid-tokens';
  style.textContent = tokens.cssText;
  // Prepend so anything in styles.css can override (e.g., density-aware
  // component rules). The token rules themselves only define vars.
  document.head.prepend(style);
})();
