package dev.centraid.shared.design

/**
 * THE PARTY HUE WHEEL, PORTED ONCE FOR BOTH SHELLS (#1020, D-1020-T1; #883,
 * ruling O-identity).
 *
 * **HAND-WRITTEN. NOT EMITTED.** Every file under `dev.centraid.design` carries
 * a `// GENERATED by …` first line and is written by
 * `contracts/tools/export-native-theme.ts` or its catalogue sibling; this one is
 * a port of `packages/design/src/identity.ts`'s FUNCTIONS, which an emitter
 * cannot lower because they are logic rather than a table. The package boundary
 * is what says so, and it is not decorative: `shared/build.gradle.kts` excludes
 * `dev.centraid.design.*` from Kover on the stated grounds that it is "the
 * token/copy emitter's" code, so a hand-written port filed in there would have
 * quietly opted itself out of the coverage rule it belongs under. It lives
 * beside the state machines that call it instead.
 *
 * ## Why one port and not two
 *
 * `crates/design/src/lib.rs` is the Rust half of the same lowering and exists
 * for a blocked parity comparison. The shells' half could have been written
 * twice — once in Compose, once in SwiftUI — and the two would have agreed by
 * luck, for as long as the luck held. They agree by construction instead:
 * [HomeReads][dev.centraid.shared.shell.HomeReads] resolves the hue HERE and
 * puts the answer in `TileBody.People.Face.color`, so a view's whole job is to
 * look up an emitted colour role. There is no second place for the wheel to
 * turn differently.
 *
 * ## The three sign questions, and which of them is real
 *
 * v0's `identityHash` is `Math.imul(hash, 31) + codePoint`, wrapped by hand:
 *
 * ```js
 * const next = Math.trunc(Math.imul(hash, 31) + character.codePointAt(0));
 * hash = next > 0x7fffffff ? next - 0x1_0000_0000 : next;
 * ```
 *
 * **1. The hand-wrap. Not a subtlety — it is `Int` overflow, spelled out.**
 * `Math.imul` multiplies as int32, which Kotlin's `Int` times `Int` already is,
 * and JS then adds the code point as a double so the sum can land above
 * `Int.MAX_VALUE`. But a code point is NON-NEGATIVE, so the sum can only
 * overflow UPWARD and never below `Int.MIN_VALUE`, and it can exceed
 * `Int.MAX_VALUE` by at most 0x10FFFF — well inside one wrap. Subtracting 2³²
 * exactly when it does is therefore the definition of two's-complement `Int`
 * addition, and `hash * 31 + codePoint` in plain `Int` is the SAME FUNCTION.
 * `crates/design`'s own comment says otherwise ("would wrap at a different
 * place and give a different hue for a minority of ids"); it is wrong, and
 * `PartyHueWheelSpec` carries the proof and the corrected reasoning. The
 * transcription below is kept because it is what the source says and because
 * `crates/design` is spelled the same way — not because it changes an answer.
 *
 * **2. The code-point walk. Real, and the corpus catches it.**
 * `for (const character of value)` walks CODE POINTS, and a Kotlin `String`
 * walks UTF-16 units. `"🙂"` is one code point to v0 and two chars here, so
 * [identityHash] pairs surrogates itself. The corpus carries `🙂` and `🙂🙂`
 * precisely so a unit walk cannot pass; the spec runs one to prove the corpus
 * says no.
 *
 * **3. The absolute value. Real in the function, inert at the wheel.**
 * `Math.abs` of an int32 is a DOUBLE and answers 2 147 483 648 for
 * `Int.MIN_VALUE`, which no `Int` holds; `kotlin.math.abs(Int.MIN_VALUE)`
 * answers `Int.MIN_VALUE`, still negative. So the absolute value is taken in
 * [Long], the same way `crates/design` takes it with
 * `i64::from(hash).unsigned_abs()`. What it does NOT change is the hue: 2³¹ is
 * divisible by eight, so both the right answer and the wrong one index place
 * zero. This is a guard on what the function RETURNS, and the spec says so
 * rather than letting a reader think a hue rides on it.
 */
public object PartyHueWheel {
    /**
     * The eight party hues, in the order the wheel indexes them
     * (`packages/design/src/identity.ts:48-57`). INK is not among them: the
     * vault wheel's ninth place is the ink brand, and keying a PERSON off it
     * draws them as a black disc (#883, ruling O-identity).
     *
     * The order is the index, so a reordering is a repaint of every face a
     * member already recognises. `PartyHueWheelSpec` pins it against the corpus
     * rather than against a reading of this list.
     */
    public val HUE_KEYS: List<String> = listOf(
        "rose",
        "amber",
        "ochre",
        "forest",
        "teal",
        "slate",
        "indigo",
        "violet",
    )

    /**
     * `var(--c-` — the opening of the value `avatar_color` stores.
     *
     * The vault stores the KEY inside a `var()` and never a hex, so a hue
     * follows the theme (`identity.ts:66`). Kept whole here, as
     * `crates/design` keeps it whole: the halving in the TypeScript is there to
     * keep the design-token gate from reading it as CSS, and that gate does not
     * scan Kotlin.
     */
    private const val HUE_VAR_OPEN: String = "var(--c-"

    /**
     * v0's `identityHash`, sign for sign (`identity.ts:30-37`).
     *
     * Answers a non-negative [Long] rather than an [Int] because `Math.abs` of
     * `Int.MIN_VALUE` does not fit in one. The class comment takes the three
     * sign questions in turn and says which of them a port actually gets
     * wrong — one of the three, and it is not the one that looks hardest.
     */
    public fun identityHash(value: String): Long {
        var hash = 0
        var index = 0
        while (index < value.length) {
            val high = value[index]
            val codePoint: Int
            val low = if (index + 1 < value.length) value[index + 1] else null
            if (high.isHighSurrogate() && low != null && low.isLowSurrogate()) {
                codePoint = 0x10000 +
                    ((high.code - 0xD800) shl 10) +
                    (low.code - 0xDC00)
                index += 2
            } else {
                // An UNPAIRED surrogate is its own code unit, which is exactly
                // what `String.prototype.codePointAt` answers for one.
                codePoint = high.code
                index += 1
            }
            // `hash * 31` in `Int` IS `Math.imul(hash, 31)` — two's complement,
            // wrapping, 32 bits. The sum is carried in `Long` and folded by
            // hand below because that is what the source says; see the class
            // comment for why it is the same function as an `Int` sum.
            val product = hash * 31
            val next = product.toLong() + codePoint.toLong()
            hash = if (next > Int.MAX_VALUE.toLong()) {
                // Exactly v0's `next - 0x1_0000_0000`.
                (next - 0x1_0000_0000L).toInt()
            } else {
                next.toInt()
            }
        }
        val wide = hash.toLong()
        return if (wide < 0L) -wide else wide
    }

    /**
     * The hue an id lands on when the vault stored nothing
     * (`identity.ts:59-62`).
     *
     * The id is trimmed first, which is v0's own `id.trim()`. Kotlin's `trim()`
     * reads a `Char` as whitespace when it is `Character.isWhitespace` OR a
     * space character, so ` ` trims on both sides — the corpus carries a
     * lone NBSP id to say so. The one divergence left is `﻿`, which JS
     * trims and Kotlin does not; no id in the corpus carries one, and a party id
     * with a byte-order mark in it is a vault bug rather than a hue question.
     */
    public fun identityHueKey(id: String): String {
        val index = (identityHash(id.trim()) % HUE_KEYS.size.toLong()).toInt()
        return HUE_KEYS[index]
    }

    /**
     * THE party hue, from the id and whatever the row stored
     * (`identity.ts:74-85`).
     *
     * Three answers, and the third is why this is nullable:
     *
     * - nothing stored (null, empty or whitespace) → the id's own hue;
     * - a stored `var(--c-<hue>)` naming one of the eight → that hue;
     * - anything else → `null`, a stored literal the wheel cannot name.
     *
     * A port that substituted a default for the third would be inventing an
     * answer, which is the reason `crates/design`'s `party_hue_key` returns an
     * `Option` too. What the shells DO with the `null` is
     * [HomeReads][dev.centraid.shared.shell.HomeReads]'s decision and is
     * recorded there.
     */
    public fun partyHueKey(partyId: String, avatarColor: String?): String? {
        val stored = (avatarColor ?: "").trim()
        if (stored.isEmpty()) return identityHueKey(partyId)
        if (!stored.startsWith(HUE_VAR_OPEN) || !stored.endsWith(")")) return null
        val key = stored.substring(HUE_VAR_OPEN.length, stored.length - 1)
        return if (key in HUE_KEYS) key else null
    }
}
