// Hand-maintained (no emitter writes it). `copy/chat.json` is its twin: edit
// both, and `KitTimeMoneyCopySpec` fails when they disagree.
//
// THE ON-DEVICE CHAT: a tab on the bottom bar, not an app. Every sentence a
// member reads on it is here; the model's own line and the rows it found are
// data, not copy.

package dev.centraid.design.copy

/** The chat's strings. STRINGS ONLY: a function composes a sentence and is the machine's to write. */
public object ChatCopy {
    public const val A11Y_ANSWER: String = "Centraid said"
    public const val A11Y_ATTACHED: String = "Attached"
    public const val A11Y_YOU: String = "You said"
    public const val AGO_DAYS: String = "{n} days ago"
    public const val AGO_HOURS: String = "{n} hr ago"
    public const val AGO_JUST_NOW: String = "Just now"
    public const val AGO_MINUTES: String = "{n} min ago"
    public const val ATTACH: String = "Attach"
    public const val ATTACH_DOCUMENT: String = "Document"
    public const val ATTACH_LIBRARY_PHOTO: String = "Photo library"
    public const val ATTACH_NO_DOCUMENTS: String = "No text documents yet."
    public const val ATTACH_NO_PHOTOS: String = "No photos in your vault."
    public const val ATTACH_PICK_DOCUMENT: String = "Choose a document"
    public const val ATTACH_PICK_PHOTO: String = "Choose a photo"
    public const val ATTACH_VAULT_PHOTO: String = "Photo from vault"
    public const val CANCEL: String = "Cancel"
    public const val CARD_GONE: String = "This item is gone."
    public const val CHIP_DOCUMENT: String = "Document"
    public const val CHIP_PHOTO: String = "Photo"
    public const val CLOSE: String = "Close"
    public const val COMPOSER_PLACEHOLDER: String = "Ask your vault"
    public const val COPIED: String = "Copied"
    public const val COPY: String = "Copy"
    public const val CURRENT_CHAT: String = "Open chat"
    public const val DELETE: String = "Delete"
    public const val DELETE_ALL: String = "Delete all chats"
    public const val DELETE_ALL_BODY: String = "Every chat in this vault is removed. This cannot be undone."
    public const val DELETE_ALL_TITLE: String = "Delete all chats?"
    public const val DELETE_BODY: String = "Its messages are removed from this vault. This cannot be undone."
    public const val DELETE_TITLE: String = "Delete this chat?"
    public const val DOWNLOAD_ACTION: String = "Download model"
    public const val DOWNLOAD_FAILED: String = "Download stopped. Retry."
    public const val DOWNLOAD_NOTE: String = "This is the only time Centraid fetches anything."
    public const val DOWNLOAD_PROGRESS: String = "Downloading {percent}"
    public const val DOWNLOAD_PROGRESS_UNKNOWN: String = "Downloading"
    public const val DRAWER_LABEL: String = "Chats"
    public const val EMPTY_LINE: String = "Ask about anything in your vault."
    public const val ERROR_ATTACH_TOO_LARGE: String = "That attachment is too large."
    public const val ERROR_ATTACH_UNREADABLE: String = "That attachment would not open."
    public const val ERROR_ATTACH_UNSUPPORTED: String = "Chat reads photos and text documents."
    public const val ERROR_GENERIC: String = "Chat could not answer. Retry."
    public const val ERROR_MODEL: String = "The model stopped. Retry."
    public const val ERROR_NO_TOOL: String = "Nothing in your vault answers that."
    public const val ERROR_READ: String = "Chat could not read your vault. Retry."
    public const val ERROR_THREAD_GONE: String = "This chat is gone."
    public const val ERROR_VISION: String = "The photo reader is not loaded. Retry."
    public const val LOADING: String = "Loading model"
    public const val LOAD_FAILED: String = "The model would not load. Download it again."
    public const val LOOKING: String = "Looking in {app}"
    public const val MENU_LABEL: String = "Chat options"
    public const val NEW_CHAT: String = "New chat"
    public const val NOTE_DOC_TRUNCATED: String = "Read the first part of the document."
    public const val READING_DOCUMENT: String = "Reading the document"
    public const val READING_PHOTO: String = "Reading the photo"
    public const val REMOVE_ATTACHMENT: String = "Remove"
    public const val RENAME: String = "Rename"
    public const val RENAME_TITLE: String = "Rename chat"
    public const val RETRY: String = "Retry"
    public const val SAID_APPLIED: String = "Done."
    public const val SAID_BALANCE: String = "Balance {value}."
    public const val SAID_BALANCE_EVEN: String = "You and {name} are settled up."
    public const val SAID_BALANCE_OWED: String = "{name} owes you {value}."
    public const val SAID_BALANCE_OWING: String = "You owe {name} {value}."
    public const val SAID_CAP: String = "Out of steps. Ask a smaller question."
    public const val SAID_COUNT: String = "Counted {what}."
    public const val SAID_DECLINE_FABRICATED_SECRET: String = "Chat does not invent secrets."
    public const val SAID_DECLINE_NEVER_MIND: String = "Okay. Nothing changed."
    public const val SAID_DECLINE_OUT_OF_SCOPE: String = "Outside what chat can do here."
    public const val SAID_DECLINE_SEALED_EGRESS: String = "Secrets stay in Locker. Chat does not read or send them."
    public const val SAID_DECLINE_UNBOUNDED_DESTRUCTION: String = "Too much at once. Nothing changed."
    public const val SAID_FOUND: String = "Found {what}."
    public const val SAID_FOUND_SOME: String = "Found {what}. Showing {shown}."
    public const val SAID_HIGHEST: String = "Highest {field}: {value}."
    public const val SAID_LOWEST: String = "Lowest {field}: {value}."
    public const val SAID_NOTHING: String = "Nothing found."
    public const val SAID_NOTHING_WAITING: String = "Nothing is waiting on that."
    public const val SAID_NOT_DONE: String = "Not done. {reason}"
    public const val SAID_PROPOSED: String = "Proposed: {what}."
    public const val SAID_STALE: String = "That changed since. Ask again."
    public const val SAID_TOTAL: String = "Total {field}: {value}."
    public const val SAVE: String = "Save"
    public const val SCOPE_ALL: String = "All apps"
    public const val SCOPE_LABEL: String = "Chat scope"
    public const val SEND: String = "Send"
    public const val SIZE_LINE: String = "{size} download"
    public const val STOP: String = "Stop"
    public const val STOPPED: String = "Stopped"
    public const val SUBTITLE: String = "On this phone"
    public const val SUBTITLE_VAULT: String = "{vault} · on this phone"
    public const val TAB_LABEL: String = "Chat"
    public const val THINKING: String = "Thinking"
    public const val THREADS_EMPTY: String = "No chats yet."
    public const val TITLE: String = "Chat"
    public const val UNAVAILABLE: String = "Chat is not available here."
    public const val VISION_ACTION: String = "Download"
    public const val VISION_LINE: String = "Reading photos needs a {size} download"
    public const val VISION_LOADING: String = "Loading photo reader"
    public const val VISION_LOAD_FAILED: String = "The photo reader would not load. Download it again."
}
