// Hand-maintained (the emitter, `export-copy.ts`, left with v0's copy leaves
// in #1020 wave 6). `copy/shared.json` is its twin: edit both, and
// `CopySyncSpec` fails when they disagree. One file per app, so an app's
// port edits only its own.

package dev.centraid.design.copy

/** Shared's strings. STRINGS ONLY: a function composes a sentence and is the app's to write. */
public object SharedCopy {
    public const val ALL_DAY: String = "All day"
    public const val AUTOSAVE_CHANGED_ELSEWHERE: String = "Changed on another device"
    public const val AUTOSAVE_EDITED: String = "Edited"
    public const val AUTOSAVE_NOT_SAVED: String = "Not saved"
    public const val AUTOSAVE_SAVED: String = "Saved"
    public const val AUTOSAVE_SAVING: String = "Saving…"
    public const val BACK: String = "Back"
    public const val BACK_TO: String = "Back to {parent}"
    public const val BAND_HOME: String = "Home"
    public const val BAND_MORE: String = "More"
    public const val BAND_MORE_SPOKEN: String = "All apps and places"
    public const val HOME_ALL_APPS: String = "All apps"
    public const val HOME_DAY_ONE_BODY: String = "Bring your photographs and documents in and this becomes the front of your own archive."
    public const val HOME_DAY_ONE_TITLE: String = "Nothing in here yet"
    public const val HOME_FIRST_MOVES: String = "Fill this out"
    public const val HOME_LOADING: String = "Loading"
    public const val HOME_PHOTOS_ABSENT: String = "These photographs are not on this device yet."
    public const val KIT_CANCEL: String = "Cancel"
    public const val KIT_CLOSE_SEARCH: String = "Close search"
    public const val KIT_DONE: String = "Done"
    public const val KIT_LOADING_MORE: String = "Loading more"
    public const val KIT_OPENING: String = "Opening"
    public const val KIT_PENDING: String = "Saving"
    public const val KIT_REFRESH: String = "Refresh"
    public const val KIT_RETRY: String = "Try again"
    public const val KIT_SEARCH: String = "Search"
    public const val KIT_SHOW_MORE: String = "Show more"
    public const val MONTH_01: String = "January"
    public const val MONTH_02: String = "February"
    public const val MONTH_03: String = "March"
    public const val MONTH_04: String = "April"
    public const val MONTH_05: String = "May"
    public const val MONTH_06: String = "June"
    public const val MONTH_07: String = "July"
    public const val MONTH_08: String = "August"
    public const val MONTH_09: String = "September"
    public const val MONTH_10: String = "October"
    public const val MONTH_11: String = "November"
    public const val MONTH_12: String = "December"
    public const val OPEN_APP: String = "Open {name}"
    public const val STRANDED_WRITE: String = "Your last change in {app} was not saved."
    public const val STRANDED_WRITE_WHY: String = "{app}: {sentence}"
    public const val TODAY: String = "Today"
    public const val TOMORROW: String = "Tomorrow"
    public const val TRASH_DELETED: String = "Deleted"
    public const val TRASH_EMPTY_ACTION: String = "Empty trash"
    public const val TRASH_EMPTY_BODY: String = "Everything in trash leaves this vault for good. This cannot be undone."
    public const val TRASH_EMPTY_HEADLINE: String = "Trash is empty."
    public const val TRASH_EMPTY_STATE_BODY: String = "Deleted things wait here before they go for good."
    public const val TRASH_EMPTY_TITLE: String = "Empty trash?"
    public const val TRASH_PURGE: String = "Delete forever"
    public const val TRASH_PURGE_BODY: String = "It leaves this vault for good. This cannot be undone."
    public const val TRASH_PURGE_TITLE: String = "Delete this forever?"
    public const val TRASH_RESTORE: String = "Restore"
    public const val TRASH_TITLE: String = "Trash"
    public const val TRASH_UNTITLED: String = "Untitled"
    public const val VAULTS_CURRENT: String = "Currently open"
    public const val VAULTS_FORGET: String = "Forget"
    public const val VAULTS_FORGET_BODY: String = "This deletes the vault and everything in it. There is no copy anywhere else."
    public const val VAULTS_FORGET_THIS: String = "this vault"
    public const val VAULTS_FORGET_TITLE: String = "Forget {name}?"
    public const val VAULTS_KEEP: String = "Keep"
    public const val VAULTS_MAKE: String = "Make a vault"
    public const val VAULTS_MAKE_SPOKEN: String = "Make a vault on this phone"
    public const val VAULTS_NONE: String = "This device holds no vault."
    public const val VAULTS_ONE: String = "This device holds one vault."
    public const val VAULTS_TITLE: String = "Vaults"
    public const val VAULTS_UNNAMED: String = "Unnamed vault"
    public const val VAULT_DENIED_TITLE: String = "No vault access yet."
    public const val WEEKDAY_FRI: String = "Fri"
    public const val WEEKDAY_MON: String = "Mon"
    public const val WEEKDAY_SAT: String = "Sat"
    public const val WEEKDAY_SUN: String = "Sun"
    public const val WEEKDAY_THU: String = "Thu"
    public const val WEEKDAY_TUE: String = "Tue"
    public const val WEEKDAY_WED: String = "Wed"
    public const val YESTERDAY: String = "Yesterday"
}
