// Hand-maintained (the emitter, `export-copy.ts`, left with v0's copy leaves
// in #1020 wave 6). `copy/words.json` is its twin: edit both, and
// `KitTimeMoneyCopySpec` fails when they disagree.
//
// THE 24 WORDS (#1047 E1): making a vault and its words, and typing them back
// to restore or to re-key. Every sentence a member reads on either screen is
// here; no word of the phrase ever is.

package dev.centraid.design.copy

/** The words screens' strings. STRINGS ONLY: a function composes a sentence and is the flow's to write. */
public object WordsCopy {
    public const val BAD_CHECKSUM: String = "Every word is a real one, and together they are not a phrase Centraid made. Check their order, and each word against what you wrote down."
    public const val CANCEL: String = "Cancel"
    public const val CHECK_BODY: String = "Type words {positions} from what you wrote down."
    public const val CHECK_PRIMARY: String = "Check"
    public const val CHECK_PROMPT: String = "Word {n}"
    public const val CHECK_SECONDARY: String = "Show the words again"
    public const val CHECK_TITLE: String = "Check your words"
    public const val CHECK_WRONG: String = "One of these is not the word at its place. Check what you wrote down."
    public const val COUNT_MANY: String = "Centraid needs 24 words. There are {n} here."
    public const val COUNT_ONE: String = "Centraid needs 24 words. There is 1 here."
    public const val COUNT_TOO_MANY: String = "Centraid needs 24 words. There are more than 24 here."
    public const val DIFFERENT_WORDS: String = "This phone already holds a different set of 24 words, and its vaults open with those. Nothing was changed."
    public const val DONE: String = "Done"
    public const val ENDPOINT_LABEL: String = "Paste the pairing code your laptop prints with “centraid-gateway pair”."
    public const val FAILED_TITLE: String = "Your vault was not made"
    public const val KEEP_FAILED: String = "Centraid could not keep your key on this phone. Nothing was changed."
    public const val MADE_BODY: String = "{name} is on this phone, and your 24 words bring it back."
    public const val MADE_TITLE: String = "Your vault is ready"
    public const val MAKING_BODY: String = "Your vault's keys come from your 24 words."
    public const val MAKING_TITLE: String = "Making your vault"
    public const val MINT_FAILED: String = "This phone could not make your words. Nothing was made."
    public const val NOT_A_PHRASE: String = "Centraid could not read these as 24 words. Check them and try again."
    public const val PAIR_NOT_A_CODE: String = "That is not a pairing code this phone can use, or it has run out. Run “centraid-gateway pair” on your laptop again and use the new one."
    public const val PAIR_NOT_TAKEN: String = "Your laptop answered and did not take this pairing code. Each code works once: run “centraid-gateway pair” on your laptop again and use the new one."
    public const val PAIR_WORDS_ACTION: String = "Enter your 24 words"
    public const val REKEYED_BODY: String = "Locker and backups open again for the vaults made with these words."
    public const val REKEYED_PAIR_BODY: String = "The vaults made with these words can pair with your laptop now."
    public const val REKEYED_TITLE: String = "Your words are back on this phone"
    public const val REKEYING: String = "Opening your vaults with your words…"
    public const val REKEY_BODY: String = "Locker's secrets open with a key from your 24 words. Type them to give this phone the key again."
    public const val REKEY_PAIR_BODY: String = "Your laptop knows your vaults by a key from your 24 words. Type them to give this phone the key again, then pair."
    public const val REKEY_NONE: String = "These are valid words, and no vault on this phone was made with them here. Restore from your laptop to bring your vaults back with their keys."
    public const val REKEY_NONE_ACTION: String = "Restore from my laptop"
    public const val REKEY_PRIMARY: String = "Use these words"
    public const val REKEY_TITLE: String = "Enter your 24 words"
    public const val RESTORED_LINE_MANY: String = "Vault {index}: {rows} rows."
    public const val RESTORED_LINE_NONE: String = "Vault {index}."
    public const val RESTORED_LINE_ONE: String = "Vault {index}: 1 row."
    public const val RESTORED_SAFETY: String = "Check this number matches the one your laptop shows for this vault."
    public const val RESTORED_SOME_TITLE: String = "Some of your vaults are back"
    public const val RESTORED_STAYED: String = "Vault {index} stayed on your other phone. Your laptop would not hand it over this time, so none of it moved here."
    public const val RESTORED_STAYED_BODY: String = "Your other phone keeps each vault that stayed and goes on backing it up, so keep that phone for now. Try again to bring those vaults here on their own; the ones already here stay as they are."
    public const val RESTORED_STAYED_RETRY: String = "Try again"
    public const val RESTORED_TITLE: String = "Your vaults are back"
    public const val RESTORE_BODY: String = "Type the 24 words you wrote down, and paste a pairing code from your laptop."
    public const val RESTORE_FIRST_ACTION: String = "Restore my vaults"
    public const val RESTORE_FIRST_BODY: String = "This phone already holds the key from your 24 words, and no record of which vaults you made with it. Restore them first, so a new vault does not take the place of one you already have."
    public const val RESTORE_FIRST_TITLE: String = "Restore your vaults first"
    public const val RESTORE_HELD_BODY: String = "This phone already has your key from your other phone, so there are no words to type. Centraid asks your laptop for every vault it opens."
    public const val RESTORE_HELD_TITLE: String = "Restore your vaults"
    public const val RESTORE_DID_NOT_CHECK: String = "Your laptop sent your vault back, and it did not pass this phone's check, so nothing was restored and nothing changed. Your other phone still backs up. Try again, and if it happens again, keep that phone."
    public const val RESTORE_NOTHING_HELD: String = "Those words are valid and your laptop is holding no backup for them. Check you are restoring onto the right laptop."
    public const val RESTORE_NOT_TAKEN: String = "Your laptop answered and would not let this phone take your vault. Nothing was restored. Try again, and check this is the laptop you paired."
    public const val RESTORE_PRIMARY: String = "Restore"
    public const val RESTORE_STAYED_STILL: String = "Your laptop did not hand it over this time either. It stays on your other phone, which goes on backing it up, and nothing here changed."
    public const val RESTORE_TITLE: String = "Restore from your 24 words"
    public const val RESTORE_UNREACHABLE: String = "Centraid could not reach your laptop. Check that centraid-gateway is running on it, or paste a new pairing code."
    public const val RESTORING: String = "Looking for your laptop…"
    public const val SHOW_A11Y: String = "Your 24 words. Write them down in order, on paper."
    public const val SHOW_AGAIN_ASK_BODY: String = "Your phone checks it's you before it shows them. Make sure nobody can see your screen."
    public const val SHOW_AGAIN_BODY: String = "Write them down in order and keep them somewhere safe. Anyone who has them can open your vaults."
    public const val SHOW_AGAIN_NONE: String = "This phone has no 24 words yet. Make a vault or restore one first."
    public const val SHOW_AGAIN_NONE_SYNCED: String = "This phone got your key from your other phone, not from your words. Your words are on the phone that made them, and on the paper you wrote them on."
    public const val SHOW_AGAIN_NONE_TITLE: String = "No words on this phone"
    public const val SHOW_AGAIN_PRIMARY: String = "Show my words"
    public const val SHOW_AGAIN_REASON: String = "Show your 24 words"
    public const val SHOW_AGAIN_ROW: String = "Show my 24 words"
    public const val SHOW_AGAIN_TITLE: String = "Your 24 words"
    public const val SHOW_AGAIN_VERIFY_FAILED: String = "Your phone could not check it's you, so your words stay hidden."
    public const val SHOW_BODY: String = "These 24 words are your vaults. Anyone who has them has everything in Centraid, and nobody can give them back to you — not us, not your laptop. Write them down on paper and keep them somewhere safe."
    public const val SHOW_PRIMARY: String = "I have written them down"
    public const val SHOW_TITLE: String = "Your 24 words"
    public const val STILL_OPENING: String = "Centraid is still opening. Try again in a moment."
    public const val TRY_AGAIN: String = "Try again"
    public const val UNKNOWN_WORD: String = "Word {n} is not on the list of words Centraid uses. Check its spelling."
    public const val WORD_PROMPT: String = "Word {n}"
    public const val WORD_SPOKEN: String = "Word {n}, {word}"
}
