//! **v0 is the oracle**: every case in `contracts/automations/` is compared
//! against this crate's answer (#1020, D-1020-D3-6).
//!
//! The fixtures are generated by `contracts/tools/export-automations-parity.ts`
//! from the live v0 modules — `cronMatches`, `readCronCursor`, `parseManifest`,
//! `decideEnrichmentGate` and `system-recognition.ts` — and
//! `tests/quality/automations-parity.contract.test.ts` is both the emitter and
//! the v0-side oracle. Nothing here is typed by hand, and nothing here is
//! regenerated from this crate: a fixture a port could rewrite proves nothing.
//!
//! ## The two divergences, named
//!
//! 1. **The host-clock tier.** v0 resolves a fire zone in three tiers and the
//!    third is the process clock; v1 deletes it (D-1020-AU2, R-1020-33).
//!    `cron-cases.json` carries every case WITH a zone, which both builds
//!    agree on, plus one `finding` block recording what v0 answers with no
//!    zone at all on a UTC host. That case is asserted as a DIFFERENCE rather
//!    than as parity, because agreeing with it would be the bug.
//! 2. **The connector block's own fields.** v0 validates a connector's `label`
//!    and `kind`; this crate records the block's PRESENCE only, because the
//!    connectors plane is on the back burner (owner, 2026-09-12) and a
//!    validator with no consumer is a validator nobody keeps true. The two
//!    agree that the manifest is REFUSED and disagree about which field is
//!    named; [`DIVERGENT_FIELDS`] is the list, and it has one entry.

use std::collections::BTreeMap;
use std::path::PathBuf;

use centraid_automations::cron::{self, FireZone};
use centraid_automations::fire::cron_cursor::{self, Schedule};
use centraid_automations::fire::cursor::StoredCursor;
use centraid_automations::fire::enrich_gate::{GateDecision, GateInput, Tier, decide};
use centraid_automations::manifest::{self, Backfill, EnrichDomain, EnrichLane, Notify};

fn fixture(name: &str) -> serde_json::Value {
    let path: PathBuf = [
        env!("CARGO_MANIFEST_DIR"),
        "..",
        "..",
        "contracts",
        "automations",
        name,
    ]
    .iter()
    .collect();
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("{} is missing: {error}", path.display()));
    serde_json::from_str(&text).unwrap_or_else(|error| panic!("{name} is not JSON: {error}"))
}

/// Parse an ISO instant to epoch milliseconds. The fixture writes
/// `toISOString()`, so the shape is fixed and this parser need accept only it.
fn epoch_ms(iso: &str) -> i64 {
    let bytes = iso.as_bytes();
    assert!(iso.len() >= 20 && bytes[10] == b'T' && iso.ends_with('Z'), "{iso}");
    let field = |from: usize, to: usize| -> i64 {
        iso[from..to].parse().unwrap_or_else(|_| panic!("{iso}"))
    };
    let (year, month, day) = (field(0, 4), field(5, 7), field(8, 10));
    let (hour, minute, second) = (field(11, 13), field(14, 16), field(17, 19));
    let millis = if iso.len() > 21 { field(20, 23) } else { 0 };
    // Days from the civil epoch (Howard Hinnant's algorithm), because a date
    // crate for one parser in one test would be a dependency nobody reads.
    let year = if month <= 2 { year - 1 } else { year };
    let era = year.div_euclid(400);
    let year_of_era = year - era * 400;
    let day_of_year = (153 * (if month > 2 { month - 3 } else { month + 9 }) + 2) / 5 + day - 1;
    let day_of_era =
        year_of_era * 365 + year_of_era / 4 - year_of_era / 100 + day_of_year;
    let days = era * 146_097 + day_of_era - 719_468;
    ((days * 24 + hour) * 60 + minute) * 60_000 + second * 1_000 + millis
}

/// THE MATCHER, over every case v0 answered.
#[test]
fn every_cron_case_agrees_with_v0() {
    let bundle = fixture("cron-cases.json");
    let cases = bundle["cases"].as_array().expect("an array of cases");
    assert!(cases.len() > 2_000, "{}", cases.len());
    let mut zones: BTreeMap<String, FireZone> = BTreeMap::new();
    let mut disagreements = Vec::new();
    for case in cases {
        let expr = case["expr"].as_str().expect("an expression");
        let zone_name = case["zone"].as_str().expect("a zone");
        let instant = case["instant"].as_str().expect("an instant");
        let expected = case["matches"].as_bool().expect("an answer");
        let zone = zones
            .entry(zone_name.to_owned())
            .or_insert_with(|| FireZone::named(zone_name).expect("bundled"));
        let answer = cron::matches(expr, epoch_ms(instant), zone);
        if answer != expected {
            disagreements.push(format!("{expr} @ {instant} in {zone_name}: {answer} vs {expected}"));
        }
    }
    assert!(
        disagreements.is_empty(),
        "{} of {} cases disagree with v0:\n{}",
        disagreements.len(),
        cases.len(),
        disagreements
            .iter()
            .take(10)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
}

/// THE FINDING (R-1020-35): the one case where agreeing with v0 would be the
/// bug.
#[test]
fn the_host_clock_tier_is_a_difference_and_the_fixture_says_so() {
    let finding = fixture("cron-cases.json")["finding"].clone();
    assert_eq!(finding["name"], "utc-host-third-tier");
    assert_eq!(finding["withVaultZone"], true);
    assert_eq!(
        finding["withNoZone"], false,
        "on a UTC host v0's third tier answers the wrong hour"
    );
    let vault_zone = finding["vaultZone"].as_str().expect("a zone");
    let instant = epoch_ms(finding["instant"].as_str().expect("an instant"));
    let expr = finding["expr"].as_str().expect("an expression");
    // THE PORT HAS NO THIRD TIER AT ALL, so it answers the vault's zone — and
    // there is no call it can make that answers the host's.
    let resolved = FireZone::resolve(None, Some(vault_zone)).expect("the vault's zone");
    assert!(cron::matches(expr, instant, &resolved));
    assert_eq!(
        FireZone::resolve(None, None),
        Err(cron::ZoneUnset::Missing),
        "there is no third tier to fall through to"
    );
}

/// THE CURSOR, over the eight windows v0 answered.
#[test]
fn every_cron_window_agrees_with_v0() {
    let bundle = fixture("cron-windows.json");
    assert_eq!(
        bundle["maxBackfillOccurrences"].as_u64(),
        Some(manifest::MAX_BACKFILL_OCCURRENCES as u64),
        "the `each` bound is v0's"
    );
    let cases = bundle["cases"].as_array().expect("an array");
    assert_eq!(cases.len(), 8);
    for case in cases {
        let name = case["name"].as_str().expect("a name");
        let schedules: Vec<Schedule> = case["schedules"]
            .as_array()
            .expect("schedules")
            .iter()
            .map(|entry| Schedule {
                expr: entry["expr"].as_str().expect("an expression").to_owned(),
                zone: FireZone::named(entry["timeZone"].as_str().expect("a zone"))
                    .expect("bundled"),
                backfill: match entry["backfill"].as_str() {
                    Some("each") => Backfill::Each,
                    _ => Backfill::Latest,
                },
            })
            .collect();
        let from = epoch_ms(case["from"].as_str().expect("from"));
        let to = epoch_ms(case["to"].as_str().expect("to"));
        let cursor = StoredCursor {
            source_kind: "cron".to_owned(),
            position_json: Some(from.to_string()),
            ..StoredCursor::default()
        };
        let read = cron_cursor::read(&schedules, Some(&cursor), to);
        let delivered: Vec<i64> = read
            .elements
            .iter()
            .map(|element| element.occurred_at)
            .collect();
        let expected: Vec<i64> = case["delivered"]
            .as_array()
            .expect("delivered")
            .iter()
            .map(|value| epoch_ms(value.as_str().expect("an instant")))
            .collect();
        assert_eq!(delivered, expected, "{name}: delivered instants");
        assert_eq!(
            u64::from(read.skipped),
            case["skipped"].as_u64().expect("a count"),
            "{name}: skipped"
        );
        assert_eq!(
            read.gap_reason.as_deref(),
            case["gapReason"].as_str(),
            "{name}: gap reason"
        );
    }
}

/// The one manifest case where the two parsers name different fields, and why.
///
/// v0 validates a connector block's own `kind` and `label`; this crate records
/// the block's PRESENCE only. Both REFUSE the manifest.
const DIVERGENT_FIELDS: [(&str, &str, &str); 1] = [(
    "a-connector-with-no-vault-block",
    "connector.label",
    "manifest.connector",
)];

/// THE PARSER, over every document v0 answered.
#[test]
fn every_manifest_case_agrees_with_v0() {
    let cases = fixture("manifests.json");
    let cases = cases.as_array().expect("an array");
    assert!(cases.len() >= 20, "{}", cases.len());
    let mut accepted = 0;
    let mut refused = 0;
    for case in cases {
        let name = case["name"].as_str().expect("a name");
        let document = &case["document"];
        let answer = manifest::from_value(document);
        match case["outcome"].as_str() {
            Some("accepted") => {
                accepted += 1;
                let parsed = answer
                    .unwrap_or_else(|error| panic!("{name}: v0 accepted this, we refused: {error}"));
                let kinds: Vec<&str> = parsed
                    .triggers
                    .iter()
                    .map(|trigger| trigger.kind().as_str())
                    .collect();
                let expected: Vec<&str> = case["kinds"]
                    .as_array()
                    .expect("kinds")
                    .iter()
                    .map(|value| value.as_str().expect("a kind"))
                    .collect();
                assert_eq!(kinds, expected, "{name}: trigger kinds, in order");
                assert_eq!(
                    parsed.notify.as_str(),
                    case["notify"].as_str().expect("notify"),
                    "{name}: notify"
                );
                assert_eq!(
                    parsed.version,
                    case["version"].as_str().expect("version"),
                    "{name}: version"
                );
                assert_eq!(
                    parsed.enabled,
                    case["enabled"].as_bool().expect("enabled"),
                    "{name}: enabled"
                );
                match case["enrichLane"].as_str() {
                    Some(lane) => {
                        let enrich = parsed.enrich.expect("an enrich block");
                        assert_eq!(enrich.lane.as_str(), lane, "{name}: enrich lane");
                    }
                    None => assert!(parsed.enrich.is_none(), "{name}: no enrich block"),
                }
            }
            Some("refused") => {
                refused += 1;
                let error = answer
                    .err()
                    .unwrap_or_else(|| panic!("{name}: v0 refused this, we accepted it"));
                let v0_field = case["field"].as_str().expect("a field");
                let divergent = DIVERGENT_FIELDS
                    .iter()
                    .find(|(case_name, _, _)| *case_name == name);
                let expected_field = match divergent {
                    Some((_, expected_v0, ours)) => {
                        assert_eq!(
                            v0_field, *expected_v0,
                            "{name}: the recorded divergence is stale"
                        );
                        (*ours).to_owned()
                    }
                    // v0's field is unprefixed; this crate's carries the
                    // `manifest.` root so a refusal reads as a path.
                    None => format!("manifest.{v0_field}"),
                };
                assert_eq!(error.field, expected_field, "{name}: refused field");
            }
            other => panic!("{name}: unknown outcome {other:?}"),
        }
    }
    assert!(accepted >= 3, "{accepted}");
    assert!(refused >= 16, "{refused}");
}

/// THE WATCH GUARD: v0 calls it an `invalid_trigger`, this crate gives it a
/// code of its own so a surface can say "you named a table you may not watch"
/// rather than "your trigger is malformed".
#[test]
fn the_watch_refusals_carry_their_own_code_here() {
    let cases = fixture("manifests.json");
    let guarded = [
        "a-data-trigger-on-the-cursor-table",
        "a-data-trigger-on-the-outbox",
        "a-condition-trigger-on-the-ingress",
    ];
    for name in guarded {
        let case = cases
            .as_array()
            .expect("an array")
            .iter()
            .find(|case| case["name"] == name)
            .unwrap_or_else(|| panic!("{name} is missing from the fixture"));
        assert_eq!(case["outcome"], "refused", "{name}");
        assert_eq!(case["code"], "invalid_trigger", "{name}: v0's code");
        let error = manifest::from_value(&case["document"]).expect_err("refused");
        assert_eq!(
            error.code,
            manifest::ManifestErrorCode::DeniedWatch,
            "{name}: this crate's code"
        );
    }
}

/// THE GATE, over v0's whole grid. v1 adds a fourth rung; v0's three are
/// compared here and the fourth is the unit tests'.
#[test]
fn every_gate_cell_agrees_with_v0_over_v0s_three_tiers() {
    let bundle = fixture("gate.json");
    assert_eq!(
        bundle["tiers"].as_array().expect("tiers").len(),
        3,
        "v0 has three tiers; v1's fourth has no v0 answer to compare"
    );
    let grid = bundle["grid"].as_array().expect("a grid");
    assert_eq!(grid.len(), 16);
    for cell in grid {
        let lane = match cell["lane"].as_str() {
            Some("device") => EnrichLane::Device,
            _ => EnrichLane::Gateway,
        };
        let tier = cell["tier"].as_str().map(|stored| {
            Tier::read_forward(stored).unwrap_or_else(|| panic!("{stored} reads forward"))
        });
        let system = cell["system"].as_bool().expect("a provenance answer");
        let decision = decide(&GateInput {
            automation_ref: "faces/faces",
            domain: EnrichDomain::Photos,
            capability: "faces",
            lane,
            tier,
            system,
            capability_enabled: None,
            profile_id: None,
        });
        let expected = cell["allowed"].as_bool().expect("an answer");
        assert_eq!(
            decision.allowed(),
            expected,
            "tier={:?} lane={:?} system={system}",
            cell["tier"],
            cell["lane"]
        );
        if let (
            GateDecision::Allowed {
                seal_model_turns, ..
            },
            Some(v0_sealed),
        ) = (&decision, cell["sealModelTurns"].as_bool())
        {
            assert_eq!(
                *seal_model_turns, v0_sealed,
                "tier={:?} lane={:?} system={system}: sealModelTurns",
                cell["tier"], cell["lane"]
            );
        }
    }
}

/// THE CATALOGUE: the two provenance constants and the pinned weights, against
/// v0's own.
#[test]
fn the_recipe_catalogue_agrees_with_v0s_constants_and_the_weights_manifest() {
    use centraid_automations::handler::{
        BUNDLED_OPTIONAL_AUTOMATION_IDS, SYSTEM_AUTOMATION_IDS, recipes, reserved_ids,
    };

    let bundle = fixture("recipes.json");
    let system: Vec<&str> = bundle["tiers"]["system"]
        .as_array()
        .expect("the system tier")
        .iter()
        .map(|value| value.as_str().expect("an id"))
        .collect();
    assert_eq!(system, SYSTEM_AUTOMATION_IDS);
    let optional: Vec<&str> = bundle["tiers"]["bundled-optional"]
        .as_array()
        .expect("the optional tier")
        .iter()
        .map(|value| value.as_str().expect("an id"))
        .collect();
    assert_eq!(optional, BUNDLED_OPTIONAL_AUTOMATION_IDS);
    let reserved: Vec<&str> = bundle["reserved"]
        .as_array()
        .expect("the reservation set")
        .iter()
        .map(|value| value.as_str().expect("an id"))
        .collect();
    assert_eq!(reserved, reserved_ids());

    // Every capability the catalogue needs is pinned, and every pinned
    // capability is one the catalogue needs — so a recipe cannot ask for
    // weights nobody ships, and a 600 MB download cannot survive the recipe
    // that wanted it.
    let pinned: Vec<&str> = bundle["weights"]
        .as_array()
        .expect("the weights")
        .iter()
        .map(|entry| entry["capability"].as_str().expect("a capability"))
        .collect();
    assert_eq!(pinned, recipes::weights_capabilities());
    for entry in bundle["weights"].as_array().expect("the weights") {
        let bytes = entry["bytes"].as_u64().expect("a size");
        assert!(bytes > 0, "{entry}");
        let models = entry["models"].as_array().expect("models");
        assert_eq!(models.len(), 1, "one model id per capability: {entry}");
        let model = models[0].as_str().expect("a model id");
        let capability = entry["capability"].as_str().expect("a capability");
        // The stamp's model id is the lock's model id: a recipe that stamped
        // another name would re-derive the library on every boot.
        let recipe = recipes::CATALOGUE
            .iter()
            .find(|recipe| recipe.weights_capability == Some(capability));
        if let Some(recipe) = recipe {
            assert_eq!(recipe.model_id, Some(model), "{capability}");
        }
    }
}

/// The fixture's own epoch parser, held against the instants it must read.
#[test]
fn the_fixtures_instants_parse_the_way_the_generator_wrote_them() {
    assert_eq!(epoch_ms("1970-01-01T00:00:00.000Z"), 0);
    assert_eq!(epoch_ms("2026-01-01T00:00:00.000Z"), 1_767_225_600_000);
    assert_eq!(epoch_ms("2026-03-08T05:00:00.000Z"), 1_772_946_000_000);
    assert_eq!(epoch_ms("2026-11-01T04:00:00.000Z"), 1_793_505_600_000);
    assert_eq!(epoch_ms("2028-02-29T09:00:00.000Z"), 1_835_427_600_000);
    // And the round trip against the crate's own wall clock.
    let utc = FireZone::named("UTC").expect("bundled");
    let wall = utc.wall_clock(epoch_ms("2026-03-08T05:00:00.000Z"));
    assert_eq!((wall.year, wall.month, wall.day, wall.hour), (2026, 3, 8, 5));
}

/// `Notify`'s vocabulary is v0's, read from the fixture rather than retyped.
#[test]
fn the_notify_vocabulary_is_v0s() {
    let cases = fixture("manifests.json");
    let observed: std::collections::BTreeSet<&str> = cases
        .as_array()
        .expect("an array")
        .iter()
        .filter_map(|case| case["notify"].as_str())
        .collect();
    assert!(observed.contains("failures"), "{observed:?}");
    for value in observed {
        assert!(
            [
                Notify::Always.as_str(),
                Notify::Failures.as_str(),
                Notify::Never.as_str()
            ]
            .contains(&value),
            "{value} is not a notify class this crate carries"
        );
    }
}
