// Shell CSS lowering for the product-grammar registry.
//
// This is the only place that turns shared design values into a browser
// custom-property sheet.  It deliberately emits solved values and adapters;
// clients do not need a CSS parser or a second semantic vocabulary.

import { paletteText } from "./color";
import { spacing } from "./density";
import { library } from "./library";
import { palette } from "./palette";
import { radii } from "./radii";
import { emitRecipeCss } from "./recipes/css";
import { EASE, themes } from "./themes";
import type { Theme, ThemeName } from "./themes";
import {
  fontStacks,
  type,
  typeKeyToKebab,
  typeShorthand,
  typeSizeRungs,
} from "./typography";

function block(selector: string, props: Record<string, string>): string {
  const lines: string[] = [`${selector} {`];
  for (const [key, value] of Object.entries(props)) {
    lines.push(`  ${key}: ${value};`);
  }
  lines.push("}");
  return lines.join("\n");
}

function themeProps(theme: Theme): Record<string, string> {
  const out: Record<string, string> = {
    "--accent": theme.accent,
    "--accent-deep": theme.accentDeep,
    "--accent-fill": theme.accentDeep,
    "--accent-deep-hover": `color-mix(in oklab, ${theme.accentDeep} 88%, ${theme.text} 12%)`,
    "--accent-light": theme.accentLight,
    "--accent-soft": `color-mix(in oklab, ${theme.accent} 12%, transparent)`,
    "--accent-text": theme.accentText,
    "--app-identity-text": paletteText[theme.kind].teal,
    "--bg": theme.bg,
    "--bg-app": theme.bgApp,
    "--bg-chrome": theme.sidebarBg,
    "--bg-elev": theme.bgElev,
    "--bg-hud": theme.sidebarBg,
    "--bg-hover": `color-mix(in oklab, ${theme.text} 5%, transparent)`,
    "--bg-press": `color-mix(in oklab, ${theme.text} 9%, transparent)`,
    "--bg-sel": "color-mix(in oklab, var(--accent) 12%, transparent)",
    "--bg-sunken": theme.bgSunken,
    "--bg-wall": theme.bgWall,
    "--danger": theme.danger,
    "--device-wall": theme.deviceWall,
    "--glass-film": theme.sidebarBg,
    "--glass-sheen": theme.sidebarBlur,
    "--focus-ring": "0 0 0 2px var(--accent-soft), 0 0 0 1px var(--accent)",
    "--focus-ring-color": theme.accent,
    "--line": theme.line,
    "--line-strong": theme.lineStrong,
    "--line-sel": "color-mix(in oklab, var(--accent) 42%, var(--line))",
    "--on-accent": "#141820",
    "--scrim": theme.scrim,
    "--shadow-lg": theme.shadowLg,
    "--shadow-md": theme.shadowMd,
    "--shadow-sm": theme.shadowSm,
    "--success": theme.success,
    "--text": theme.text,
    "--text-faint": theme.textFaint,
    "--text-ghost": theme.textGhost,
    "--text-inv": theme.textInv,
    "--text-disabled": `color-mix(in oklab, ${theme.text} 36%, ${theme.bg})`,
    "--text-soft": theme.textSoft,
    "--warning": theme.warning,
  };
  if (theme.bgL !== undefined) out["--bg-l"] = theme.bgL;
  for (const [key, value] of Object.entries(paletteText[theme.kind])) {
    out[`--c-${key}-text`] = value;
  }
  return out;
}

export function toCss(): string {
  const staticProps: Record<string, string> = {};
  for (const [key, value] of Object.entries(palette))
    staticProps[`--c-${key}`] = value;
  for (const [key, value] of Object.entries(radii))
    staticProps[`--r-${key}`] = `${value}px`;
  for (const [key, value] of Object.entries(spacing))
    staticProps[`--sp-${key}`] = `${value}px`;

  staticProps["--ease"] = EASE;
  staticProps["--target-min"] = "44px";
  staticProps["--o-disabled"] = "0.45";
  staticProps["--dur-1"] = "120ms";
  staticProps["--dur-2"] = "200ms";
  for (const [key, value] of Object.entries(fontStacks))
    staticProps[`--font-${key}`] = value;
  for (const [key, value] of Object.entries(type)) {
    staticProps[`--t-${typeKeyToKebab(key)}`] = typeShorthand(value);
  }
  Object.assign(staticProps, typeSizeRungs(type));

  // Library became a tile recipe.  The values stay shared between Home and
  // Discover, but the semantic namespace no longer suggests a separate UI.
  for (const [key, value] of Object.entries(library)) {
    const suffix = key.startsWith("tile-") ? key.slice("tile-".length) : key;
    staticProps[`--tile-${suffix}`] = value;
  }

  const blocks = [
    "/* Generated by @centraid/design — do not edit by hand. */",
    block(":root", { ...staticProps, ...themeProps(themes.light) }),
    emitRecipeCss(":root"),
    "@media (pointer: fine) { :root { --target-min: 32px; } }",
  ];
  for (const name of Object.keys(themes) as ThemeName[]) {
    blocks.push(block(`[data-theme='${name}']`, themeProps(themes[name])));
  }
  return `${blocks.join("\n\n")}\n`;
}
