// Centraid — CSS generator.
// `toCss()` walks the typed tokens (themes, densities, palette, radii) and
// emits the entire `:root` + `[data-theme='dark']` + density-override
// blocks as a single CSS string. Desktop injects this into a <style> tag
// at preload time — the only token-related CSS it ships.

import { paletteText } from "./color";
import { spacing } from "./density";
import { library } from "./library";
import { palette } from "./palette";
import { radii } from "./radii";
import { BRAND, EASE, ON_ACCENT, themes } from "./themes";
import type { Theme, ThemeName } from "./themes";
import { fontStacks, marketingType, type, typeShorthand } from "./typography";

function block(selector: string, props: Record<string, string>): string {
  const lines: string[] = [`${selector} {`];
  for (const [k, v] of Object.entries(props)) {
    lines.push(`  ${k}: ${v};`);
  }
  lines.push("}");
  return lines.join("\n");
}

function themeProps(t: Theme): Record<string, string> {
  const out: Record<string, string> = {
    "--accent": t.accent,
    "--accent-deep": t.accentDeep,
    "--accent-light": t.accentLight,
    "--accent-midnight": t.accentMidnight,
    "--accent-text": t.accentText,
    "--danger": t.danger,
    "--success": t.success,
    "--warning": t.warning,
  };
  // --bg-l must precede --bg/--bg-elev/--bg-sunken/--bg-app on dark, since
  // those reference it via var(). Light theme omits it entirely.
  if (t.bgL !== undefined) out["--bg-l"] = t.bgL;
  Object.assign(out, {
    "--bezel": t.bezel,
    "--bezel-inner": t.bezelInner,
    "--bg": t.bg,
    "--bg-app": t.bgApp,
    "--bg-elev": t.bgElev,
    "--bg-sunken": t.bgSunken,
    "--bg-wall": t.bgWall,
    "--device-wall": t.deviceWall,
    "--text": t.text,
    "--text-soft": t.textSoft,
    "--text-faint": t.textFaint,
    "--text-ghost": t.textGhost,
    "--text-inv": t.textInv,
    "--line": t.line,
    "--line-strong": t.lineStrong,
    "--scrim": t.scrim,
    "--shadow-lg": t.shadowLg,
    "--shadow-md": t.shadowMd,
    "--shadow-sm": t.shadowSm,
    "--sidebar-bg": t.sidebarBg,
    "--sidebar-blur": t.sidebarBlur,
    "--sidebar-divider": t.sidebarDivider,
  });
  // The palette hues as TEXT. The `--c-*` hues themselves are icon fills and
  // are theme-independent; this solved rung is not — it deepens on light and
  // lifts on dark, so it belongs to the theme block rather than the static one.
  for (const [k, v] of Object.entries(paletteText[t.kind]))
    out[`--c-${k}-text`] = v;
  return out;
}

/**
 * Returns the full token CSS string. Stable order: static (palette, radii,
 * default density) → light theme → dark theme → density overrides.
 */
export function toCss(): string {
  const staticProps: Record<string, string> = {};
  // App-icon palette has one canonical `--c-<hue>` spelling.
  for (const [k, v] of Object.entries(palette)) {
    staticProps[`--c-${k}`] = v;
  }
  for (const [k, v] of Object.entries(radii))
    staticProps[`--r-${k}`] = `${v}px`;
  // Fixed spacing scale (density.ts) — the only rungs any surface may use.
  for (const [k, v] of Object.entries(spacing))
    staticProps[`--sp-${k}`] = `${v}px`;
  // The one easing curve — same value the blueprint layer publishes.
  staticProps["--ease"] = EASE;
  // Brand teal — theme-independent, matches the logo / app-icon SVGs.
  staticProps["--brand"] = BRAND;
  // Ink for a saturated-accent or scrim surface. Theme-independent for the
  // same reason `--brand` is: the surfaces it lands on (a photo, a 52% scrim,
  // an `--accent` badge) are dark in both themes. The ink for `--accent-deep`
  // is `--text-inv`, which DOES flip — see themes/shared.ts.
  staticProps["--on-accent"] = ON_ACCENT;
  // Typography — web font stacks + the semantic type scale as CSS `font`
  // shorthands (`font: var(--t-title)`). camelCase keys emit kebab-case
  // (`bodyStrong` → `--t-body-strong`, `display1` → `--t-display-1`).
  for (const [k, v] of Object.entries(fontStacks))
    staticProps[`--font-${k}`] = v;
  for (const [k, v] of Object.entries({ ...type, ...marketingType })) {
    const kebab = k
      .replace(/(?<lower>[a-z])(?<upper>[A-Z])/gu, "$<lower>-$<upper>")
      .toLowerCase();
    staticProps[`--t-${kebab}`] = typeShorthand(v);
  }
  // Shared library-tile tokens (Home + Discover render the same tile).
  for (const [k, v] of Object.entries(library)) staticProps[`--lib-${k}`] = v;

  const blocks = [
    "/* Generated by @centraid/design — do not edit by hand. */",
    block(":root", { ...staticProps, ...themeProps(themes.light) }),
  ];

  // One block per registered theme — picker selections write the matching
  // `data-theme` attribute on <html> and the right block wins.
  for (const name of Object.keys(themes) as ThemeName[]) {
    blocks.push(block(`[data-theme='${name}']`, themeProps(themes[name])));
  }

  return blocks.join("\n\n") + "\n";
}
