import { describe, expect, test } from "vitest";

import { toCss } from "./css.js";
import { palette } from "./palette.js";
import { radii } from "./radii.js";
import { themes } from "./themes/index.js";

const css = toCss();

function blockFor(selector: string): string {
  const start = css.indexOf(`${selector} {`);
  expect(start, `no block for ${selector}`).toBeGreaterThanOrEqual(0);
  return css.slice(start, css.indexOf("\n}", start));
}

describe("shell CSS lowering", () => {
  test("emits the palette, radii and product accent under canonical names", () => {
    const root = blockFor(":root");
    for (const [key, value] of Object.entries(palette)) {
      expect(root).toContain(`--c-${key}: ${value};`);
    }
    for (const [key, value] of Object.entries(radii)) {
      expect(root).toContain(`--r-${key}: ${value}px;`);
    }
    expect(root).toContain("--accent: #3EC8B4;");
    expect(root).toContain("--target-min: 44px;");
  });

  test("emits lower-case role names and no retired aliases", () => {
    const root = blockFor(":root");
    expect(root).toContain("--t-body-strong:");
    expect(root).toContain("--t-small-strong:");
    expect(root).not.toMatch(/--t-[a-z-]*[A-Z]/u);
    expect(root).not.toMatch(/--brand\b|--font-title\b|--mono\b|--lib-/u);
  });

  test("emits each theme and a single neutral dark anchor", () => {
    for (const name of Object.keys(themes)) {
      expect(css).toContain(`[data-theme='${name}'] {`);
    }
    const dark = blockFor("[data-theme='dark']");
    expect(dark).toContain("--bg: hsl(0 0% var(--bg-l));");
    expect(dark).toContain("--bg-l: 5%;");
    expect(dark).not.toMatch(/hsl\(\d+\s+(?!0%)/u);
  });

  test("is a balanced generated stylesheet", () => {
    expect(css.startsWith("/* Generated by @centraid/design")).toBe(true);
    expect(css.endsWith("\n")).toBe(true);
    expect(css.split("{")).toHaveLength(css.split("}").length);
  });
});
