// The bundled faces are only a design decision while the bytes are actually
// present and actually the ones the lockfile pins. A missing file does not
// throw anywhere — the browser silently falls through the stack — so this is
// the only place the vendoring can be checked.

import { existsSync, readFileSync } from "node:fs";
import path from "node:path";

import { describe, expect, it } from "vitest";

import { FONT_FILES, FONT_SUBSET_RANGE, toFontFaceCss } from "./font-faces.js";
import { FONTS_DIR, fontFilePath, fontSourceFile } from "./fonts.js";
import { fonts } from "./typography.js";

describe("bundled font seam", () => {
  it("exports an absolute path to the on-disk font layer", () => {
    expect(path.isAbsolute(FONTS_DIR)).toBe(true);
    expect(path.basename(FONTS_DIR)).toBe("fonts");
  });

  it("ships every declared file, in both subsets", () => {
    expect(FONT_FILES).toHaveLength(4);
    for (const file of FONT_FILES) {
      expect(existsSync(fontFilePath(file)), file.fileName).toBe(true);
      expect(readFileSync(fontFilePath(file)).byteLength).toBeGreaterThan(1000);
    }
    expect([
      ...new Set(
        FONT_FILES.filter((f) => f.weight === 600).map((f) => f.genus)
      ),
    ]).toStrictEqual(["sans"]);
  });

  it("vendors no bytes for the platform code stack", () => {
    // `mono` is a family the stacks name, not a face this package ships. If a
    // file ever appears for it, the two-download win has been quietly undone.
    expect(FONT_FILES.some((f) => (f.genus as string) === "mono")).toBe(false);
    expect(
      existsSync(path.join(FONTS_DIR, "dm-mono-latin-400-normal.woff2"))
    ).toBe(false);
  });

  it("keeps the vendored bytes identical to the pinned @fontsource copy", () => {
    for (const file of FONT_FILES) {
      const vendored = readFileSync(fontFilePath(file));
      const upstream = readFileSync(fontSourceFile(file));
      expect(vendored.equals(upstream), file.fileName).toBe(true);
    }
  });

  it("names the one bundled face the type scale declares", () => {
    expect([...new Set(FONT_FILES.map((f) => f.family))].sort()).toStrictEqual(
      Object.values(fonts).sort()
    );
  });

  it("emits self-hosted @font-face rules with no network reference", () => {
    const css = toFontFaceCss("/centraid/fonts/");
    expect(css.startsWith("/* Generated by @centraid/design")).toBe(true);
    expect(css.endsWith("\n")).toBe(true);
    expect(css.split("@font-face")).toHaveLength(FONT_FILES.length + 1);
    for (const file of FONT_FILES) {
      expect(css).toContain(
        `src: url(/centraid/fonts/${file.fileName}) format('woff2');`
      );
    }
    // A CDN reference is the whole failure this bundling exists to prevent.
    expect(css).not.toMatch(/https?:\/\//u);
    expect(css).toContain(FONT_SUBSET_RANGE.latin);
    expect(css).toContain(FONT_SUBSET_RANGE["latin-ext"]);
  });

  // Electron's preload runs in the SANDBOXED renderer, where `node:path` does
  // not resolve. When `toFontFaceCss` shared a module with `FONTS_DIR`, the
  // desktop preload pulled `require("node:path")` into its bundle, failed to
  // load, and took the entire app down — no tokens, no icons, no IPC bridge
  // (issue #707). Nothing in the type layer prevents that regression; the file
  // boundary is the only thing that does, so it is asserted here.
  it("the browser-safe font module reaches for no node builtin", () => {
    const source = readFileSync(
      path.join(import.meta.dirname, "font-faces.ts"),
      "utf8"
    );
    const code = source.replaceAll(/\/\/.*$/gmu, "");
    expect(code).not.toMatch(/\bfrom\s+["']node:/u);
    expect(code).not.toMatch(/\brequire\s*\(/u);
    expect(code).not.toMatch(/\b__dirname\b/u);
  });
});
