// The bundled faces are only a design decision while the bytes are actually
// present and actually the ones the lockfile pins. A missing file does not
// throw anywhere — the browser silently falls through the stack — so this is
// the only place the vendoring can be checked.

import { existsSync, readFileSync } from "node:fs";
import path from "node:path";

import { describe, expect, it } from "vitest";

import {
  FONT_FILES,
  FONT_SUBSET_RANGE,
  FONTS_DIR,
  fontFilePath,
  fontSourceFile,
  toFontFaceCss,
} from "./fonts.js";
import { fonts } from "./typography.js";

describe("bundled font seam", () => {
  it("exports an absolute path to the on-disk font layer", () => {
    expect(path.isAbsolute(FONTS_DIR)).toBe(true);
    expect(path.basename(FONTS_DIR)).toBe("fonts");
  });

  it("ships every declared file, in both subsets", () => {
    expect(FONT_FILES).toHaveLength(10);
    for (const file of FONT_FILES) {
      expect(existsSync(fontFilePath(file)), file.fileName).toBe(true);
      expect(readFileSync(fontFilePath(file)).byteLength).toBeGreaterThan(1000);
    }
    // Only the sans carries the ramp's second weight; the display serif, the
    // reading serif and the mono are 400-only roles.
    expect([
      ...new Set(
        FONT_FILES.filter((f) => f.weight === 500).map((f) => f.genus)
      ),
    ]).toStrictEqual(["sans"]);
  });

  it("keeps the vendored bytes identical to the pinned @fontsource copy", () => {
    for (const file of FONT_FILES) {
      const vendored = readFileSync(fontFilePath(file));
      const upstream = readFileSync(fontSourceFile(file));
      expect(vendored.equals(upstream), file.fileName).toBe(true);
    }
  });

  it("names the four genus faces the type scale declares", () => {
    expect([...new Set(FONT_FILES.map((f) => f.family))].sort()).toStrictEqual(
      Object.values(fonts).sort()
    );
  });

  it("emits self-hosted @font-face rules with no network reference", () => {
    const css = toFontFaceCss("/centraid/fonts/");
    expect(css.startsWith("/* Generated by @centraid/design")).toBe(true);
    expect(css.endsWith("\n")).toBe(true);
    expect(css.split("@font-face")).toHaveLength(FONT_FILES.length + 1);
    for (const file of FONT_FILES) {
      expect(css).toContain(
        `src: url(/centraid/fonts/${file.fileName}) format('woff2');`
      );
    }
    // A CDN reference is the whole failure this bundling exists to prevent.
    expect(css).not.toMatch(/https?:\/\//u);
    expect(css).toContain(FONT_SUBSET_RANGE.latin);
    expect(css).toContain(FONT_SUBSET_RANGE["latin-ext"]);
  });
});
