import { fonts } from "./typography";
import type { BundledFace } from "./typography";

const FONT_SLUG = {
  sans: "instrument-sans",
} as const satisfies Record<BundledFace, string>;

export type FontSubset = "latin" | "latin-ext";

export const FONT_SUBSET_RANGE = {
  latin:
    "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
  "latin-ext":
    "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF",
} as const satisfies Record<FontSubset, string>;

export interface FontFile {
  genus: BundledFace;
  family: string;
  weight: 400 | 600;
  subset: FontSubset;
  fileName: string;
}

export const FONT_FILES: readonly FontFile[] = (
  [
    ["sans", 400],
    ["sans", 600],
  ] as const
).flatMap(([genus, weight]) =>
  (["latin", "latin-ext"] as const).map((subset) => ({
    family: fonts[genus],
    fileName: `${FONT_SLUG[genus]}-${subset}-${weight}-normal.woff2`,
    genus,
    subset,
    weight,
  }))
);

export function toFontFaceCss(baseUrl: string): string {
  const base = baseUrl.replace(/\/+$/u, "");
  const lines = ["/* Generated by @centraid/design — do not edit by hand. */"];
  for (const file of FONT_FILES) {
    lines.push(
      "@font-face {",
      `  font-family: '${file.family}';`,
      "  font-style: normal;",
      "  font-display: swap;",
      `  font-weight: ${file.weight};`,
      `  src: url(${base}/${file.fileName}) format('woff2');`,
      `  unicode-range: ${FONT_SUBSET_RANGE[file.subset]};`,
      "}"
    );
  }
  return `${lines.join("\n")}\n`;
}
