// Centraid — the bundled face, described without touching a filesystem.
//
// This is the half of the font seam a BROWSER may hold. `fonts.ts` owns the
// other half: where the `.woff2` bytes live on disk, which needs `node:path`
// and `require.resolve`.
//
// The split is structural, not stylistic. Electron's preload runs in the
// sandboxed renderer, where `require("node:path")` does not resolve — a single
// module carrying both halves takes the whole preload down with it, and with
// the preload goes the entire desktop app (#707). A build-time-only
// consumer can reach past this into `./fonts`; anything that ships to a
// browser, a renderer, or an app surface behind a strict CSP imports HERE.

import { fonts } from "./typography";
import type { BundledFace } from "./typography";

/** Filename stem of each vendored face, matching the upstream convention.
 *  Only the one BUNDLED face appears: `code` is the platform code stack and
 *  ships no bytes, so it has no slug and no `@font-face` rule. */
const FONT_SLUG = {
  sans: "instrument-sans",
} as const satisfies Record<BundledFace, string>;

export type FontSubset = "latin" | "latin-ext";

/**
 * The Unicode coverage of each subset, copied from the upstream `unicode.json`
 * so a browser downloads `latin-ext` only when a page actually needs it.
 */
export const FONT_SUBSET_RANGE = {
  latin:
    "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
  "latin-ext":
    "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF",
} as const satisfies Record<FontSubset, string>;

export interface FontFile {
  /** The type-scale genus this file serves (`--font-<genus>`). */
  genus: BundledFace;
  /** The CSS `font-family` name, as the type scale spells it. */
  family: string;
  weight: 400 | 600;
  subset: FontSubset;
  /** File name inside `FONTS_DIR`. */
  fileName: string;
}

/**
 * Every vendored file, and only those. The one face carries the ramp's two
 * weights. Code uses the platform stack and ships no bytes.
 */
export const FONT_FILES: readonly FontFile[] = (
  [
    ["sans", 400],
    ["sans", 600],
  ] as const
).flatMap(([genus, weight]) =>
  (["latin", "latin-ext"] as const).map((subset) => ({
    family: fonts[genus],
    fileName: `${FONT_SLUG[genus]}-${subset}-${weight}-normal.woff2`,
    genus,
    subset,
    weight,
  }))
);

/**
 * The `@font-face` block for the bundled faces, pointing at `baseUrl`.
 *
 * `font-display: swap` is deliberate: the fallback stacks in `fontStacks`
 * carry the CJK coverage neither bundled face has, so a blocking swap period
 * would show nothing at all to the readers who need the fallback most.
 */
export function toFontFaceCss(baseUrl: string): string {
  const base = baseUrl.replace(/\/+$/u, "");
  const lines = ["/* Generated by @centraid/design — do not edit by hand. */"];
  for (const file of FONT_FILES) {
    lines.push(
      "@font-face {",
      `  font-family: '${file.family}';`,
      "  font-style: normal;",
      "  font-display: swap;",
      `  font-weight: ${file.weight};`,
      `  src: url(${base}/${file.fileName}) format('woff2');`,
      `  unicode-range: ${FONT_SUBSET_RANGE[file.subset]};`,
      "}"
    );
  }
  return `${lines.join("\n")}\n`;
}
