/*
 * Publish-time token-purity gate for authored app CSS (issue #686, item D3).
 *
 * Agent-authored apps were grounded on the design token contract by prompt
 * alone (`src/skills/ui-grounding.ts` tells the model "never write #hexcodes or
 * rgb() literals"), and nothing checked what the model actually wrote. Checked-in
 * blueprint apps have a vitest ratchet; runtime-authored apps had nothing.
 *
 * This module walks an app dir's `.css` files and runs app-engine's pure
 * {@link scanCssTokenPurity} over each, wired into `validateManifestAt` so a
 * violating stylesheet fails the publish exactly like a malformed `app.json`
 * or a replay-unsafe automation handler — a 400 with an actionable message the
 * authoring agent reads and can fix. Nothing re-validates already-installed
 * apps: this runs only when a draft goes live, and bundled blueprint apps are
 * installed in place (issue #434) without passing through this gate.
 */

import { promises as fs } from "node:fs";
import path from "node:path";

import {
  formatTokenPurityError,
  scanCssTokenPurity,
} from "@centraid/app-engine";
import { BLUEPRINT_TOKEN_CONTRACT } from "@centraid/design";

/** Marker line `toBlueprintCss()` stamps at the top of its emit. */
const GENERATED_MARKER = "Generated by @centraid/design";

/**
 * Dirs that never hold authored app CSS. `node_modules` is vendored code, and
 * the git store's own metadata is not app content.
 */
const SKIPPED_DIRS = new Set(["node_modules", ".git", "dist"]);

/**
 * Files that are design-system artifacts served to the app rather than
 * authored by it. `kit.css` is `packages/design`'s component substrate — apps
 * normally don't carry a copy at all (the runtime serves it from KIT_DIR), and
 * a vendored copy is still not the app's code to police.
 */
const SKIPPED_FILES = new Set(["kit.css"]);

/** Recursively list `*.css` files under `dir`, app-relative and posix-joined. */
async function listCssFiles(dir: string, rel = ""): Promise<string[]> {
  let entries;
  try {
    entries = await fs.readdir(path.join(dir, rel), { withFileTypes: true });
  } catch {
    return [];
  }
  const here: string[] = [];
  const descend: Promise<string[]>[] = [];
  for (const entry of entries) {
    const childRel = rel ? `${rel}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      if (!SKIPPED_DIRS.has(entry.name))
        descend.push(listCssFiles(dir, childRel));
    } else if (entry.name.endsWith(".css") && !SKIPPED_FILES.has(entry.name)) {
      here.push(childRel);
    }
  }
  const nested = await Promise.all(descend);
  return [...here, ...nested.flat()].sort();
}

/** Index just past the `}` matching the `{` at `open`, or -1 when unbalanced. */
function matchBrace(css: string, open: number): number {
  let depth = 0;
  for (let i = open; i < css.length; i += 1) {
    if (css[i] === "{") depth += 1;
    else if (css[i] === "}") {
      depth -= 1;
      if (depth === 0) return i + 1;
    }
  }
  return -1;
}

/**
 * True when a block body contains only custom-property declarations (or nested
 * blocks that do) — i.e. it is a token block, not authored styling.
 */
function isTokenOnlyBlock(body: string): boolean {
  let rest = body;
  let hadNested = false;
  // Peel nested blocks (the dark-theme `@media` wrapper) and recurse.
  for (;;) {
    const open = rest.indexOf("{");
    if (open === -1) break;
    const end = matchBrace(rest, open);
    if (end === -1) return false;
    if (!isTokenOnlyBlock(rest.slice(open + 1, end - 1))) return false;
    hadNested = true;
    rest = rest.slice(0, open) + rest.slice(end);
  }
  // What's left of an at-rule wrapper is the nested rules' selectors, not
  // declarations — every nested block was already checked above.
  if (hadNested) return true;
  return rest
    .split(";")
    .map((decl) => decl.trim())
    .filter((decl) => decl !== "")
    .every((decl) => decl.startsWith("--"));
}

/**
 * Blank out the generated token baseline `scaffoldAppFiles` prepends to
 * `app.css`, so the design package's own emit is not reported as the app's
 * violations. Deliberately structural rather than a byte-compare against the
 * current `toBlueprintCss()`: an app scaffolded against an older design
 * version must not suddenly fail its next publish.
 *
 * Only a *leading* run of token-only blocks introduced by the generation
 * marker is stripped, and stripped bytes are replaced by newlines so line
 * numbers in findings still point at the real file.
 */
export function stripGeneratedTokenBaseline(source: string): string {
  const marker = source.indexOf(GENERATED_MARKER);
  // The marker must sit in the file's leading comment, not somewhere an app
  // pasted it later.
  if (marker === -1 || marker > 200) return source;
  let cursor = source.indexOf("*/", marker);
  if (cursor === -1) return source;
  cursor += 2;
  for (;;) {
    const open = source.indexOf("{", cursor);
    if (open === -1) break;
    const end = matchBrace(source, open);
    if (end === -1) break;
    if (!isTokenOnlyBlock(source.slice(open + 1, end - 1))) break;
    cursor = end;
  }
  const head = source.slice(0, cursor);
  return "\n".repeat((head.match(/\n/gu) ?? []).length) + source.slice(cursor);
}

/**
 * Scan every authored stylesheet in `appDir`. Returns the first offending
 * file's formatted error, or `undefined` when the app is token-pure.
 */
export async function validateAppCssAt(
  appDir: string
): Promise<string | undefined> {
  const rels = await listCssFiles(appDir);
  const sources = await Promise.all(
    rels.map(async (rel) => {
      try {
        return await fs.readFile(path.join(appDir, rel), "utf8");
      } catch {
        return ""; // vanished between listing and reading — not this gate's problem
      }
    })
  );
  for (const [index, rel] of rels.entries()) {
    const findings = scanCssTokenPurity(
      stripGeneratedTokenBaseline(sources[index] ?? ""),
      { contractProps: BLUEPRINT_TOKEN_CONTRACT }
    );
    const error = formatTokenPurityError(findings, rel);
    if (error) return error;
  }
  return undefined;
}
