// Copies the lockfile-pinned PDF.js browser runtime into the canonical shared
// kit directory. Apps are build-free browser modules, so they cannot import
// the npm package's bare specifier directly; the app engine serves these two
// generated files through the same root-level fallback as kit.js and React.
//
// The generated bytes are gitignored, not opaque checked-in blobs. Rebuild:
//
//   bun --cwd packages/blueprints run vendor:pdfjs

// `build`, `build:manifest`, and `test` invoke this automatically.

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const PACKAGE_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const KIT_ROOT = path.join(PACKAGE_ROOT, 'kit');
const OUT_FILES = ['pdf.min.mjs', 'pdf.worker.min.mjs'];

function resolvePdfjsRoot() {
  // Prefer Node/bun module resolution (hoisted or package-local) over a fixed
  // monorepo-root path — Docker/workspace layouts differ.
  const require = createRequire(import.meta.url);
  try {
    return path.dirname(require.resolve('pdfjs-dist/package.json'));
  } catch {
    // fall through
  }
  const candidates = [
    path.join(PACKAGE_ROOT, 'node_modules/pdfjs-dist'),
    path.join(PACKAGE_ROOT, '../../node_modules/pdfjs-dist'),
  ];
  for (const c of candidates) {
    if (existsSync(path.join(c, 'package.json'))) return c;
  }
  return null;
}

const PDFJS_ROOT = resolvePdfjsRoot();
const kitPresent = OUT_FILES.every((f) => existsSync(path.join(KIT_ROOT, f)));

if (!PDFJS_ROOT) {
  if (kitPresent) {
    // Host already vendored kit (gitignored but present in Docker context).
    console.log(`pdfjs-dist not installed; reusing existing kit files in ${KIT_ROOT}`);
    process.exit(0);
  }
  throw new Error(
    'pdfjs-dist not found (devDependency of @centraid/blueprints). Run bun install at the monorepo root.',
  );
}

const version = JSON.parse(readFileSync(path.join(PDFJS_ROOT, 'package.json'), 'utf8')).version;

// PDF.js 5 uses the new Uint8Array base64/hex helpers and Promise.try. Current
// Chromium/Node releases have them, but the v0 web shell can outlive a browser
// release and the Node 20 CI realm has no Promise.try. Prepending this tiny
// standards-compatible bridge to both realms keeps the generated display and
// Worker builds honest.
const compatibilityBridge = `(()=>{const p=Uint8Array.prototype;
if(!p.toHex)Object.defineProperty(p,"toHex",{value:function(){let s="";for(const b of this)s+=b.toString(16).padStart(2,"0");return s}});
if(!p.toBase64)Object.defineProperty(p,"toBase64",{value:function(){let s="";for(let i=0;i<this.length;i+=32768)s+=String.fromCharCode(...this.subarray(i,i+32768));return btoa(s)}});
if(!Uint8Array.fromBase64)Object.defineProperty(Uint8Array,"fromBase64",{value:function(v){const s=atob(v);return Uint8Array.from(s,c=>c.charCodeAt(0))}});
if(!Promise.try)Object.defineProperty(Promise,"try",{configurable:true,writable:true,value:function(fn,...args){return new this(resolve=>resolve(fn(...args)))}});
})();\n`;
const banner = `// Generated from pdfjs-dist@${version} by scripts/vendor-pdfjs.mjs; do not edit.\n`;

for (const file of OUT_FILES) {
  const source = readFileSync(path.join(PDFJS_ROOT, 'build', file), 'utf8');
  writeFileSync(path.join(KIT_ROOT, file), banner + compatibilityBridge + source);
}

console.log(`Copied PDF.js ${version} display + worker builds into ${KIT_ROOT}`);
