// Regenerates `kit/react-core.min.js` — the runtime-only React bundle the kit
// serves so builder-generated apps can be written in React with NO build
// step. The kit is served as-is, so it needs React as a
// single self-contained, browser-loadable ESM file rather than the npm
// packages' bare-specifier module graph (`react`, `react-dom/client`,
// `react-dom`, `react/jsx-runtime` all resolve to separate CJS files that
// branch on `process.env.NODE_ENV` internally). This script bundles exactly
// the entry points the kit's JSX runtime and apps need out of the
// workspace-pinned `react` / `react-dom` devDependencies (see
// packages/blueprints/package.json), in production mode (dev-mode warnings
// stripped by dead-code elimination once `process.env.NODE_ENV` is inlined —
// React's package.json has no dedicated "production" export
// condition, so the NODE_ENV env var at build time is what actually matters).
// Run it after bumping the `react` / `react-dom` versions:
//
//   node packages/blueprints/scripts/vendor-react.mjs
//
// Provenance: the output is derived solely from the lockfile-pinned `react` +
// `react-dom` packages — never fetched from a CDN — so `bun install` + this
// script fully reproduce it.
import { execFileSync } from 'node:child_process';
import { mkdtempSync, writeFileSync, readFileSync, rmSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const KIT_DIR = path.resolve(fileURLToPath(import.meta.url), '../../kit');
const OUT = path.join(KIT_DIR, 'react-core.min.js');
const WORKSPACE_NODE_MODULES = path.resolve(KIT_DIR, '../../..', 'node_modules');
const reactVersion = JSON.parse(
  readFileSync(path.join(WORKSPACE_NODE_MODULES, 'react/package.json'), 'utf8'),
).version;
const reactDomVersion = JSON.parse(
  readFileSync(path.join(WORKSPACE_NODE_MODULES, 'react-dom/package.json'), 'utf8'),
).version;

// Bun resolves bare specifiers against the workspace node_modules; the entry
// must live inside the repo tree for that resolution to work.
const scratch = mkdtempSync(path.join(KIT_DIR, '.vendor-react-'));
const entry = path.join(scratch, 'entry.js');
writeFileSync(
  entry,
  [
    // Everything an app or the kit's JSX runtime could need from React
    // itself: hooks, Fragment, createElement, createContext, StrictMode, etc.
    "export * from 'react';",
    // The client render entrypoint apps mount into a container with.
    "export { createRoot } from 'react-dom/client';",
    // Synchronous flush — used by the smoke test and by any app that needs
    // a commit to land before reading the DOM back out (event handlers).
    "export { flushSync } from 'react-dom';",
    // The automatic-JSX-transform runtime. `kit/jsx-runtime.js` re-exports
    // these two (plus `Fragment` from the `export *` above) so esbuild's
    // `jsx: 'automatic', jsxImportSource: '.'` output — which imports
    // `./jsx-runtime` — resolves to this single bundled React instance.
    "export { jsx, jsxs } from 'react/jsx-runtime';",
    '',
  ].join('\n'),
);

try {
  execFileSync(
    'bun',
    ['build', entry, '--minify', '--format=esm', '--conditions=production', `--outfile=${OUT}`],
    { stdio: 'inherit', env: { ...process.env, NODE_ENV: 'production' } },
  );
} finally {
  rmSync(scratch, { recursive: true, force: true });
}

const banner =
  `// governance: allow-repo-hygiene file-size-limit (#363) vendored, regenerated by this script — see the header below\n` +
  `/*! React ${reactVersion} + ReactDOM ${reactDomVersion} — vendored runtime bundle for the\n` +
  ` * Centraid blueprint kit. Self-contained ESM (all of \`react\`'s exports,\n` +
  ` * createRoot, flushSync, jsx, jsxs), production build (dev-mode warnings\n` +
  ` * stripped).\n` +
  ` * Do NOT hand-edit: regenerate with \`node packages/blueprints/scripts/vendor-react.mjs\`.\n` +
  ` * Upstream: react@${reactVersion} + react-dom@${reactDomVersion} (MIT, Meta Platforms, Inc.). */\n`;
writeFileSync(OUT, banner + readFileSync(OUT, 'utf8'));

console.log(`Wrote ${OUT} from react@${reactVersion} + react-dom@${reactDomVersion}`);
