// Regenerates `kit/tokens.css` — the blueprint-app token layer, generated
// from `@centraid/design-tokens`'s `toBlueprintCss()` (the formal source for
// the apps' "field notebook" design language: hue-tinted neutrals, system
// font stacks, the shared light/dark recipe). Also copies
// `packages/design-tokens/wall.css` → `kit/wall.css` byte-verbatim, so the
// kit can serve both as shared assets (see SHARED_ASSET_FILES in
// packages/app-engine/src/http/static-server.ts) the same way it already
// serves kit.js/kit.css/elements.js/react-core.min.js
// (vendor-react.mjs). An app folder with its own local copy
// of either file still wins over the shared one (app-folder precedence in
// serveStatic) — this is what preserves e.g. apps/people/wall.css's
// deliberate light-branch override.
//
// Run it after any edit to packages/design-tokens/src/blueprint.ts (or
// packages/design-tokens/wall.css):
//
//   bun scripts/vendor-tokens.mjs
//
// `--check` verifies kit/tokens.css and kit/wall.css already match what this
// script would generate, without writing anything — exits 1 (with a
// diff-ish message) if either file is stale. Used by
// packages/blueprints/src/tokens-sync.test.ts as a CI gate against a
// design-tokens edit that forgot to re-vendor.
//
// This script does NOT rebuild `@centraid/design-tokens` itself — it reads
// whatever `dist/index.js` is already there (run `bun run build` in
// packages/design-tokens first, same as any other workspace consumer of that
// package). Deliberately no side-effecting rebuild here: this script (via
// its `--check` mode) runs inside the blueprints vitest suite alongside
// other tests that import `@centraid/design-tokens` at the same time, and an
// `rm -rf dist` partway through a parallel test run raced those imports.
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const KIT_DIR = path.resolve(fileURLToPath(import.meta.url), '../../kit');
const DESIGN_TOKENS_DIR = path.resolve(KIT_DIR, '../../design-tokens');
const TOKENS_OUT = path.join(KIT_DIR, 'tokens.css');
const WALL_SRC = path.join(DESIGN_TOKENS_DIR, 'wall.css');
const WALL_OUT = path.join(KIT_DIR, 'wall.css');

const { toBlueprintCss } = await import(path.join(DESIGN_TOKENS_DIR, 'dist/index.js'));

const banner =
  '/* Generated by scripts/vendor-tokens.mjs — do not edit.\n' +
  ' * Regenerate: bun scripts/vendor-tokens.mjs\n' +
  ' * Source: packages/design-tokens/src/blueprint.ts (toBlueprintCss). */\n\n';
const tokensCss = banner + toBlueprintCss();
const wallCss = readFileSync(WALL_SRC, 'utf8');

const check = process.argv.includes('--check');

if (check) {
  const problems = [];
  for (const [label, out, expected] of [
    ['kit/tokens.css', TOKENS_OUT, tokensCss],
    ['kit/wall.css', WALL_OUT, wallCss],
  ]) {
    let actual;
    try {
      actual = readFileSync(out, 'utf8');
    } catch {
      problems.push(`${label} is missing — run \`bun scripts/vendor-tokens.mjs\`.`);
      continue;
    }
    if (actual !== expected) {
      problems.push(
        `${label} is stale (does not match what \`bun scripts/vendor-tokens.mjs\` would ` +
          `generate). Diff: expected ${expected.length} bytes, found ${actual.length} bytes. ` +
          'Run `bun scripts/vendor-tokens.mjs` to regenerate.',
      );
    }
  }
  if (problems.length > 0) {
    console.error(problems.join('\n'));
    process.exit(1);
  }
  console.log('kit/tokens.css and kit/wall.css are up to date.');
  process.exit(0);
}

writeFileSync(TOKENS_OUT, tokensCss);
writeFileSync(WALL_OUT, wallCss);
console.log(`Wrote ${TOKENS_OUT} and ${WALL_OUT}`);
