/*
 * Dev-time refresh of the committed LiteLLM pricing snapshot (issue #445).
 *
 * Fetches BerriAI/litellm's `model_prices_and_context_window.json` (MIT),
 * filters it through the SAME `filterLiteLLM` the gateway warmer uses, and
 * writes `packages/app-engine/src/pricing/litellm-snapshot.json`. Run
 * manually when refreshing bundled prices — this is NOT wired into CI (the
 * live disk-cached warmer handles day-to-day drift at runtime).
 *
 *   bun scripts/refresh-pricing-snapshot.ts
 */

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { filterLiteLLM } from '../packages/app-engine/src/pricing/filter.ts';

const LITELLM_URL =
  'https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json';

async function main(): Promise<void> {
  const res = await fetch(LITELLM_URL);
  if (!res.ok) throw new Error(`fetch failed: HTTP ${res.status}`);
  const raw = (await res.json()) as Record<string, unknown>;
  const models = filterLiteLLM(raw);
  const count = Object.keys(models).length;
  if (count === 0) throw new Error('filter produced zero entries — refusing to overwrite');

  const here = path.dirname(fileURLToPath(import.meta.url));
  const out = path.join(
    here,
    '..',
    'packages',
    'app-engine',
    'src',
    'pricing',
    'litellm-snapshot.json',
  );
  const doc = {
    $source: 'BerriAI/litellm model_prices_and_context_window.json (MIT license)',
    $note:
      'Filtered snapshot: Anthropic Claude + OpenAI GPT/Codex text families, per-token USD price fields only. Generated by scripts/refresh-pricing-snapshot.ts — do not hand-edit.',
    generatedAt: new Date().toISOString().slice(0, 10),
    models,
  };
  writeFileSync(out, `${JSON.stringify(doc, null, 2)}\n`);
  console.log(`wrote ${count} models to ${path.relative(process.cwd(), out)}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
