import Foundation
import SwiftProtobuf

/// The thin decoders between a screen's bytes and its SwiftUI view
/// (#1020, D-1020-E3; wired in #1025 S5, lane L5).
///
/// **One file, three screens, no logic.** Each of these takes the `bytes` the
/// shared module published and exposes exactly what its view renders. Every
/// one of them keeps the three-state read law as a Swift `enum` with three
/// cases, which is how the law survives the language boundary: Swift's
/// `Optional` would collapse two of the three, exactly as Kotlin's nullable
/// would.
///
/// The `Centraid_Screen_V1_*` types are generated by `protoc-gen-swift` from
/// `crates/api-proto/proto` — the same tree Wire reads on the Kotlin side, and
/// the reason `buf.gen.yaml` names SwiftProtobuf as this lane's plugin. They
/// are generated now (`Sources/Generated`), so the `unwired()` hand-off that
/// stood here is gone and these decode for real.
///
/// **A DECODE THAT FAILS RENDERS THE INITIAL STATE, NOT AN EMPTY ONE.** The
/// initial state of every screen is `loading`, which is the honest thing to
/// draw when the bytes have not arrived: `Data()` is what these views hold
/// before the bridge has published anything, and an empty `.data` case in its
/// place would be a screen claiming an empty vault before it had read one.

/// Loading, a failure with a sentence, or data. Three cases, always.
enum ScreenContent<Value> {
    case loading(Bool)
    case failure(String, String)
    case data(Value)
}

struct TallyRowView: Hashable {
    let identifier: String
    let description: String
    let amount: String
    let pending: Bool
}

struct BandView: Hashable {
    let label: String
    let event: Data
    /// The catalog mark a drawn band shows above the label. Empty for a band
    /// still drawn as a row of words (Tally's), which has none.
    var iconKey: String = ""
    /// Whether this is the destination on screen — read off the state, never
    /// written down by the view that draws it.
    var selected: Bool = false
}

struct TallyListStateView {
    let data: Data

    private var state: Centraid_Screen_V1_TallyListState {
        (try? Centraid_Screen_V1_TallyListState(serializedBytes: data)) ?? .init()
    }

    /// The list's own destinations, in the order the screen names them.
    ///
    /// **A BAND DESTINATION IS A PARAMETER, NOT A SECOND SCREEN** — so each of these carries a
    /// `DestinationChanged` for the SAME machine, and never a route.
    /// v0's order and marks (`packages/blueprints/apps/tally/shelves.ts`):
    /// Balances, Activity, Groups. v0's fourth, Waiting, has no destination in
    /// this state, and its More has no sheet here, so neither is drawn.
    var bands: [BandView] {
        let current = state.destination
        return [
            (Centraid_Screen_V1_TallyListState.Destination.balances, "Balances", "Coin"),
            (.activity, "Activity", "Activity"),
            (.groups, "Groups", "Users"),
        ].map { destination, label, iconKey in
            var event = Centraid_Screen_V1_TallyListEvent()
            event.destination = .with { $0.destination = destination }
            return BandView(
                label: label,
                event: event.encoded,
                iconKey: iconKey,
                // `unspecified` is Activity: the machine opens there.
                selected: destination == current
                    || (destination == .activity && current == .unspecified)
            )
        }
    }

    var content: ScreenContent<[TallyRowView]> {
        let state = self.state
        switch state.content {
        case let .failure(failure):
            return .failure(failure.sentence, failure.remedy)
        case let .data(data):
            // THE PENDING SET IS THE STATE'S, not the row's: a write in flight
            // is the screen's knowledge and never a column in the vault.
            let pending = Set(state.pendingExpenseIds)
            return .data(
                data.rows.map { row in
                    TallyRowView(
                        identifier: row.expenseID,
                        description: row.description_p,
                        amount: row.amount.spelled,
                        pending: pending.contains(row.expenseID)
                    )
                }
            )
        // `loading`, and the `nil` a message with no content set decodes to,
        // are the SAME screen — a state that has not read yet. Collapsing them
        // into `.data([])` is the fourth state the read law forbids.
        case let .loading(loading):
            return .loading(loading.firstLoad)
        case .none:
            return .loading(true)
        }
    }

    var recurringWithheld: Bool { state.recurringMaterialisationWithheld }

    var refreshEvent: Data {
        var event = Centraid_Screen_V1_TallyListEvent()
        event.refreshed = .init()
        return event.encoded
    }
}

// `PhotoCellView` IS GONE, AND WITH IT THE SECOND DERIVATION (#1029, photos
// port). It restated `held`, `originalHash` and the `offersDownload` rule that
// `PhotoCells.swift` now owns for every surface that draws photographs — and a
// second spelling of "which cell gets the download arrow" is a second answer
// waiting to disagree with the first. The views take the WIRE TYPE, which is
// already decoded by the time a screen has a data case.

struct PhotosGridStateView {
    let data: Data

    private var state: Centraid_Screen_V1_PhotosGridState {
        (try? Centraid_Screen_V1_PhotosGridState(serializedBytes: data)) ?? .init()
    }

    /// v0's three places, in v0's order and with v0's marks
    /// (`photos-band.ts`): Library first, because the band is judged by how
    /// few taps the timeline costs. More is not among them — it opens a sheet,
    /// so the band draws it as its own bordered square.
    ///
    /// **"Collections", not "Albums".** The label once said Albums over a page
    /// titled Collections that has an Albums section of its own, so one word
    /// named two different things on one screen.
    /// The event that moves the grid to `destination` — the band's own, and
    /// the one the search bar's close sends to put the band back.
    static func destinationEvent(_ destination: Centraid_Screen_V1_PhotosGridState.Destination) -> Data {
        var event = Centraid_Screen_V1_PhotosGridEvent()
        event.destination = .with { $0.destination = destination }
        return event.encoded
    }

    var bands: [BandView] {
        let current = destination
        return [
            (Centraid_Screen_V1_PhotosGridState.Destination.library, "Library", "Image"),
            (.collections, "Collections", "Layers"),
            (.search, "Search", "Search"),
        ].map { destination, label, iconKey in
            var event = Centraid_Screen_V1_PhotosGridEvent()
            event.destination = .with { $0.destination = destination }
            return BandView(
                label: label,
                event: event.encoded,
                iconKey: iconKey,
                // `unspecified` IS the library: the machine opens there, and a
                // band with nothing lit would be a band saying "nowhere".
                selected: destination == current
                    || (destination == .library && current == .unspecified)
            )
        }
    }

    /// The cells, AS THE WIRE HOLDS THEM, and whether this device has a
    /// thumbnail pack at all.
    ///
    /// No per-cell struct in between: `PhotoCellsGrid` renders
    /// `Centraid_Screen_V1_PhotoCell` directly, so a mapping step here would
    /// decode a message that is already decoded and give the held derivation a
    /// second home.
    var content: ScreenContent<([Centraid_Screen_V1_PhotoCell], Bool)> {
        switch state.content {
        case let .failure(failure):
            return .failure(failure.sentence, failure.remedy)
        case let .data(data):
            return .data((data.cells, data.thumbnailPackAbsent))
        case let .loading(loading):
            return .loading(loading.firstLoad)
        case .none:
            return .loading(true)
        }
    }

    /// THE MEMBER TAPPED THE DOWNLOAD ARROW ON ONE CELL (#1025 S5).
    ///
    /// Both ids, because they answer two different questions: the hash
    /// addresses the bytes and the asset id is what the grid keys the cell by,
    /// so the reducer can start that one spinner without a round trip.
    func fetchEvent(assetIdentifier: String, contentHash: String) -> Data {
        var event = Centraid_Screen_V1_PhotosGridEvent()
        event.fetchOriginal = .with {
            $0.assetID = assetIdentifier
            $0.contentHash = contentHash
        }
        return event.encoded
    }

    /// What the backup is doing, in a member's words.
    ///
    /// The phase and nothing else. `paused_reason` is rendered BESIDE this, by
    /// the view, because a phase says what is happening and a reason says why it
    /// is not — and running the two together would produce a sentence for
    /// `IDLE` with nothing to be idle about.
    var backupSentence: String {
        let done = state.backup.assetsTransferredThisSession
        let left = state.backup.assetsRemaining
        switch state.backup.phase {
        case .transferring:
            // BOTH NUMBERS (`docs/mobile-offline.md:374`). This said "Backing up
            // N photos" over `assetsRemaining` alone, which counts DOWN — so a
            // member watching a roll upload saw a number shrink with nothing to
            // say how much had been done, and a backup near the end and a backup
            // that had barely started both read as a small number.
            return "Importing: \(done) done, \(left) to go"
        case .enumerating:
            return "Looking through your camera roll."
        case .waitingForPower:
            return waiting(done: done, left: left, "Centraid imports these when this phone is charging.")
        case .waitingForUnmetered:
            return waiting(done: done, left: left, "Centraid imports these on Wi-Fi.")
        case .parkedLowDisk:
            return "Centraid has paused the import."
        case .done:
            return done > 0
                ? "Your camera roll is in your vault \u{2014} \(done) this time."
                : "Your camera roll is in your vault."
        case .idle, .unspecified, .UNRECOGNIZED:
            return "Camera roll import is off."
        }
    }

    /// A wait still says what it has already carried.
    ///
    /// A member who moved off Wi-Fi mid-roll is told the work is not lost, which
    /// is the whole difference between a pause and a failure.
    private func waiting(done: UInt32, left: UInt32, _ sentence: String) -> String {
        done == 0 ? sentence : "\(sentence) \(done) done, \(left) waiting."
    }

    var pausedReason: String { state.backup.pausedReason }

    /// The member chose a SELECTION, and can change it.
    ///
    /// **A limited grant is not a broken one and the copy never says it is.**
    /// iOS's own remedy is `presentLimitedLibraryPicker`, which is the member
    /// adding photographs to their own selection — not a second permission
    /// prompt, and not a trip to Settings. Offering it is the honest half of
    /// treating `LIMITED` as a first-class state: the state is reported, and the
    /// one thing that changes it is one tap away.
    var isLimitedSelection: Bool { state.permission == .limited }

    /// Is a pass moving right now? A button that started a second one would be
    /// refused by the runner's own lock, so it is not offered.
    var backupIsRunning: Bool {
        state.backup.phase == .transferring || state.backup.phase == .enumerating
    }

    /// Is there a grant worth asking for?
    ///
    /// **`LIMITED` IS NOT A DENIAL and `RESTRICTED` IS NOT A REFUSAL TO ASK.**
    /// A limited library is one the member chose, so there is nothing to ask
    /// for; a restricted device will never grant, so a button would be a button
    /// that does nothing. Only "not asked" and "denied" have a next move, and
    /// only one of them is this button — a denied grant is a trip to Settings,
    /// which `PhotosGridMachine` already words in `paused_reason`.
    var canAskForPhotos: Bool { state.permission == .notAsked }

    var moreSheetEvent: Data {
        var event = Centraid_Screen_V1_PhotosGridEvent()
        // `more` IS A SHEET, NEVER A DESTINATION. The type system says so: this
        // is `SheetChanged` and there is no band value it could carry.
        event.sheet = .with { $0.sheet = .more }
        return event.encoded
    }

    var permissionRequestEvent: Data {
        var event = Centraid_Screen_V1_PhotosGridEvent()
        event.permissionRequested = .init()
        return event.encoded
    }

    /// WHICH TRANSPORT CARRIED THEM, as a member-readable word.
    ///
    /// Reported, never claimed: the iOS background-transfer experiment
    /// (`mobile/maestro/ios-transfer-experiment.md`) decides which of these the
    /// product ships, and until it has run this is what a diagnostics surface
    /// says rather than a sentence in a document. `unspecified` is an honest
    /// "nothing has moved yet" and not a default.
    var backupTransport: String {
        switch state.backup.transport {
        case .irohBlobs: return "Direct"
        case .httpsBlobDoor: return "HTTPS"
        case .unspecified, .UNRECOGNIZED: return "Nothing carried yet"
        }
    }

    /// WHICH SHEET IS OPEN, if one is.
    ///
    /// It was set and never read: `moreSheetEvent` moved the state and nothing
    /// on either shell drew anything, so the `···` on the band was a control
    /// that reduced correctly and did nothing a member could see.
    var sheet: Centraid_Screen_V1_PhotosGridState.Sheet { state.sheet }

    /// WHICH BAND IS SHOWING. A PARAMETER, NOT A SECOND SCREEN (law 2).
    ///
    /// The three destinations are one screen with one state; moving between
    /// them is not a push, so back does not walk through the bands a member
    /// happened to tap. `PhotosGridView` reads this to decide which BODY to
    /// draw — the library grid, Collections or Search — which is why there is
    /// no `Destination.PhotosCollections` in `nav/Navigation.kt` and never
    /// will be.
    var destination: Centraid_Screen_V1_PhotosGridState.Destination { state.destination }

    func sheetEvent(_ sheet: Centraid_Screen_V1_PhotosGridState.Sheet) -> Data {
        var event = Centraid_Screen_V1_PhotosGridEvent()
        event.sheet = .with { $0.sheet = sheet }
        return event.encoded
    }
}

struct NoteDraftView {
    let title: String
    let body: String
    let pinned: Bool
    let saveFailure: String?
}

struct NotesEditorStateView {
    let data: Data

    private var state: Centraid_Screen_V1_NotesEditorState {
        (try? Centraid_Screen_V1_NotesEditorState(serializedBytes: data)) ?? .init()
    }

    var content: ScreenContent<NoteDraftView> {
        switch state.content {
        case let .failure(failure):
            return .failure(failure.sentence, failure.remedy)
        case let .draft(draft):
            return .data(
                NoteDraftView(
                    title: draft.title,
                    body: draft.body,
                    pinned: draft.pinned,
                    // THE SAVE'S SENTENCE IS NOT THE READ'S. It rides on the
                    // draft and the view draws it OVER the words, never instead
                    // of them — a refused save that replaced the editor would
                    // have thrown away the only copy.
                    saveFailure: draft.hasSaveFailure ? draft.saveFailure.sentence : nil
                )
            )
        case let .loading(loading):
            return .loading(loading.firstLoad)
        case .none:
            return .loading(true)
        }
    }

    /// What the line above the editor says about the save.
    ///
    /// A member needs to know whether their words are safe, and the five
    /// answers are genuinely different: nothing to do, not yet sent, going,
    /// queued for a gateway this seat cannot reach, and refused.
    var saveLabel: String {
        switch state.save {
        case .clean: return "Saved"
        case .dirty: return "Unsaved changes"
        case .saving: return "Saving"
        case .queued: return "Waiting for your gateway"
        case .refused: return "Not saved"
        case .unspecified, .UNRECOGNIZED: return ""
        }
    }

    var pinEvent: Data {
        var event = Centraid_Screen_V1_NotesEditorEvent()
        event.pin = .init()
        return event.encoded
    }

    var saveEvent: Data {
        var event = Centraid_Screen_V1_NotesEditorEvent()
        event.save = .init()
        return event.encoded
    }

    /// A TITLE THE MEMBER TYPED (#1025 S5).
    ///
    /// This used to re-assert the title the state already held, with a comment
    /// saying so plainly: a state-derived event cannot carry text that is in a
    /// field rather than in the state, and the view bound its `TextField` to
    /// `.constant`, so there was nothing to carry. The view now owns its typed
    /// text (`NotesEditorView`'s `@State`), which is the only place a keystroke
    /// exists before it is saved, and hands it here.
    ///
    /// An edit NEVER writes: it moves the draft to dirty and the member presses
    /// Save. No autosave-per-keystroke — every keystroke would be a command with
    /// its own `invoke_key`, an audit receipt and a replica round trip, and a
    /// member typing a paragraph would fill their outbox with a hundred
    /// revisions of one note.
    static func titleEvent(_ title: String) -> Data {
        var event = Centraid_Screen_V1_NotesEditorEvent()
        event.title = .with { $0.title = title }
        return event.encoded
    }

    static func bodyEvent(_ body: String) -> Data {
        var event = Centraid_Screen_V1_NotesEditorEvent()
        event.body = .with { $0.body = body }
        return event.encoded
    }
}

/// The three content cases, spelled out where a reader of the views will look.
///
/// PhotosGridView's `.data` case carries a tuple whose second member is
/// `thumbnail_pack_absent`, because the two empty-cell sentences are two facts
/// and a view cannot pick between them from the cells alone.
extension ScreenContent {
    var isFailure: Bool {
        if case .failure = self { return true }
        return false
    }
}

// ONE `encoded`, FOR EVERY SCREEN IN THIS TARGET.
//
// Three views each grew a `private extension SwiftProtobuf.Message` with this
// same body, and a fourth used `.encoded` without declaring one — which does
// not compile, because a fileprivate helper is not visible from the file that
// needed it. Same shape as the four cell renderers: written once is written
// once.
extension SwiftProtobuf.Message {
    /// The bytes that cross back into `CentraidShared`.
    ///
    /// A serialisation that throws yields EMPTY bytes rather than a crash, and
    /// the shared module decodes those as a message with no `kind` set, which
    /// every reducer's `else` branch already answers with `Step(state)` — a tap
    /// that does nothing rather than a shell that dies on one.
    var encoded: Data { (try? serializedData()) ?? Data() }
}

private extension Centraid_Screen_V1_Money {
    /// An amount, spelled with what the row actually carried.
    ///
    /// **THE EXPONENT IS NOT ASSUMED TO BE 2.** The schema says it comes "from
    /// the kit's table through the core, never guessed", and `TallyReads` says
    /// why it cannot state one yet: the table is `crates/apps/kit`'s
    /// `minor_units`, it is code rather than a column, and no door on this seat
    /// serves it. So a zero exponent spells the MINOR amount beside its code —
    /// visibly a raw figure — rather than dividing by a hundred and labelling a
    /// JPY expense in the vault's base money, which is v0's own bug
    /// (`packages/design/src/format.ts:38`) and the one D-1020-CL3 closed.
    var spelled: String {
        if currency.isEmpty { return "" }
        if exponent == 0 { return "\(minor) \(currency)" }
        let divisor = pow(10.0, Double(exponent))
        let formatter = NumberFormatter()
        formatter.numberStyle = .decimal
        formatter.minimumFractionDigits = Int(exponent)
        formatter.maximumFractionDigits = Int(exponent)
        // THE VAULT'S LOCALE, NEVER THE DEVICE'S. A member reading their vault
        // on a borrowed phone must see their own separators.
        if !locale.isEmpty { formatter.locale = Locale(identifier: locale) }
        let value = Double(minor) / divisor
        let body = formatter.string(from: NSNumber(value: value)) ?? "\(value)"
        return "\(body) \(currency)"
    }
}
