import Foundation

/// The thin decoders between a screen's bytes and its SwiftUI view
/// (#1020, D-1020-E3).
///
/// **One file, three screens, no logic.** Each of these takes the `bytes` the
/// shared module published and exposes exactly what its view renders. Every
/// one of them keeps the three-state read law as a Swift `enum` with three
/// cases, which is how the law survives the language boundary: Swift's
/// `Optional` would collapse two of the three, exactly as Kotlin's nullable
/// would.
///
/// The `Centraid_screen_v1_*` types are generated by `protoc-gen-swift` from
/// `crates/api-proto/proto` — the same tree Wire reads on the Kotlin side, and
/// the reason `buf.gen.yaml` names SwiftProtobuf as this lane's plugin. The
/// decode call sites are `fatalError` until an Xcode has run the generator:
/// returning an empty state would make every screen look like an empty vault.

/// Loading, a failure with a sentence, or data. Three cases, always.
enum ScreenContent<Value> {
    case loading(Bool)
    case failure(String, String)
    case data(Value)
}

struct TallyRowView: Hashable {
    let identifier: String
    let description: String
    let amount: String
    let pending: Bool
}

struct BandView: Hashable {
    let label: String
    let event: Data
}

struct TallyListStateView {
    let data: Data

    var bands: [BandView] { generated() }
    var content: ScreenContent<[TallyRowView]> { generated() }
    var recurringWithheld: Bool { generated() }
    var refreshEvent: Data { generated() }

    private func generated<T>() -> T { unwired() }
}

struct PhotoCellView: Hashable {
    let identifier: String
    let thumbnailPath: String?
}

struct PhotosGridStateView {
    let data: Data

    var bands: [BandView] { generated() }
    var content: ScreenContent<([PhotoCellView], Bool)> { generated() }
    var backupSentence: String { generated() }
    var pausedReason: String { generated() }
    var canAskForPhotos: Bool { generated() }
    var moreSheetEvent: Data { generated() }
    var permissionRequestEvent: Data { generated() }

    private func generated<T>() -> T { unwired() }
}

struct NoteDraftView {
    let title: String
    let body: String
    let pinned: Bool
    let saveFailure: String?
}

struct NotesEditorStateView {
    let data: Data

    var content: ScreenContent<NoteDraftView> { generated() }
    var saveLabel: String { generated() }
    var pinEvent: Data { generated() }
    var saveEvent: Data { generated() }
    var titleEvent: Data { generated() }

    private func generated<T>() -> T { unwired() }
}

/// The hand-off point, in one function so it is one grep.
///
/// `mobile/README.md` -> "The iOS hand-off" names what a macOS session does
/// first: run `protoc-gen-swift` over `crates/api-proto/proto`, then replace
/// each `generated()` above with the decode it stands for. A `fatalError` and
/// not a default value, because a screen that rendered an empty list here would
/// be indistinguishable from an empty vault.
private func unwired<T>() -> T {
    fatalError(
        "the SwiftProtobuf decoders are not generated yet: see mobile/README.md " +
        "-> \"The iOS hand-off\". Nineteen fixtures in contracts/screens are " +
        "waiting for them, and ScreenFixtureTests.swift is the test that will pass."
    )
}

/// The three content cases, spelled out where a reader of the views will look.
///
/// PhotosGridView's `.data` case carries a tuple whose second member is
/// `thumbnail_pack_absent`, because the two empty-cell sentences are two facts
/// and a view cannot pick between them from the cells alone.
extension ScreenContent {
    var isFailure: Bool {
        if case .failure = self { return true }
        return false
    }
}
