/*!
 * Native module created for Expo Share Intent (https://github.com/achorein/expo-share-intent)
 * author: achorein (https://github.com/achorein)
 * inspired by :
 *  - https://ajith-ab.github.io/react-native-receive-sharing-intent/docs/ios#create-share-extension
 */
// governance: allow-repo-hygiene file-size-limit (#419) generated by expo-share-intent as the complete OS extension controller; splitting it would make Expo prebuild overwrite or disconnect the generated target
import MobileCoreServices
import Photos
import Social
import UIKit

class ShareViewController: UIViewController {
  let hostAppGroupIdentifier = "group.dev.centraid.mobile"
  let shareProtocol = "centraid"
  let sharedKey = "centraidShareKey"
  var sharedMedia: [SharedMediaFile] = []
  let imageContentType: String = UTType.image.identifier
  let videoContentType: String = UTType.movie.identifier
  let fileURLType: String = UTType.fileURL.identifier
  let pkpassContentType: String = "com.apple.pkpass"
  let pdfContentType: String = UTType.pdf.identifier
  let vcardContentType: String = "public.vcard"

  // One attachment's load result. Every supported share resolves to a file
  // that lands in `shareIntent.files`; a hard load error aborts the whole
  // share rather than delivering a partial set (#431 F7). Text and web-URL
  // shares are no longer advertised (#431 F9), so there is no text/url case.
  private enum LoadOutcome {
    case media(SharedMediaFile)
    case failed(String)
  }

  override func viewDidLoad() {
    super.viewDidLoad()
  }

  override func viewDidAppear(_ animated: Bool) {
    super.viewDidAppear(animated)
    Task {
      guard let extensionContext = self.extensionContext,
        let content = extensionContext.inputItems.first as? NSExtensionItem,
        let attachments = content.attachments, !attachments.isEmpty
      else {
        dismissWithError(message: "No content found")
        return
      }
      // Await EVERY attachment before writing anything, then write userDefaults
      // and redirect exactly once. The previous per-handler "if this is the last
      // index" check fired whenever the LAST-indexed attachment finished, so a
      // slow early item (a large video) was silently dropped when a fast later
      // one (a small image) completed first (#431 F7). Loading in index order
      // and collecting the results guarantees all complete first and the
      // delivered order matches the share order, at the activation rule's scale
      // (100 images / 20 movies). Awaited sequentially rather than in a task
      // group so a non-Sendable SharedMediaFile is never sent across a task
      // boundary (the loads are I/O-bound and suspend, so this stays responsive).
      var outcomes: [LoadOutcome] = []
      outcomes.reserveCapacity(attachments.count)
      for attachment in attachments {
        outcomes.append(await self.load(attachment: attachment))
      }
      self.finish(with: outcomes)
    }
  }

  private func load(attachment: NSItemProvider) async -> LoadOutcome {
    if attachment.hasItemConformingToTypeIdentifier(imageContentType) {
      return await loadImage(attachment: attachment)
    } else if attachment.hasItemConformingToTypeIdentifier(videoContentType) {
      return await loadVideo(attachment: attachment)
    } else if attachment.hasItemConformingToTypeIdentifier(vcardContentType) {
      return await loadVCard(attachment: attachment)
    } else if attachment.hasItemConformingToTypeIdentifier(fileURLType) {
      return await loadFile(attachment: attachment)
    } else if attachment.hasItemConformingToTypeIdentifier(pkpassContentType) {
      return await loadPkPass(attachment: attachment)
    } else if attachment.hasItemConformingToTypeIdentifier(pdfContentType) {
      return await loadPdf(attachment: attachment)
    } else {
      NSLog("[ERROR] content type not handled")
      return .failed("content type not handled")
    }
  }

  private func finish(with outcomes: [LoadOutcome]) {
    // A single failed load aborts the whole share with a visible error rather
    // than delivering a partial (and silently truncated) set.
    for case let .failed(message) in outcomes {
      dismissWithError(message: message)
      return
    }
    let files = outcomes.compactMap { outcome -> SharedMediaFile? in
      if case let .media(file) = outcome { return file }
      return nil
    }
    guard !files.isEmpty else {
      dismissWithError(message: "No content found")
      return
    }
    self.sharedMedia = files
    // Generic documents (pdf, vCard, pkpass, arbitrary files) redirect as
    // `.file`; a pure photo/video share as `.media`. Both decode to
    // `shareIntent.files` on the JS side.
    let redirect: RedirectType = files.contains { $0.type == .file } ? .file : .media
    let userDefaults = UserDefaults(suiteName: self.hostAppGroupIdentifier)
    userDefaults?.set(self.toData(data: self.sharedMedia), forKey: self.sharedKey)
    userDefaults?.synchronize()
    self.redirectToHostApp(type: redirect)
  }

  private func loadVCard(attachment: NSItemProvider) async -> LoadOutcome {
    do {
      if let url = try? await attachment.loadItem(forTypeIdentifier: self.vcardContentType) as? URL
      {
        // ensure a .vcf file extension so mime resolves properly
        let tmp = FileManager.default.temporaryDirectory.appendingPathComponent(
          UUID().uuidString + ".vcf")
        _ = self.copyFile(at: url, to: tmp)
        return self.fileEntry(from: tmp)
      } else if let data = try? await attachment.loadItem(forTypeIdentifier: self.vcardContentType)
        as? Data
      {
        let tmp = FileManager.default.temporaryDirectory.appendingPathComponent(
          UUID().uuidString + ".vcf")
        try data.write(to: tmp)
        return self.fileEntry(from: tmp)
      } else {
        NSLog("[ERROR] Cannot load vcard content")
        return .failed("Cannot load vCard content")
      }
    } catch {
      NSLog("[ERROR] loadVCard exception: \(error.localizedDescription)")
      return .failed("vCard error: \(error.localizedDescription)")
    }
  }

  private func loadPkPass(attachment: NSItemProvider) async -> LoadOutcome {
    do {
      if let url = try await attachment.loadItem(forTypeIdentifier: self.pkpassContentType) as? URL {
        return self.fileEntry(from: url)
      } else if let data = try await attachment.loadItem(forTypeIdentifier: self.pkpassContentType)
        as? Data
      {
        let tempFileURL = FileManager.default.temporaryDirectory.appendingPathComponent(
          UUID().uuidString + ".pkpass")
        try data.write(to: tempFileURL)
        return self.fileEntry(from: tempFileURL)
      } else {
        NSLog("[ERROR] Cannot load pkpass content: item was neither URL nor Data")
        return .failed("Cannot load pkpass content (unexpected data type).")
      }
    } catch {
      NSLog("[ERROR] Exception when handling pkpass: \(error.localizedDescription)")
      return .failed("Error processing pkpass: \(error.localizedDescription)")
    }
  }

  private func loadImage(attachment: NSItemProvider) async -> LoadOutcome {
    do {
      let item = try await attachment.loadItem(forTypeIdentifier: self.imageContentType)
      var url: URL? = nil

      if let dataURL = item as? URL {
        url = dataURL
      } else if let imageData = item as? UIImage {
        url = self.saveScreenshot(imageData)
        if url == nil {
          NSLog("[ERROR] loadImage: saveScreenshot returned nil")
        }
      } else if let data = item as? Data {
        if let image = UIImage(data: data) {
          url = self.saveScreenshot(image)
        } else {
          NSLog("[ERROR] loadImage: Failed to create UIImage from Data")
        }
      } else {
        NSLog("[ERROR] loadImage: Item is unexpected type: \(type(of: item))")
      }

      guard let safeURL = url else {
        NSLog("[ERROR] loadImage: Failed to get URL for image item")
        return .failed("Failed to process image")
      }

      var pixelWidth: Int? = nil
      var pixelHeight: Int? = nil
      if let imageSource = CGImageSourceCreateWithURL(safeURL as CFURL, nil) {
        if let imageProperties = CGImageSourceCopyPropertiesAtIndex(imageSource, 0, nil)
          as Dictionary?
        {
          pixelWidth = imageProperties[kCGImagePropertyPixelWidth] as? Int
          pixelHeight = imageProperties[kCGImagePropertyPixelHeight] as? Int
          // Check orientation and flip size if required
          if let orientationNumber = imageProperties[kCGImagePropertyOrientation] as! CFNumber?
          {
            var orientation: Int = 0
            CFNumberGetValue(orientationNumber, .intType, &orientation)
            if orientation > 4 {
              let temp: Int? = pixelWidth
              pixelWidth = pixelHeight
              pixelHeight = temp
            }
          }
        }
      }

      // Always copy
      let fileName = self.getFileName(from: safeURL, type: .image)
      let fileExtension = self.getExtension(from: safeURL, type: .image)
      let fileSize = self.getFileSize(from: safeURL)
      let mimeType = safeURL.mimeType(ext: fileExtension)
      let newName = "\(UUID().uuidString).\(fileExtension)"
      let newPath = FileManager.default
        .containerURL(
          forSecurityApplicationGroupIdentifier: self.hostAppGroupIdentifier)!
        .appendingPathComponent(newName)

      guard self.copyFile(at: safeURL, to: newPath) else {
        return .failed("Failed to copy image")
      }
      return .media(
        SharedMediaFile(
          path: newPath.absoluteString, thumbnail: nil, fileName: fileName,
          fileSize: fileSize, width: pixelWidth, height: pixelHeight, duration: nil,
          mimeType: mimeType, type: .image))
    } catch {
      NSLog("[ERROR] loadImage: Exception loading image item: \(error)")
      return .failed("Cannot load image content: \(error.localizedDescription)")
    }
  }

  private func documentDirectoryPath() -> URL? {
    let paths = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)

    if let firstPath = paths.first {
      _ = FileManager.default.fileExists(atPath: firstPath.path)
      return firstPath
    } else {
      return nil
    }
  }

  private func saveScreenshot(_ image: UIImage) -> URL? {
    guard let screenshotData = image.pngData() else {
      return nil
    }

    // Try using the app group container instead of documents directory
    guard let containerURL = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: self.hostAppGroupIdentifier) else {
      return nil
    }

    let fileName = "screenshot_\(UUID().uuidString).png"
    let screenshotPath = containerURL.appendingPathComponent(fileName)

    do {
      try screenshotData.write(to: screenshotPath)

      let fileExists = FileManager.default.fileExists(atPath: screenshotPath.path)

      if fileExists {
        let attributes = try? FileManager.default.attributesOfItem(atPath: screenshotPath.path)
        _ = attributes?[.size] as? Int ?? 0
      }

      return screenshotPath
    } catch {
      NSLog("[ERROR] saveScreenshot: Failed to write screenshot: \(error)")
      NSLog("[ERROR] saveScreenshot: Error details: \(error.localizedDescription)")
      return nil
    }
  }

  private func loadVideo(attachment: NSItemProvider) async -> LoadOutcome {
    guard
      let url = try? await attachment.loadItem(forTypeIdentifier: self.videoContentType) as? URL
    else {
      NSLog("[ERROR] Cannot load video content")
      return .failed("Cannot load video content")
    }
    // Always copy
    let fileName = self.getFileName(from: url, type: .video)
    let fileExtension = self.getExtension(from: url, type: .video)
    let fileSize = self.getFileSize(from: url)
    let mimeType = url.mimeType(ext: fileExtension)
    let newName = "\(UUID().uuidString).\(fileExtension)"
    let newPath = FileManager.default
      .containerURL(
        forSecurityApplicationGroupIdentifier: self.hostAppGroupIdentifier)!
      .appendingPathComponent(newName)
    guard self.copyFile(at: url, to: newPath) else {
      return .failed("Failed to copy video")
    }
    guard
      let sharedFile = self.getSharedMediaFile(
        forVideo: newPath, fileName: fileName, fileSize: fileSize, mimeType: mimeType)
    else {
      return .failed("Failed to process video")
    }
    return .media(sharedFile)
  }

  private func loadPdf(attachment: NSItemProvider) async -> LoadOutcome {
    guard let url = try? await attachment.loadItem(forTypeIdentifier: self.pdfContentType) as? URL
    else {
      NSLog("[ERROR] Cannot load pdf content")
      return .failed("Cannot load pdf content")
    }
    return self.fileEntry(from: url)
  }

  private func loadFile(attachment: NSItemProvider) async -> LoadOutcome {
    guard let url = try? await attachment.loadItem(forTypeIdentifier: self.fileURLType) as? URL
    else {
      NSLog("[ERROR] Cannot load file content")
      return .failed("Cannot load file content")
    }
    return self.fileEntry(from: url)
  }

  private func fileEntry(from url: URL) -> LoadOutcome {
    // Always copy
    let fileName = self.getFileName(from: url, type: .file)
    let fileExtension = self.getExtension(from: url, type: .file)
    let fileSize = self.getFileSize(from: url)
    let mimeType = url.mimeType(ext: fileExtension)
    let newName = "\(UUID().uuidString).\(fileExtension)"
    let newPath = FileManager.default
      .containerURL(
        forSecurityApplicationGroupIdentifier: self.hostAppGroupIdentifier)!
      .appendingPathComponent(newName)
    guard self.copyFile(at: url, to: newPath) else {
      return .failed("Failed to copy file")
    }
    return .media(
      SharedMediaFile(
        path: newPath.absoluteString, thumbnail: nil, fileName: fileName,
        fileSize: fileSize, width: nil, height: nil, duration: nil, mimeType: mimeType,
        type: .file))
  }

  private func dismissWithError(message: String? = nil) {
    DispatchQueue.main.async {
      NSLog("[ERROR] Error loading application ! \(message!)")
      let alert = UIAlertController(
        title: "Error", message: "Error loading application: \(message!)", preferredStyle: .alert)

      let action = UIAlertAction(title: "OK", style: .cancel) { _ in
        self.dismiss(animated: true, completion: nil)
        self.extensionContext!.completeRequest(returningItems: [], completionHandler: nil)
      }

      alert.addAction(action)
      self.present(alert, animated: true, completion: nil)
    }
  }

  private func redirectToHostApp(type: RedirectType) {
    let url = URL(string: "\(shareProtocol)://dataUrl=\(sharedKey)#\(type)")!
    var responder = self as UIResponder?

    while responder != nil {
      if let application = responder as? UIApplication {
        if application.canOpenURL(url) {
          application.open(url)
        } else {
          NSLog("redirectToHostApp canOpenURL KO: \(shareProtocol)")
          self.dismissWithError(
            message: "Application not found, invalid url scheme \(shareProtocol)")
          return
        }
      }
      responder = responder!.next
    }
    extensionContext!.completeRequest(returningItems: [], completionHandler: nil)
  }

  enum RedirectType {
    case media
    case file
  }

  func getExtension(from url: URL, type: SharedMediaType) -> String {
    let parts = url.lastPathComponent.components(separatedBy: ".")
    var ex: String? = nil
    if parts.count > 1 {
      ex = parts.last
    }
    if ex == nil {
      switch type {
      case .image:
        ex = "PNG"
      case .video:
        ex = "MP4"
      case .file:
        ex = "TXT"
        if url.lastPathComponent.lowercased().contains("pkpass") { ex = "pkpass" }
      }
    }
    return ex ?? "Unknown"
  }

  func getFileName(from url: URL, type: SharedMediaType) -> String {
    var name = url.lastPathComponent
    if name == "" {
      name = UUID().uuidString + "." + getExtension(from: url, type: type)
    }
    return name
  }

  func getFileSize(from url: URL) -> Int? {
    do {
      let resources = try url.resourceValues(forKeys: [.fileSizeKey])
      return resources.fileSize
    } catch {
      NSLog("Error: \(error)")
      return nil
    }
  }

  func copyFile(at srcURL: URL, to dstURL: URL) -> Bool {
    do {
      if FileManager.default.fileExists(atPath: dstURL.path) {
        try FileManager.default.removeItem(at: dstURL)
      }
      try FileManager.default.copyItem(at: srcURL, to: dstURL)
    } catch (let error) {
      NSLog("Cannot copy item at \(srcURL) to \(dstURL): \(error)")
      return false
    }
    return true
  }

  private func getSharedMediaFile(forVideo: URL, fileName: String, fileSize: Int?, mimeType: String)
    -> SharedMediaFile?
  {
    let asset = AVAsset(url: forVideo)
    let thumbnailPath = getThumbnailPath(for: forVideo)
    let duration = (CMTimeGetSeconds(asset.duration) * 1000).rounded()
    var trackWidth: Int? = nil
    var trackHeight: Int? = nil

    // get video info
    let track = asset.tracks(withMediaType: AVMediaType.video).first ?? nil
    if track != nil {
      let size = track!.naturalSize.applying(track!.preferredTransform)
      trackWidth = abs(Int(size.width))
      trackHeight = abs(Int(size.height))
    }

    if FileManager.default.fileExists(atPath: thumbnailPath.path) {
      return SharedMediaFile(
        path: forVideo.absoluteString, thumbnail: thumbnailPath.absoluteString, fileName: fileName,
        fileSize: fileSize, width: trackWidth, height: trackHeight, duration: duration,
        mimeType: mimeType, type: .video)
    }

    var saved = false
    let assetImgGenerate = AVAssetImageGenerator(asset: asset)
    assetImgGenerate.appliesPreferredTrackTransform = true
    assetImgGenerate.maximumSize = CGSize(width: 360, height: 360)
    do {
      let img = try assetImgGenerate.copyCGImage(
        at: CMTimeMakeWithSeconds(600, preferredTimescale: Int32(1.0)), actualTime: nil)
      try UIImage.pngData(UIImage(cgImage: img))()?.write(to: thumbnailPath)
      saved = true
    } catch {
      saved = false
    }

    return saved
      ? SharedMediaFile(
        path: forVideo.absoluteString, thumbnail: thumbnailPath.absoluteString, fileName: fileName,
        fileSize: fileSize, width: trackWidth, height: trackHeight, duration: duration,
        mimeType: mimeType, type: .video) : nil
  }

  private func getThumbnailPath(for url: URL) -> URL {
    let fileName = Data(url.lastPathComponent.utf8).base64EncodedString().replacingOccurrences(
      of: "==", with: "")
    let path = FileManager.default
      .containerURL(forSecurityApplicationGroupIdentifier: self.hostAppGroupIdentifier)!
      .appendingPathComponent("\(fileName).jpg")
    return path
  }

  class SharedMediaFile: Codable {
    var path: String  // can be image, video or url path
    var thumbnail: String?  // video thumbnail
    var fileName: String  // uuid + extension
    var fileSize: Int?
    var width: Int?  // for image
    var height: Int?  // for image
    var duration: Double?  // video duration in milliseconds
    var mimeType: String
    var type: SharedMediaType

    init(
      path: String, thumbnail: String?, fileName: String, fileSize: Int?, width: Int?, height: Int?,
      duration: Double?, mimeType: String, type: SharedMediaType
    ) {
      self.path = path
      self.thumbnail = thumbnail
      self.fileName = fileName
      self.fileSize = fileSize
      self.width = width
      self.height = height
      self.duration = duration
      self.mimeType = mimeType
      self.type = type
    }
  }

  enum SharedMediaType: Int, Codable {
    case image
    case video
    case file
  }

  func toData(data: [SharedMediaFile]) -> Data? {
    let encodedData = try? JSONEncoder().encode(data)
    return encodedData
  }
}

internal let mimeTypes = [
  "html": "text/html",
  "htm": "text/html",
  "shtml": "text/html",
  "css": "text/css",
  "xml": "text/xml",
  "gif": "image/gif",
  "jpeg": "image/jpeg",
  "jpg": "image/jpeg",
  "js": "application/javascript",
  "atom": "application/atom+xml",
  "rss": "application/rss+xml",
  "mml": "text/mathml",
  "txt": "text/plain",
  "jad": "text/vnd.sun.j2me.app-descriptor",
  "wml": "text/vnd.wap.wml",
  "htc": "text/x-component",
  "png": "image/png",
  "tif": "image/tiff",
  "tiff": "image/tiff",
  "wbmp": "image/vnd.wap.wbmp",
  "ico": "image/x-icon",
  "jng": "image/x-jng",
  "bmp": "image/x-ms-bmp",
  "svg": "image/svg+xml",
  "svgz": "image/svg+xml",
  "webp": "image/webp",
  "woff": "application/font-woff",
  "jar": "application/java-archive",
  "war": "application/java-archive",
  "ear": "application/java-archive",
  "json": "application/json",
  "hqx": "application/mac-binhex40",
  "doc": "application/msword",
  "pdf": "application/pdf",
  "ps": "application/postscript",
  "eps": "application/postscript",
  "ai": "application/postscript",
  "rtf": "application/rtf",
  "m3u8": "application/vnd.apple.mpegurl",
  "xls": "application/vnd.ms-excel",
  "eot": "application/vnd.ms-fontobject",
  "ppt": "application/vnd.ms-powerpoint",
  "wmlc": "application/vnd.wap.wmlc",
  "kml": "application/vnd.google-earth.kml+xml",
  "kmz": "application/vnd.google-earth.kmz",
  "7z": "application/x-7z-compressed",
  "cco": "application/x-cocoa",
  "jardiff": "application/x-java-archive-diff",
  "jnlp": "application/x-java-jnlp-file",
  "pkpass": "application/vnd.apple.pkpass",
  "run": "application/x-makeself",
  "pl": "application/x-perl",
  "pm": "application/x-perl",
  "prc": "application/x-pilot",
  "pdb": "application/x-pilot",
  "rar": "application/x-rar-compressed",
  "rpm": "application/x-redhat-package-manager",
  "sea": "application/x-sea",
  "swf": "application/x-shockwave-flash",
  "sit": "application/x-stuffit",
  "tcl": "application/x-tcl",
  "tk": "application/x-tcl",
  "der": "application/x-x509-ca-cert",
  "pem": "application/x-x509-ca-cert",
  "crt": "application/x-x509-ca-cert",
  "xpi": "application/x-xpinstall",
  "xhtml": "application/xhtml+xml",
  "xspf": "application/xspf+xml",
  "zip": "application/zip",
  "epub": "application/epub+zip",
  "docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  "pptx": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  "mid": "audio/midi",
  "midi": "audio/midi",
  "kar": "audio/midi",
  "mp3": "audio/mpeg",
  "ogg": "audio/ogg",
  "m4a": "audio/x-m4a",
  "ra": "audio/x-realaudio",
  "3gpp": "video/3gpp",
  "3gp": "video/3gpp",
  "ts": "video/mp2t",
  "mp4": "video/mp4",
  "mpeg": "video/mpeg",
  "mpg": "video/mpeg",
  "mov": "video/quicktime",
  "webm": "video/webm",
  "flv": "video/x-flv",
  "m4v": "video/x-m4v",
  "mng": "video/x-mng",
  "asx": "video/x-ms-asf",
  "asf": "video/x-ms-asf",
  "wmv": "video/x-ms-wmv",
  "avi": "video/x-msvideo",
  "vcf": "text/vcard",
]

extension URL {
  func mimeType(ext: String?) -> String {
    if #available(iOSApplicationExtension 14.0, *) {
      if let pathExt = ext,
        let mimeType = UTType(filenameExtension: pathExt)?.preferredMIMEType
      {
        return mimeType
      } else {
        return "application/octet-stream"
      }
    } else {
      return mimeTypes[ext?.lowercased() ?? ""] ?? "application/octet-stream"
    }
  }
}

extension Array {
  subscript(safe index: UInt) -> Element? {
    return Int(index) < count ? self[Int(index)] : nil
  }
}
