import { isIconName } from "@centraid/design";
import type { IconName } from "@centraid/design";

const ALIASES: Record<string, IconName> = {
  activity: "Activity",
  "alert-circle": "AlertCircle",
  archive: "Archive",
  "arrow-left": "ArrowLeft",
  "arrow-up": "Send",
  "bar-chart-2": "BarChart2",
  "battery-charging": "BatteryCharging",
  bell: "Bell",
  "book-open": "Book",
  bookmark: "Bookmark",
  check: "Check",
  "check-circle": "CheckCircle",
  "chevron-down": "ChevronDown",
  "chevron-left": "ChevronLeft",
  "chevron-right": "ChevronRight",
  "chevrons-down": "ChevronsDown",
  clock: "Clock",
  cloud: "Cloud",
  "cloud-off": "CloudOff",
  copy: "Copy",
  cpu: "Cpu",
  "dollar-sign": "Coin",
  download: "Download",
  "download-cloud": "Download",
  "edit-2": "Pencil",
  "edit-3": "Pencil",
  file: "FileEdit",
  "file-text": "FileEdit",
  folder: "Folder",
  "folder-plus": "FolderPlus",
  grid: "Grid",
  "hard-drive": "Gauge",
  headphones: "Music",
  heart: "Heart",
  home: "Home",
  image: "Image",
  info: "AlertCircle",
  layers: "Layers",
  list: "List",
  "map-pin": "Pin",
  maximize: "Maximize",
  menu: "Menu",
  "message-circle": "MessageCircle",
  "more-horizontal": "MoreHoriz",
  "more-vertical": "MoreVert",
  paperclip: "Paperclip",
  play: "Play",
  plus: "Plus",
  "rotate-ccw": "Reset",
  search: "Search",
  settings: "Settings",
  share: "Share",
  shield: "Shield",
  smartphone: "Smartphone",
  square: "Stop",
  star: "Star",
  "trash-2": "Trash",
  "upload-cloud": "Upload",
  user: "User",
  "user-plus": "UserPlus",
  users: "Users",
  video: "Video",
  x: "X",
  "x-circle": "XCircle",
  zap: "Bolt",
  "zap-off": "BoltOff",
};

export function resolveIconName(name: string): IconName {
  if (isIconName(name)) return name;
  const alias = ALIASES[name];
  if (alias) return alias;
  throw new Error(`Unknown mobile icon name: ${name}`);
}
