// The managed tree: what the kit recorded, and what is actually on disk
// (#1005).
//
// `packs.lock` and `install.yaml` are read by narrow line parsers rather than a
// YAML implementation: they are generated in one shape, and a dependency for
// reading a handful of known keys is a dependency the commit path would pay for
// on every run.
import { readFileSync, readdirSync } from "node:fs";
import path from "node:path";

import { ROOT } from "./git.mjs";
import { byteCompare, dirDigest, sha256File } from "./digest.mjs";

/**
 * Read the `digest:` maps out of `.governance/packs.lock`.
 *
 * A narrow line parser, not a YAML implementation: this file is generated by
 * the kit in one shape, and a dependency for reading four known keys would be a
 * dependency the commit path pays for on every run.
 *
 * @param {string} text The lockfile.
 * @returns {{id: string, digest: Record<string, string>}[]} The packs.
 */
export function parsePacksLock(text) {
  const packs = [];
  let current = null;
  let inDigest = false;
  let inDirectives = false;
  for (const line of text.split("\n")) {
    const entry = /^- id: (?<id>.+)$/u.exec(line);
    if (entry) {
      current = { id: entry.groups.id.trim(), directives: [], digest: {} };
      packs.push(current);
      inDigest = false;
      inDirectives = false;
      continue;
    }
    if (!current) continue;
    if (/^ {2}digest:\s*$/u.test(line)) {
      inDigest = true;
      inDirectives = false;
      continue;
    }
    if (/^ {2}directives:\s*$/u.test(line)) {
      inDirectives = true;
      inDigest = false;
      continue;
    }
    if (inDirectives) {
      const item = /^ {2}- (?<name>.+)$/u.exec(line);
      if (item) {
        current.directives.push(item.groups.name.trim());
        continue;
      }
      inDirectives = false;
    }
    if (inDigest) {
      const row = /^ {4}(?<key>[^:]+): (?<value>.+)$/u.exec(line);
      if (row) current.digest[row.groups.key.trim()] = row.groups.value.trim();
      else if (/^\S/u.test(line) || /^ {2}\S/u.test(line)) inDigest = false;
    }
  }
  return packs;
}

/**
 * Read `managed_digests:` out of `.governance/install.yaml`. Same narrowness,
 * same reason as `parsePacksLock`.
 *
 * @param {string} text The install manifest.
 * @returns {Record<string, string>} path → recorded digest.
 */
export function parseManagedDigests(text) {
  const out = {};
  let inBlock = false;
  for (const line of text.split("\n")) {
    if (/^managed_digests:\s*$/u.test(line)) {
      inBlock = true;
      continue;
    }
    if (!inBlock) continue;
    const row = /^ {2}(?<key>[^:\s]+): (?<value>.+)$/u.exec(line);
    if (row) out[row.groups.key] = row.groups.value.trim();
    else if (line.trim() !== "") break;
  }
  return out;
}

/**
 * The managed-tree section: recorded digest against actual, for every unit the
 * kit locks. `managed-tree-integrity` already fails a commit on a mismatch;
 * this repeats the arithmetic so a rule can *reason* about it — which unit
 * moved, and whether the change set explains it.
 *
 * @returns {{packs: object[], files: object[]}} The section.
 */
export function collectManagedTree() {
  const packs = [];
  const unrecorded = [];
  for (const pack of parsePacksLock(
    readFileSync(path.join(ROOT, ".governance/packs.lock"), "utf8")
  )) {
    const [owner, name] = pack.id.split("/");
    const recordedDirectives = new Set([...Object.keys(pack.digest), ...pack.directives]);
    for (const directive of Object.keys(pack.digest).sort(byteCompare)) {
      packs.push({
        id: pack.id,
        directive,
        recorded: pack.digest[directive],
        actual: dirDigest(
          path.join(ROOT, ".governance/packs", owner, name, "directives", directive)
        ),
      });
    }
    // A pack that records no digests is a pre-digest install and is skipped
    // whole, exactly as the shell directive skipped it.
    if (Object.keys(pack.digest).length === 0) continue;
    const dir = path.join(ROOT, ".governance/packs", owner, name, "directives");
    let onDisk = [];
    try {
      onDisk = readdirSync(dir, { withFileTypes: true })
        .filter((entry) => entry.isDirectory())
        .map((entry) => entry.name);
    } catch {
      onDisk = [];
    }
    for (const directive of onDisk.sort(byteCompare)) {
      if (!recordedDirectives.has(directive)) unrecorded.push({ id: pack.id, directive });
    }
  }
  const manifest = readFileSync(path.join(ROOT, ".governance/install.yaml"), "utf8");
  const recorded = parseManagedDigests(manifest);
  const kitVersion = /^kit_version:\s*["']?(?<version>[^"'#\s]*)/mu.exec(manifest)?.groups.version ?? "";
  const files = Object.keys(recorded)
    .sort(byteCompare)
    .map((file) => {
      let actual = "";
      let marker = "";
      try {
        actual = sha256File(path.join(ROOT, file));
        // The marker is what catches a hand-edited manifest: the files still
        // match their recorded digests, so only the stamp disagrees.
        marker =
          /governance-kit:managed.*kit-version=(?<version>\S+)/u.exec(
            readFileSync(path.join(ROOT, file), "utf8").split("\n").slice(0, 3).join("\n")
          )?.groups.version ?? "";
      } catch {
        actual = "";
      }
      return { path: file, recorded: recorded[file], actual, marker };
    });
  return { packs, unrecorded, files, kitVersion };
}

