// The managed tree: what the kit recorded, and what is actually on disk
// (#1005).
//
// `packs.lock` and `install.yaml` are read by narrow line parsers rather than a
// YAML implementation: they are generated in one shape, and a dependency for
// reading a handful of known keys is a dependency the commit path would pay for
// on every run.
import { byteCompare, digestEntries, sha256 } from "./digest.mjs";

/**
 * Read the `digest:` maps out of `.governance/packs.lock`.
 *
 * A narrow line parser, not a YAML implementation: this file is generated by
 * the kit in one shape, and a dependency for reading four known keys would be a
 * dependency the commit path pays for on every run.
 *
 * @param {string} text The lockfile.
 * @returns {{id: string, digest: Record<string, string>}[]} The packs.
 */
export function parsePacksLock(text) {
  const packs = [];
  let current = null;
  let inDigest = false;
  let inDirectives = false;
  for (const line of text.split("\n")) {
    const entry = /^- id: (?<id>.+)$/u.exec(line);
    if (entry) {
      current = { id: entry.groups.id.trim(), directives: [], digest: {} };
      packs.push(current);
      inDigest = false;
      inDirectives = false;
      continue;
    }
    if (!current) continue;
    if (/^ {2}digest:\s*$/u.test(line)) {
      inDigest = true;
      inDirectives = false;
      continue;
    }
    if (/^ {2}directives:\s*$/u.test(line)) {
      inDirectives = true;
      inDigest = false;
      continue;
    }
    if (inDirectives) {
      const item = /^ {2}- (?<name>.+)$/u.exec(line);
      if (item) {
        current.directives.push(item.groups.name.trim());
        continue;
      }
      inDirectives = false;
    }
    if (inDigest) {
      const row = /^ {4}(?<key>[^:]+): (?<value>.+)$/u.exec(line);
      if (row) current.digest[row.groups.key.trim()] = row.groups.value.trim();
      else if (/^\S/u.test(line) || /^ {2}\S/u.test(line)) inDigest = false;
    }
  }
  return packs;
}

/**
 * Read `managed_digests:` out of `.governance/install.yaml`. Same narrowness,
 * same reason as `parsePacksLock`.
 *
 * @param {string} text The install manifest.
 * @returns {Record<string, string>} path → recorded digest.
 */
export function parseManagedDigests(text) {
  const out = {};
  let inBlock = false;
  for (const line of text.split("\n")) {
    if (/^managed_digests:\s*$/u.test(line)) {
      inBlock = true;
      continue;
    }
    if (!inBlock) continue;
    const row = /^ {2}(?<key>[^:\s]+): (?<value>.+)$/u.exec(line);
    if (row) out[row.groups.key] = row.groups.value.trim();
    else if (line.trim() !== "") break;
  }
  return out;
}

/**
 * The managed-tree section: recorded digest against actual, for every unit the
 * kit locks. `managed-tree-integrity` already fails a commit on a mismatch;
 * this repeats the arithmetic so a rule can *reason* about it — which unit
 * moved, and whether the change set explains it.
 *
 * Every byte comes from the tree the record is about — the range's head, or the
 * index inside the commit hook — never from the working copy. A record whose
 * managed digests were whatever happened to be checked out would say a
 * different thing on every machine that read the same range (R-1005-27).
 *
 * @param {object} source The tree reader from `treeSource`.
 * @returns {{packs: object[], unrecorded: object[], files: object[], kitVersion: string}} The section.
 */
export function collectManagedTree(source) {
  const text = (bytes) => (bytes === null ? "" : bytes.toString("utf8"));
  const roots = source.read([".governance/packs.lock", ".governance/install.yaml"]);
  const packsTree = source.list([".governance/packs"]);
  const blobs = source.read(packsTree);
  const packs = [];
  const unrecorded = [];
  for (const pack of parsePacksLock(text(roots.get(".governance/packs.lock")))) {
    const [owner, name] = pack.id.split("/");
    const base = `.governance/packs/${owner}/${name}/directives`;
    const recordedDirectives = new Set([...Object.keys(pack.digest), ...pack.directives]);
    for (const directive of Object.keys(pack.digest).sort(byteCompare)) {
      const prefix = `${base}/${directive}/`;
      packs.push({
        id: pack.id,
        directive,
        recorded: pack.digest[directive],
        actual: digestEntries(
          packsTree
            .filter((file) => file.startsWith(prefix))
            .map((file) => [file.slice(prefix.length), blobs.get(file) ?? Buffer.alloc(0)])
        ),
      });
    }
    // A pack that records no digests is a pre-digest install and is skipped
    // whole, exactly as the shell directive skipped it.
    if (Object.keys(pack.digest).length === 0) continue;
    const onTree = new Set(
      packsTree
        .filter((file) => file.startsWith(`${base}/`))
        .map((file) => file.slice(base.length + 1).split("/")[0])
    );
    for (const directive of [...onTree].sort(byteCompare)) {
      if (!recordedDirectives.has(directive)) unrecorded.push({ id: pack.id, directive });
    }
  }
  const manifest = text(roots.get(".governance/install.yaml"));
  const recorded = parseManagedDigests(manifest);
  const kitVersion =
    /^kit_version:\s*["']?(?<version>[^"'#\s]*)/mu.exec(manifest)?.groups.version ?? "";
  const paths = Object.keys(recorded).sort(byteCompare);
  const managed = source.read(paths);
  const files = paths.map((file) => {
    const bytes = managed.get(file);
    // The marker is what catches a hand-edited manifest: the files still match
    // their recorded digests, so only the stamp disagrees.
    const marker =
      bytes === null
        ? ""
        : (/governance-kit:managed.*kit-version=(?<version>\S+)/u.exec(
            bytes.toString("utf8").split("\n").slice(0, 3).join("\n")
          )?.groups.version ?? "");
    return {
      path: file,
      recorded: recorded[file],
      actual: bytes === null ? "" : sha256(bytes),
      marker,
    };
  });
  return { packs, unrecorded, files, kitVersion };
}
