import { StyleSheet } from "react-native";

import { family, t, radii } from "../../kit/theme";

export const styles = StyleSheet.create({
  addCopy: { flex: 1, marginLeft: 12 },
  addIcon: {
    alignItems: "center",
    borderRadius: radii.lg,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  addRow: {
    alignItems: "center",
    borderBottomWidth: 1,
    flexDirection: "row",
    marginTop: 12,
    minHeight: 64,
  },
  backdrop: { flex: 1 },
  copy: { flex: 1, marginLeft: 12 },
  create: {
    alignItems: "center",
    borderRadius: radii.lg,
    marginTop: 12,
    padding: 12,
  },
  createText: { fontFamily: family.sansMedium, fontSize: t("mono").fontSize },
  // The custody exception mark (docs-custody.ts `marksLocalOnly`) — 6px after
  // the meta line, matching Photos' bottom-slot custody chip gutter.
  custodyMark: { marginLeft: 6 },
  dialog: {
    borderRadius: radii.lg,
    left: 24,
    padding: 20,
    position: "absolute",
    right: 24,
    top: "25%",
  },
  dialogTitle: { fontFamily: family.sansMedium, fontSize: t("title").fontSize },
  empty: {
    ...t("small"),
    marginTop: 7,
    textAlign: "center",
  },
  emptyTitle: {
    fontFamily: family.sansMedium,
    fontSize: t("reading").fontSize,
    marginTop: 14,
  },
  emptyWrap: { alignItems: "center", paddingHorizontal: 30, paddingTop: 60 },
  filter: {
    alignItems: "center",
    borderRadius: radii.pill,
    flexDirection: "row",
    gap: 6,
    minHeight: 34,
    paddingHorizontal: 12,
  },
  filters: { alignItems: "center", gap: 8, paddingHorizontal: 18 },
  filterScroll: { flexGrow: 0, height: 50 },
  filterText: { fontFamily: family.sansMedium, fontSize: t("mono").fontSize },
  folderInput: {
    borderRadius: radii.lg,
    borderWidth: 1,
    fontFamily: family.sansRegular,
    fontSize: t("body").fontSize,
    marginTop: 7,
    padding: 11,
  },
  gridCard: {
    borderRadius: radii.lg,
    borderWidth: 1,
    minHeight: 164,
    padding: 10,
    width: "48.5%",
  },
  gridList: { paddingTop: 4 },
  gridMenu: { position: "absolute", right: 9, top: 9, zIndex: 1 },
  gridPreview: {
    alignItems: "center",
    borderRadius: radii.lg,
    height: 82,
    justifyContent: "center",
  },
  gridRow: { gap: 10 },
  gridTitle: {
    ...t("smallStrong"),
    marginTop: 9,
  },
  header: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    minHeight: 56,
    paddingHorizontal: 18,
  },
  headerActions: { alignItems: "center", flexDirection: "row", gap: 12 },
  headerCopy: { flex: 1 },
  icon: {
    alignItems: "center",
    borderRadius: radii.lg,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  input: {
    flex: 1,
    fontFamily: family.sansRegular,
    fontSize: t("body").fontSize,
    paddingVertical: 10,
  },
  libraryHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    paddingBottom: 7,
    paddingTop: 13,
  },
  libraryMeta: {
    fontFamily: family.sansRegular,
    fontSize: t("control").fontSize,
    marginTop: 3,
  },
  libraryTitle: {
    fontFamily: family.sansMedium,
    fontSize: t("reading").fontSize,
  },
  list: { paddingBottom: 48, paddingHorizontal: 18 },
  meta: {
    fontFamily: family.sansRegular,
    fontSize: t("control").fontSize,
    marginTop: 4,
  },
  // Row wrapper so the custody mark sits beside the meta text instead of
  // below it — the meta Text itself keeps its own marginTop.
  metaRow: { alignItems: "center", flexDirection: "row" },
  newFolderLabel: {
    fontFamily: family.sansMedium,
    fontSize: t("mono").fontSize,
    letterSpacing: 1,
    marginTop: 18,
  },
  row: {
    alignItems: "center",
    borderBottomWidth: 1,
    flexDirection: "row",
    minHeight: 68,
  },
  rowTitle: { fontFamily: family.sansMedium, fontSize: t("body").fontSize },
  safe: { flex: 1 },
  search: {
    alignItems: "center",
    borderRadius: radii.lg,
    flexDirection: "row",
    gap: 8,
    marginHorizontal: 18,
    paddingHorizontal: 12,
  },
  shareFolder: { alignItems: "center", flexDirection: "row", gap: 5 },
  shareFolderText: t("control"),
  subtitle: {
    fontFamily: family.sansRegular,
    fontSize: t("control").fontSize,
    marginTop: 2,
  },
  title: {
    fontFamily: family.sansMedium,
    fontSize: t("title").fontSize,
    letterSpacing: -0.5,
  },
  viewButton: {
    alignItems: "center",
    borderRadius: radii.md,
    height: 30,
    justifyContent: "center",
    width: 32,
  },
  viewSwitch: { borderRadius: radii.md, flexDirection: "row", padding: 2 },
});
