/* Centraid core — the C ABI. GENERATED by cbindgen; do not edit.
 *
 * Five symbols and a contract. The clauses are in crates/core-ffi/CONTRACT.md
 * and each one has a test in crates/core-ffi/tests/contract.rs. Read the
 * contract before calling any of these: a shell's memory safety depends on
 * claims that are not visible in these signatures.
 *
 * Regenerate with:
 *   CENTRAID_WRITE_HEADER=1 cargo build -p centraid-core-ffi
 */

#ifndef CENTRAID_H
#define CENTRAID_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * The call completed. The out-buffer, if there is one, holds the answer.
 */
#define CENTRAID_OK 0

/**
 * A pointer argument was null, or a length was impossible.
 */
#define CENTRAID_BAD_ARGUMENT -1

/**
 * The bytes were not a decodable `Envelope`.
 */
#define CENTRAID_MALFORMED -2

/**
 * The handle is closed. Distinct from [`CENTRAID_PANICKED`]: a closed handle
 * was closed on purpose and a poisoned one was not.
 */
#define CENTRAID_CLOSED -3

/**
 * A panic was caught. The handle is poisoned; restart the core.
 */
#define CENTRAID_PANICKED -4

/**
 * `next_event` returned with nothing, because its timeout elapsed. **Not an
 * error** — it is negative only because every non-`OK` code is, and a caller
 * that treats it as a failure will restart the core once a second.
 */
#define CENTRAID_TIMEOUT -5

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Open a core over a vault file.
 *
 * `config` is `len` bytes of UTF-8 JSON: `{"path": "...", "role":
 * "gateway"|"seat-replicated"|"seat-thin", "gateway": "<hex>"?, "create":
 * bool?, "uiThreadName": "..."?}`. JSON and not protobuf, because a
 * configuration is read once at startup by a human-written call site and being
 * able to log it verbatim is worth more than the encoding.
 *
 * On success writes an owned handle to `out` and returns [`CENTRAID_OK`]. The
 * handle is released **only** by [`centraid_close`].
 *
 * # Safety
 *
 * `config` must point to `len` readable bytes and `out` must point to writable
 * storage for one pointer. Both are borrowed for the duration of the call
 * only; this function keeps neither.
 */
int32_t centraid_open(const uint8_t *config, size_t len, Handle **out);

/**
 * Answer one request.
 *
 * `req`/`len` are a protobuf-encoded `centraid.core.v1.Envelope` carrying a
 * `Request`. On return `*out_buf`/`*out_len` hold a **callee-allocated**
 * `Envelope` carrying a `Response` or an `Error`, released only by
 * [`centraid_free`].
 *
 * **Reentrant across threads.** This function takes no lock of its own; two
 * concurrent calls contend only for whatever the core's own serialisation
 * requires (see `crates/core`'s `handle.rs`, D-1020-D2-9). The FFI is never the
 * bottleneck, and `tests/contract.rs` asserts it.
 *
 * # Safety
 *
 * `handle` must be a live pointer from [`centraid_open`] that has not been
 * passed to [`centraid_close`]. `req` must point to `len` readable bytes.
 * `out_buf` and `out_len` must point to writable storage.
 */
int32_t centraid_call(Handle *handle,
                      const uint8_t *req,
                      size_t len,
                      uint8_t **out_buf,
                      size_t *out_len);

/**
 * Wait for the next event, up to `timeout_ms`.
 *
 * On [`CENTRAID_OK`], `*out_buf`/`*out_len` hold an `Envelope` carrying an
 * `Event`. On [`CENTRAID_TIMEOUT`] nothing is allocated and the out-pointers are
 * left alone — a caller must not call [`centraid_free`] on them.
 *
 * # Safety
 *
 * As [`centraid_call`], for `handle`, `out_buf` and `out_len`.
 */
int32_t centraid_next_event(Handle *handle,
                            uint32_t timeout_ms,
                            uint8_t **out_buf,
                            size_t *out_len);

/**
 * Release a buffer this library allocated.
 *
 * `len` must be the length the call handed back. It is required rather than
 * tracked because Rust's allocator needs the layout to deallocate, and
 * carrying a header inside the buffer would make the bytes the shell reads
 * offset from the pointer it was given — a mistake every shell would make
 * once.
 *
 * A null `buf` is a **no-op**, so a caller need not branch on the timeout case.
 *
 * # Safety
 *
 * `buf` must be a pointer this library returned through an out-parameter, with
 * exactly the `len` it reported, and must not have been freed already.
 */
void centraid_free(uint8_t *buf, size_t len);

/**
 * Close a core and release its handle.
 *
 * Unblocks any thread parked in [`centraid_next_event`] — which returns
 * [`CENTRAID_CLOSED`] — and then drops the handle. Every later call on the same
 * pointer is undefined: the pointer is dangling, and no ABI can make a
 * use-after-free safe. A shell must null its own copy, and `CONTRACT.md` says
 * so in those words.
 *
 * # Safety
 *
 * `handle` must be a live pointer from [`centraid_open`] that has not already
 * been closed. It must not be used afterwards.
 */
int32_t centraid_close(Handle *handle);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* CENTRAID_H */
